# -*- coding: utf-8 -*-
"""Datos de contenido para el cluster de funciones y hardware.

Cada entrada produce una pagina con intencion de busqueda propia. El texto es
especifico del tema: nada de plantillas rellenadas con sinonimos.
"""

# slug: contenido
FUNCIONES = {
"matriz-tallas-y-colores": dict(
    titulo="Matriz de Tallas y Colores en el TPV: cómo funciona | Caja 5",
    h1="Matriz de tallas y colores: un artículo, todas las combinaciones",
    desc="Cómo gestionar tallas y colores en el TPV sin dar de alta 40 artículos. Matriz visual, códigos de barras por combinación y control de stock real por talla.",
    kw="matriz de tallas y colores, tpv tallas y colores, programa tallas colores, stock por talla, software tienda ropa tallas, codigo barras por talla",
    badge="MATRIZ DE TALLAS Y COLORES",
    sub="La diferencia entre un TPV de comercio general y uno de moda está aquí. Un modelo, una ficha y una cuadrícula donde marcas qué combinaciones existes de verdad.",
    intro=[
      "En una tienda de ropa, un mismo modelo puede existir en seis tallas y cinco colores. Son treinta artículos distintos de cara al stock, pero un solo producto de cara al cliente y al escaparate. Un TPV que te obliga a dar de alta treinta fichas independientes te condena a un catálogo inmanejable: buscar «camiseta» devuelve treinta líneas casi idénticas y cualquier cambio de precio hay que repetirlo treinta veces.",
      "La matriz de tallas y colores resuelve exactamente eso. Creas una ficha para el modelo, defines el rango de tallas y la lista de colores, y marcas en una cuadrícula qué combinaciones existen realmente. El programa genera cada combinación con su propio código de barras y lleva el stock por separado, pero tú sigues trabajando con un único artículo.",
    ],
    bullets=[
      ("Una ficha por modelo", "Cambias el precio, la familia o la temporada una vez y se aplica a todas las combinaciones."),
      ("Cuadrícula visual", "Ves de un vistazo qué tienes en cada cruce de talla y color, y dónde te has quedado a cero."),
      ("Código de barras por combinación", "Cada talla y color tiene su EAN propio, así que la caja no se equivoca nunca."),
      ("Reposición inteligente", "El pedido a proveedor se calcula por combinación: pides las tallas que faltan, no el modelo entero."),
      ("Etiquetas de colgador", "Imprimes la etiqueta con modelo, talla, color y precio directamente desde la matriz."),
    ],
    como=[
      "Das de alta el modelo con su nombre, familia, proveedor, precio de coste y precio de venta.",
      "Eliges la escala de tallas: numérica (36-46), alfabética (XS-4XL) o la que uses en tu sector, incluida una escala propia.",
      "Marcas los colores disponibles y activas las casillas de la cuadrícula que existen de verdad. Si el vestido rojo no viene en talla 46, esa casilla queda vacía y no ensucia el inventario.",
      "Introduces las unidades recibidas en cada cruce. A partir de ahí, cada venta descuenta de la combinación exacta.",
      "Imprimes etiquetas con código de barras para todas las combinaciones de golpe, en formato adhesivo pequeño o de colgador.",
    ],
    faqs=[
      ("¿Cuántas variables admite la matriz además de talla y color?",
       "Caja 5 trabaja con talla, color y una tercera variable libre que puedes renombrar según tu sector: largo de pernera en pantalones, ancho de horma en calzado, formato en perfumería o material en bisutería. Con eso cubres prácticamente cualquier catálogo de moda y complementos."),
      ("¿Puedo usar mi propia escala de tallas?",
       "Sí. Además de las escalas habituales (numérica, alfabética, infantil por edades, calzado), puedes definir escalas propias con las etiquetas que quieras. Es lo normal en ropa de baño, corsetería, ropa laboral o moda flamenca, donde las escalas no son estándar."),
      ("¿Qué pasa si un proveedor me manda un modelo con colores nuevos a mitad de temporada?",
       "Añades el color a la ficha del modelo y la matriz se amplía sola. El histórico de ventas de los colores anteriores se conserva intacto, así que sigues pudiendo comparar qué se vendió mejor."),
      ("¿Se pueden imprimir etiquetas solo de las combinaciones que he recibido?",
       "Sí. Al registrar la entrada de mercancía puedes lanzar la impresión de etiquetas exactamente de las unidades recibidas, sin tener que seleccionar a mano talla por talla."),
      ("¿La matriz sirve para hacer el inventario anual?",
       "Sí, y es donde más se nota. Puedes contar con lector o con PDA e ir viendo la cuadrícula rellenarse; al final el programa te muestra las diferencias entre stock teórico y contado por cada combinación, no solo por modelo."),
    ],
    rel=[("Software TPV para tiendas de ropa y moda","/negocio_moda.asp"),
         ("TPV para zapaterías y calzado","/negocio_calzado.asp"),
         ("Cómo hacer el inventario de una tienda","/como-hacer-un-inventario-tienda.asp"),
         ("Etiquetas con código de barras","/etiquetas-codigo-de-barras-tpv.asp")]),

"control-de-stock-multialmacen": dict(
    titulo="Control de Stock Multialmacén en el TPV | Caja 5",
    h1="Control de stock multialmacén: tienda, almacén y trastienda",
    desc="Control de stock en varios almacenes desde un solo TPV: traspasos entre tiendas, stock por ubicación, alertas de mínimos y valoración de inventario.",
    kw="control de stock multialmacen, tpv varias tiendas, traspaso entre tiendas, stock por almacen, gestion inventario comercio, alertas stock minimo",
    badge="STOCK Y MULTIALMACÉN",
    sub="Saber cuántas unidades tienes no sirve de nada si no sabes dónde están. Stock por almacén, traspasos con documento y alertas antes de quedarte a cero.",
    intro=[
      "El error clásico del pequeño comercio es llevar un único stock global cuando en realidad hay tres: lo que está expuesto en tienda, lo que duerme en la trastienda y lo que está en el almacén o en la segunda tienda. Cuando un cliente pregunta por una talla, la respuesta «me parece que queda una» cuesta ventas.",
      "El control multialmacén separa esas ubicaciones y te deja mover mercancía entre ellas dejando rastro. Cada traspaso genera su documento, de forma que si falta género sabes entre qué dos puntos se perdió.",
    ],
    bullets=[
      ("Stock independiente por almacén", "Tienda, trastienda, almacén central o segunda tienda, cada uno con sus unidades."),
      ("Traspasos con documento", "Mueves género de un punto a otro y queda registrado quién, cuándo y cuánto."),
      ("Alertas de stock mínimo", "Defines el mínimo por artículo y el programa te avisa antes de romper stock."),
      ("Valoración de inventario", "Sabes cuánto dinero tienes inmovilizado, a precio de coste y a precio de venta."),
      ("Consulta desde caja", "El dependiente ve si la talla que falta está en la otra tienda sin levantarse del mostrador."),
    ],
    como=[
      "Defines tus almacenes: normalmente «Tienda» y «Almacén», y uno más por cada punto de venta adicional.",
      "Al registrar una compra, indicas a qué almacén entra la mercancía.",
      "Cuando repones el expositor, generas un traspaso de Almacén a Tienda. El stock total no cambia; cambia su ubicación.",
      "Configuras el stock mínimo de los artículos que no puedes permitirte agotar y revisas el informe de reposición cada semana.",
      "En el inventario anual cuentas por almacén, lo que permite cuadrar por partes en lugar de cerrar la tienda un día entero.",
    ],
    faqs=[
      ("¿Necesito la versión en la nube para trabajar con dos tiendas?",
       "Depende de si necesitas ver el stock de la otra tienda en tiempo real. Caja 5 Nube sincroniza todos los puntos de venta al instante. Con Caja 5 para PC cada tienda trabaja con su base de datos local y se consolidan los datos periódicamente, que para muchos negocios de dos tiendas es más que suficiente y sale bastante más barato."),
      ("¿Puedo saber cuánto dinero tengo inmovilizado en stock?",
       "Sí. El informe de valoración de inventario te da el total a precio de coste, que es el dato que necesita tu asesor para el cierre, y a precio de venta, que es el que necesitas tú para saber cuánto puedes liquidar en rebajas."),
      ("¿Qué pasa si vendo una unidad que no tenía registrada?",
       "Puedes permitir o bloquear el stock negativo. Lo habitual es permitirlo en caja para no frenar una venta real y revisar después el informe de descuadres, que te señala exactamente qué artículos han quedado en negativo."),
      ("¿Se puede hacer inventario sin cerrar la tienda?",
       "Sí, contando por zonas o por familias en momentos de poca afluencia. El recuento se guarda parcialmente y no bloquea la caja, así que puedes contar la sección de camisería un martes por la mañana y el resto otro día."),
    ],
    rel=[("Cómo hacer el inventario de una tienda","/como-hacer-un-inventario-tienda.asp"),
         ("Inventario con PDA o lector","/inventario-con-pda-lector-codigo-barras.asp"),
         ("Matriz de tallas y colores","/matriz-tallas-y-colores.asp"),
         ("Caja 5 Nube para varias tiendas","/caja5_nube.asp")]),

"programa-fidelizacion-puntos": dict(
    titulo="Programa de Fidelización y Puntos en el TPV | Caja 5",
    h1="Programa de puntos y fidelización desde el propio TPV",
    desc="Monta un programa de puntos en tu tienda sin apps ni cuotas: acumulación por compra, canje en caja, tarjeta de cliente y avisos por email o SMS.",
    kw="programa de puntos tienda, fidelizacion clientes comercio, tarjeta puntos tpv, crm tienda ropa, club de clientes, marketing tienda fisica",
    badge="FIDELIZACIÓN Y CRM",
    sub="Traer un cliente nuevo cuesta entre cinco y siete veces más que hacer volver a uno que ya te compró. El programa de puntos vive dentro del TPV, sin apps de terceros.",
    intro=[
      "La ficha de cliente de un TPV suele quedarse en un nombre y un teléfono. Desaprovechada, es solo una agenda. Bien usada, es la lista de personas que ya han demostrado que te compran, y es el activo comercial más rentable que tiene una tienda.",
      "Un programa de puntos convierte esa lista en algo accionable: cada compra acumula saldo, el saldo se canjea en caja y, de paso, el cliente te deja su historial. Con eso puedes avisar a las veinte personas que compraron una marca concreta cuando entre la nueva temporada.",
    ],
    bullets=[
      ("Puntos por compra", "Defines cuántos puntos da cada euro y a cuánto equivale el punto al canjear."),
      ("Canje en caja", "El dependiente ve el saldo del cliente al identificarlo y aplica el descuento en el ticket."),
      ("Historial de compras", "Sabes qué compró cada cliente, cuándo y en qué talla, lo que convierte cualquier aviso en algo relevante."),
      ("Segmentación real", "Filtras por marca, familia, importe o fecha de última visita para preparar campañas concretas."),
      ("Vales y tarjetas regalo", "Emites vales por devolución o tarjetas regalo con saldo y control de caducidad."),
    ],
    como=[
      "Configuras la regla de acumulación: por ejemplo, 1 punto por cada euro y 100 puntos equivalen a 5 € de descuento.",
      "Das de alta al cliente en caja con lo mínimo imprescindible: nombre, teléfono o email y consentimiento para recibir comunicaciones.",
      "En cada venta identificas al cliente y los puntos se acumulan solos.",
      "Cuando quiera canjear, el programa aplica el descuento sobre el ticket y descuenta el saldo.",
      "Periódicamente sacas un listado segmentado y lanzas la campaña por email o SMS.",
    ],
    faqs=[
      ("¿Esto cumple con la protección de datos?",
       "Debes recoger el consentimiento del cliente para tratar sus datos y para enviarle comunicaciones comerciales, informarle de la finalidad y permitirle darse de baja. El programa guarda los datos en tu equipo y te deja registrar el consentimiento, pero la responsabilidad del tratamiento como responsable es tuya: consúltalo con tu asesor y ten a mano tu política de privacidad."),
      ("¿Hace falta una app para el cliente?",
       "No. Se identifica con su teléfono, su DNI o una tarjeta de fidelización con código de barras. Para el pequeño comercio la app suele ser una barrera: el cliente no se la instala y el programa muere."),
      ("¿Puedo hacer promociones solo para clientes del club?",
       "Sí, es lo más rentable del sistema. Puedes preparar precios o descuentos que solo se apliquen a clientes identificados, y avisar por email de una preventa de rebajas exclusiva 48 horas antes de abrirla al público."),
      ("¿Los puntos caducan?",
       "Tú decides. Puedes dejarlos indefinidos o ponerles caducidad, que es lo habitual para empujar la segunda visita. Si los pones a caducar, avisa al cliente con antelación: un punto que caduca por sorpresa genera más queja que fidelidad."),
    ],
    rel=[("Vales y tarjetas regalo","/vales-y-tarjetas-regalo-tpv.asp"),
         ("TPV con gestión de clientes","/negocio_gestion_clientes.asp"),
         ("Software TPV para perfumerías","/negocio_perfumeria.asp"),
         ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp")]),

"tpv-sin-internet-modo-offline": dict(
    titulo="TPV que funciona sin internet: modo offline real | Caja 5",
    h1="TPV sin internet: seguir cobrando cuando se cae la línea",
    desc="Por qué un TPV local sigue cobrando sin conexión y qué pierdes con un TPV 100% en la nube cuando falla internet. Modo offline real y datos en tu equipo.",
    kw="tpv sin internet, tpv offline, programa tpv local, tpv que funciona sin conexion, tpv sin nube, caja registradora sin internet",
    badge="FUNCIONAMIENTO SIN CONEXIÓN",
    sub="Un sábado a mediodía sin línea, con la tienda llena, es la prueba real de tu TPV. Con la base de datos en local, sigues cobrando como si nada.",
    intro=[
      "Los TPV en la nube tienen ventajas claras: acceso desde cualquier sitio, copias automáticas y sincronización entre tiendas. Pero comparten un punto débil que rara vez aparece en la web del fabricante: si se cae internet, dejas de facturar. No es una hipótesis remota; una avería de la operadora, un router quemado o un corte de luz en la centralita basta.",
      "Caja 5 para PC guarda los datos en el propio ordenador de la tienda. Internet lo necesitas para actualizaciones, para enviar correos o para sincronizar con la web, pero no para cobrar. Si la línea cae, la caja sigue abriendo, el lector sigue leyendo y el ticket sigue imprimiéndose.",
    ],
    bullets=[
      ("Base de datos local", "El catálogo, el stock y los tickets viven en tu equipo, no en un servidor ajeno."),
      ("Cobro garantizado", "Sin conexión sigues vendiendo, imprimiendo tickets y cerrando caja con normalidad."),
      ("Datáfono independiente", "El TPV bancario funciona por su propia línea, así que el cobro con tarjeta tampoco depende de tu wifi."),
      ("Sin cuota que te apague el programa", "La licencia es tuya: si dejas de pagar algo, el software no se bloquea."),
      ("Copias de seguridad a tu criterio", "Programas la copia en disco externo, red o nube, según cómo trabajes."),
    ],
    como=[
      "Instalas Caja 5 en el ordenador de la tienda; ahí queda la base de datos.",
      "Configuras la copia de seguridad automática: lo recomendable es diaria y con una copia fuera del local.",
      "Si tienes varios puestos, uno hace de servidor y el resto se conectan por la red local del establecimiento, que sigue funcionando aunque no haya internet.",
      "Para la sincronización con la tienda online o entre tiendas, el programa aprovecha la conexión cuando está disponible y espera si no lo está.",
    ],
    faqs=[
      ("¿Y si se rompe el ordenador? ¿Pierdo todo?",
       "Solo si no haces copias, exactamente igual que con cualquier otro sistema. Por eso la copia de seguridad automática es lo primero que hay que configurar, y conviene que una de las copias salga del local: un disco externo que te llevas o una carpeta sincronizada en la nube. Con la copia al día, restaurar en otro equipo es cuestión de minutos."),
      ("¿VeriFactu no obliga a estar conectado con Hacienda?",
       "No en tiempo real de forma permanente. El sistema contempla el envío de los registros de facturación y también el modo de facturación verificable con QR; un corte puntual de conexión no te impide emitir tickets. Consulta con tu asesor el escenario concreto de tu actividad, porque los plazos y obligaciones dependen de tu situación fiscal."),
      ("¿Puedo consultar las ventas desde casa si los datos están en la tienda?",
       "Con la versión de PC necesitarías acceso remoto al equipo. Si consultar desde fuera es importante para ti, ahí es donde Caja 5 Nube tiene sentido. Mucha gente combina: caja en local para no depender de la línea y consulta remota puntual."),
      ("¿Funciona en un ordenador antiguo?",
       "Suele funcionar en equipos modestos con Windows, que es precisamente una de las razones por las que se elige. Antes de comprar, descarga la demo e instálala en el ordenador que piensas usar: es la única forma fiable de saberlo."),
    ],
    rel=[("Caja 5 para PC","/caja5_pc.asp"),
         ("TPV en la nube o en tu PC","/comparativa_tpv_nube.asp"),
         ("Alternativa a TPV por suscripción","/alternativa-tpv-suscripcion.asp"),
         ("Qué es VeriFactu","/verifactu-tpv.asp")]),

"etiquetas-codigo-de-barras-tpv": dict(
    titulo="Etiquetas con Código de Barras para tu Tienda | TPV Caja 5",
    h1="Etiquetas con código de barras: colgador, adhesiva y escaparate",
    desc="Diseña e imprime etiquetas con código de barras desde el TPV: adhesivas, de colgador con talla y color, y carteles de precio para escaparate y rebajas.",
    kw="etiquetas codigo de barras tienda, imprimir etiquetas tpv, etiqueta colgador ropa, cartel precio escaparate, generar codigo barras ean13, impresora etiquetas comercio",
    badge="ETIQUETADO Y CÓDIGOS DE BARRAS",
    sub="Etiquetar bien no es estética: es la diferencia entre cobrar en tres segundos con lector y teclear el precio a mano equivocándote.",
    intro=[
      "Muchas tiendas pequeñas siguen etiquetando a mano con pistola de precios. Funciona hasta que el catálogo crece: entonces empiezan los errores de precio en caja, las devoluciones sin saber qué artículo era y un inventario anual que se convierte en una tortura de dos días.",
      "Generar tu propio código de barras y etiquetar cada artículo cuesta menos de lo que parece y cambia por completo la operativa de la tienda. En caja pasas el lector; en el inventario pasas el lector; en las rebajas cambias el precio en el programa y reimprimes.",
    ],
    bullets=[
      ("Códigos propios o del fabricante", "Si el artículo trae EAN13 lo aprovechas; si no, el programa genera uno interno que no colisiona."),
      ("Etiqueta adhesiva pequeña", "El formato clásico de 28x17 mm para complementos, perfumería, papelería o ferretería."),
      ("Etiqueta de colgador", "Con modelo, talla, color, composición y precio, pensada para prenda colgada."),
      ("Cartel de escaparate", "Precios grandes con antes y después para rebajas y promociones."),
      ("Impresión por lotes", "Imprimes las etiquetas de toda una entrada de mercancía de una sola vez."),
    ],
    como=[
      "Al dar de alta el artículo, el programa asigna o genera su código de barras.",
      "Eliges el diseño de etiqueta y ajustas qué campos aparecen: precio, talla, color, referencia, composición o el logo de la tienda.",
      "Seleccionas los artículos a etiquetar, normalmente los de un albarán de entrada, e indicas cuántas etiquetas por artículo.",
      "Imprimes en una impresora térmica de etiquetas o en una láser con hojas troqueladas, según el volumen que manejes.",
    ],
    faqs=[
      ("¿Puedo crear códigos de barras si mis artículos no traen ninguno?",
       "Sí. El programa genera códigos internos para tu tienda. Es lo habitual en moda de proveedor pequeño, artesanía, bisutería o segunda mano, donde el artículo no viene con EAN de fábrica."),
      ("¿Qué impresora de etiquetas necesito?",
       "Para volumen medio o alto compensa una térmica de etiquetas, que no gasta tinta. Para volumen bajo puedes empezar con hojas troqueladas en una impresora láser normal. Caja 5 no obliga a marca concreta: si Windows la reconoce, imprime."),
      ("¿Se pueden imprimir etiquetas de rebajas con el precio anterior tachado?",
       "Sí, y conviene hacerlo porque la normativa de venta en rebajas exige informar del precio anterior. Los diseños de cartel y etiqueta permiten mostrar precio original y precio rebajado."),
      ("¿La etiqueta puede llevar el logo de mi tienda?",
       "Sí, puedes incluir tu logotipo y texto fijo. En el formato de colgador es lo habitual, porque la etiqueta acaba siendo parte de la imagen de la prenda."),
    ],
    rel=[("Matriz de tallas y colores","/matriz-tallas-y-colores.asp"),
         ("Impresoras y lectores compatibles","/impresoras-tickets-y-lectores-compatibles.asp"),
         ("Inventario con PDA o lector","/inventario-con-pda-lector-codigo-barras.asp"),
         ("App de etiquetas QL5","/app_etiquetas_ql5.asp")]),

"inventario-con-pda-lector-codigo-barras": dict(
    titulo="Inventario con PDA o Lector de Código de Barras | Caja 5",
    h1="Inventario con PDA: contar la tienda sin cerrar dos días",
    desc="Cómo hacer el inventario con PDA o lector de código de barras: recuento por zonas, comparación con stock teórico e informe de descuadres y mermas.",
    kw="inventario con pda, hacer inventario tienda lector, recuento stock codigo barras, inventario tienda ropa, descuadre stock, control mermas comercio",
    badge="INVENTARIO Y RECUENTO",
    sub="El inventario a papel y boli tarda el triple y falla el doble. Con lector o PDA, contar la tienda pasa de ser un fin de semana perdido a un par de horas.",
    intro=[
      "El inventario es el momento en que descubres la verdad: cuánto género tienes de verdad frente a lo que dice el programa. La diferencia entre ambos números tiene nombre, merma, y suele repartirse entre robo, roturas, errores de caja y entradas mal registradas.",
      "Hacerlo con lector cambia la escala del problema. En vez de anotar referencias a mano y teclearlas después, vas pasando el lector por las etiquetas y el recuento se construye solo. Al terminar, el informe de diferencias te dice exactamente en qué artículos y en qué combinaciones falla.",
    ],
    bullets=[
      ("Recuento por zonas", "Cuentas la tienda por secciones o familias, sin bloquear la caja ni cerrar el local."),
      ("Lector fijo o PDA", "Con el lector del mostrador o con una PDA que te llevas por la tienda y la trastienda."),
      ("Comparación automática", "El programa enfrenta lo contado con el stock teórico y te da la diferencia por artículo."),
      ("Informe de mermas", "Sabes cuánto dinero has perdido y en qué familias se concentra."),
      ("Ajuste con un clic", "Validado el recuento, el stock se regulariza y queda registro del ajuste."),
    ],
    como=[
      "Preparas el recuento indicando qué almacén o qué familias vas a contar.",
      "Vas leyendo las etiquetas con el lector o la PDA. Si un artículo no está etiquetado, aparece y lo resuelves en el momento.",
      "Repites por zonas hasta cubrir la tienda; los recuentos parciales se van acumulando.",
      "Revisas el informe de diferencias antes de aplicar nada: muchas veces el descuadre es un error de registro y no una pérdida real.",
      "Validas y el programa ajusta el stock dejando constancia del movimiento.",
    ],
    faqs=[
      ("¿Cada cuánto conviene hacer inventario?",
       "El inventario completo, una vez al año como mínimo, y en moda lo lógico es al cerrar temporada. Además compensa hacer recuentos parciales frecuentes de las familias con más rotación o más valor: contar la vitrina de joyería cada semana cuesta diez minutos y detecta problemas cuando aún se pueden resolver."),
      ("¿Necesito comprar una PDA cara?",
       "No necesariamente. Puedes hacer el recuento con el lector del mostrador si el género se puede acercar, o con una PDA de gama básica. Lo importante es que la PDA sea compatible con tu forma de trabajar; te podemos orientar por teléfono antes de que compres nada."),
      ("¿Puedo contar mientras la tienda está abierta?",
       "Sí, contando por zonas en horas de poca afluencia. Ten en cuenta que si vendes un artículo de una zona ya contada el dato se mueve; por eso conviene contar secciones completas de una vez y validar al terminar cada una."),
      ("¿Qué hago si el descuadre es enorme?",
       "Antes de dar nada por perdido, revisa las entradas de mercancía del periodo: el motivo más frecuente de un descuadre grande no es el robo, es un albarán que se registró dos veces o que no se registró. El informe te deja ver el histórico de movimientos de cada artículo."),
    ],
    rel=[("Cómo hacer el inventario de una tienda","/como-hacer-un-inventario-tienda.asp"),
         ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
         ("Etiquetas con código de barras","/etiquetas-codigo-de-barras-tpv.asp"),
         ("Impresoras y lectores compatibles","/impresoras-tickets-y-lectores-compatibles.asp")]),

"vales-y-tarjetas-regalo-tpv": dict(
    titulo="Vales de Devolución y Tarjetas Regalo en el TPV | Caja 5",
    h1="Vales de devolución y tarjetas regalo controlados de verdad",
    desc="Gestiona vales por devolución y tarjetas regalo desde el TPV: saldo, caducidad, canje parcial y control antifraude. Sin papeles ni libretas.",
    kw="vales de devolucion tienda, tarjeta regalo comercio, vale regalo tpv, control vales tienda ropa, cambio sin ticket, saldo a favor cliente",
    badge="VALES Y TARJETAS REGALO",
    sub="El vale escrito a mano es un agujero: no sabes cuántos hay vivos, ni por cuánto, ni si alguno se ha canjeado dos veces.",
    intro=[
      "Cualquier tienda de moda vive de los cambios. Y el cambio suele acabar en un vale, que en muchos comercios sigue siendo un papel con un sello. Ese papel no está contabilizado en ninguna parte: no sabes cuánto dinero tienes comprometido en vales pendientes, ni puedes evitar que se canjee dos veces.",
      "Gestionar los vales desde el TPV convierte ese papel en un documento con número, saldo y caducidad. Al canjearlo, el programa comprueba que está vivo y descuenta el importe. Y en cualquier momento sabes cuánto debes en vales, que es un pasivo real de tu negocio.",
    ],
    bullets=[
      ("Vale con número y código", "Cada vale se identifica con un código que se lee en caja, sin teclear nada."),
      ("Canje parcial", "Si el vale es de 40 € y compra por 25 €, el resto queda como saldo disponible."),
      ("Caducidad controlada", "Defines la validez y el programa avisa si está caducado al intentar canjearlo."),
      ("Tarjetas regalo con saldo", "Vendes tarjetas regalo por el importe que quiera el cliente y se recargan si hace falta."),
      ("Informe de vales vivos", "Sabes en todo momento cuánto dinero tienes comprometido en vales sin canjear."),
    ],
    como=[
      "En la devolución, en lugar de devolver efectivo, generas un vale por el importe.",
      "El programa imprime el vale con su código de barras y su fecha de validez.",
      "Cuando el cliente vuelve, se lee el vale en caja y se aplica al ticket.",
      "Si sobra saldo, el vale sigue vivo con el resto; si se agota, queda cerrado y no puede reutilizarse.",
      "Periódicamente consultas el informe de vales pendientes para saber tu compromiso real.",
    ],
    faqs=[
      ("¿Estoy obligado a aceptar devoluciones y dar vales?",
       "En compra en tienda física, si el producto no es defectuoso, la política de cambios y devoluciones la fijas tú, pero debes informarla claramente antes de la venta (por ejemplo, en el ticket y en un cartel visible). Si el producto es defectuoso, se aplica la garantía legal y ahí no decides tú. Consúltalo con tu asesor para tu caso concreto."),
      ("¿Puedo poner caducidad a una tarjeta regalo?",
       "Puedes establecer condiciones de validez, pero infórmalas de forma clara y visible en el momento de la venta y en la propia tarjeta. Las condiciones no informadas dan problemas con el cliente y con consumo; las informadas con claridad, no."),
      ("¿Qué pasa si un cliente pierde el vale?",
       "Como el vale está registrado con su número y a nombre del cliente si lo identificaste, puedes localizarlo y reimprimirlo anulando el anterior. Es justo la ventaja frente al papel con sello: el papel perdido no se puede reconstruir."),
      ("¿Los vales cuentan como venta?",
       "La entrega del vale no es un ingreso nuevo, es un compromiso; el ingreso se produjo en la venta original. Por eso el informe de vales vivos es útil para tu contabilidad. Concreta el tratamiento contable exacto con tu asesor fiscal."),
    ],
    rel=[("Programa de fidelización y puntos","/programa-fidelizacion-puntos.asp"),
         ("TPV con gestión de clientes","/negocio_gestion_clientes.asp"),
         ("Software TPV para tiendas de ropa","/negocio_moda.asp"),
         ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp")]),

"rebajas-y-promociones-tpv": dict(
    titulo="Rebajas y Promociones en el TPV: cómo aplicarlas | Caja 5",
    h1="Rebajas, 2x1 y promociones sin cambiar los precios a mano",
    desc="Aplica rebajas por porcentaje, 2x1, descuentos por familia y precios por temporada desde el TPV, con precio anterior en el ticket y vuelta atrás automática.",
    kw="rebajas tpv tienda, aplicar descuento por familia, promocion 2x1 tpv, precio anterior rebajas, campaña descuentos comercio, black friday tienda",
    badge="REBAJAS Y PROMOCIONES",
    sub="Cambiar 800 precios a mano el 7 de enero y volver a cambiarlos en febrero es la manera más rápida de equivocarse. Se hace por campaña, con fecha de inicio y de fin.",
    intro=[
      "Las rebajas mal gestionadas cuestan dinero de dos maneras: por los errores de precio en caja y por no saber después qué margen real dejó la campaña. Si bajas los precios machacando el precio original, pierdes la referencia y ya no puedes calcular cuánto has sacrificado.",
      "La forma correcta es tratar la rebaja como una campaña con fechas: el precio original se conserva, se aplica un descuento por familia, marca o temporada, y al terminar la campaña los precios vuelven solos.",
    ],
    bullets=[
      ("Descuento por familia o marca", "Aplicas un 30 % a toda la temporada anterior sin tocar artículo por artículo."),
      ("Fechas de inicio y fin", "La campaña se activa y se desactiva sola; no dependes de acordarte."),
      ("Precio anterior en el ticket", "El ticket refleja el precio original y el rebajado, como pide la normativa de rebajas."),
      ("Promociones por cantidad", "2x1, 3x2 o segunda unidad al 50 %, calculadas automáticamente en caja."),
      ("Margen real por campaña", "Al cerrar sabes cuánto vendiste, con qué descuento medio y qué margen quedó."),
    ],
    como=[
      "Creas la campaña indicando qué artículos entran: por familia, marca, temporada o selección manual.",
      "Defines el tipo de descuento (porcentaje, importe fijo o precio de campaña) y las fechas.",
      "El TPV aplica el precio rebajado automáticamente durante ese periodo.",
      "Al terminar, los precios recuperan su valor original sin que tengas que hacer nada.",
      "Consultas el informe de la campaña para decidir qué repetir el año siguiente.",
    ],
    faqs=[
      ("¿Tengo que mostrar el precio anterior en rebajas?",
       "La normativa española de venta en rebajas exige informar del precio anterior junto al rebajado. El programa lo imprime en la etiqueta y en el cartel, pero verifica los requisitos concretos vigentes con tu asesor o con la normativa autonómica que te aplique, porque hay matices por comunidad."),
      ("¿Puedo hacer promociones solo para clientes fidelizados?",
       "Sí. Puedes condicionar una campaña a que el cliente esté identificado, que es la base de las preventas de rebajas para el club de clientes."),
      ("¿Cómo aplico un 2x1 sin liarla en caja?",
       "Se configura como promoción por cantidad sobre un grupo de artículos. El dependiente pasa las dos prendas y el descuento se aplica solo; no tiene que calcular nada ni acordarse de la condición."),
      ("¿Se puede rebajar solo el stock de la temporada pasada?",
       "Sí, y es lo más habitual. Si tienes bien informado el campo de temporada en las fichas, la campaña se define en un minuto: temporada anterior al 40 %, temporada actual sin descuento."),
    ],
    rel=[("Etiquetas y carteles de escaparate","/etiquetas-codigo-de-barras-tpv.asp"),
         ("Programa de fidelización y puntos","/programa-fidelizacion-puntos.asp"),
         ("Software TPV para tiendas de ropa","/negocio_moda.asp"),
         ("Control de stock multialmacén","/control-de-stock-multialmacen.asp")]),

"arqueo-de-caja-cierre-diario": dict(
    titulo="Arqueo de Caja y Cierre Diario en el TPV | Caja 5",
    h1="Arqueo de caja: cuadrar el día en cinco minutos",
    desc="Cierre de caja diario en el TPV: arqueo por medio de pago, descuadres, entradas y salidas de efectivo, informe Z y control por dependiente.",
    kw="arqueo de caja, cierre de caja diario, cuadrar caja tienda, informe z tpv, descuadre caja, control efectivo comercio",
    badge="ARQUEO Y CIERRE DE CAJA",
    sub="Cuadrar la caja no es contar billetes: es saber cuánto debería haber, por qué medio de pago, y qué ha pasado si no coincide.",
    intro=[
      "El cierre de caja es el control diario más básico de una tienda y el que más se descuida. Contar el efectivo y meterlo en un sobre no es un arqueo: un arqueo es comparar lo que hay con lo que debería haber según las ventas, separando efectivo, tarjeta y otros medios de pago.",
      "Cuando el cierre se hace bien todos los días, un descuadre de veinte euros salta el mismo día y se puede investigar. Cuando se hace mal, los descuadres se acumulan hasta que la única conclusión posible es «falta dinero» sin saber de dónde.",
    ],
    bullets=[
      ("Arqueo por medio de pago", "Efectivo, tarjeta, bizum, vale o mixto, cada uno con su total esperado."),
      ("Entradas y salidas de efectivo", "Registras el cambio inicial, los pagos a proveedor en efectivo y las retiradas."),
      ("Descuadre visible", "El programa te dice la diferencia exacta entre lo contado y lo esperado."),
      ("Cierre por dependiente", "Si hay varios turnos, cada uno cuadra lo suyo y las responsabilidades quedan claras."),
      ("Histórico de cierres", "Puedes revisar cualquier día anterior y ver quién cerró y con qué diferencia."),
    ],
    como=[
      "Al abrir, registras el fondo de caja inicial.",
      "Durante el día, cualquier entrada o salida de efectivo que no sea una venta se registra (pago a un proveedor, compra de material, retirada al banco).",
      "Al cerrar, cuentas el efectivo e introduces el importe contado.",
      "El programa compara con lo esperado y muestra el descuadre por medio de pago.",
      "Validas el cierre y queda guardado con fecha, hora y usuario.",
    ],
    faqs=[
      ("¿Qué hago si la caja descuadra todos los días por poco?",
       "Un descuadre pequeño y constante suele venir de tres sitios: cambio mal dado, ventas cobradas en efectivo y anotadas como tarjeta, o salidas de efectivo sin registrar. Revisa primero si las salidas de dinero para gastos menores se están registrando, que es la causa más frecuente."),
      ("¿Puedo saber qué dependiente cerró cada día?",
       "Sí, si trabajas con usuarios identificados. Cada cierre queda asociado a quien lo hizo, lo que no es cuestión de desconfianza sino de poder reconstruir qué pasó un día concreto."),
      ("¿El arqueo sirve como justificante contable?",
       "El informe de cierre es tu control interno y la base para el resumen que le pasas a tu asesor, pero el soporte fiscal son las facturas y tickets emitidos. Habla con tu asesoría sobre qué documentación concreta necesita de ti cada mes."),
      ("¿Se puede cerrar caja varias veces al día?",
       "Sí, es lo normal si hay dos turnos. Cada turno hace su arqueo y el programa mantiene el histórico de ambos, de forma que el descuadre queda acotado al turno en el que se produjo."),
    ],
    rel=[("Software TPV para comercios","/caja5_pc.asp"),
         ("Ley Antifraude y TPV","/ley-antifraude-tpv.asp"),
         ("Qué es VeriFactu","/verifactu-tpv.asp"),
         ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp")]),

"gestion-de-proveedores-y-pedidos": dict(
    titulo="Gestión de Proveedores y Pedidos de Compra | TPV Caja 5",
    h1="Proveedores y pedidos: comprar lo que se vende, no lo que sobra",
    desc="Gestión de proveedores en el TPV: pedidos de compra, recepción de albaranes, control de precios de coste, plazos de entrega y sugerencia de reposición.",
    kw="gestion de proveedores tienda, pedido de compra tpv, albaran entrada mercancia, precio de coste articulo, reposicion automatica stock, control compras comercio",
    badge="COMPRAS Y PROVEEDORES",
    sub="El margen de una tienda se decide al comprar, no al vender. Si no sabes qué rota y qué no, acabas repitiendo el pedido del año pasado.",
    intro=[
      "En comercio minorista, el dinero se pierde en la compra mucho antes que en la venta. Comprar de más inmoviliza caja y termina en rebajas; comprar de menos rompe stock justo en lo que más se vende. La diferencia entre una cosa y otra es tener el histórico delante al hacer el pedido.",
      "Llevar los proveedores dentro del TPV te permite hacer el pedido mirando lo que realmente pasó: qué se vendió, en qué tallas, a qué ritmo y con qué margen. Y al recibir la mercancía, el albarán actualiza el stock y los precios de coste sin doble trabajo.",
    ],
    bullets=[
      ("Ficha completa de proveedor", "Condiciones, plazos, descuentos y artículos que le compras habitualmente."),
      ("Pedido de compra", "Generas el pedido desde el programa y lo envías; queda pendiente hasta que llegue."),
      ("Recepción de albarán", "Al recibir, confirmas cantidades reales y el stock se actualiza con lo que llegó de verdad."),
      ("Control de precio de coste", "Si el proveedor sube precios, lo ves al recepcionar y decides si repercutes en el PVP."),
      ("Sugerencia de reposición", "El programa propone qué reponer según stock mínimo y ventas del periodo."),
    ],
    como=[
      "Das de alta al proveedor con sus condiciones y asocias sus artículos.",
      "Al preparar la temporada o la reposición, consultas el informe de rotación por artículo y combinación.",
      "Generas el pedido de compra con las cantidades que decidas y lo envías al proveedor.",
      "Cuando llega la mercancía, recepcionas el albarán marcando lo que ha venido realmente; el stock sube y las diferencias con el pedido quedan registradas.",
      "Etiquetas la entrada directamente desde el albarán recibido.",
    ],
    faqs=[
      ("¿Puedo saber qué proveedor me deja más margen?",
       "Sí. Como el programa guarda el precio de coste y el de venta de cada artículo asociado a su proveedor, el informe de márgenes por proveedor te dice con quién ganas dinero de verdad, que muchas veces no coincide con quién te vende más volumen."),
      ("¿Qué pasa si llega menos mercancía de la pedida?",
       "Recepcionas lo que ha llegado y el pedido queda parcialmente servido. El pendiente sigue registrado, así que no se te olvida reclamarlo ni lo cuentas como stock disponible."),
      ("¿Puedo llevar precios de coste distintos del mismo artículo?",
       "Sí, es lo habitual cuando compras el mismo producto a distintos proveedores o con distintos descuentos. El programa mantiene el histórico de costes para que la valoración de inventario sea realista."),
      ("¿Sirve para hacer pedidos a depósito?",
       "Puedes registrar la entrada de mercancía en depósito para tenerla controlada en stock y liquidarla al proveedor según se venda. Es común en joyería, óptica y librería. Cómo lo documentes fiscalmente conviene acordarlo con tu asesor."),
    ],
    rel=[("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
         ("Inventario con PDA","/inventario-con-pda-lector-codigo-barras.asp"),
         ("Rebajas y promociones","/rebajas-y-promociones-tpv.asp"),
         ("Cómo abrir una tienda de ropa","/guia-abrir-tienda-de-ropa.asp")]),
}


HARDWARE = {
"impresora-tickets-compatible-tpv": dict(
    titulo="Impresora de Tickets para TPV: cuál comprar y compatibilidad | Caja 5",
    h1="Impresora de tickets: qué comprar y cómo conectarla al TPV",
    desc="Guía para elegir impresora de tickets térmica para tu TPV: conexión USB, red o serie, ancho de papel 58 u 80 mm, corte automático y compatibilidad Windows.",
    kw="impresora de tickets tpv, impresora termica comercio, impresora tickets 80mm, impresora ticket usb, compatibilidad impresora tpv, papel termico ticket",
    badge="IMPRESORA DE TICKETS",
    sub="La regla práctica: si Windows la reconoce e imprime una página de prueba, Caja 5 imprime tickets con ella.",
    intro=[
      "La impresora de tickets es el periférico que más se avería en una tienda, porque es el que más trabaja. Elegir bien la primera vez ahorra bastantes disgustos, y no siempre significa gastar más.",
      "Lo relevante es que sea térmica (sin tinta, imprime por calor sobre papel térmico), que tenga corte automático si vas a emitir muchos tickets, y que el ancho de papel encaje con lo que ya compras. Y sobre todo, que el fabricante ofrezca un driver de Windows en condiciones.",
    ],
    bullets=[
      ("Térmica, no matricial", "Más rápida, más silenciosa y sin cambiar cintas. El papel es el consumible."),
      ("Ancho 80 mm o 58 mm", "El de 80 mm es el estándar de comercio; el de 58 mm es más barato pero se queda corto."),
      ("Corte automático", "Imprescindible si emites más de treinta o cuarenta tickets al día."),
      ("Conexión USB, red o serie", "USB para un puesto; red si quieres compartirla entre varias cajas."),
      ("Driver de Windows", "Es lo que de verdad determina la compatibilidad, más que la marca."),
    ],
    como=[
      "Instalas el driver de Windows que facilita el fabricante de la impresora.",
      "Imprimes una página de prueba desde Windows: si sale, el resto es configuración.",
      "En Caja 5 seleccionas esa impresora como impresora de tickets y ajustas el ancho del papel.",
      "Configuras la cabecera del ticket con tus datos fiscales, el logotipo y el pie con la política de cambios.",
      "Imprimes un ticket de prueba y ajustas márgenes si hiciera falta.",
    ],
    faqs=[
      ("¿Sirve cualquier marca de impresora de tickets?",
       "En la práctica, sí: si tiene driver de Windows y aparece en la lista de impresoras del sistema, Caja 5 imprime con ella. No obligamos a comprar hardware propio ni de una marca concreta, que es justo lo contrario de lo que hacen algunas plataformas con hardware cerrado."),
      ("¿Puedo usar la impresora que ya tengo?",
       "Si es térmica de tickets y funciona en Windows, casi con seguridad sí. Antes de comprar nada, descarga la demo e imprime un ticket de prueba con tu equipo actual: sale de dudas en cinco minutos."),
      ("¿El ticket con QR de VeriFactu cabe en papel de 58 mm?",
       "Cabe, pero queda muy justo y el código puede leerse peor. Si vas a emitir facturas simplificadas con QR reglamentario, el papel de 80 mm es la opción sensata."),
      ("¿Necesito una impresora distinta para facturas A4?",
       "Sí, para facturas completas en A4 necesitas una impresora normal, que puede ser la que ya tengas en el despacho. Caja 5 permite tener una impresora para tickets y otra para documentos A4."),
    ],
    rel=[("Impresoras y lectores compatibles","/impresoras-tickets-y-lectores-compatibles.asp"),
         ("Lector de código de barras","/lector-codigo-barras-compatible-tpv.asp"),
         ("Cajón portamonedas","/cajon-portamonedas-tpv.asp"),
         ("Qué es VeriFactu","/verifactu-tpv.asp")]),

"lector-codigo-barras-compatible-tpv": dict(
    titulo="Lector de Código de Barras para TPV: cuál elegir | Caja 5",
    h1="Lector de código de barras: láser, CCD o 2D para tu tienda",
    desc="Qué lector de código de barras comprar para el TPV: láser o imager, con cable o inalámbrico, lectura de QR y compatibilidad plug and play con Windows.",
    kw="lector codigo de barras tpv, pistola codigo barras tienda, escaner codigo barras usb, lector inalambrico comercio, lector 2d qr, lector compatible windows",
    badge="LECTOR DE CÓDIGO DE BARRAS",
    sub="Un lector se comporta como un teclado: escribe el código y pulsa intro. Por eso casi cualquiera funciona sin instalar nada.",
    intro=[
      "El lector de código de barras es, con diferencia, la inversión que más rápido se amortiza en una tienda. Pasa de teclear referencias a leerlas, y con ello desaparecen los errores de precio en caja y el inventario deja de ser una pesadilla.",
      "Técnicamente son sencillos: la inmensa mayoría se conectan por USB y el sistema los ve como un teclado, así que no hay drivers ni configuraciones raras. Las diferencias importantes están en el tipo de lectura y en si necesitas moverte con él.",
    ],
    bullets=[
      ("Láser o imager (CCD)", "El láser va muy bien con etiquetas planas; el imager lee también códigos arrugados o en pantalla."),
      ("1D o 2D", "El 2D lee además QR y DataMatrix, útil si aceptas cupones o entradas en el móvil."),
      ("Con cable o inalámbrico", "Con cable para mostrador; inalámbrico si vas a contar género por la tienda."),
      ("Soporte de sobremesa", "Deja el lector fijo leyendo en cuanto acercas el artículo, sin cogerlo con la mano."),
      ("Plug and play", "Se comporta como un teclado: lo conectas y ya escribe el código donde tengas el cursor."),
    ],
    como=[
      "Conectas el lector por USB y esperas a que Windows lo reconozca.",
      "Abres el bloc de notas y lees una etiqueta: si aparece el número, ya está listo.",
      "En Caja 5 sitúas el cursor en el campo de búsqueda de artículo y lees: el artículo entra en el ticket.",
      "Si el lector añade caracteres raros o no salta de línea, se corrige leyendo los códigos de configuración del manual del propio lector.",
    ],
    faqs=[
      ("¿Necesito instalar algún programa para el lector?",
       "Normalmente no. Los lectores USB estándar se comportan como un teclado y funcionan directamente. Si el tuyo trae software propio, casi siempre es opcional."),
      ("¿Puedo leer códigos desde la pantalla del móvil de un cliente?",
       "Solo con un lector 2D de tipo imager. Los lectores láser clásicos no leen bien sobre pantalla. Si vas a trabajar con cupones digitales o entradas en el móvil, compra directamente un 2D."),
      ("¿Me sirve para hacer el inventario?",
       "Sí. Con un lector inalámbrico puedes recorrer la tienda leyendo etiquetas. Si el almacén es grande o está lejos del mostrador, una PDA con almacenamiento propio es más cómoda."),
      ("¿Y si mis artículos no tienen código de barras?",
       "Los generas tú desde el programa y los imprimes en etiqueta. Es lo habitual en moda de proveedor pequeño, artesanía o segunda mano."),
    ],
    rel=[("Etiquetas con código de barras","/etiquetas-codigo-de-barras-tpv.asp"),
         ("Inventario con PDA o lector","/inventario-con-pda-lector-codigo-barras.asp"),
         ("Impresora de tickets","/impresora-tickets-compatible-tpv.asp"),
         ("Impresoras y lectores compatibles","/impresoras-tickets-y-lectores-compatibles.asp")]),

"cajon-portamonedas-tpv": dict(
    titulo="Cajón Portamonedas para TPV: conexión y apertura | Caja 5",
    h1="Cajón portamonedas: cómo se conecta y cuándo se abre",
    desc="Cómo conectar un cajón portamonedas al TPV mediante la impresora de tickets (puerto RJ11), apertura automática al cobrar y control de aperturas sin venta.",
    kw="cajon portamonedas tpv, cajon monedero comercio, conectar cajon impresora rj11, apertura automatica cajon, cajon registradora, control aperturas caja",
    badge="CAJÓN PORTAMONEDAS",
    sub="Casi nadie lo sabe la primera vez: el cajón no se conecta al ordenador, se conecta a la impresora de tickets.",
    intro=[
      "El cajón portamonedas es el periférico más simple del mostrador y el que más dudas genera al montar el TPV, porque su conexión no es la que uno esperaría. La inmensa mayoría de cajones no tienen USB: llevan un conector RJ11, parecido a un cable de teléfono, que va a la parte trasera de la impresora de tickets.",
      "La impresora es la que abre el cajón enviándole un impulso eléctrico cuando el programa se lo pide, normalmente justo al imprimir el ticket. Por eso, si el cajón no abre, el problema casi siempre está en la configuración de la impresora y no en el cajón.",
    ],
    bullets=[
      ("Conexión RJ11 a la impresora", "El cable va del cajón al puerto DK de la impresora de tickets, no al PC."),
      ("Apertura automática al cobrar", "Se abre al cerrar la venta en efectivo, sin que el dependiente haga nada."),
      ("Apertura manual controlada", "Puedes permitir abrirlo sin venta, dejando registro de quién lo hizo y cuándo."),
      ("Bandeja configurable", "Compartimentos para billetes y monedas según cómo trabajes."),
      ("Cierre con llave", "Para bloquearlo al cerrar la tienda o durante ausencias."),
    ],
    como=[
      "Conectas el cable RJ11 del cajón al puerto de la impresora de tickets (suele estar marcado como DK o Cash Drawer).",
      "En Caja 5 activas la apertura del cajón asociada a la impresora.",
      "Defines cuándo debe abrirse: al cobrar en efectivo, en todas las ventas o solo bajo petición.",
      "Configuras si se permite la apertura manual y qué usuarios pueden hacerlo.",
    ],
    faqs=[
      ("Mi cajón no abre, ¿qué reviso primero?",
       "Por orden: que el cable RJ11 esté en el puerto de la impresora y no en el de red, que la impresora esté seleccionada correctamente en el programa, y que la apertura de cajón esté activada en la configuración. En más del noventa por ciento de los casos es una de esas tres cosas."),
      ("¿Puedo tener cajón sin impresora de tickets?",
       "Existen cajones con conexión USB directa, pero son menos comunes y más caros. Si vas a montar el mostrador desde cero, lo estándar y más barato es impresora térmica más cajón por RJ11."),
      ("¿Se puede saber quién ha abierto el cajón?",
       "Si trabajas con usuarios identificados, sí: las aperturas sin venta quedan registradas con usuario y hora. Es un control básico y muy recomendable cuando hay varios dependientes."),
      ("¿El cajón sirve para cualquier impresora?",
       "El conector RJ11 es un estándar de hecho en impresoras de tickets, así que la compatibilidad es muy alta. Comprueba solo que tu modelo de impresora tenga el puerto de cajón, porque algunos modelos muy básicos no lo llevan."),
    ],
    rel=[("Impresora de tickets","/impresora-tickets-compatible-tpv.asp"),
         ("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
         ("Pack TPV completo","/pack-tpv-completo-comercio.asp"),
         ("Impresoras y lectores compatibles","/impresoras-tickets-y-lectores-compatibles.asp")]),

"tpv-tactil-o-teclado-raton": dict(
    titulo="TPV Táctil o con Teclado y Ratón: qué conviene | Caja 5",
    h1="TPV táctil o teclado y ratón: cuál va mejor en tu mostrador",
    desc="Comparativa entre TPV táctil y TPV con teclado y ratón para comercio: velocidad de cobro, coste del equipo, mantenimiento y aprovechar el PC que ya tienes.",
    kw="tpv tactil, pantalla tactil comercio, tpv con teclado, ordenador para tpv, monitor tactil tienda, que ordenador necesito para tpv",
    badge="EQUIPO Y PANTALLA TÁCTIL",
    sub="La pantalla táctil es cómoda en hostelería, donde se pulsan botones grandes. En una tienda con lector de código de barras, el teclado sigue ganando.",
    intro=[
      "Existe la idea de que un TPV «de verdad» tiene que ser táctil. Viene de la hostelería, donde el camarero pulsa botones de productos en una pantalla y la velocidad depende de eso. En comercio minorista la operativa es distinta: el artículo entra leyendo su código de barras, no pulsando un botón.",
      "Por eso, en una tienda de ropa, una zapatería o una perfumería, un ordenador normal con lector suele ser más rápido y bastante más barato que un terminal táctil. La pantalla táctil aporta cuando vendes pocos artículos repetidos sin código de barras.",
    ],
    bullets=[
      ("Táctil, mejor para catálogo corto", "Si vendes veinte cosas sin etiqueta, los botones en pantalla ganan."),
      ("Teclado y lector, mejor para catálogo largo", "Con miles de referencias etiquetadas, el lector es imbatible."),
      ("Aprovecha el PC que tengas", "Caja 5 funciona en equipos Windows corrientes; no obliga a comprar terminal."),
      ("Coste muy distinto", "Un terminal táctil de comercio multiplica el precio de un PC normal con monitor."),
      ("Mantenimiento", "Un PC estándar lo repara cualquier técnico; un terminal cerrado depende del fabricante."),
    ],
    como=[
      "Valora cuántas referencias manejas: si están etiquetadas con código de barras, el táctil aporta poco.",
      "Si vas a montar mostrador nuevo, calcula el coste completo: equipo, monitor, impresora, cajón y lector.",
      "Prueba la demo en el ordenador que ya tienes antes de comprar nada nuevo.",
      "Si finalmente eliges táctil, comprueba que el monitor sea táctil reconocido por Windows; Caja 5 funcionará igual.",
    ],
    faqs=[
      ("¿Qué ordenador necesito para el TPV?",
       "Un equipo Windows corriente y en buen estado suele bastar para una tienda de un puesto. Más importante que la potencia es que el disco sea SSD y que el equipo no esté saturado de programas: eso nota más en la velocidad de caja que el procesador."),
      ("¿Puedo usar una tablet como TPV?",
       "Caja 5 para PC es una aplicación de Windows; en tablets Windows funciona. Si lo que quieres es trabajar desde un iPad o una tablet Android, la vía es Caja 5 Nube, que se usa desde el navegador."),
      ("¿Merece la pena comprar un terminal TPV todo en uno?",
       "Si el mostrador es pequeño y valoras el orden estético, sí, porque integra pantalla y ordenador. Si buscas el mejor precio y facilidad de reparación, un PC normal con monitor cumple exactamente igual."),
      ("¿Y si se me estropea el equipo, pierdo el programa?",
       "No. La licencia es tuya y se reinstala en otro equipo. Lo que no debes perder son los datos: por eso la copia de seguridad automática es lo primero que hay que dejar configurado."),
    ],
    rel=[("Caja 5 para PC","/caja5_pc.asp"),
         ("Pack TPV completo para comercio","/pack-tpv-completo-comercio.asp"),
         ("Impresora de tickets","/impresora-tickets-compatible-tpv.asp"),
         ("TPV sin internet","/tpv-sin-internet-modo-offline.asp")]),
}
