# -*- coding: utf-8 -*-
"""Cluster «abrir un negocio», lote 1. Cada pagina escrita entera para su oficio."""

ABRIR_1 = {

"abrir-tienda-de-ropa.asp": dict(
  nom="una tienda de ropa", crumb="Tienda de ropa", icono="fa-shirt",
  page="negocio_moda.asp",
  title="Cómo Abrir una Tienda de Ropa: costes y trámites",
  desc="Cómo abrir una tienda de ropa en España: inversión real, compra de primera temporada, trámites, errores de stock y qué tener listo antes del primer día.",
  kw="abrir tienda de ropa, montar tienda de ropa, cuanto cuesta abrir una tienda de ropa, tramites tienda ropa, negocio tienda de ropa",
  h1="Cómo abrir una tienda de ropa",
  sub="El error que más tiendas cierra no es el alquiler ni la decoración: es comprar mal la primera temporada y quedarse sin caja en febrero.",
  bloques=[
    ("La primera compra decide el primer año",
     ["Antes de pensar en el rótulo, haz esta cuenta: cuánto vas a inmovilizar en género y cuántos meses tardas en recuperarlo. En moda, entre que compras la temporada y la cobras vendida pueden pasar cinco o seis meses, y las rebajas se llevan una parte del margen que ya dabas por hecho.",
      "La tentación del primer año es comprar variedad: muchos modelos con pocas tallas de cada uno. Es exactamente al revés de lo que funciona. Con pocos modelos y la curva de tallas completa vendes más, porque el cliente que entra encuentra su talla. Con veinte modelos a tres tallas, la mitad de la gente se va con las manos vacías y tú te quedas con la 38 de todo."],
     ["<strong>Compra en profundidad, no en variedad.</strong> Menos modelos con la curva de tallas completa.",
      "<strong>Reserva presupuesto para reposición.</strong> Gastarlo todo en la compra inicial te deja sin poder reponer lo que sí funciona.",
      "<strong>Negocia depósito o pago aplazado</strong> con los proveedores del primer año.",
      "<strong>Calcula el margen después de rebajas</strong>, no el de tarifa."]),
    ("Trámites, en el orden que hay que hacerlos",
     ["El orden importa porque unos dependen de otros. Lo habitual es: alta censal en Hacienda con el epígrafe del IAE que corresponda al comercio textil, alta en el régimen especial de trabajadores autónomos o constitución de la sociedad, y licencia de actividad o declaración responsable en tu ayuntamiento.",
      "Antes de firmar el alquiler, comprueba que el local tenga o pueda tener la licencia para tu actividad. Firmar y descubrir después que el local no es apto es un error caro y sorprendentemente frecuente. Los requisitos concretos varían por municipio y comunidad: llévale esta lista a tu asesor y que te confirme la tuya."],
     ["Alta censal y epígrafe de actividad.",
      "Alta de autónomo o constitución de sociedad.",
      "Licencia de actividad o declaración responsable municipal.",
      "Contrato de alquiler, revisado antes de firmar.",
      "Seguro de responsabilidad civil y de contenido.",
      "Hojas de reclamaciones y cartelería obligatoria a la vista.",
      "Programa de facturación adaptado a VeriFactu antes de tu fecha límite."]),
    ("Cuánto cuesta de verdad",
     ["Para una tienda de barrio de 60 a 80 metros, una horquilla realista está entre 20.000 y 60.000 euros. El reparto habitual: la primera compra de temporada se lleva entre el 40 y el 55 por ciento, la reforma y el mobiliario entre el 20 y el 35, y el resto son fianza, licencias, rótulo y equipamiento.",
      "La partida que casi nadie presupuesta es el colchón. Necesitas dinero para pagar alquiler, autónomos y proveedores durante los meses en que la tienda todavía no factura lo que debería. Seis meses de gastos fijos guardados es lo que separa a quien aguanta el primer bache de quien echa el cierre en el mes ocho."],
     None),
    ("Lo que tiene que estar montado antes de abrir",
     ["El catálogo. Si abres con una libreta y la idea de «ya lo meteremos en el ordenador cuando arranque esto», acabarás con seis meses de ventas sin saber qué se vendió, en qué tallas ni con qué margen. Y montar el catálogo con la tienda ya abierta no lo hace nadie.",
      "Da de alta tus modelos con su matriz de tallas y colores antes del primer día, aunque sea por familias. Desde el primer ticket sabrás qué talla se te agota y qué modelo no se mueve, que es la información con la que se decide la segunda compra. Y con VeriFactu llegando en 2027, empezar ya con un programa adaptado te evita migrar dos veces."],
     None),
  ],
  faqs=[
    ("¿Cuánto dinero necesito para abrir una tienda de ropa?",
     "Para un local de barrio de 60 a 80 metros, entre 20.000 y 60.000 euros según ciudad y estado del local. La primera compra de temporada se lleva casi la mitad. A eso hay que sumarle un colchón de unos seis meses de gastos fijos, que es la partida que más se olvida y la que más cierres provoca."),
    ("¿Qué trámites necesito?",
     "Alta censal con el epígrafe del comercio textil, alta de autónomo o constitución de sociedad, licencia de actividad o declaración responsable municipal, seguro del local y cartelería obligatoria. Comprueba que el local pueda tener licencia para tu actividad antes de firmar el alquiler. Los requisitos varían por municipio: confírmalos con tu asesor."),
    ("¿Es mejor comprar muchos modelos o pocos con todas las tallas?",
     "Pocos modelos con la curva de tallas completa. Es contraintuitivo pero es lo que funciona: si el cliente entra y no está su talla, se va. Con veinte modelos a tres tallas cada uno pierdes la mitad de las ventas posibles y te quedas con las tallas extremas sin vender."),
    ("¿Necesito ya un TPV adaptado a VeriFactu?",
     "En 2026 la adaptación es voluntaria; la obligación llega en enero de 2027 para sociedades y julio de 2027 para autónomos. Si abres ahora, empezar directamente con un programa adaptado te ahorra hacer la migración dos veces."),
    ("¿Puedo empezar sin programa y meterlo más adelante?",
     "Puedes, pero es la decisión que más caro sale. Sin catálogo dado de alta no sabes qué talla se agota ni qué modelo no rota, que es justo lo que necesitas para acertar en la segunda compra. Y montar el catálogo con la tienda abierta no lo hace nadie."),
    ("¿Cuánto tardaré en recuperar la inversión?",
     "Depende demasiado de la ubicación y del acierto en la compra para dar una cifra honesta. Lo que sí puede decirse: en moda el ciclo entre comprar y cobrar vendido es de cinco o seis meses, así que planifica la tesorería con ese calendario y no con el de un negocio de rotación diaria."),
  ],
  rel=[("Software TPV para tiendas de ropa","/negocio_moda.asp"),
       ("Guía para abrir una tienda de ropa","/guia-abrir-tienda-de-ropa.asp"),
       ("Matriz de tallas y colores","/matriz-tallas-y-colores.asp"),
       ("Cómo abrir una zapatería","/abrir-zapateria.asp"),
       ("Pack TPV completo para comercio","/pack-tpv-completo-comercio.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),

"abrir-zapateria.asp": dict(
  nom="una zapatería", crumb="Zapatería", icono="fa-shoe-prints",
  page="negocio_calzado.asp",
  title="Cómo Abrir una Zapatería: inversión y curva de tallas",
  desc="Cómo abrir una zapatería: por qué la inversión inicial es mayor que en ropa, cómo comprar la curva de números, trámites y espacio de almacén necesario.",
  kw="abrir zapateria, montar zapateria, cuanto cuesta abrir una zapateria, negocio zapateria, tramites zapateria",
  h1="Cómo abrir una zapatería",
  sub="Una zapatería necesita más dinero que una tienda de ropa del mismo tamaño, y el motivo es la curva de números: no puedes tener un modelo con tres tallas.",
  bloques=[
    ("Por qué el calzado necesita más capital que la ropa",
     ["Aquí está la diferencia que sorprende a casi todo el que viene de otro comercio. Un modelo de camiseta puede funcionar con cuatro tallas. Un modelo de zapato necesita del 36 al 41 en señora, y del 39 al 45 en caballero, si quieres atender a quien entra. Eso son de seis a ocho pares por modelo solo para tenerlo disponible.",
      "Multiplica por el número de modelos que quieres ofrecer y verás por qué la primera compra de una zapatería es más alta que la de una tienda de ropa del mismo tamaño de local. Y por qué el almacén importa: cada par ocupa su caja."],
     ["<strong>Curva completa por modelo</strong>, o el modelo no se vende.",
      "<strong>Almacén dimensionado</strong>: el género ocupa mucho más volumen que en textil.",
      "<strong>Menos modelos y bien surtidos</strong>, sobre todo el primer año.",
      "<strong>Números centrales con más profundidad</strong>: del 38 al 41 se vende el grueso."]),
    ("Trámites y local",
     ["Los trámites son los del comercio minorista: alta censal con el epígrafe correspondiente, alta de autónomo o sociedad, y licencia de actividad o declaración responsable en tu ayuntamiento. Nada específico del calzado en la mayoría de casos, aunque conviene confirmarlo con tu asesor.",
      "Lo que sí es específico es el local. Necesitas zona de prueba con asientos, espejo bajo y, sobre todo, almacén accesible: el dependiente va a subir y bajar a por cajas todo el día. Un almacén mal situado te cuesta minutos en cada venta y esos minutos son ventas perdidas los sábados."],
     ["Alta censal, autónomo o sociedad y licencia municipal.",
      "Local con zona de prueba cómoda y espejo bajo.",
      "Almacén accesible desde la sala, no en otra planta si puedes evitarlo.",
      "Estanterías dimensionadas para cajas de zapato.",
      "Seguro del local y cartelería obligatoria.",
      "Programa adaptado a VeriFactu antes de tu fecha límite."]),
    ("Cuánto cuesta ponerla en marcha",
     ["Una horquilla razonable está entre 25.000 y 70.000 euros para un local de barrio. La primera compra de temporada se lleva la mayor parte, y ahí la diferencia con la ropa es notable por lo que ya hemos visto de la curva.",
      "Como en cualquier comercio de temporada, guarda colchón para los meses flojos. En calzado, febrero y noviembre suelen ser los peores, y llegar a ellos sin caja después de haber pagado la temporada es el escenario que más cierres provoca."],
     None),
    ("Controla los pares descabalados desde el primer día",
     ["El problema crónico de una zapatería es el par descabalado: se pierde un zapato, queda el otro, y esa caja ocupa sitio y ya no vale nada. Al cabo de dos años, una zapatería sin control acumula decenas.",
      "Dar de alta el catálogo con el número como variante desde el principio te permite ver el stock por número y detectar el descabalado cuando ocurre, no en el inventario anual. Es la diferencia entre perder un par y perder la mitad de los modelos de una temporada."],
     None),
  ],
  faqs=[
    ("¿Cuánto cuesta abrir una zapatería?",
     "Entre 25.000 y 70.000 euros para un local de barrio, con la primera compra de temporada como partida principal. Es más que una tienda de ropa equivalente porque cada modelo exige la curva de números completa, de seis a ocho pares solo para tenerlo disponible."),
    ("¿Cuántos números tengo que tener de cada modelo?",
     "Del 36 al 41 en señora y del 39 al 45 en caballero como mínimo para atender a quien entra, con más profundidad en los números centrales, que son los que más salen. Un modelo con tres números no se vende: la mayoría de la gente que lo pruebe no encontrará el suyo."),
    ("¿Qué trámites necesito?",
     "Los del comercio minorista: alta censal con su epígrafe, alta de autónomo o sociedad y licencia de actividad o declaración responsable municipal. Confirma con tu asesor si en tu municipio hay algún requisito adicional."),
    ("¿Qué tengo que mirar en el local?",
     "Zona de prueba cómoda con asientos y espejo bajo, y sobre todo un almacén accesible desde la sala. El dependiente va a ir a por cajas en cada venta, y un almacén en otra planta te cuesta minutos que en sábado son ventas."),
    ("¿Cómo evito acumular pares descabalados?",
     "Llevando el stock por número desde el primer día, no por modelo. Así detectas el descabalado cuando pasa y puedes actuar, en lugar de descubrir en el inventario anual que tienes veinte cajas con un solo zapato."),
    ("¿Merece la pena vender también online?",
     "En calzado la devolución online es alta porque el número no se prueba antes, y eso se come el margen. Si lo haces, conviene que el stock esté sincronizado para no vender un par que ya no tienes. Empieza por la tienda física bien controlada."),
  ],
  rel=[("Software TPV para zapaterías","/negocio_calzado.asp"),
       ("Matriz de tallas y colores","/matriz-tallas-y-colores.asp"),
       ("Cómo abrir una tienda de ropa","/abrir-tienda-de-ropa.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Cómo hacer el inventario de una tienda","/como-hacer-un-inventario-tienda.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),

"abrir-ferreteria.asp": dict(
  nom="una ferretería", crumb="Ferretería", icono="fa-screwdriver-wrench",
  page="negocio_ferreteria.asp",
  title="Cómo Abrir una Ferretería: surtido e inversión",
  desc="Cómo abrir una ferretería: el problema del surtido inicial, cuánto capital necesitas, proveedores y mayoristas, trámites y venta a profesionales.",
  kw="abrir ferreteria, montar ferreteria, cuanto cuesta abrir una ferreteria, negocio ferreteria, proveedores ferreteria",
  h1="Cómo abrir una ferretería",
  sub="La ferretería tiene un problema de arranque que no tiene ningún otro comercio: necesitas fondo desde el primer día, porque el cliente que no encuentra lo que busca tres veces no vuelve.",
  bloques=[
    ("El surtido inicial es el problema, y no se resuelve con dinero solo",
     ["Una ferretería vive de resolver. El cliente viene con un problema concreto (una junta que gotea, un tornillo que se ha pasado de rosca) y si se lo resuelves, vuelve; si no, se va a la de al lado o a la gran superficie y ya no regresa.",
      "Eso obliga a abrir con fondo, y el fondo son miles de referencias de las que la mayoría se venden dos veces al año. Es capital inmovilizado con rotación bajísima, y es inevitable: es el precio de entrada al negocio. Lo que sí puedes hacer es empezar por las familias que resuelven el 80 % de las visitas de tu zona y ampliar desde ahí."],
     ["<strong>Empieza por familias completas</strong>, no por un poco de todo.",
      "<strong>Fontanería y electricidad</strong> suelen ser las que más visitas resuelven en barrio.",
      "<strong>Tornillería surtida desde el día uno</strong>: es lo que más se pide suelto.",
      "<strong>Amplía con lo que te pidan y no tengas</strong>, apuntándolo religiosamente."]),
    ("Mayoristas, cooperativas y grupos de compra",
     ["Solo, comprarás caro. La mayoría de ferreterías independientes trabajan con uno o dos mayoristas de referencia y muchas están integradas en una cooperativa o grupo de compra, que mejora precios y da acceso a marca propia.",
      "Merece la pena explorar esa vía antes de abrir, porque condiciona el margen de todos los años siguientes. Y negocia desde el principio los plazos de pago: en un negocio con rotación lenta, pagar a sesenta días en lugar de al contado cambia por completo tu necesidad de tesorería."],
     None),
    ("Trámites e inversión",
     ["Los trámites son los del comercio minorista, con la particularidad de que si vas a manejar determinados productos químicos o pinturas puede haber requisitos añadidos de almacenamiento y seguridad. Confírmalo con tu asesor y con tu ayuntamiento según lo que vayas a vender.",
      "En inversión, una horquilla realista está entre 40.000 y 120.000 euros, muy condicionada por el tamaño del surtido inicial. Es de los comercios donde más pesa el género frente a la reforma, justo lo contrario que en moda o estética."],
     ["Alta censal con el epígrafe correspondiente.",
      "Alta de autónomo o constitución de sociedad.",
      "Licencia de actividad o declaración responsable municipal.",
      "Requisitos específicos si almacenas químicos o pinturas.",
      "Seguro de responsabilidad civil y de contenido.",
      "Programa adaptado a VeriFactu antes de tu fecha límite."]),
    ("El cliente profesional llega pronto y hay que estar preparado",
     ["A los pocos meses de abrir empezarán a entrar fontaneros y electricistas. Ese cliente compra a diario, en cantidades pequeñas, y no quiere pagar cada vez: quiere albarán y factura a fin de mes.",
      "Si no tienes montado el sistema de cuentas de cliente desde el principio, acabarás apuntando en una libreta y perdiendo albaranes, que es dinero regalado. Y conviene fijar desde el primer día el límite de riesgo por cliente: el profesional que acumula seis meses sin pagar es un problema que se ve venir en el informe de saldos, si lo tienes."],
     None),
  ],
  faqs=[
    ("¿Cuánto cuesta abrir una ferretería?",
     "Entre 40.000 y 120.000 euros, con el surtido inicial como partida dominante. Es de los comercios donde más pesa el género y menos la reforma, al contrario que en moda. La rotación es lenta, así que el capital inmovilizado tarda en recuperarse."),
    ("¿Por dónde empiezo el surtido si no puedo tenerlo todo?",
     "Por familias completas en lugar de un poco de todo. Fontanería, electricidad y tornillería suelen resolver la mayoría de visitas de barrio. Y apunta religiosamente todo lo que te pidan y no tengas: esa lista es tu plan de ampliación."),
    ("¿Me conviene entrar en una cooperativa o grupo de compra?",
     "Merece la pena estudiarlo antes de abrir. Comprando solo pagarás más caro que la competencia integrada, y eso condiciona el margen de todos los años siguientes. También da acceso a marca propia, que ayuda al margen."),
    ("¿Cuándo empiezan a llegar los clientes profesionales?",
     "Antes de lo que esperas, a los pocos meses. Conviene tener montado desde el principio el sistema de albaranes y factura mensual, con tarifa propia y límite de riesgo por cliente. Apuntar en una libreta funciona hasta que se pierde el primer albarán."),
    ("¿Hay requisitos especiales por vender pinturas o químicos?",
     "Puede haberlos en cuanto a almacenamiento, seguridad y cantidades. Depende de qué productos manejes y de tu municipio: confírmalo con tu asesor y con el ayuntamiento antes de decidir el surtido."),
    ("¿Necesito etiquetar las 12.000 referencias?",
     "No de golpe. Empieza etiquetando lo que rota y lo de más valor, y trabaja el resto con búsqueda por descripción y ubicación en la tienda. Muchas ferreterías etiquetan por balda en lugar de por unidad."),
  ],
  rel=[("Software TPV para ferreterías","/negocio_ferreteria.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Cómo abrir una tienda de electrodomésticos","/abrir-tienda-electrodomesticos.asp"),
       ("Pack TPV completo para comercio","/pack-tpv-completo-comercio.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),

"abrir-peluqueria.asp": dict(
  nom="una peluquería", crumb="Peluquería", icono="fa-scissors",
  page="negocio_peluqueria.asp",
  title="Cómo Abrir una Peluquería: instalación y personal",
  desc="Cómo abrir una peluquería: inversión en obra e instalación, licencias, contratación de personal, precios por servicio y control del producto profesional.",
  kw="abrir peluqueria, montar peluqueria, cuanto cuesta abrir una peluqueria, licencia peluqueria, negocio peluqueria",
  h1="Cómo abrir una peluquería",
  sub="Aquí la inversión no está en el género: está en la fontanería, los lavacabezas y el mobiliario. Y el negocio depende de retener profesionales tanto como clientes.",
  bloques=[
    ("La obra manda sobre el presupuesto",
     ["A diferencia de un comercio, donde el dinero se va en género, en una peluquería se va en obra. Lavacabezas, fontanería, desagües, instalación eléctrica para secadores y climatización son la partida principal, y son cosas que no puedes improvisar después.",
      "El error clásico es alquilar un local barato que necesita rehacer toda la fontanería. Sale más caro que uno más caro que ya venía de peluquería. Antes de firmar, lleva a un fontanero a ver el local: media hora de su tiempo puede ahorrarte quince mil euros."],
     ["<strong>Lavacabezas y fontanería</strong>: la partida más cara y la menos visible.",
      "<strong>Instalación eléctrica</strong> dimensionada para varios secadores a la vez.",
      "<strong>Mobiliario técnico</strong>: sillones, tocadores, espejos y carros.",
      "<strong>Climatización</strong>, que en un local con secadores deja de ser un lujo."]),
    ("Licencias y requisitos del local",
     ["Además de los trámites habituales de alta censal, autónomo o sociedad y licencia de actividad, los centros de peluquería y estética suelen estar sujetos a requisitos higiénico-sanitarios propios, con diferencias notables entre comunidades autónomas.",
      "Pueden incluir cuestiones de ventilación, aseos, gestión de residuos, esterilización de material y, en algunos casos, formación acreditada. No lo deduzcas de una web: pregunta en tu ayuntamiento y en la consejería de sanidad de tu comunidad antes de firmar nada."],
     ["Alta censal, autónomo o sociedad y licencia de actividad.",
      "Requisitos higiénico-sanitarios de tu comunidad autónoma.",
      "Gestión de residuos y esterilización de material.",
      "Seguro de responsabilidad civil.",
      "Cartelería obligatoria y lista de precios visible.",
      "Programa de facturación adaptado a VeriFactu."]),
    ("El personal es el negocio",
     ["Una peluquería no escala con género: escala con manos. Cada profesional atiende a un número limitado de clientes al día, y el techo de facturación lo pone el número de sillones ocupados.",
      "Eso convierte la contratación en la decisión estratégica principal. Y trae un riesgo que conviene tener presente desde el principio: la clientela tiende a seguir a su profesional. Trabajar la relación con el centro, y no solo con la persona, es lo que evita que una baja se lleve media cartera."],
     None),
    ("Precios, bonos y el producto que se gasta sin verse",
     ["Define desde el principio los precios por servicio y tenlos visibles, que además suele ser obligatorio. Y decide pronto si vas a vender bonos, porque cambian tu tesorería: cobras por adelantado servicios que prestarás en meses.",
      "El agujero silencioso es el producto profesional. Tintes y tratamientos se consumen en cada servicio sin que nadie los apunte, así que el stock de cabina siempre está mal y nadie sabe cuánto cuesta de verdad un color. Definir el consumo estimado por servicio desde el principio te da el margen real de cada cosa que vendes."],
     None),
  ],
  faqs=[
    ("¿Cuánto cuesta abrir una peluquería?",
     "Entre 25.000 y 80.000 euros, dominado por obra e instalación más que por género. Lavacabezas, fontanería y electricidad son la partida principal. Un local que ya venía de peluquería puede salir más barato aunque el alquiler sea mayor."),
    ("¿Qué licencias necesito?",
     "Los trámites habituales de alta censal, autónomo o sociedad y licencia de actividad, más los requisitos higiénico-sanitarios de tu comunidad autónoma, que varían bastante y pueden incluir ventilación, aseos, gestión de residuos o esterilización. Pregunta en tu ayuntamiento y en sanidad antes de firmar el local."),
    ("¿Qué miro antes de alquilar el local?",
     "La fontanería y la instalación eléctrica. Lleva a un fontanero a verlo antes de firmar: rehacer desagües y acometidas para lavacabezas puede costar más que la diferencia de alquiler de un local ya preparado."),
    ("¿Cómo evito que un profesional que se va se lleve la clientela?",
     "No hay forma de evitarlo del todo, pero ayuda que la relación sea con el centro: ficha de cliente propia, histórico de servicios, programa de fidelización y comunicación desde el negocio y no solo desde la persona. Cuanto más dependa la clientela de una sola persona, mayor es el riesgo."),
    ("¿Me conviene vender bonos de sesiones?",
     "Mejoran la tesorería y fidelizan, pero recuerda que un bono es un servicio ya cobrado y aún no prestado: es un compromiso. Llévalos controlados para saber cuántas sesiones debe el centro en total, que es un dato que casi nadie tiene."),
    ("¿Cómo controlo el producto que se gasta en cabina?",
     "Definiendo el consumo estimado por servicio y descontándolo de un almacén de cabina separado del producto de venta al público. Sin eso, el stock profesional nunca cuadra y no sabes cuánto te cuesta un color."),
  ],
  rel=[("Software TPV para peluquerías","/negocio_peluqueria.asp"),
       ("TPV para centros de estética","/negocio_estetica.asp"),
       ("Programa de fidelización y puntos","/programa-fidelizacion-puntos.asp"),
       ("Vales y tarjetas regalo","/vales-y-tarjetas-regalo-tpv.asp"),
       ("Cómo abrir un centro de estética","/abrir-centro-estetica.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),

"abrir-panaderia.asp": dict(
  nom="una panadería", crumb="Panadería", icono="fa-bread-slice",
  page="negocio_panaderia.asp",
  title="Cómo Abrir una Panadería: obrador o despacho",
  desc="Cómo abrir una panadería: decidir entre obrador propio o despacho, licencias sanitarias, inversión en horno, horarios y control del sobrante diario.",
  kw="abrir panaderia, montar panaderia, cuanto cuesta abrir una panaderia, licencia obrador panaderia, despacho de pan",
  h1="Cómo abrir una panadería",
  sub="La primera decisión no es el local: es si vas a fabricar o solo a despachar. De ahí cuelga todo lo demás, desde la licencia hasta el horario de tu vida.",
  bloques=[
    ("Obrador propio o despacho: dos negocios distintos",
     ["Con obrador propio fabricas, controlas el producto y el margen es mayor, pero la inversión se multiplica, la licencia es más compleja y tu jornada empieza de madrugada. Con despacho compras el producto ya hecho a un obrador industrial o artesano y te dedicas a vender, con menos margen y muchísima menos complicación.",
      "Ninguna de las dos es mejor en abstracto. Lo que no se puede es elegir la primera creyendo que es la segunda: el obrador cambia tu vida, no solo tu cuenta de resultados."],
     ["<strong>Obrador:</strong> más margen, más inversión, licencia sanitaria compleja, jornada de madrugada.",
      "<strong>Despacho:</strong> menos margen, arranque mucho más barato, dependes de tu proveedor.",
      "<strong>Mixto:</strong> comprar el pan base y elaborar bollería propia es una vía intermedia frecuente.",
      "<strong>Personal:</strong> el obrador exige oficio, y encontrar panadero no siempre es fácil."]),
    ("Licencias: aquí hay más de lo habitual",
     ["Manipular y elaborar alimentos añade requisitos sobre el comercio corriente. Normalmente entra en juego el registro sanitario que corresponda a tu actividad, un sistema de autocontrol basado en principios de análisis de peligros, formación en manipulación de alimentos para el personal y requisitos concretos del local en cuanto a superficies, ventilación y separación de zonas.",
      "Los detalles varían según tu comunidad autónoma y según si fabricas o solo despachas. Es de los sectores donde más conviene hablar con sanidad y con tu asesor antes de firmar el alquiler, porque un local no apto no se arregla después."],
     ["Alta censal, autónomo o sociedad.",
      "Licencia de actividad y, si fabricas, la de obrador.",
      "Registro sanitario que corresponda a tu actividad.",
      "Sistema de autocontrol de higiene alimentaria.",
      "Formación en manipulación de alimentos del personal.",
      "Información de alérgenos disponible para el consumidor.",
      "Programa de facturación adaptado a VeriFactu."]),
    ("Cuánto cuesta",
     ["Con obrador propio, una horquilla realista va de 60.000 a 200.000 euros: el horno, la amasadora, la cámara de fermentación y la obra sanitaria son partidas fuertes. Solo despacho, puedes moverte entre 25.000 y 60.000.",
      "Presupuesta el horno con cuidado: es la pieza que condiciona tu capacidad de producción durante los próximos diez años. Comprar uno pequeño porque es lo que entra en el presupuesto y descubrir a los seis meses que no da abasto es un error que cuesta el doble de arreglar."],
     None),
    ("El sobrante diario es tu margen",
     ["Todo lo que fabricas y no vendes se pierde el mismo día. En una panadería, producir de más es tirar dinero literalmente, y producir de menos es perder ventas a media mañana y clientes a medio plazo.",
      "La única forma de acertar es tener el histórico de ventas por producto y día de la semana. Un martes no se parece a un sábado, y una víspera de festivo no se parece a nada. Registrar el sobrante al cerrar, aunque sea a ojo por familias, te da en tres meses la información con la que se planifica el obrador de verdad."],
     None),
  ],
  faqs=[
    ("¿Cuánto cuesta abrir una panadería?",
     "Con obrador propio, entre 60.000 y 200.000 euros: horno, amasadora, cámara de fermentación y obra sanitaria son las partidas fuertes. Solo despacho, entre 25.000 y 60.000. Son dos proyectos de escala muy distinta."),
    ("¿Me compensa obrador propio o mejor solo despacho?",
     "Depende de cuánto margen necesites y de qué vida quieras. El obrador da más margen y control del producto, pero multiplica la inversión, complica la licencia y te pone a trabajar de madrugada. El despacho arranca mucho más barato pero dependes de tu proveedor."),
    ("¿Qué licencias necesito para un obrador?",
     "Además de los trámites habituales, entra en juego el registro sanitario que corresponda, un sistema de autocontrol de higiene, formación en manipulación de alimentos y requisitos del local sobre superficies, ventilación y separación de zonas. Varía por comunidad: habla con sanidad antes de firmar el alquiler."),
    ("¿Cómo sé cuánto producir cada día?",
     "Con el histórico de ventas por producto y día de la semana, más el sobrante registrado al cerrar. En tres meses tienes un patrón fiable y la producción deja de basarse en la intuición, que en un producto que caduca el mismo día es caro."),
    ("¿Tengo que informar de los alérgenos?",
     "Sí, la información sobre alérgenos es obligatoria también en productos sin envasar, y en panadería casi todo lleva alguno. La forma concreta de facilitarla está regulada: confírmala con tu asesor o con sanidad de tu comunidad."),
    ("¿Puedo repartir a bares y restaurantes?",
     "Sí, y suele ser una línea de negocio interesante porque da volumen previsible. Se lleva con cuenta de cliente: albarán en cada reparto y factura agrupada a fin de mes, con la tarifa propia de hostelería."),
  ],
  rel=[("Software TPV para panaderías","/negocio_panaderia.asp"),
       ("TPV para tiendas de alimentación","/negocio_alimentacion.asp"),
       ("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
       ("Cómo abrir una frutería","/abrir-fruteria.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),
}
