# -*- coding: utf-8 -*-
"""Cluster «abrir un negocio», lote 2."""

ABRIR_2 = {

"abrir-fruteria.asp": dict(
  nom="una frutería", crumb="Frutería", icono="fa-apple-whole", page="negocio_fruteria.asp",
  title="Cómo Abrir una Frutería: ubicación y merma",
  desc="Cómo abrir una frutería: por qué la ubicación decide el negocio, cómo comprar en mercas, controlar la merma diaria, licencias sanitarias e inversión real.",
  kw="abrir fruteria, montar fruteria, cuanto cuesta abrir una fruteria, licencia fruteria, comprar en mercamadrid",
  h1="Cómo abrir una frutería",
  sub="Ningún otro comercio depende tanto de estar en la acera correcta. A cincuenta metros de la calle buena, la misma frutería factura la mitad.",
  bloques=[
    ("La ubicación no es un factor: es el factor",
     ["Una frutería vive de la compra diaria y del paso a pie. La gente no cruza la calle para comprar tomates, y no coge el coche para eso. Tu radio de captación real son dos o tres manzanas.",
      "Antes de firmar, siéntate en la acera del local a distintas horas y cuenta gente. Cuenta también cuántos llevan bolsa de la compra. Un local barato en una calle sin paso no es barato: es un negocio que no va a funcionar por mucho que trabajes."],
     ["<strong>Paso peatonal real</strong>, contado tú mismo a varias horas.",
      "<strong>Cerca de otros comercios de alimentación</strong>: se ayudan, no se quitan clientes.",
      "<strong>Sitio para descargar</strong> de madrugada sin multas.",
      "<strong>Acera ancha</strong> si vas a sacar expositor a la calle, comprobando que el ayuntamiento lo permita."]),
    ("Comprar en el mercado mayorista",
     ["La mayor parte de las fruterías se surten en la unidad alimentaria de su provincia. Eso significa madrugar: la compra se hace de noche o a primera hora, y hay que ir con criterio porque el precio cambia cada día y la calidad se ve en el momento.",
      "El primer año pagarás la novatada: comprarás de más, comprarás mal y aprenderás qué proveedor te trata bien. Lo que acelera esa curva es llevar el dato de lo que vendiste ayer, no la intuición. Con tres semanas de histórico ya compras mejor que con seis meses de memoria."],
     None),
    ("Licencias y requisitos del local",
     ["Además del alta censal, el alta de autónomo o la sociedad y la licencia de actividad, manipular alimentos añade requisitos: formación en manipulación para quien atienda, condiciones del local en cuanto a superficies lavables y ventilación, y en su caso el registro sanitario que corresponda.",
      "Si además vas a cortar, envasar o preparar producto (bandejas de fruta pelada, por ejemplo), los requisitos suben bastante. Los detalles cambian por comunidad autónoma: confírmalo con sanidad y con tu ayuntamiento antes de firmar nada."],
     ["Alta censal, autónomo o sociedad, licencia de actividad.",
      "Formación en manipulación de alimentos.",
      "Requisitos del local: superficies, ventilación, cámara frigorífica.",
      "Registro sanitario si procede por tu actividad concreta.",
      "Información al consumidor: origen, categoría y precio por unidad de medida.",
      "Balanza sometida a control metrológico.",
      "Programa de facturación adaptado a VeriFactu."]),
    ("La merma se lleva el margen si no la miras",
     ["Este es el negocio donde más producto se tira, y donde menos se mide. El género entra por la mañana y en tres días ya no está en condiciones. Producir una lista de lo retirado cada día parece un engorro y es la información más valiosa que vas a tener.",
      "Con la merma registrada por familia descubres cosas incómodas y útiles: que un producto que se vende bien te hace perder dinero porque tiras el 30 %, o que compras siempre el doble de lo que sale de una variedad concreta. Ajustar eso vale más que cualquier subida de precios."],
     None),
  ],
  faqs=[
    ("¿Cuánto cuesta abrir una frutería?",
     "Entre 15.000 y 40.000 euros para un local de barrio, con cámara frigorífica, expositores y balanza como partidas principales. Es de las aperturas más económicas del comercio, pero también de las que más dependen de acertar con la ubicación."),
    ("¿Qué es lo más importante al elegir local?",
     "El paso peatonal, y con diferencia. Una frutería capta a dos o tres manzanas: la gente no cruza la calle ni coge el coche para comprar fruta. Siéntate en la acera a varias horas y cuenta gente antes de firmar."),
    ("¿Dónde compro el género?",
     "La mayoría de fruterías se surten en la unidad alimentaria mayorista de su provincia, comprando de madrugada. El primer año se paga novatada; lo que acelera el aprendizaje es llevar el dato de lo que vendiste ayer en lugar de comprar de memoria."),
    ("¿Qué licencias necesito?",
     "Alta censal, autónomo o sociedad y licencia de actividad, más formación en manipulación de alimentos y requisitos del local sobre superficies y ventilación. Si vas a cortar o envasar producto, los requisitos suben. Confírmalo con sanidad de tu comunidad."),
    ("¿La balanza tiene que estar homologada?",
     "Los instrumentos de pesaje usados en transacciones comerciales están sujetos a control metrológico y a verificaciones periódicas. Es obligación tuya como comerciante; consúltala con el organismo competente de tu comunidad."),
    ("¿Cuánta merma es normal?",
     "Varía mucho por familia y por temporada, así que más que buscar una cifra de referencia conviene medir la tuya. Lo importante es registrarla a diario: en tres meses sabrás qué productos te hacen perder dinero pese a venderse bien, que es información que cambia lo que compras."),
  ],
  rel=[("Software TPV para fruterías","/negocio_fruteria.asp"),
       ("TPV para tiendas de alimentación","/negocio_alimentacion.asp"),
       ("Cómo abrir una panadería","/abrir-panaderia.asp"),
       ("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),

"abrir-papeleria.asp": dict(
  nom="una papelería", crumb="Papelería", icono="fa-pen-ruler", page="negocio_papeleria.asp",
  title="Cómo Abrir una Papelería: campaña y colegios",
  desc="Cómo abrir una papelería: por qué septiembre lo decide todo, cómo conseguir las listas de los colegios, márgenes por familia, servicios de copistería e inversión.",
  kw="abrir papeleria, montar papeleria, cuanto cuesta abrir una papeleria, papeleria colegio listas, negocio papeleria",
  h1="Cómo abrir una papelería",
  sub="Una papelería factura en tres semanas de septiembre lo que en cuatro meses normales. Si no llegas preparado a esa campaña, ya no hay año.",
  bloques=[
    ("Todo gira alrededor de septiembre",
     ["La vuelta al cole concentra una parte desproporcionada de la facturación anual. Y no es solo cuestión de tener género: es cuestión de tener las listas de material de los colegios de tu zona cargadas antes de que empiece la avalancha.",
      "Si abres en primavera, tienes tiempo de conseguirlas. Si abres en agosto, vas a improvisar tu campaña más importante. Elegir el mes de apertura importa aquí más que en casi cualquier otro comercio."],
     ["<strong>Consigue las listas en junio</strong>, hablando con los colegios de tu radio.",
      "<strong>Compra la campaña en julio</strong>, que es cuando hay disponibilidad y mejores condiciones.",
      "<strong>Prepara presupuestos por lista</strong>, para que el padre venga, pida precio y vuelva a recoger.",
      "<strong>Refuerza personal</strong> las tres semanas clave: con cola en la puerta se pierden ventas."]),
    ("Dónde está el margen y dónde no",
     ["El material escolar de marca tiene margen ajustado y compite con grandes superficies, así que no es ahí donde ganas el año. El margen está en tres sitios: la papelería de oficina para empresas del barrio, los servicios de copistería y encuadernación, y el regalo y manualidades.",
      "Los servicios son la partida más rentable y la peor controlada. Fotocopia, plastificado, encuadernado e impresión desde memoria se cobran a ojo en muchas tiendas y no se registran. Dados de alta como artículos con precio, descubrirás que la fotocopiadora aporta más margen que buena parte del lineal."],
     None),
    ("Trámites e inversión",
     ["Los trámites son los del comercio minorista, sin requisitos sanitarios ni especiales en el caso general: alta censal con su epígrafe, alta de autónomo o sociedad y licencia de actividad o declaración responsable municipal.",
      "La inversión se mueve entre 20.000 y 50.000 euros. La partida grande es el surtido inicial, que en papelería significa muchísimas referencias de bajo importe, y la fotocopiadora si vas a dar servicio de reprografía, que se puede comprar o alquilar con contrato de mantenimiento por copia."],
     ["Alta censal con el epígrafe correspondiente.",
      "Alta de autónomo o constitución de sociedad.",
      "Licencia de actividad o declaración responsable municipal.",
      "Contrato de la fotocopiadora, comparando compra frente a alquiler por copia.",
      "Seguro del local y cartelería obligatoria.",
      "Programa de facturación adaptado a VeriFactu."]),
    ("Cuentas de empresas y academias del barrio",
     ["La facturación estable de una papelería, la que paga las facturas de enero a mayo, viene de gestorías, academias, despachos y asociaciones que compran a diario y pagan a fin de mes.",
      "Ese cliente hay que buscarlo activamente cuando abres: darse una vuelta por los despachos del barrio con una tarifa en la mano funciona mejor de lo que parece. Y hay que llevarlo con albarán y factura mensual desde el principio, no con una libreta, porque en cuanto tienes ocho cuentas abiertas se pierde algún albarán y eso es dinero regalado."],
     None),
  ],
  faqs=[
    ("¿Cuánto cuesta abrir una papelería?",
     "Entre 20.000 y 50.000 euros, con el surtido inicial como partida principal: muchísimas referencias de bajo importe. Si vas a dar servicio de reprografía, la fotocopiadora se puede comprar o alquilar con contrato por copia, que reduce bastante el desembolso inicial."),
    ("¿En qué mes conviene abrir?",
     "Idealmente en primavera, para llegar a septiembre con las listas de los colegios conseguidas y la campaña comprada. Abrir en agosto significa improvisar la campaña más importante del año, que es justo la que no se puede improvisar."),
    ("¿Cómo consigo las listas de material de los colegios?",
     "Hablando con ellos en junio, cuando las preparan. Muchos las publican y otros las facilitan a las papelerías de la zona. Tenerlas cargadas como conjuntos convierte una venta de veinte minutos en una de tres, y en campaña eso es todo."),
    ("¿Dónde está el margen de verdad?",
     "En papelería de oficina para empresas del barrio, en los servicios de copistería y encuadernación, y en regalo y manualidades. El material escolar de marca compite con grandes superficies y tiene el margen ajustado."),
    ("¿Merece la pena tener fotocopiadora?",
     "Suele ser el producto de mayor margen y el peor controlado. Dando de alta los servicios como artículos con precio empiezas a ver el dato real, que sorprende a casi todo el mundo. Compara compra frente a alquiler con coste por copia según el volumen que esperes."),
    ("¿Cómo llevo las cuentas de empresas que pagan a fin de mes?",
     "Con cuenta de cliente: albarán en cada compra y factura agrupada a fin de mes, con su tarifa propia. En cuanto tienes varias cuentas abiertas, la libreta empieza a perder albaranes."),
  ],
  rel=[("Software TPV para papelerías","/negocio_papeleria.asp"),
       ("TPV para librerías","/negocio_libreria.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("Cómo abrir una juguetería","/abrir-jugueteria.asp"),
       ("Rebajas y promociones","/rebajas-y-promociones-tpv.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),

"abrir-jugueteria.asp": dict(
  nom="una juguetería", crumb="Juguetería", icono="fa-gamepad", page="negocio_jugueteria.asp",
  title="Cómo Abrir una Juguetería: campaña de Navidad",
  desc="Cómo abrir una juguetería: financiar la compra de campaña en verano, seguridad del producto infantil, competencia online, trámites e inversión inicial.",
  kw="abrir jugueteria, montar jugueteria, cuanto cuesta abrir una jugueteria, campaña navidad jugueteria, negocio juguetes",
  h1="Cómo abrir una juguetería",
  sub="El año se juega en seis semanas y la compra hay que pagarla en verano. Ese desfase de tesorería es lo que hunde a las jugueterías que por lo demás funcionan.",
  bloques=[
    ("Compras en julio y cobras en diciembre",
     ["Este es el problema estructural del sector. Los pedidos de campaña se hacen en verano, con entrega en otoño, y la venta llega en las seis semanas anteriores a Reyes. Entre que pagas y cobras pueden pasar cuatro o cinco meses.",
      "Eso significa que necesitas financiar la campaña, negociar plazos con los proveedores o ambas cosas. Abrir una juguetería sin haber resuelto ese desfase es empezar con una bomba de relojería: puedes tener una campaña excelente y aun así quedarte sin caja en noviembre."],
     ["<strong>Negocia plazos de pago</strong> para el pedido de campaña antes de comprometerlo.",
      "<strong>Reserva línea de financiación</strong> para el otoño, aunque creas que no la vas a usar.",
      "<strong>No dimensiones la tienda para diciembre</strong>: tiene que aguantar los otros once meses.",
      "<strong>Vigila la devolución de enero</strong>, que llega justo cuando la caja está más justa."]),
    ("Competir con el online sin bajar el precio",
     ["El juguete es de los productos más comparados en internet, y no vas a ganar por precio a una plataforma global. Lo que sí puedes ofrecer es lo que ellos no tienen: consejo real, envoltorio, disponibilidad inmediata y la posibilidad de cambiar sin trámites.",
      "Eso funciona mejor si tienes una especialización clara. Las jugueterías generalistas lo tienen más difícil que las que se centran en juego educativo, juegos de mesa, puericultura o modelismo, donde el consejo tiene valor y el cliente vuelve."],
     None),
    ("Seguridad del producto y trámites",
     ["El juguete tiene requisitos de seguridad y marcado propios, y la responsabilidad del distribuidor incluye comprobar que el producto que vende cumple y que va correctamente identificado y etiquetado.",
      "En la práctica: compra a proveedores serios, guarda la documentación de cada partida y no metas en la tienda género de procedencia dudosa por barato que sea. Los requisitos concretos y tus obligaciones como distribuidor conviene confirmarlos con tu asesor."],
     ["Alta censal, autónomo o sociedad y licencia de actividad.",
      "Documentación de conformidad del producto por proveedor.",
      "Etiquetado e instrucciones en español y advertencias de edad.",
      "Seguro de responsabilidad civil.",
      "Programa de facturación adaptado a VeriFactu.",
      "Previsión para las devoluciones de enero."]),
    ("Reservas: la herramienta que casi nadie usa bien",
     ["A partir de noviembre, muchos clientes quieren asegurar un juguete concreto. La reserva con señal es una herramienta excelente y mal aprovechada: te da liquidez cuando más falta hace y te garantiza la venta.",
      "Lo importante es llevarlas registradas con el cliente, el artículo y la señal cobrada, y apartar físicamente el género. Una reserva perdida en campaña no es solo una venta menos: es un cliente enfadado en la semana peor del año."],
     None),
  ],
  faqs=[
    ("¿Cuánto cuesta abrir una juguetería?",
     "Entre 30.000 y 90.000 euros, con la compra de campaña como partida dominante. Lo crítico no es tanto la cifra como el calendario: se paga en verano y se cobra en diciembre, y ese desfase hay que tenerlo financiado."),
    ("¿Cómo financio la compra de Navidad?",
     "Negociando plazos de pago con los proveedores y teniendo prevista una línea de financiación para el otoño. Es el problema estructural del sector y conviene resolverlo antes de comprometer el pedido, no cuando llega la factura."),
    ("¿Cómo compito con las grandes plataformas online?",
     "No por precio. Por consejo, disponibilidad inmediata, envoltorio y cambios sin trámites. Y sobre todo con especialización: juego educativo, juegos de mesa o puericultura son nichos donde el consejo vale y el cliente vuelve."),
    ("¿Qué requisitos tiene el juguete que vendo?",
     "El juguete tiene requisitos de seguridad, marcado y etiquetado, con instrucciones y advertencias de edad en español. Como distribuidor tienes obligaciones sobre lo que vendes: compra a proveedores serios y guarda la documentación de cada partida. Confirma tus obligaciones concretas con tu asesor."),
    ("¿Cuándo hago el inventario?",
     "En febrero. En diciembre no se puede parar y en enero el almacén está deformado por la campaña y las devoluciones. Febrero es el único mes en que el recuento refleja la realidad del año."),
    ("¿Merece la pena aceptar reservas con señal?",
     "Mucho, y está infrautilizado. Te da liquidez justo cuando más falta hace y te asegura la venta. Llévalas registradas con cliente, artículo y señal, y aparta el género físicamente: perder una reserva en campaña es perder al cliente."),
  ],
  rel=[("Software TPV para jugueterías","/negocio_jugueteria.asp"),
       ("TPV para papelerías","/negocio_papeleria.asp"),
       ("Vales y tarjetas regalo","/vales-y-tarjetas-regalo-tpv.asp"),
       ("Rebajas y promociones","/rebajas-y-promociones-tpv.asp"),
       ("Cómo hacer el inventario de una tienda","/como-hacer-un-inventario-tienda.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),

"abrir-centro-estetica.asp": dict(
  nom="un centro de estética", crumb="Centro de estética", icono="fa-spa", page="negocio_estetica.asp",
  title="Cómo Abrir un Centro de Estética: cabinas y bonos",
  desc="Cómo abrir un centro de estética: requisitos sanitarios por comunidad, inversión en cabinas y aparatología, precios por tratamiento y gestión de bonos.",
  kw="abrir centro de estetica, montar centro estetica, requisitos centro estetica, cuanto cuesta abrir centro de belleza, licencia estetica",
  h1="Cómo abrir un centro de estética",
  sub="El techo de facturación lo pone el número de cabinas por las horas que abres. Todo lo demás, incluida la inversión, se decide a partir de ese número.",
  bloques=[
    ("Cuenta las cabinas antes de firmar el local",
     ["Un centro de estética no vende producto: vende tiempo de cabina. Tu facturación máxima es el número de cabinas multiplicado por las horas útiles del día y por el precio medio del tratamiento. Esa cuenta se hace en una servilleta y decide si el local tiene sentido.",
      "Un local que solo permite dos cabinas tiene un techo, por muy bien situado que esté. Y las cabinas necesitan medidas mínimas para trabajar con comodidad, insonorización razonable y a menudo toma de agua, así que no todas las distribuciones valen."],
     ["<strong>Número de cabinas posibles</strong>, que fija tu techo de facturación.",
      "<strong>Toma de agua y desagüe</strong> en las cabinas que lo requieran.",
      "<strong>Insonorización</strong>: se oye todo, y el cliente lo nota.",
      "<strong>Zona de recepción y espera</strong>, que también vende producto."]),
    ("Requisitos sanitarios: mira tu comunidad, no una web",
     ["Los centros de estética están sujetos a requisitos higiénico-sanitarios que varían de forma notable entre comunidades autónomas, y que pueden endurecerse mucho según los tratamientos que ofrezcas. No es lo mismo un centro de manicura que uno con aparatología o con técnicas invasivas.",
      "Pueden entrar en juego autorizaciones sanitarias, formación acreditada del personal, protocolos de esterilización, gestión de residuos y requisitos concretos del local. Es de los sectores donde antes hay que hablar con la consejería de sanidad de tu comunidad, y hacerlo antes de firmar el alquiler."],
     ["Alta censal, autónomo o sociedad y licencia de actividad.",
      "Autorización o comunicación sanitaria según tu comunidad y tus tratamientos.",
      "Formación acreditada del personal para determinadas técnicas.",
      "Protocolos de higiene, esterilización y gestión de residuos.",
      "Seguro de responsabilidad civil, imprescindible con aparatología.",
      "Lista de precios visible y hojas de reclamaciones.",
      "Programa de facturación adaptado a VeriFactu."]),
    ("Aparatología: la decisión más cara y la más arriesgada",
     ["La aparatología es donde se va el presupuesto y donde más gente se equivoca. Un equipo puede costar decenas de miles de euros y solo se amortiza si lo llenas de sesiones, lo que exige que ya tengas clientela o una inversión seria en captación.",
      "Empezar con tratamientos manuales y una aparatología básica, e incorporar equipos cuando la agenda lo justifique, es más lento y bastante más seguro. Si aun así compras equipo caro al principio, calcula cuántas sesiones al mes necesitas para pagarlo y sé honesto sobre si vas a llegar."],
     None),
    ("Bonos: mejoran la caja y crean una deuda",
     ["Vender bonos de sesiones es casi obligatorio en este sector: fideliza y te da liquidez por adelantado. Pero conviene tener claro desde el principio que un bono es un servicio cobrado y no prestado, es decir, una deuda del centro.",
      "Si no llevas el control de cuántas sesiones debes en total, puedes tener la caja llena y el negocio comprometido. Llevar los bonos en el programa, con sus sesiones restantes y su caducidad si la aplicas, evita además la discusión más frecuente del mostrador."],
     None),
  ],
  faqs=[
    ("¿Cuánto cuesta abrir un centro de estética?",
     "Entre 30.000 y 100.000 euros según cabinas y aparatología. La obra y la instalación son la base, y los equipos pueden dispararlo. Empezar con aparatología básica e incorporar equipos cuando la agenda lo justifique es más seguro."),
    ("¿Qué requisitos sanitarios necesito?",
     "Varían mucho entre comunidades autónomas y según los tratamientos que ofrezcas: pueden incluir autorización sanitaria, formación acreditada, protocolos de esterilización y gestión de residuos. Habla con la consejería de sanidad de tu comunidad antes de firmar el local."),
    ("¿Cuántas cabinas necesito?",
     "Las que quepan bien, porque tu techo de facturación es cabinas por horas útiles por precio medio. Un local que solo permite dos cabinas limita el negocio por muy buena que sea la ubicación. Haz esa cuenta antes de firmar."),
    ("¿Merece la pena invertir en aparatología desde el principio?",
     "Es la decisión más arriesgada. Un equipo caro solo se amortiza con la agenda llena, y al abrir no la tienes. Calcula cuántas sesiones mensuales necesitas para pagarlo y sé honesto sobre si vas a llegar en el primer año."),
    ("¿Cómo gestiono los bonos de sesiones?",
     "Registrándolos en el programa con sus sesiones restantes, para que el saldo se vea al identificar a la clienta. Y sacando el informe de sesiones pendientes del centro: son servicios cobrados y no prestados, o sea una deuda, y conviene saber cuánta tienes."),
    ("¿Puedo vender también producto de cosmética?",
     "Sí, y suele ser una línea de margen interesante que aprovecha la confianza del tratamiento. Lo importante es tener separado el almacén de venta del producto profesional de cabina, para que el consumo no se confunda con la venta."),
  ],
  rel=[("Software TPV para centros de estética","/negocio_estetica.asp"),
       ("TPV para peluquerías","/negocio_peluqueria.asp"),
       ("Cómo abrir una peluquería","/abrir-peluqueria.asp"),
       ("Programa de fidelización y puntos","/programa-fidelizacion-puntos.asp"),
       ("Vales y tarjetas regalo","/vales-y-tarjetas-regalo-tpv.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),

"abrir-tienda-electrodomesticos.asp": dict(
  nom="una tienda de electrodomésticos", crumb="Electrodomésticos", icono="fa-blender",
  page="negocio_electrodomesticos.asp",
  title="Cómo Abrir una Tienda de Electrodomésticos",
  desc="Cómo abrir una tienda de electrodomésticos: grupos de compra, logística de entrega e instalación, financiación al cliente, RAEE e inversión inicial.",
  kw="abrir tienda electrodomesticos, montar tienda electrodomesticos, grupo compra electrodomesticos, cuanto cuesta abrir tienda electrodomesticos",
  h1="Cómo abrir una tienda de electrodomésticos",
  sub="Vendes producto caro con margen estrecho contra grandes cadenas. Lo que te hace competitivo no es el precio: es que tú entregas, instalas y das la cara al mes siguiente.",
  bloques=[
    ("Solo no compras: entra en un grupo",
     ["El margen del electrodoméstico es estrecho y la competencia son cadenas con un poder de compra que tú no vas a igualar. Comprando de forma independiente pagarás por encima del precio al que la cadena de al lado vende.",
      "Por eso casi todo el comercio independiente que sobrevive en este sector está integrado en una central o grupo de compra, que negocia condiciones, da acceso a marca propia y muchas veces aporta la logística y el servicio postventa. Explora esa vía antes de abrir: condiciona todo lo demás."],
     None),
    ("Tu ventaja competitiva es el servicio, y hay que dimensionarlo",
     ["Lo que te compra el cliente que no va a la gran superficie es tranquilidad: que le entregues cuando dijiste, que le instalen bien, que le retiren el viejo y que cuando falle algo tenga a quien llamar.",
      "Eso significa que la logística no es un accesorio del negocio: es el negocio. Necesitas furgoneta, alguien que instale y una previsión de entregas que se cumpla. Vender un frigorífico y no aparecer el día prometido cuesta ese cliente y los que le pregunten."],
     ["<strong>Furgoneta y personal de entrega</strong>, propios o subcontratados con fiabilidad.",
      "<strong>Almacén con acceso de carga</strong>: el género es voluminoso y pesado.",
      "<strong>Listado de entregas por día</strong>, con dirección, teléfono y observaciones de acceso.",
      "<strong>Servicio postventa</strong> resuelto, propio o mediante el grupo."]),
    ("Trámites, RAEE y etiquetado",
     ["Además de los trámites habituales del comercio, la venta de aparatos eléctricos y electrónicos conlleva obligaciones sobre residuos, incluida la recogida del aparato usado en los supuestos previstos y la adhesión al sistema de gestión que corresponda.",
      "También hay requisitos sobre etiquetado energético e información al consumidor. Los detalles concretos y cómo deben reflejarse en factura conviene confirmarlos con tu asesor y con el sistema de gestión al que te adhieras, porque no es un asunto menor."],
     ["Alta censal, autónomo o sociedad y licencia de actividad.",
      "Adhesión al sistema de gestión de residuos que corresponda.",
      "Requisitos de etiquetado energético e información al consumidor.",
      "Seguro de responsabilidad civil y de contenido.",
      "Acuerdo con central o grupo de compra.",
      "Programa de facturación adaptado a VeriFactu."]),
    ("Financiación y tesorería",
     ["Buena parte de la venta se paga a plazos o con financiación de una entidad, y eso hay que tenerlo montado desde el primer día porque es un argumento de venta real.",
      "Ojo con la tesorería: el dinero de una venta financiada no entra en tu caja ese día. Registrar la financiación como medio de pago propio, separado del efectivo y la tarjeta, es lo que hace que el arqueo diario cuadre y que sepas de verdad cuánto has ingresado."],
     None),
  ],
  faqs=[
    ("¿Cuánto cuesta abrir una tienda de electrodomésticos?",
     "Entre 50.000 y 150.000 euros, con el stock inicial y el almacén como partidas principales, más la furgoneta si haces la entrega tú. El género es caro y voluminoso, así que el capital inmovilizado es alto desde el primer día."),
    ("¿Puedo competir con las grandes cadenas?",
     "Por precio, no. Por servicio, sí: entrega cuando dijiste, instalación correcta, retirada del viejo y alguien a quien llamar cuando falle. Eso es lo que compra el cliente que no va a la gran superficie, y hay que dimensionarlo de verdad."),
    ("¿Me conviene entrar en un grupo de compra?",
     "Es prácticamente imprescindible en este sector. Comprando solo pagarás por encima del precio al que vende la cadena de al lado. Los grupos negocian condiciones, dan acceso a marca propia y muchas veces aportan logística y postventa."),
    ("¿Qué obligaciones tengo sobre RAEE?",
     "La venta de aparatos eléctricos conlleva obligaciones sobre residuos, incluida la recogida del usado en los supuestos previstos, y la adhesión a un sistema de gestión. Los detalles y su reflejo en factura conviene confirmarlos con tu asesor."),
    ("¿Cómo llevo la financiación en el TPV?",
     "Como medio de pago separado del efectivo y la tarjeta. Es importante para el arqueo: el dinero de una venta financiada no entra en tu caja ese día, y mezclarlo hace que el cierre no cuadre nunca."),
    ("¿Cómo controlo las entregas pendientes?",
     "Con la fecha y franja comprometidas registradas en la venta, y un listado de entregas por día para el repartidor con dirección, teléfono y observaciones de acceso. No aparecer el día prometido es el fallo más caro de este sector."),
  ],
  rel=[("Software TPV para electrodomésticos","/negocio_electrodomesticos.asp"),
       ("TPV para tiendas de informática","/negocio_informatica.asp"),
       ("Cómo abrir una ferretería","/abrir-ferreteria.asp"),
       ("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),
}
