# -*- coding: utf-8 -*-
"""Cluster de normativa y obligaciones del comercio. Lote 1.

Contenido informativo, nunca asesoramiento. Toda afirmacion con consecuencias
fiscales o sancionadoras remite al asesor y evita el alarmismo.
"""

NORMATIVA_1 = {

"sanciones-ley-antifraude.asp": dict(
  nom="las sanciones de la Ley Antifraude", crumb="Sanciones", icono="fa-gavel",
  title="Sanciones de la Ley Antifraude: qué dice la norma",
  desc="Qué régimen sancionador establece la Ley 11/2021 sobre software de facturación, a quién afecta (fabricante y usuario) y cómo se acredita que tu programa cumple.",
  kw="sanciones ley antifraude, multa software doble uso, ley 11/2021 sanciones, declaracion responsable software, sancion tpv no homologado",
  h1="Sanciones de la Ley Antifraude: lo que dice la norma y lo que no",
  sub="Circula mucho miedo y pocas cifras contrastadas. Esto es lo que establece la ley, dicho sin exagerar y remitiendo a tu asesor donde toca.",
  faq_titulo="Preguntas frecuentes sobre las sanciones de la Ley Antifraude",
  cta=("¿Tu programa actual cumple?",
       "Pídele a tu proveedor la declaración responsable por escrito. Si no la tiene, hablamos."),
  bloques=[
    ("Qué persigue exactamente la norma",
     ["La Ley 11/2021 de medidas de prevención y lucha contra el fraude fiscal ataca lo que se conoce como <em>software de doble uso</em>: programas que permiten llevar una contabilidad para Hacienda y otra real, borrando ventas sin dejar rastro.",
      "Para cortarlo, la norma exige que los sistemas informáticos de facturación garanticen integridad, conservación, trazabilidad e inalterabilidad de los registros. El reglamento que lo desarrolla, el Real Decreto 1007/2023, es el que concreta los requisitos técnicos que conocemos como VeriFactu."],
     None),
    ("La responsabilidad es doble: fabricante y usuario",
     ["Esto sorprende a mucha gente. La norma contempla infracciones tanto para quien produce o comercializa software que no cumple como para quien lo utiliza en su negocio.",
      "Es decir, no basta con decir «me lo vendieron así». Por eso el documento clave es la <strong>declaración responsable</strong>: el fabricante declara formalmente que su programa cumple, y ese papel es tu respaldo. Pídelo por escrito y guárdalo.",
      "Los importes concretos, los supuestos y las circunstancias agravantes están en el texto de la ley y su desarrollo, y su aplicación a tu caso depende de factores que no se pueden resolver desde una página web. Habla con tu asesor fiscal si quieres una valoración de tu exposición real."],
     ["<strong>Fabricante o comercializador:</strong> infracción por producir o distribuir sistemas que no cumplan.",
      "<strong>Usuario:</strong> infracción por utilizar sistemas que no se ajusten a lo exigido.",
      "<strong>Tu respaldo:</strong> la declaración responsable del fabricante, por escrito.",
      "<strong>Los importes concretos:</strong> consúltalos con tu asesor, no con un anuncio."]),
    ("Lo que se exagera y conviene desmontar",
     ["El terreno de las sanciones es donde más alarmismo se vende, porque el miedo cierra ventas de software. Tres cosas que circulan y no son ciertas.",
      "La primera, que Hacienda va a mirar tu caja en directo: lo que se remiten son registros de facturación con la información que establece la norma, no un acceso a tu negocio. La segunda, que hay que pagar una tasa por VeriFactu: no existe. La tercera, que te multan mañana: hasta la fecha que te aplique, no hay obligación.",
      "Toma la decisión con datos y con tu asesor. Un proveedor que te vende con miedo en lugar de con argumentos ya te está diciendo algo sobre cómo va a ser la relación."],
     None),
    ("Qué hacer en la práctica, por orden",
     ["Casi todo se resuelve con una conversación con tu proveedor actual y otra con tu asesoría. Este es el orden que tiene sentido.",
      "Si tu proveedor responde con evasivas a la primera pregunta, eso ya es información suficiente para empezar a mirar alternativas con calma, que es mucho mejor que hacerlo con prisa en el último trimestre de 2026."],
     ["Pregunta a tu proveedor si el programa está adaptado y si te dará la declaración responsable.",
      "Pide fecha concreta de disponibilidad y si la actualización tiene coste.",
      "Confirma con tu asesor qué fecha te aplica según tu forma jurídica.",
      "Guarda la declaración responsable con el resto de tu documentación fiscal.",
      "Si vas a cambiar de programa, hazlo en tu mes de menos facturación."]),
  ],
  faqs=[
    ("¿Cuánto es la multa por usar un TPV no homologado?",
     "Los importes y supuestos están en el texto de la Ley 11/2021 y su desarrollo, y su aplicación depende de circunstancias concretas de cada caso. Desconfía de cualquier web o comercial que te dé una cifra tajante: quien puede valorar tu exposición real es tu asesor fiscal."),
    ("¿Me pueden sancionar a mí o solo al fabricante del programa?",
     "La norma contempla infracciones para ambos: para quien produce o comercializa sistemas que no cumplen y para quien los utiliza. Por eso conviene tener la declaración responsable del fabricante por escrito."),
    ("¿Qué es la declaración responsable y para qué me sirve?",
     "Es el documento en el que el fabricante del software declara formalmente que su programa cumple los requisitos de la norma. Es tu respaldo documental: pídelo por escrito y guárdalo con tu documentación fiscal."),
    ("¿Hay sanciones ya en 2026?",
     "La obligación llega el 1 de enero de 2027 para sociedades y el 1 de julio de 2027 para autónomos, según el calendario vigente tras el RD-ley 15/2025. Durante 2026 la adaptación es voluntaria. Confirma tu fecha con tu asesor, porque el calendario ya se ha movido dos veces."),
    ("¿Es verdad que Hacienda verá mis ventas en tiempo real?",
     "No en el sentido que sugiere esa frase. En modo VeriFactu se remiten los registros de facturación con la información que establece la norma. No es un acceso a tu caja ni a tu contabilidad. Es uno de los puntos donde más alarmismo circula."),
    ("¿Tengo que pagar alguna tasa a la Agencia Tributaria?",
     "No existe tasa ni cuota por VeriFactu. Lo que puede costarte dinero es adaptar o cambiar tu programa de facturación, que es un asunto comercial entre tú y tu proveedor de software."),
    ("Mi programa es antiguo y ya no tiene mantenimiento. ¿Qué hago?",
     "Un programa sin mantenimiento activo lo normal es que no se adapte, porque nadie va a desarrollar la adaptación. Ahí las opciones son actualizar a una versión con soporte o cambiar de programa. Empieza a mirarlo ahora, no en el último trimestre."),
    ("¿Puedo seguir facturando con Excel o con Word?",
     "A partir de la fecha que te aplique, no: la norma exige un sistema informático de facturación que genere registros con los requisitos establecidos, y una hoja de cálculo no los cumple. Es el cambio que sí o sí tendrás que hacer si facturas así."),
    ("¿Qué pasa si me equivoco en una factura? ¿No puedo borrarla?",
     "El registro es inalterable por diseño, así que no se borra: se corrige con una factura rectificativa que hace referencia a la original. Es el procedimiento correcto y el que la norma exige. En la práctica el programa lo hace desde la propia venta."),
  ],
  rel=[("Ley Antifraude 11/2021 y TPV","/ley-antifraude-tpv.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp"),
       ("Cuándo entra en vigor VeriFactu","/verifactu-cuando-entra-en-vigor.asp"),
       ("VeriFactu para autónomos","/verifactu-autonomos.asp"),
       ("Normativa del comercio","/normativa-comercio.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp")]),

"ticketbai-pais-vasco.asp": dict(
  nom="ticketBAI", crumb="ticketBAI", icono="fa-receipt",
  title="ticketBAI: qué es y en qué se diferencia de VeriFactu",
  desc="ticketBAI es el sistema de las haciendas forales vascas, distinto de VeriFactu. Qué exige, a quién afecta en Álava, Bizkaia y Gipuzkoa, y cómo convive con el estatal.",
  kw="ticketbai, ticket bai que es, ticketbai vs verifactu, ticketbai bizkaia gipuzkoa alava, tpv ticketbai homologado",
  h1="ticketBAI: qué es y por qué no es lo mismo que VeriFactu",
  sub="Si tu comercio está en Álava, Bizkaia o Gipuzkoa, tu sistema no es VeriFactu. Y lleva más tiempo en marcha que el estatal.",
  faq_titulo="Preguntas frecuentes sobre ticketBAI",
  cta=("¿Tienes tienda en el País Vasco?",
       "Caja 5 está adaptado a ticketBAI además de a VeriFactu. Llámanos y te contamos qué necesitas en tu territorio."),
  bloques=[
    ("Un sistema foral, tres territorios y calendarios propios",
     ["ticketBAI es el sistema impulsado por las haciendas forales de Álava, Bizkaia y Gipuzkoa junto al Gobierno Vasco para garantizar la integridad y trazabilidad de las facturas. Nació antes que VeriFactu y ha ido implantándose por fases.",
      "La particularidad que más confunde es que <strong>cada territorio histórico tiene su propia normativa y su propio calendario</strong>. Lo que aplica en Gipuzkoa no tiene por qué coincidir en plazos con Bizkaia o Álava. Por eso aquí más que en ningún otro sitio conviene confirmar tu situación con tu asesor o con la hacienda foral que te corresponda."],
     None),
    ("Qué exige en la práctica",
     ["El planteamiento se parece al de VeriFactu en el fondo: que el programa genere un fichero por cada factura, firmado y encadenado con el anterior, y que la factura lleve un código identificativo y un código QR.",
      "Para el comerciante el cambio operativo es pequeño: el ticket sale igual y lleva un QR. Lo que cambia es que el programa tiene que estar en el registro de software adaptado del territorio correspondiente, que es un requisito adicional respecto al modelo estatal."],
     ["<strong>Fichero por factura</strong>, firmado y encadenado con el anterior.",
      "<strong>Código TBAI y QR</strong> impresos en la factura o el ticket.",
      "<strong>Software registrado</strong> en el territorio que corresponda.",
      "<strong>Envío a la hacienda foral</strong> según lo que establezca tu normativa."]),
    ("ticketBAI y VeriFactu no se suman: se excluyen",
     ["La duda más frecuente es si un comercio vasco tiene que cumplir los dos. Con carácter general no: en los territorios forales lo aplicable es su propio sistema.",
      "Donde puede complicarse es si tienes actividad en varios territorios, o si tu domicilio fiscal y el lugar de la actividad no coinciden. Esa casuística la resuelve tu asesor, no una tabla en internet."],
     None),
    ("Qué preguntar a tu proveedor de software",
     ["Aquí hay una pregunta adicional respecto al resto de España, y es la que más se olvida: no basta con que el programa «esté adaptado», tiene que estar registrado en tu territorio.",
      "Caja 5 está adaptado tanto a ticketBAI como a VeriFactu. Si tienes tienda en el País Vasco, llámanos y te confirmamos la situación concreta para tu territorio antes de que compres nada."],
     ["¿Está el programa adaptado a ticketBAI y registrado en mi territorio?",
      "¿Cuál es su identificador en el registro de software correspondiente?",
      "¿Tiene coste añadido la adaptación o las actualizaciones normativas?",
      "Si abro otra tienda fuera del País Vasco, ¿el mismo programa sirve para VeriFactu?"]),
  ],
  faqs=[
    ("¿Qué es ticketBAI?",
     "Es el sistema de las haciendas forales de Álava, Bizkaia y Gipuzkoa, junto al Gobierno Vasco, para garantizar la integridad y trazabilidad de las facturas. Exige que el programa genere un fichero firmado y encadenado por cada factura, con código TBAI y QR."),
    ("¿ticketBAI y VeriFactu son lo mismo?",
     "No. Comparten el objetivo pero son sistemas distintos, con normativa, requisitos técnicos y calendarios diferentes. ticketBAI es foral y lleva más tiempo en marcha; VeriFactu es estatal."),
    ("Si mi tienda está en Bilbao, ¿qué me aplica?",
     "Con carácter general, ticketBAI de la Hacienda Foral de Bizkaia. Los plazos y requisitos concretos dependen de tu actividad y de tu situación: confírmalo con tu asesor o con la hacienda foral, porque cada territorio tiene su propia normativa."),
    ("¿Tengo que cumplir los dos sistemas?",
     "Con carácter general no: en los territorios forales lo aplicable es su propio sistema. Si tienes actividad en varios territorios o tu domicilio fiscal no coincide con el lugar de actividad, es una casuística que debe resolverte tu asesor."),
    ("¿Basta con que el programa esté adaptado?",
     "En ticketBAI hay un requisito adicional respecto al modelo estatal: el software tiene que estar registrado en el territorio correspondiente. Pregunta a tu proveedor por su identificador en ese registro, no solo si «está adaptado»."),
    ("¿Caja 5 está adaptado a ticketBAI?",
     "Sí, además de a VeriFactu. Si tienes tienda en el País Vasco, llámanos antes de comprar y te confirmamos la situación concreta para tu territorio."),
    ("Tengo una tienda en Vitoria y otra en Burgos. ¿Qué hago?",
     "Es justo el escenario que conviene consultar con tu asesor, porque puede implicar cumplir ticketBAI en un establecimiento y VeriFactu en el otro. Lo que sí conviene es que el programa sirva para ambos, para no llevar dos sistemas distintos."),
    ("¿El cliente nota algo en el ticket?",
     "Un código QR y un identificador impresos. Nada más: el cobro es igual de rápido y la operativa del mostrador no cambia."),
    ("¿Qué pasa si mi programa no está registrado en mi territorio?",
     "Que no cumple, aunque el fabricante diga que está adaptado. Es la comprobación específica de ticketBAI que más se pasa por alto. Pide el identificador del registro por escrito."),
  ],
  rel=[("Qué es VeriFactu","/que-es-verifactu.asp"),
       ("Sanciones de la Ley Antifraude","/sanciones-ley-antifraude.asp"),
       ("Software TPV homologado VeriFactu","/verifactu-tpv.asp"),
       ("Cuándo entra en vigor VeriFactu","/verifactu-cuando-entra-en-vigor.asp"),
       ("Normativa del comercio","/normativa-comercio.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp")]),

"factura-electronica-obligatoria-crea-y-crece.asp": dict(
  nom="la factura electrónica obligatoria", crumb="Factura electrónica", icono="fa-file-invoice",
  title="Factura Electrónica Obligatoria: Crea y Crece",
  desc="La factura electrónica entre empresas viene de la Ley Crea y Crece y no es lo mismo que VeriFactu. Qué exige, a quién afecta y en qué se diferencian ambas.",
  kw="factura electronica obligatoria, ley crea y crece factura, factura electronica empresas autonomos, diferencia verifactu factura electronica",
  h1="Factura electrónica obligatoria: no la confundas con VeriFactu",
  sub="Son dos obligaciones distintas, de dos leyes distintas, con dos calendarios distintos. Y mucha gente cree que cumpliendo una cumple la otra.",
  faq_titulo="Preguntas frecuentes sobre la factura electrónica obligatoria",
  cta=("¿Te lía tener dos obligaciones a la vez?",
       "Llámanos y te decimos en cuál estás y en cuál no, sin venderte lo que no necesitas."),
  bloques=[
    ("Dos obligaciones que se confunden constantemente",
     ["Es probablemente la confusión más extendida del momento entre comerciantes y autónomos, y conviene despejarla porque cambia lo que tienes que hacer.",
      "<strong>VeriFactu</strong> regula cómo debe comportarse tu programa de facturación: registros encadenados, inalterables y con QR. Nace de la Ley Antifraude 11/2021 y su reglamento. <strong>La factura electrónica obligatoria</strong> regula en qué formato se intercambian las facturas entre empresas y profesionales. Nace de la Ley 18/2022, conocida como Crea y Crece.",
      "Puedes estar afectado por las dos, por una o por ninguna, según tu actividad y tus clientes. Cumplir una no implica cumplir la otra."],
     ["<strong>VeriFactu:</strong> cómo genera y conserva los registros tu programa.",
      "<strong>Factura electrónica:</strong> en qué formato mandas la factura a otra empresa.",
      "<strong>Origen distinto:</strong> Ley 11/2021 frente a Ley 18/2022.",
      "<strong>Calendario distinto:</strong> y el de la factura electrónica ha ido más lento."]),
    ("A quién afecta la factura electrónica",
     ["La obligación de la Ley Crea y Crece se refiere a las relaciones comerciales <strong>entre empresarios y profesionales</strong>, lo que se conoce como B2B. Las ventas a consumidores finales, que es el grueso del comercio minorista, no entran en ese ámbito.",
      "Traducido a una tienda de barrio: los tickets que emites a tus clientes no se ven afectados por esta obligación. Sí puede afectarte la parte de tu facturación a otras empresas, si la tienes: el fontanero al que vendes con factura, la comunidad de vecinos, la academia que te compra material.",
      "El despliegue de esta obligación depende de un desarrollo reglamentario que ha sufrido retrasos, y los plazos se han ligado a la facturación de cada empresa. Es de las materias donde más conviene no fiarse de una fecha leída en internet: pregunta a tu asesor por tu situación concreta."],
     None),
    ("Qué cambia si te afecta",
     ["No se trata de mandar un PDF por correo. La factura electrónica en este sentido implica un formato estructurado que el sistema del destinatario pueda procesar automáticamente, y la obligación de informar sobre los estados de la factura, como su aceptación o su pago efectivo.",
      "Ese último punto es el que más trabajo añade y el que menos se menciona: no basta con emitir, hay que reportar estados. Si buena parte de tu facturación es a empresas, conviene que lo tengas previsto con tiempo."],
     None),
    ("Qué hacer ahora, según tu caso",
     ["Si vendes casi todo a consumidor final con ticket, tu prioridad es VeriFactu y la factura electrónica B2B te afecta poco o nada. Si tienes una parte relevante de facturación a empresas, conviene que hables con tu asesor sobre cómo te va a encajar el calendario.",
      "En ambos casos, lo sensato es no comprar hoy una solución para una obligación cuyo desarrollo reglamentario todavía está moviéndose. Ten claro en qué grupo estás y actúa con la información confirmada, no con la de un anuncio."],
     None),
  ],
  faqs=[
    ("¿La factura electrónica obligatoria es lo mismo que VeriFactu?",
     "No. VeriFactu regula cómo se comporta tu programa de facturación y viene de la Ley Antifraude 11/2021. La factura electrónica entre empresas viene de la Ley Crea y Crece y regula el formato de intercambio. Son obligaciones distintas con calendarios distintos."),
    ("¿Me afecta si solo vendo a particulares?",
     "La obligación de factura electrónica se refiere a relaciones entre empresarios y profesionales. Los tickets a consumidor final no entran en ese ámbito. Lo que sí te aplica en ese caso es VeriFactu."),
    ("¿Cuándo entra en vigor?",
     "Depende de un desarrollo reglamentario que ha sufrido retrasos, con plazos ligados al volumen de facturación de cada empresa. Es materia donde las fechas han cambiado varias veces: confírmala con tu asesor y no con una web."),
    ("¿Vale con mandar un PDF por email?",
     "No. Se refiere a un formato estructurado que el sistema del destinatario pueda procesar automáticamente, no a un documento para leer. Además existe la obligación de informar sobre los estados de la factura."),
    ("¿Qué son los estados de la factura?",
     "Información sobre lo que ocurre con la factura después de emitirla: su aceptación o rechazo y su pago efectivo. Es la parte que más trabajo añade y la que menos se menciona cuando se habla de este asunto."),
    ("Vendo a algunas empresas con factura. ¿Qué hago?",
     "Habla con tu asesor sobre cómo te encaja el calendario según tu volumen y tus clientes. Y no compres hoy una solución para una obligación cuyo desarrollo reglamentario sigue moviéndose."),
    ("¿Puedo cumplir las dos cosas con el mismo programa?",
     "Son requisitos distintos y conviene tratarlos por separado. Caja 5 emite facturas simplificadas conformes a VeriFactu; para el intercambio estructurado B2B, consúltanos tu caso concreto antes de dar nada por hecho."),
    ("¿Y si soy autónomo con pocos clientes empresa?",
     "Lo primero es tener claro qué parte de tu facturación es B2B. Si es marginal, tu prioridad clara es VeriFactu. Tu asesor puede decírtelo mirando tus facturas de un ejercicio."),
    ("¿Esto sustituye al ticket de toda la vida?",
     "No. El ticket, que técnicamente es una factura simplificada, sigue existiendo para la venta a consumidor final. Lo que cambia con VeriFactu es cómo lo genera y lo conserva tu programa."),
  ],
  rel=[("Qué es VeriFactu","/que-es-verifactu.asp"),
       ("Sanciones de la Ley Antifraude","/sanciones-ley-antifraude.asp"),
       ("Cuentas de cliente y factura a fin de mes","/cuentas-de-cliente-cobrar-fin-de-mes.asp"),
       ("VeriFactu para autónomos","/verifactu-autonomos.asp"),
       ("Normativa del comercio","/normativa-comercio.asp"),
       ("ticketBAI","/ticketbai-pais-vasco.asp")]),

"obligaciones-legales-abrir-tienda.asp": dict(
  nom="las obligaciones legales de una tienda", crumb="Obligaciones de la tienda", icono="fa-clipboard-check",
  title="Obligaciones Legales de una Tienda: la lista completa",
  desc="Qué carteles, hojas de reclamaciones, información de precios y documentación tiene que tener a la vista un comercio en España, y qué mira una inspección.",
  kw="obligaciones legales tienda, hojas de reclamaciones comercio, cartel horario obligatorio, informacion precios comercio, inspeccion consumo tienda",
  h1="Obligaciones legales de una tienda: lo que tiene que estar a la vista",
  sub="Casi todas las sanciones de consumo que se llevan los comercios pequeños son por cosas de cartelería y de información al cliente, no por fraudes.",
  faq_titulo="Preguntas frecuentes sobre las obligaciones de un comercio",
  cta=("¿Vas a abrir y no sabes por dónde empezar?",
       "Mira nuestras guías de apertura por sector. Y consulta tu lista concreta con tu asesor: cambia por comunidad."),
  bloques=[
    ("Lo que se sanciona de verdad en un comercio pequeño",
     ["La imagen del inspector buscando un fraude fiscal es minoritaria. Lo que genera la mayor parte de las sanciones a comercios pequeños es mucho más prosaico: falta de hojas de reclamaciones, precios mal indicados, ausencia de cartelería obligatoria o condiciones de devolución no informadas.",
      "Son incumplimientos baratos de evitar y caros de tener. Y casi todos se resuelven en una tarde con una visita a la web de consumo de tu comunidad autónoma."],
     None),
    ("Cartelería e información obligatoria",
     ["La lista concreta varía entre comunidades autónomas, y en algunos puntos entre municipios, así que esta es una guía de qué revisar, no una lista cerrada. Confírmala con tu asesor o con la oficina de consumo de tu comunidad.",
      "El detalle que más se descuida es la política de cambios y devoluciones. Si el producto no es defectuoso, en tienda física tú fijas tu política, pero <strong>tienes que informarla antes de la venta</strong>. Una política no informada no se puede oponer al cliente después."],
     ["<strong>Hojas de reclamaciones</strong> disponibles y el cartel que anuncia que existen.",
      "<strong>Horario comercial</strong> visible desde el exterior.",
      "<strong>Precios de todos los artículos</strong> expuestos, incluidos los del escaparate.",
      "<strong>Precio por unidad de medida</strong> donde sea exigible.",
      "<strong>Política de cambios y devoluciones</strong> informada antes de la venta.",
      "<strong>Cartel de admisión de medios de pago</strong> si limitas alguno."]),
    ("Precios: donde más se falla sin saberlo",
     ["Todos los artículos expuestos deben tener su precio visible, y eso incluye el escaparate, que es donde más se incumple. En determinados productos hay además que indicar el precio por unidad de medida, como el precio por kilo o por litro.",
      "En rebajas la exigencia sube: hay que informar del precio anterior junto al rebajado. Por eso conviene aplicar los descuentos como campaña en el programa y no machacando el precio base: así conservas la referencia del original y la etiqueta sale correcta."],
     None),
    ("Documentación fiscal y de datos",
     ["Además de la parte de consumo, hay dos bloques que conviene tener ordenados. El fiscal: facturas emitidas y recibidas, y a partir de tu fecha, un programa conforme a VeriFactu con su declaración responsable.",
      "Y el de protección de datos: si guardas datos de clientes, aunque sea para un programa de puntos, tienes obligaciones de información, consentimiento donde proceda y seguridad. En sectores como óptica, ortopedia o estética, parte de esa información puede ser sensible y las exigencias son mayores. Consúltalo con tu asesor: es de las cosas que menos se miran y más se sancionan cuando llega el caso."],
     None),
  ],
  faqs=[
    ("¿Qué carteles son obligatorios en una tienda?",
     "Habitualmente el de existencia de hojas de reclamaciones, el horario comercial visible desde fuera y los precios de todo lo expuesto, escaparate incluido. La lista concreta varía por comunidad autónoma: confírmala con la oficina de consumo de la tuya."),
    ("¿Tengo que tener hojas de reclamaciones?",
     "En la práctica totalidad de las comunidades autónomas sí, junto con el cartel que anuncia su disponibilidad. El formato y el procedimiento los establece cada comunidad."),
    ("¿Estoy obligado a aceptar devoluciones?",
     "Si el producto es defectuoso o no conforme, se aplica la garantía legal. Si está perfecto y es un cambio de opinión en tienda física, la política la fijas tú, pero debes informarla claramente antes de la venta. Una política no informada no se puede oponer después."),
    ("¿Tengo que poner precio a lo del escaparate?",
     "Sí, y es donde más se incumple. Todos los artículos expuestos deben tener su precio visible, incluido el escaparate. En determinados productos hay que indicar además el precio por unidad de medida."),
    ("¿Qué tengo que hacer en rebajas?",
     "Informar del precio anterior junto al rebajado. Por eso conviene aplicar los descuentos como campaña en el programa, conservando el precio original como referencia, en lugar de sobrescribirlo."),
    ("¿Puedo negarme a aceptar pagos en efectivo?",
     "Hay límites legales al pago en efectivo en determinadas operaciones y consideraciones sobre la aceptación de medios de pago. Si vas a limitar alguno, infórmalo con un cartel visible y consulta con tu asesor qué puedes y qué no."),
    ("¿Necesito hacer algo por protección de datos si tengo fichas de clientes?",
     "Sí: informar de la finalidad, recoger consentimiento donde proceda y aplicar medidas de seguridad. Si tu sector maneja información sensible, como óptica, ortopedia o estética, las exigencias son mayores. Consúltalo con tu asesor."),
    ("¿Qué documentación fiscal debo conservar y cuánto tiempo?",
     "Facturas emitidas y recibidas, y los registros que exija tu régimen. Los plazos concretos dependen de tu situación: pregúntaselos a tu asesoría, sobre todo antes de dar de baja un programa antiguo, porque el histórico vive ahí."),
    ("¿Una inspección mira el TPV?",
     "Puede pedir que el sistema de facturación cumpla lo que exige la norma, y a partir de tu fecha de VeriFactu, la declaración responsable del fabricante. Tenerla guardada por escrito es lo que resuelve esa parte en un minuto."),
  ],
  rel=[("Cómo abrir un negocio","/abrir-un-negocio.asp"),
       ("Rebajas y promociones en el TPV","/rebajas-y-promociones-tpv.asp"),
       ("Cómo hacer una devolución en el TPV","/como-hacer-una-devolucion-tpv.asp"),
       ("Sanciones de la Ley Antifraude","/sanciones-ley-antifraude.asp"),
       ("Normativa del comercio","/normativa-comercio.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),

"declaracion-responsable-software-facturacion.asp": dict(
  nom="la declaración responsable del software", crumb="Declaración responsable", icono="fa-file-signature",
  title="Declaración Responsable del Software de Facturación",
  desc="Qué es la declaración responsable que debe darte el fabricante de tu programa de facturación, qué debe contener, cómo pedirla y por qué es tu respaldo.",
  kw="declaracion responsable software facturacion, certificado tpv homologado, como saber si mi tpv cumple verifactu, documento fabricante software",
  h1="La declaración responsable: el papel que demuestra que tu programa cumple",
  sub="Es el documento más importante de todo este asunto y el que menos gente pide. Sin él, la palabra de tu proveedor no te respalda ante nadie.",
  faq_titulo="Preguntas frecuentes sobre la declaración responsable",
  cta=("Pídesela a tu proveedor hoy",
       "Si te la da sin problema, tranquilo. Si te da largas, es el momento de mirar alternativas con calma."),
  bloques=[
    ("Qué es y por qué te importa a ti",
     ["La normativa que desarrolla VeriFactu establece que los sistemas informáticos de facturación deben certificar mediante declaración responsable que cumplen los requisitos exigidos. Ese documento lo emite el productor del software, no tú.",
      "Pero te importa a ti por una razón concreta: la norma contempla infracciones también para quien utiliza sistemas que no cumplen. La declaración responsable es la prueba de que hiciste lo que te correspondía, que era usar un programa conforme.",
      "Si tu proveedor te dice de palabra que «sí, está adaptado» y no te da nada por escrito, no tienes nada. Y es gratis pedirlo."],
     None),
    ("Qué deberías recibir",
     ["No hay que ser experto para valorar si lo que te dan sirve. Un documento serio identifica claramente el software, su versión y al responsable que declara.",
      "Desconfía de un PDF genérico sin versión ni fecha, de un sello de «homologado» que no cite la normativa, o de una respuesta por WhatsApp diciendo que sí. Y guárdalo con tu documentación fiscal, no en una carpeta de descargas."],
     ["<strong>Identificación del software</strong> y de la versión concreta.",
      "<strong>Datos del productor</strong> que emite la declaración.",
      "<strong>Referencia a la normativa</strong> que se declara cumplir.",
      "<strong>Fecha</strong>, para saber a qué versión corresponde.",
      "<strong>Formato conservable</strong>: un PDF que puedas guardar y volver a encontrar."]),
    ("Cómo pedirla sin que suene a desconfianza",
     ["Es una petición absolutamente normal y cualquier fabricante serio la tiene preparada. Basta un correo de dos líneas pidiendo la declaración responsable correspondiente a la versión que usas.",
      "Lo relevante no es solo el documento: es la respuesta. Un proveedor que la envía en un día te está diciendo que tiene la casa en orden. Uno que da largas durante semanas te está dando información valiosa sobre cómo va a ser el soporte cuando lo necesites de verdad."],
     None),
    ("Si tu programa no la tiene",
     ["Hay dos escenarios. El primero, que el fabricante esté trabajando en la adaptación y te dé una fecha concreta: ahí lo razonable es esperar, pidiendo que te confirmen si tiene coste.",
      "El segundo, que tu programa sea antiguo, esté sin mantenimiento o el fabricante ya no exista. Ahí no hay adaptación posible y toca cambiar. Con la obligación llegando en 2027, tienes margen para hacerlo con calma; lo que no conviene es descubrirlo en noviembre de 2026, cuando todo el sector esté migrando a la vez."],
     None),
  ],
  faqs=[
    ("¿Qué es la declaración responsable de un software de facturación?",
     "Es el documento en el que el productor del software declara que su programa cumple los requisitos que exige la normativa. Lo emite el fabricante, no el comerciante, pero es tu respaldo documental."),
    ("¿Por qué me importa a mí si la emite el fabricante?",
     "Porque la norma contempla infracciones también para quien utiliza sistemas que no cumplen. La declaración es la prueba de que usaste un programa conforme, que es lo que te correspondía a ti."),
    ("¿Qué debe contener?",
     "Identificación del software y su versión, datos del productor, referencia a la normativa que se declara cumplir y fecha. Desconfía de un sello genérico de «homologado» que no cite normativa ni versión."),
    ("¿Cómo se la pido a mi proveedor?",
     "Con un correo de dos líneas pidiendo la declaración responsable de la versión que usas. Es una petición normal que cualquier fabricante serio tiene preparada. La rapidez de la respuesta ya te dice mucho."),
    ("¿Y si mi proveedor me da largas?",
     "Es información valiosa: te está enseñando cómo será el soporte cuando lo necesites en serio. Con la obligación llegando en 2027 tienes margen para mirar alternativas con calma, que es mucho mejor que hacerlo con prisa."),
    ("Mi programa es de hace diez años y el fabricante ya no existe.",
     "No va a haber adaptación, así que toca cambiar. Empieza a mirarlo ahora: en el último trimestre antes de la fecha límite, los plazos de instalación se alargan y el soporte de todos los fabricantes se satura."),
    ("¿Vale un sello de 'homologado' en la web del fabricante?",
     "Un logotipo en una web no es una declaración responsable. Pide el documento, con la versión y la fecha, en un formato que puedas guardar con tu documentación fiscal."),
    ("¿Tengo que renovarla con cada actualización?",
     "Conviene tener la que corresponde a la versión que estás usando. Si actualizas a una versión nueva, pide la declaración correspondiente. Es el motivo por el que el documento debe llevar versión y fecha."),
    ("¿Caja 5 tiene declaración responsable?",
     "Sí. Llámanos al 953 050 112 o escríbenos y te la enviamos para la versión que tengas instalada."),
  ],
  rel=[("Sanciones de la Ley Antifraude","/sanciones-ley-antifraude.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp"),
       ("Cuándo entra en vigor VeriFactu","/verifactu-cuando-entra-en-vigor.asp"),
       ("Cómo cambiar de programa TPV","/migrar-de-tpv-cambiar-programa.asp"),
       ("Normativa del comercio","/normativa-comercio.asp"),
       ("Software TPV homologado VeriFactu","/verifactu-tpv.asp")]),
}
