# -*- coding: utf-8 -*-
"""Cluster de operativa diaria: «cómo hacer X en el TPV». Lote 1."""

OPERATIVA_1 = {

"como-hacer-una-devolucion-tpv.asp": dict(
  nom="devoluciones y cambios", crumb="Devoluciones y cambios", icono="fa-rotate-left",
  title="Cómo Hacer una Devolución o Cambio en el TPV",
  desc="Cómo registrar devoluciones y cambios en el TPV: localizar el ticket, devolver el stock, emitir vale o factura rectificativa y qué dice la ley sobre devoluciones.",
  kw="como hacer una devolucion tpv, cambio sin ticket, vale de devolucion, factura rectificativa tienda, politica de devoluciones comercio",
  h1="Cómo hacer una devolución o un cambio en el TPV",
  sub="La devolución mal hecha descuadra el stock, descuadra la caja y a veces genera un vale que se canjea dos veces. Se arregla haciéndola siempre sobre el ticket original.",
  bloques=[
    ("Siempre sobre el ticket original, nunca como venta negativa",
     ["El atajo más común es meter la devolución como una venta con importe negativo. Funciona en la caja del día y rompe todo lo demás: el stock no vuelve bien, no queda constancia de qué ticket se está corrigiendo y la trazabilidad fiscal se pierde.",
      "La forma correcta es localizar el ticket original y devolver desde él. El programa sabe entonces qué artículo era, a qué precio se vendió y qué descuento llevaba, así que el stock vuelve con su coste correcto y la operación queda enlazada con la venta que corrige."],
     ["<strong>Busca el ticket</strong> por número, por fecha, por importe o por cliente si estaba identificado.",
      "<strong>Selecciona las líneas</strong> que se devuelven, que no tienen por qué ser todas.",
      "<strong>El stock vuelve</strong> a la combinación exacta, talla y color incluidos.",
      "<strong>Elige la forma de reintegro</strong>: efectivo, mismo medio de pago o vale."]),
    ("Devolución, cambio y vale no son lo mismo",
     ["Un cambio es una devolución más una venta en el mismo acto, y la diferencia se cobra o se devuelve. Un vale es una devolución donde en lugar de dinero entregas un saldo a futuro. Contablemente y para tu tesorería son cosas distintas.",
      "El vale, además, es un compromiso: dinero que has cobrado y que todavía debes en género. Llevarlos con número y saldo te permite saber cuánto tienes comprometido en vales vivos, que es un dato que casi ningún comercio conoce."],
     None),
    ("Qué dice la ley y qué decides tú",
     ["Conviene tener clara la diferencia. Si el producto es defectuoso o no conforme, se aplica la garantía legal y ahí no decides tú. Si el producto está perfecto y el cliente simplemente cambia de opinión en una compra hecha en tienda física, la política de cambios y devoluciones la fijas tú.",
      "Lo que sí tienes que hacer es informarla de forma clara antes de la venta, típicamente en el ticket y en un cartel visible. Y ten en cuenta que en venta a distancia el régimen es distinto y existe derecho de desistimiento. Concreta tu caso con tu asesor: aquí hay matices que importan."],
     None),
    ("La factura rectificativa cuando el cliente pidió factura",
     ["Si la venta original se documentó con factura, la corrección no se hace borrando: se emite una factura rectificativa que anula o modifica la anterior, con referencia a ella.",
      "Con VeriFactu esto cobra más importancia todavía, porque el registro de facturación es inalterable por diseño: no se puede hacer desaparecer una venta. La rectificativa deja de ser una formalidad y pasa a ser el único mecanismo válido de corrección."],
     None),
  ],
  faqs=[
    ("¿Puedo hacer una devolución sin el ticket?",
     "Técnicamente sí, si localizas la venta por fecha, importe o cliente identificado. La cuestión de si debes aceptarla es otra: en compra en tienda física y producto no defectuoso, la política la fijas tú, siempre que la hayas informado con claridad antes de la venta."),
    ("¿Por qué no puedo meter la devolución como venta negativa?",
     "Porque el stock no vuelve con su coste correcto, no queda enlazada con la venta que corrige y pierdes la trazabilidad. Funciona para cuadrar la caja del día y rompe el inventario y el histórico, que es donde luego buscarás respuestas."),
    ("¿Estoy obligado a devolver el dinero?",
     "Si el producto es defectuoso o no conforme, se aplica la garantía legal. Si está perfecto y es un cambio de opinión en tienda física, tú decides tu política, pero debes informarla antes de la venta. En venta a distancia el régimen es distinto. Consúltalo con tu asesor."),
    ("¿Cómo evito que un vale se canjee dos veces?",
     "Emitiéndolo con número y código desde el programa. Al canjearlo se comprueba que está vivo y se descuenta el saldo; si se agota queda cerrado. Con vales escritos a mano no hay forma de evitarlo."),
    ("¿Qué pasa si la venta llevaba factura?",
     "Se emite una factura rectificativa que hace referencia a la original. Con VeriFactu el registro es inalterable, así que la rectificativa es el único mecanismo válido para corregir: no se puede borrar una venta."),
    ("¿Puedo saber cuánto dinero tengo comprometido en vales?",
     "Sí, con el informe de vales vivos. Es dinero que ya has cobrado y que todavía debes en género, así que conviene tenerlo a la vista: en tiendas de moda suele ser una cifra mayor de lo que la gente imagina."),
  ],
  rel=[("Vales y tarjetas regalo en el TPV","/vales-y-tarjetas-regalo-tpv.asp"),
       ("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp"),
       ("Software TPV para tiendas de ropa","/negocio_moda.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp"),
       ("Operativa diaria del TPV","/operativa-tpv.asp")]),

"cambiar-precios-masivamente-tpv.asp": dict(
  nom="cambios de precio", crumb="Cambios de precio", icono="fa-tags",
  title="Cómo Cambiar Precios en Masa en el TPV",
  desc="Cómo subir o bajar precios de muchos artículos a la vez en el TPV: por familia, por proveedor, por porcentaje o por margen, y cómo reimprimir las etiquetas.",
  kw="cambiar precios masivamente tpv, subir precios por familia, actualizar tarifa proveedor, cambio precio porcentaje tienda, reimprimir etiquetas precio",
  h1="Cómo cambiar precios en masa sin volverte loco",
  sub="Cuando el proveedor sube un 4 %, nadie debería tocar cuatrocientas fichas a mano. Se hace por familia, por proveedor o por margen, en un minuto.",
  bloques=[
    ("Cuatro formas de cambiar precios y cuándo usar cada una",
     ["No todos los cambios de precio son iguales, y usar el método equivocado es lo que convierte una tarea de dos minutos en una tarde perdida.",
      "El caso más frecuente es la subida de tarifa de un proveedor: afecta a sus artículos y a nadie más. El segundo, el ajuste de margen de una familia entera. El tercero, la campaña temporal, que no debería tocar el precio base. Y el cuarto, el cambio puntual de una referencia."],
     ["<strong>Por proveedor:</strong> sube un porcentaje el coste de todo lo suyo y recalcula el PVP manteniendo margen.",
      "<strong>Por familia:</strong> ajusta el margen de una sección completa.",
      "<strong>Por campaña:</strong> precio temporal con fechas, sin tocar el precio base.",
      "<strong>Por artículo:</strong> el cambio puntual de siempre."]),
    ("Sube el coste, no el precio de venta",
     ["El error que más margen destruye es actualizar el PVP y olvidarse del precio de coste. A partir de ese momento tus informes de margen mienten: creerás que ganas un 45 % cuando ganas un 31 %.",
      "Cuando llega una tarifa nueva del proveedor, lo correcto es actualizar el coste y dejar que el programa recalcule el PVP según el margen que quieras mantener. Así el margen sigue siendo real y decides tú si repercutes toda la subida o absorbes parte."],
     None),
    ("Redondeo: el detalle que nadie mira",
     ["Aplicar un 4,7 % a cuatrocientos artículos genera precios como 13,47 €. En una tienda de mostrador eso complica el cambio y queda raro en la etiqueta.",
      "Conviene definir una regla de redondeo al aplicar el cambio: a múltiplos de 5 o 10 céntimos, o terminaciones en 0,95 si es tu política. Se hace una vez al configurar y evita repasar los cuatrocientos precios después."],
     None),
    ("Reimprimir etiquetas y carteles, que es la otra mitad del trabajo",
     ["Cambiar el precio en el programa y no en la etiqueta es peor que no cambiarlo: el cliente ve un precio y la caja cobra otro, y eso genera desconfianza y a veces una reclamación.",
      "Después de cualquier cambio masivo, saca el listado de artículos afectados y reimprime sus etiquetas o carteles. En comercios de precio variable, como fruterías o pescaderías, esto se hace a diario y conviene que sea una operación de un clic."],
     None),
  ],
  faqs=[
    ("¿Puedo subir un porcentaje a todos los artículos de un proveedor?",
     "Sí, filtrando por proveedor y aplicando el porcentaje. Lo recomendable es aplicarlo al precio de coste y dejar que el PVP se recalcule según el margen objetivo, para que tus informes de margen sigan siendo ciertos."),
    ("¿Qué pasa si actualizo el PVP pero no el coste?",
     "Que tus márgenes dejan de ser reales y todas las decisiones que tomes con ellos serán erróneas. Es el error que más silenciosamente destruye rentabilidad en el pequeño comercio."),
    ("¿Puedo redondear los precios resultantes?",
     "Sí, definiendo la regla de redondeo al aplicar el cambio: múltiplos de cinco o diez céntimos, o terminaciones tipo 0,95. Evita quedarte con precios de 13,47 € en toda la tienda."),
    ("¿Cómo hago una bajada solo durante una semana?",
     "Como campaña con fecha de inicio y fin, no tocando el precio base. Al terminar, los precios vuelven solos y conservas la referencia del precio original, que además necesitas para informar del precio anterior en rebajas."),
    ("¿Tengo que reimprimir todas las etiquetas?",
     "Solo las de los artículos afectados, y el programa te da ese listado. No hacerlo es peor que no cambiar el precio: el cliente ve una cifra en la etiqueta y la caja cobra otra."),
    ("¿Se puede deshacer un cambio masivo mal aplicado?",
     "Por eso conviene revisar el listado de artículos afectados antes de confirmar. Y hacer copia de seguridad antes de un cambio grande, que es una costumbre barata que un día te salva la tarde."),
  ],
  rel=[("Rebajas y promociones en el TPV","/rebajas-y-promociones-tpv.asp"),
       ("Etiquetas con código de barras","/etiquetas-codigo-de-barras-tpv.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("TPV para fruterías","/negocio_fruteria.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Operativa diaria del TPV","/operativa-tpv.asp")]),

"dar-de-alta-articulos-tpv.asp": dict(
  nom="el alta de artículos", crumb="Alta de artículos", icono="fa-plus",
  title="Cómo Dar de Alta tu Catálogo en el TPV",
  desc="Cómo montar el catálogo de tu tienda en el TPV: importar desde Excel, estructura de familias, qué campos rellenar de verdad y por dónde empezar sin agobiarse.",
  kw="dar de alta articulos tpv, importar catalogo excel tpv, familias y subfamilias tienda, montar catalogo tpv, migrar articulos programa",
  h1="Cómo montar el catálogo en el TPV sin morir en el intento",
  sub="El motivo número uno por el que se abandona un programa nuevo es intentar dar de alta cinco mil artículos la primera semana. No se hace así.",
  bloques=[
    ("Empieza por vender, no por el catálogo perfecto",
     ["El planteamiento que falla es: «cuando tenga todo el catálogo metido, empiezo a usar el programa». Nunca llega ese momento, porque siempre hay artículos, y a las tres semanas se vuelve a la caja de siempre.",
      "El planteamiento que funciona es al revés: empieza a cobrar desde el primer día con lo que más vendes dado de alta, y ve incorporando el resto según entra mercancía o según se vende. En dos meses tienes el catálogo completo y además está limpio, porque solo has metido lo que de verdad se mueve."],
     ["<strong>Semana uno:</strong> las cincuenta referencias que más vendes, y a cobrar.",
      "<strong>Después:</strong> da de alta cada artículo cuando llegue en un albarán o cuando alguien lo pida.",
      "<strong>Lo que no se vende en seis meses</strong>, probablemente no merecía estar en el catálogo.",
      "<strong>Nunca pares la caja</strong> para meter fichas."]),
    ("Si tienes un Excel, no teclees",
     ["La mayoría de comercios tienen ya alguna lista: un Excel del proveedor, un listado del programa anterior o la tarifa del mayorista en formato digital. Todo eso se importa.",
      "Lo que hace falta es ordenar las columnas antes de importar: referencia, descripción, precio de coste, precio de venta, familia, proveedor y código de barras si lo hay. Media hora ordenando el Excel ahorra tres días de teclear."],
     None),
    ("Familias: pocas, claras y pensadas para buscar",
     ["El error clásico es montar un árbol de familias de cinco niveles con doscientas ramas. Nadie lo mantiene y nadie encuentra nada.",
      "Las familias deben responder a cómo busca tu dependiente y cómo pregunta tu cliente, no a cómo está organizado el catálogo del proveedor. Entre diez y veinte familias de primer nivel es suficiente para casi cualquier tienda, con subfamilias solo donde de verdad haga falta.",
      "Y piensa que las familias son la base de todos tus informes: si las montas bien, sabrás qué sección te da margen. Si las montas mal, tus informes no dirán nada útil."],
     None),
    ("Qué campos rellenar de verdad al principio",
     ["No todos los campos hacen falta desde el día uno. Los imprescindibles son descripción, precio de venta, precio de coste, familia y código de barras si el artículo lo trae. Con eso ya cobras, controlas stock y sabes tu margen.",
      "El resto (proveedor, ubicación, stock mínimo, temporada, composición) se va rellenando después, y cada uno desbloquea un informe. Rellenar el precio de coste desde el principio, eso sí, es innegociable: sin él no hay margen y sin margen no hay decisiones."],
     None),
  ],
  faqs=[
    ("¿Tengo que dar de alta todo el catálogo antes de empezar a usar el programa?",
     "No, y hacerlo es el motivo más habitual de abandono. Empieza con las cincuenta referencias que más vendes, ponte a cobrar, y da de alta el resto según entra mercancía. En dos meses lo tienes completo y además limpio."),
    ("¿Puedo importar mi catálogo desde un Excel?",
     "Sí, y es lo recomendable si ya tienes alguna lista. Ordena antes las columnas: referencia, descripción, coste, PVP, familia, proveedor y código de barras. Media hora de orden ahorra días de teclado."),
    ("¿Cuántas familias debo crear?",
     "Entre diez y veinte de primer nivel para casi cualquier tienda, con subfamilias solo donde haga falta. Móntalas según cómo busca tu dependiente y cómo pregunta tu cliente, no según el catálogo del proveedor. Son la base de todos tus informes."),
    ("¿Qué campos son imprescindibles al principio?",
     "Descripción, precio de venta, precio de coste, familia y código de barras si lo trae. Con eso cobras, controlas stock y conoces tu margen. El precio de coste es innegociable: sin él no sabes lo que ganas."),
    ("¿Y los artículos que no tienen código de barras?",
     "El programa genera un código interno y lo imprimes en etiqueta. Es lo normal en bisutería, artesanía, ferretería a granel o segunda mano."),
    ("¿Puedo cambiar la estructura de familias más adelante?",
     "Sí, aunque cuanto más tarde lo hagas más artículos hay que reclasificar. Merece la pena dedicar media hora a pensarla al principio en lugar de rehacerla con tres mil referencias dentro."),
  ],
  rel=[("Matriz de tallas y colores","/matriz-tallas-y-colores.asp"),
       ("Etiquetas con código de barras","/etiquetas-codigo-de-barras-tpv.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp"),
       ("Operativa diaria del TPV","/operativa-tpv.asp")]),

"cerrar-temporada-liquidar-stock.asp": dict(
  nom="el cierre de temporada", crumb="Cierre de temporada", icono="fa-calendar-check",
  title="Cómo Cerrar Temporada y Liquidar Stock",
  desc="Cómo cerrar temporada en una tienda: identificar el stock muerto, escalonar los descuentos, calcular hasta dónde puedes bajar y qué hacer con lo que no se vende.",
  kw="cerrar temporada tienda, liquidar stock temporada, stock muerto tienda, escalonar descuentos rebajas, que hacer con genero que no se vende",
  h1="Cómo cerrar temporada y liquidar el stock que sobra",
  sub="El género de la temporada pasada no vale lo que costó: vale lo que alguien pague hoy. Cuanto más tardes en asumirlo, menos vale.",
  bloques=[
    ("El stock viejo cuesta dinero cada día que sigue ahí",
     ["Un artículo que lleva ocho meses colgado no es un activo: es dinero parado ocupando el sitio de algo que sí rota. Y a diferencia de lo que la intuición dice, esperar no mejora las cosas: cada temporada que pasa, ese artículo vale menos y es más difícil de colocar.",
      "La decisión difícil, y la correcta, es liquidar antes y más agresivamente de lo que apetece. Recuperar el 40 % de lo que costó algo que no se va a vender es mejor negocio que conservar el 100 % de un valor teórico que nunca se realizará."],
     ["<strong>Saca el listado de artículos sin venta</strong> en los últimos seis meses.",
      "<strong>Ordénalos por capital inmovilizado</strong>, no por número de unidades.",
      "<strong>Marca cuáles son de temporada</strong> y cuáles son de fondo, que aguantan más.",
      "<strong>Decide un tope de descuento</strong> por familia antes de empezar."]),
    ("Escalonar los descuentos, no fusilar el precio",
     ["Bajar de golpe al 70 % es regalar margen que quizá no hacía falta regalar. La forma habitual y más rentable es escalonar: primera fase moderada, segunda más agresiva y una final de liquidación para lo que quede.",
      "Cada fase con fechas definidas y aplicada por campaña, no cambiando el precio base, para conservar la referencia del precio original y poder informarlo como manda la normativa de rebajas."],
     ["<strong>Primera fase:</strong> descuento moderado sobre la temporada completa.",
      "<strong>Segunda fase:</strong> más agresivo sobre lo que no se movió en la primera.",
      "<strong>Liquidación final:</strong> precio de derribo para vaciar.",
      "<strong>Fondo de armario aparte:</strong> lo que no es de temporada no tiene por qué entrar."]),
    ("Hasta dónde puedes bajar de verdad",
     ["Necesitas dos números: el precio de coste real del artículo y el margen medio que necesitas para cubrir gastos. Con el coste delante sabes exactamente dónde está tu suelo, y ahí es donde se nota tener el precio de coste bien metido en la ficha.",
      "Vender por debajo de coste tiene además límites legales en determinados supuestos, y la venta con pérdida está regulada. Si vas a liquidar por debajo de lo que te costó, consúltalo con tu asesor antes."],
     None),
    ("Lo que no se vende ni liquidado",
     ["Siempre queda un resto. Las salidas habituales son outlet permanente en una zona de la tienda, venta a un mayorista de saldos, plataformas de segunda mano o donación, que en algunos casos tiene tratamiento fiscal propio.",
      "Lo que no es una salida es dejarlo en el almacén otro año. Ocupa espacio, distorsiona tu valoración de inventario y te hace creer que tienes un patrimonio que en realidad no existe. Antes de decidir, saca el dato de cuánto capital tienes ahí parado: suele ser la cifra que empuja a actuar."],
     None),
  ],
  faqs=[
    ("¿Cómo sé qué artículos tengo que liquidar?",
     "Con el listado de artículos sin venta en los últimos seis meses, ordenado por capital inmovilizado y no por unidades. Diez artículos caros parados pesan más en tu caja que doscientos baratos."),
    ("¿Es mejor bajar de golpe o escalonar?",
     "Escalonar suele ser más rentable: una primera fase moderada, una segunda más agresiva sobre lo que no se movió y una liquidación final. Bajar de golpe al 70 % regala margen que a veces no hacía falta regalar."),
    ("¿Hasta dónde puedo bajar el precio?",
     "Tu suelo es el precio de coste, y por eso conviene tenerlo bien metido en la ficha. Ten en cuenta además que la venta con pérdida está regulada en determinados supuestos: si vas a vender por debajo de coste, consúltalo antes con tu asesor."),
    ("¿Tengo que mostrar el precio anterior en rebajas?",
     "La normativa de venta en rebajas exige informar del precio anterior junto al rebajado. Por eso conviene aplicar los descuentos como campaña y no machacando el precio base: así conservas la referencia original."),
    ("¿Qué hago con lo que no se vende ni liquidado?",
     "Outlet permanente en una zona de la tienda, venta a un mayorista de saldos, plataformas de segunda mano o donación. Lo que no es solución es guardarlo otro año: ocupa sitio y te hace creer que tienes un patrimonio que ya no existe."),
    ("¿Cuándo hago el inventario, antes o después de rebajas?",
     "Antes de empezar las rebajas. Contar con la tienda llena de descuentos y movimiento es la peor combinación posible, y además necesitas saber qué tienes para decidir qué liquidas."),
  ],
  rel=[("Rebajas y promociones en el TPV","/rebajas-y-promociones-tpv.asp"),
       ("Cómo hacer el inventario de una tienda","/como-hacer-un-inventario-tienda.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Software TPV para tiendas de ropa","/negocio_moda.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("Operativa diaria del TPV","/operativa-tpv.asp")]),

"copia-seguridad-tpv.asp": dict(
  nom="las copias de seguridad", crumb="Copias de seguridad", icono="fa-shield-halved",
  title="Copias de Seguridad del TPV: cómo y cada cuánto",
  desc="Cómo configurar las copias de seguridad de tu TPV: qué guardar, cada cuánto, dónde dejarlas y cómo comprobar que la copia sirve antes de necesitarla.",
  kw="copia de seguridad tpv, backup programa tienda, restaurar base de datos tpv, perder datos tienda, copia automatica comercio",
  h1="Copias de seguridad del TPV: la media hora que te salva el negocio",
  sub="El disco duro no avisa. Y la copia que nunca has probado a restaurar no es una copia: es una carpeta con la que te vas a llevar una sorpresa.",
  bloques=[
    ("Qué hay dentro de la base de datos que no quieres perder",
     ["Cuando la gente piensa en perder datos piensa en las ventas. Pero lo que más cuesta reconstruir no es eso: es el catálogo. Miles de referencias con sus precios, costes, códigos de barras, familias y proveedores, que representan meses de trabajo acumulado.",
      "Después vienen los clientes con su histórico, los vales vivos, los encargos pendientes y las cuentas de los profesionales que te deben dinero. Perder eso no es un contratiempo: puede ser el final del negocio."],
     ["<strong>El catálogo</strong>, que es lo más caro de reconstruir.",
      "<strong>Clientes y su histórico</strong>, incluidos vales y bonos pendientes.",
      "<strong>Ventas y tickets</strong>, con las implicaciones fiscales de su conservación.",
      "<strong>Encargos y cuentas abiertas</strong>, que son dinero pendiente de cobrar."]),
    ("La regla de las tres copias, adaptada a una tienda",
     ["La práctica habitual en informática es tener tres copias, en dos soportes distintos, con una fuera del local. En una tienda eso se traduce en algo muy sencillo y barato.",
      "Una copia automática diaria en el propio equipo, otra en un disco externo o unidad de red, y una tercera fuera del establecimiento, ya sea un disco que te llevas a casa o una carpeta sincronizada en la nube. El motivo de la de fuera no es el fallo del disco: es el incendio, la inundación y el robo, que se llevan el ordenador y el disco externo que estaba al lado."],
     ["<strong>Diaria y automática</strong>: si depende de que alguien se acuerde, no se hace.",
      "<strong>Al menos una copia fuera del local.</strong>",
      "<strong>Varias generaciones</strong>, no solo la última: si el fallo lleva días, la copia de ayer también está mal.",
      "<strong>Comprobar que se están haciendo</strong>, mirando fecha y tamaño de vez en cuando."]),
    ("La copia que no se ha restaurado nunca no cuenta",
     ["Este es el punto donde falla casi todo el mundo. Las copias se hacen durante dos años, llega el día malo, se intenta restaurar y la copia está incompleta, corrupta o es de una versión que ya no sirve.",
      "Una vez al año, restaura la copia en otro equipo y comprueba que abre y que están los datos. Media hora al año. Es la diferencia entre tener copias de seguridad y creer que las tienes."],
     None),
    ("Datos personales: dónde está la copia también importa",
     ["Tu base de datos contiene datos personales de clientes, y en algunos sectores información sensible. Eso significa que la copia también hay que protegerla: un disco externo con los datos de tus clientes perdido en el metro es una brecha de seguridad.",
      "Conviene que las copias estén cifradas o guardadas en lugar seguro, y tener claro cuánto tiempo conservas cada cosa. Los plazos de conservación y las medidas que te corresponden dependen de tu caso: háblalo con tu asesor."],
     None),
  ],
  faqs=[
    ("¿Cada cuánto debo hacer copia de seguridad?",
     "Diaria y automática. Piensa cuánto trabajo estás dispuesto a rehacer: si la copia es semanal, un fallo el sábado te cuesta seis días de ventas, altas y cobros. La copia manual «cuando me acuerde» no existe en la práctica."),
    ("¿Dónde guardo las copias?",
     "En al menos dos sitios, y uno fuera del local. El disco externo que está junto al ordenador no protege del incendio, la inundación ni el robo, que son escenarios en los que se pierde todo lo que hay en la tienda."),
    ("¿Vale con guardar solo la última copia?",
     "No. Conviene tener varias generaciones, porque si el problema lleva días sin detectarse la copia de ayer también está afectada. Con copias de los últimos días y de las últimas semanas cubres casi cualquier escenario."),
    ("¿Cómo sé que mi copia sirve?",
     "Restaurándola. Una vez al año, en otro equipo, y comprobando que abre y que están los datos. Es lo que casi nadie hace y donde se descubre, ya tarde, que las copias llevaban meses fallando."),
    ("¿Qué pasa si tengo el TPV en la nube?",
     "La copia la hace el proveedor, lo cual quita trabajo pero introduce otra dependencia. Pregunta qué política de copias tiene, cuánto tiempo conserva y cómo puedes exportar tus datos si algún día quieres irte."),
    ("¿Las copias también están sujetas a protección de datos?",
     "Contienen datos personales de tus clientes, así que sí: hay que protegerlas y tener claros los plazos de conservación. Un disco con la base de datos perdido fuera del local es una brecha. Consulta con tu asesor las medidas que te corresponden."),
  ],
  rel=[("TPV que funciona sin internet","/tpv-sin-internet-modo-offline.asp"),
       ("Caja 5 para PC","/caja5_pc.asp"),
       ("TPV en la nube o en tu PC","/comparativa_tpv_nube.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp"),
       ("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
       ("Operativa diaria del TPV","/operativa-tpv.asp")]),
}
