# -*- coding: utf-8 -*-
"""Cluster de operativa diaria, lote 2."""

OPERATIVA_2 = {

"controlar-empleados-tpv.asp": dict(
  nom="el control de empleados en caja", crumb="Control de empleados", icono="fa-user-shield",
  title="Cómo Controlar la Caja con Varios Empleados",
  desc="Cómo trabajar con varios dependientes en el TPV: usuarios y permisos, arqueo por turno, control de anulaciones y descuentos, y qué hacer ante un descuadre.",
  kw="control empleados tpv, usuarios y permisos tpv, arqueo por turno, descuadre caja empleado, anulaciones tickets control",
  h1="Cómo controlar la caja cuando no estás tú detrás",
  sub="No va de desconfiar de nadie. Va de poder reconstruir qué pasó un jueves concreto cuando faltan cuarenta euros, en lugar de sospechar de todos.",
  bloques=[
    ("Usuarios identificados: la base de todo lo demás",
     ["Si todo el mundo trabaja con el mismo usuario, un descuadre es un misterio sin solución. Con usuarios identificados, cada venta, cada devolución, cada anulación y cada apertura de cajón queda asociada a quien la hizo.",
      "Eso no convierte el TPV en un sistema de vigilancia: convierte un problema irresoluble en uno que se puede investigar. Y en la mayoría de casos lo que aparece no es un robo, sino un cambio mal dado o una salida de efectivo que nadie registró."],
     ["<strong>Un usuario por persona</strong>, con su clave, no uno compartido.",
      "<strong>Registro de anulaciones</strong> con quién y cuándo.",
      "<strong>Aperturas de cajón sin venta</strong> registradas.",
      "<strong>Descuentos manuales</strong> asociados a quien los aplica."]),
    ("Permisos: qué puede hacer cada uno",
     ["No todo el mundo necesita poder hacer todo. Un dependiente necesita cobrar, buscar artículos y consultar stock. No necesariamente necesita poder cambiar precios, anular tickets cerrados, ver los márgenes o modificar el catálogo.",
      "Limitar permisos no es desconfianza: es reducir la superficie de error. La mayoría de destrozos en un catálogo los hace alguien con buena intención tocando donde no debía."],
     ["<strong>Cobrar y consultar:</strong> todo el mundo.",
      "<strong>Aplicar descuentos:</strong> con límite máximo por usuario.",
      "<strong>Anular tickets cerrados:</strong> solo responsable.",
      "<strong>Ver márgenes y costes:</strong> solo quien decide compras.",
      "<strong>Modificar catálogo y precios:</strong> restringido."]),
    ("Arqueo por turno, no solo del día",
     ["Si dos personas trabajan en turnos distintos y solo cuadras al cerrar, un descuadre no se puede atribuir a nada. Con arqueo por turno, cada uno cierra lo suyo con su fondo inicial, sus ventas por medio de pago y sus movimientos de efectivo.",
      "El descuadre queda acotado al turno donde se produjo, que es la mitad del camino para entenderlo. Y tiene un efecto secundario útil: cuando cada uno cuadra lo suyo, la gente presta más atención al cambio."],
     None),
    ("Qué hacer cuando falta dinero",
     ["Antes de pensar en lo peor, revisa por este orden: salidas de efectivo no registradas (comprar sellos, pagar al mensajero), ventas cobradas en efectivo y marcadas como tarjeta, cambios mal dados y devoluciones hechas sin registrar.",
      "Esas cuatro causas explican la inmensa mayoría de los descuadres pequeños y constantes. Si después de revisarlas el patrón continúa y se concentra en un turno concreto, entonces sí toca una conversación. Pero llegar a esa conversación con datos, y no con sospechas, cambia por completo cómo va."],
     None),
  ],
  faqs=[
    ("¿Puedo saber qué empleado hizo cada operación?",
     "Sí, trabajando con usuarios identificados: cada venta, devolución, anulación y apertura de cajón queda asociada a quien la hizo. Es lo que permite investigar un descuadre concreto en lugar de sospechar en general."),
    ("¿Puedo limitar lo que puede hacer cada uno?",
     "Sí, por permisos: cobrar y consultar para todos, descuentos con límite máximo, anulación de tickets cerrados solo para responsables, y márgenes y catálogo restringidos. Reduce errores tanto como abusos."),
    ("¿Merece la pena cuadrar caja por turnos?",
     "Mucho, si hay más de una persona. Acota el descuadre al turno donde se produjo y hace que cada uno preste más atención al cambio, que es donde se origina la mayoría de diferencias pequeñas."),
    ("La caja descuadra siempre por poco. ¿Qué reviso?",
     "Por orden: salidas de efectivo sin registrar, ventas en efectivo marcadas como tarjeta, cambios mal dados y devoluciones sin registrar. Esas cuatro causas explican casi todos los descuadres pequeños y constantes."),
    ("¿Puedo limitar el descuento que puede aplicar un dependiente?",
     "Sí, fijando un porcentaje máximo por usuario. Por encima de ese límite se requiere autorización. Evita el descuento por simpatía, que sumado al cabo del año es una cifra seria."),
    ("¿Esto no genera mal ambiente con el equipo?",
     "Depende de cómo se plantee. Presentado como control individual genera recelo; presentado como que cada uno responde de su turno y no carga con los errores de otro, suele recibirse bien. Y protege al empleado honrado tanto como al negocio."),
  ],
  rel=[("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
       ("Cómo hacer una devolución en el TPV","/como-hacer-una-devolucion-tpv.asp"),
       ("TPV para supermercados","/negocio_supermercado.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp"),
       ("Copias de seguridad del TPV","/copia-seguridad-tpv.asp"),
       ("Operativa diaria del TPV","/operativa-tpv.asp")]),

"migrar-de-tpv-cambiar-programa.asp": dict(
  nom="el cambio de programa", crumb="Migrar de TPV", icono="fa-right-left",
  title="Cómo Cambiar de Programa TPV sin Perder Datos",
  desc="Cómo migrar de un TPV a otro: qué datos se pueden trasladar, qué se queda atrás, en qué momento del año hacerlo y cómo evitar quedarte sin poder facturar.",
  kw="cambiar de programa tpv, migrar datos tpv, exportar articulos tpv antiguo, cambiar software tienda, migracion tpv sin perder datos",
  h1="Cómo cambiar de programa TPV sin perder los datos",
  sub="Lo que se puede llevar es el catálogo, el stock y los clientes. Lo que casi nunca se puede llevar es el histórico de tickets. Conviene saberlo antes de empezar.",
  bloques=[
    ("Qué se traslada y qué se queda",
     ["Antes de nada, ajusta expectativas. Lo que se migra bien es el catálogo (artículos, precios, costes, códigos de barras, familias), el stock actual, la ficha de clientes y la de proveedores. Eso es lo que representa meses de trabajo y lo que de verdad importa.",
      "Lo que casi nunca se migra es el histórico de ventas ticket a ticket, porque cada programa lo estructura a su manera. Y ojo: tienes obligaciones de conservación de esa documentación, así que no puedes simplemente borrar el sistema antiguo. Consulta con tu asesor cuánto tiempo debes conservarlo y en qué forma."],
     ["<strong>Sí se migra:</strong> artículos, precios, costes, códigos, familias, stock, clientes y proveedores.",
      "<strong>Suele migrarse:</strong> saldos de clientes y vales pendientes, con trabajo manual.",
      "<strong>Rara vez se migra:</strong> el histórico de tickets y las estadísticas.",
      "<strong>Nunca borres el sistema antiguo</strong> hasta tener claro tu plazo de conservación."]),
    ("Lo primero es comprobar que puedes exportar",
     ["Esta es la pregunta que hay que hacerse antes que ninguna otra, y la que casi nadie hace al contratar un programa: ¿puedo sacar mis datos?",
      "Si tu programa actual permite exportar a Excel o CSV, la migración es un trabajo de horas. Si no lo permite, las opciones son teclear de nuevo, pagar a alguien para que extraiga los datos de la base o quedarte donde estás. Comprueba esto antes de comprometerte con el programa nuevo."],
     None),
    ("El momento del año importa",
     ["Migrar en plena campaña es buscarse un problema. El momento ideal es un periodo de poco movimiento y, si es posible, justo después de un inventario, porque así el stock que cargas en el sistema nuevo es real y no arrastras errores viejos.",
      "En moda, después de rebajas. En juguetería, febrero. En papelería, mayo o junio, nunca agosto. En hostelería y alimentación, evita vísperas de fiestas. La regla general es: el mes en que menos facturas es el mes en que hay que migrar."],
     None),
    ("Convivencia: no apagues lo viejo el primer día",
     ["Lo sensato es tener los dos sistemas disponibles unos días. Empiezas a facturar con el nuevo y mantienes el antiguo accesible para consultar histórico, resolver una devolución de una venta anterior o comprobar un dato.",
      "Y prueba con ventas reales antes del día del cambio: haz cinco tickets de prueba, una devolución, un cierre de caja y comprueba que la impresora saca el ticket como debe. Descubrir que el ticket sale mal configurado con la tienda llena es evitable dedicando media hora antes."],
     ["<strong>Inventario antes de migrar</strong>, para cargar stock real.",
      "<strong>Prueba completa</strong>: ventas, devolución, cierre e impresión.",
      "<strong>Convivencia unos días</strong> con el sistema antiguo accesible.",
      "<strong>Copia de seguridad de los datos antiguos</strong> antes de tocar nada."]),
  ],
  faqs=[
    ("¿Puedo llevarme mis artículos y clientes al programa nuevo?",
     "Sí, si tu programa actual permite exportar a Excel o CSV. Se migran artículos con precios, costes, códigos de barras y familias, el stock actual, y las fichas de clientes y proveedores. Es lo que representa meses de trabajo."),
    ("¿Y el histórico de tickets?",
     "Rara vez se migra, porque cada programa lo estructura a su manera. Ten en cuenta que tienes obligaciones de conservación de esa documentación: no borres el sistema antiguo sin confirmar con tu asesor cuánto tiempo debes conservarla."),
    ("¿Cuándo es mejor cambiar de programa?",
     "En tu mes de menos facturación y, a ser posible, justo después de un inventario, para cargar stock real. En moda, después de rebajas; en juguetería, febrero; en papelería, mayo o junio. Nunca en plena campaña."),
    ("¿Y si mi programa actual no me deja exportar?",
     "Las opciones son teclear de nuevo, pagar a alguien para extraer los datos de la base o quedarte. Es la pregunta que conviene hacer al contratar cualquier programa y que casi nadie hace: ¿puedo sacar mis datos si me voy?"),
    ("¿Cuánto se tarda en migrar?",
     "Con los datos exportados y bien ordenados, la carga es cuestión de horas. Lo que lleva tiempo es la preparación: ordenar el Excel, decidir la estructura de familias y hacer el inventario previo. Cuenta con unos días de trabajo repartidos."),
    ("¿Puedo tener los dos programas funcionando a la vez?",
     "Unos días, sí, y es lo recomendable: facturas con el nuevo y mantienes el antiguo accesible para consultas y para resolver devoluciones de ventas anteriores. Apagar lo viejo el primer día es innecesariamente arriesgado."),
  ],
  rel=[("Dar de alta el catálogo en el TPV","/dar-de-alta-articulos-tpv.asp"),
       ("Comparativas de TPV","/comparativas-tpv.asp"),
       ("Copias de seguridad del TPV","/copia-seguridad-tpv.asp"),
       ("Cómo hacer el inventario de una tienda","/como-hacer-un-inventario-tienda.asp"),
       ("Alternativa al TPV por suscripción","/alternativa-tpv-suscripcion.asp"),
       ("Operativa diaria del TPV","/operativa-tpv.asp")]),

"vender-online-y-tienda-fisica-stock.asp": dict(
  nom="la venta online con tienda física", crumb="Online y tienda física", icono="fa-globe",
  title="Vender Online y en Tienda con el Mismo Stock",
  desc="Cómo sincronizar el stock entre tu tienda física y la online: sobreventa, reservas, plazos de sincronización, devoluciones cruzadas y qué mirar antes de conectar.",
  kw="sincronizar stock tienda online, vender online y tienda fisica, sobreventa ecommerce stock, conectar tpv con tienda online, stock unificado",
  h1="Vender online y en tienda física con un solo stock",
  sub="El problema no es técnico: es que la última unidad se puede vender dos veces, una en el mostrador y otra en la web, con quince minutos de diferencia.",
  bloques=[
    ("La sobreventa es el problema real, y no se elimina del todo",
     ["Cuando tienes una unidad y dos canales, existe una ventana de tiempo en la que ambos pueden venderla. Aunque la sincronización sea rápida, el intervalo no es cero: si un cliente está pagando en la web mientras otro paga en el mostrador, alguien se va a quedar sin producto.",
      "No se elimina, se gestiona. Las dos herramientas son reducir el intervalo de sincronización y reservar un colchón de seguridad: no publicar online la última unidad de los artículos con poca profundidad de stock."],
     ["<strong>Colchón de seguridad</strong>: no publicar la última unidad de artículos únicos.",
      "<strong>Sincronización lo más frecuente posible</strong> en los artículos con más rotación.",
      "<strong>Protocolo claro</strong> para cuando pasa: avisar rápido y ofrecer alternativa o reembolso.",
      "<strong>Piezas únicas</strong>, como en joyería o segunda mano, con tratamiento aparte."]),
    ("Qué hay que sincronizar además del stock",
     ["Casi todo el mundo piensa en el stock y se olvida del resto. También conviene que viajen los precios (para no tener dos tarifas divergentes), las fichas de producto con sus fotos y descripciones, y los pedidos web hacia el TPV para que se descuenten del inventario y aparezcan en tus estadísticas de venta.",
      "Si los pedidos online no entran en el TPV, tu informe de ventas está incompleto y tus decisiones de compra se basan en la mitad de la información."],
     ["<strong>Stock</strong> en ambos sentidos.",
      "<strong>Precios y campañas</strong>, decidiendo si la web tiene tarifa propia.",
      "<strong>Fichas y fotos</strong>, para no mantener dos catálogos.",
      "<strong>Pedidos web hacia el TPV</strong>, que es lo que suele faltar."]),
    ("Devoluciones cruzadas: comprar online y devolver en tienda",
     ["Es lo que el cliente espera y lo que más descuadra los sistemas si no está previsto. El artículo vuelve físicamente a tu tienda pero la venta se hizo en la web, con su propio medio de pago y a veces con derecho de desistimiento por ser venta a distancia.",
      "Hay que decidir antes cómo se gestiona: si el reembolso sale de la caja de la tienda o del canal online, cómo vuelve el stock y qué documento se emite. Y recuerda que el régimen legal de la venta a distancia no es el mismo que el de la tienda física; consúltalo con tu asesor."],
     None),
    ("Antes de conectar nada, ordena el catálogo",
     ["El error más frecuente es intentar conectar la web con un catálogo desordenado: referencias duplicadas, artículos sin código de barras, familias inconsistentes o stock que no cuadra con la realidad.",
      "La sincronización no arregla nada de eso: lo multiplica y lo hace público. Haz inventario, limpia duplicados y asegúrate de que cada artículo tiene una referencia única antes de conectar. Media semana de orden previo ahorra meses de incidencias con clientes."],
     None),
  ],
  faqs=[
    ("¿Puedo evitar del todo vender dos veces la última unidad?",
     "Del todo, no: siempre hay una ventana entre que se vende en un canal y se actualiza en el otro. Se gestiona reduciendo el intervalo de sincronización y no publicando online la última unidad de artículos con poca profundidad."),
    ("¿Qué debo sincronizar además del stock?",
     "Precios, fichas de producto con sus fotos, y sobre todo los pedidos web hacia el TPV. Si los pedidos online no entran en tu programa, tu informe de ventas está incompleto y compras con la mitad de la información."),
    ("¿Cómo gestiono una devolución en tienda de algo comprado online?",
     "Hay que decidirlo antes: de dónde sale el reembolso, cómo vuelve el stock y qué documento se emite. Ten en cuenta que la venta a distancia tiene su propio régimen legal, con derecho de desistimiento, distinto del de la tienda física. Consúltalo con tu asesor."),
    ("¿Necesito la versión en nube para vender online?",
     "Para sincronización en tiempo real con la web, la modalidad en nube es la vía natural. Con la versión de PC puedes trabajar con sincronizaciones programadas, que para catálogos con profundidad de stock suele ser suficiente."),
    ("¿Qué hago antes de conectar la tienda online?",
     "Ordenar el catálogo: inventario hecho, duplicados eliminados y referencia única por artículo. La sincronización no arregla el desorden, lo multiplica y además lo hace público delante de tus clientes."),
    ("¿Y si vendo piezas únicas?",
     "En joyería, antigüedades o segunda mano, donde cada pieza es única, la sobreventa es especialmente grave porque no hay alternativa que ofrecer. Ahí conviene sincronización muy frecuente y, si el volumen lo permite, marcar la pieza como reservada en cuanto alguien la aparta."),
  ],
  rel=[("Caja 5 Nube","/caja5_nube.asp"),
       ("TPV en la nube o en tu PC","/comparativa_tpv_nube.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Cómo hacer una devolución en el TPV","/como-hacer-una-devolucion-tpv.asp"),
       ("Comparativas de TPV","/comparativas-tpv.asp"),
       ("Operativa diaria del TPV","/operativa-tpv.asp")]),

"cuentas-de-cliente-cobrar-fin-de-mes.asp": dict(
  nom="las cuentas de cliente", crumb="Cuentas de cliente", icono="fa-file-invoice",
  title="Cuentas de Cliente: Vender a Crédito y Cobrar a Fin de Mes",
  desc="Cómo llevar clientes que compran a diario y pagan a fin de mes: albaranes, factura agrupada, tarifas por cliente, límite de riesgo y cómo reclamar impagos.",
  kw="cuenta de cliente tienda, vender a credito comercio, albaran y factura fin de mes, tarifa por cliente, limite de riesgo cliente, impagos pequeño comercio",
  h1="Clientes que pagan a fin de mes: cómo llevarlo sin perder dinero",
  sub="El profesional que compra a diario es el cliente más rentable que tienes. Y el que más dinero te puede costar si lo llevas en una libreta.",
  bloques=[
    ("Albarán en lugar de ticket",
     ["El cliente con cuenta abierta no quiere pagar cada vez: quiere llevarse el material y que a fin de mes le llegue una factura con todo. Eso significa que cada operación genera un albarán, no un ticket, y que el cobro se produce después.",
      "Llevado en papel funciona hasta que se pierde un albarán, y siempre se pierde alguno. Cada albarán perdido es dinero regalado, y además genera discusiones incómodas con un cliente al que quieres conservar."],
     ["<strong>Albarán por operación</strong>, con firma si tu operativa lo requiere.",
      "<strong>Agrupación en factura mensual</strong> con todos los del periodo.",
      "<strong>Saldo por cliente</strong> siempre visible.",
      "<strong>Consulta de qué se llevó y cuándo</strong>, que resuelve la mayoría de discrepancias."]),
    ("Tarifas: el profesional no paga precio de mostrador",
     ["Un fontanero que te compra a diario espera un precio distinto del particular que entra una vez al año. Lo habitual es una tarifa con descuento por familia, o un porcentaje sobre el precio de mostrador.",
      "Tenerlo en la ficha del cliente evita dos problemas: que el dependiente tenga que acordarse del descuento de cada uno, y que ese descuento se aplique por simpatía a quien no le corresponde. También te permite ver el margen real por cliente, que a veces revela que el que más compra no es el que más deja."],
     None),
    ("Límite de riesgo: el número que evita el disgusto",
     ["Un cliente que acumula seis meses de albaranes sin pagar no aparece de golpe: se ve venir. Lo que hace falta es mirar, y para mirar hace falta que el dato esté.",
      "Fijar un límite de riesgo por cliente, y que el programa avise al superarlo, convierte una conversación difícil de tener en una conversación fácil de tener a tiempo. Es mucho más cómodo decir «te has puesto en el límite» a los 800 euros que reclamar 4.000 seis meses después."],
     ["<strong>Límite por cliente</strong>, ajustado a lo que puedes permitirte perder.",
      "<strong>Aviso al superarlo</strong>, visible para quien atiende.",
      "<strong>Antigüedad de la deuda</strong>, no solo el importe total.",
      "<strong>Histórico de pago</strong>: quién cumple y quién siempre se retrasa."]),
    ("Cuando hay que reclamar",
     ["Si llega el caso, tener la documentación en orden lo cambia todo: albaranes con fecha y detalle, facturas emitidas y registro de los pagos parciales. Un cliente que no paga y sabe que tienes todo documentado suele pagar antes que uno que intuye que llevas las cuentas de memoria.",
      "Las vías de reclamación y los plazos aplicables dependen de tu caso y de la cuantía. Antes de dar nada por perdido o de emprender acciones, habla con tu asesor: hay procedimientos pensados para importes pequeños que mucha gente desconoce."],
     None),
  ],
  faqs=[
    ("¿Cómo llevo un cliente que compra a diario y paga a fin de mes?",
     "Con cuenta de cliente: cada operación genera albarán en lugar de ticket, y a fin de mes se agrupan todos en una factura. El saldo pendiente está siempre visible y puedes consultar qué se llevó y cuándo, que resuelve la mayoría de discrepancias."),
    ("¿Puedo tener precios distintos para profesionales?",
     "Sí, con tarifa por cliente: descuento por familia o porcentaje sobre el precio de mostrador, guardado en su ficha. Así el dependiente no tiene que acordarse y el descuento no se aplica a quien no le corresponde."),
    ("¿Cómo evito que un cliente acumule demasiada deuda?",
     "Fijando un límite de riesgo por cliente y haciendo que el programa avise al superarlo. Es mucho más fácil comentar el asunto a los 800 euros que reclamar 4.000 medio año después."),
    ("¿Puedo saber qué cliente me deja más margen?",
     "Sí, cruzando su facturación con su tarifa y los costes de lo que compra. A veces revela que el cliente que más volumen hace no es el que más beneficio deja, porque tiene el descuento más agresivo."),
    ("¿Qué documentación necesito si tengo que reclamar?",
     "Albaranes con fecha y detalle, facturas emitidas y registro de pagos parciales. Con todo documentado la conversación es muy distinta. Las vías y plazos concretos dependen de la cuantía y de tu caso: consúltalo con tu asesor."),
    ("¿Merece la pena vender a crédito?",
     "En ferretería, papelería de oficina, panadería con reparto o suministro profesional, es donde está el volumen estable que paga las facturas de los meses flojos. El riesgo se gestiona con límites y con seguimiento, no evitando el cliente."),
  ],
  rel=[("TPV para ferreterías","/negocio_ferreteria.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("TPV para papelerías","/negocio_papeleria.asp"),
       ("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp"),
       ("Operativa diaria del TPV","/operativa-tpv.asp")]),

"informes-tpv-que-mirar.asp": dict(
  nom="los informes del TPV", crumb="Informes y decisiones", icono="fa-chart-line",
  title="Qué Informes del TPV Mirar (y Cuáles Ignorar)",
  desc="Los cinco informes del TPV que de verdad cambian decisiones en una tienda: rotación, margen por familia, stock muerto, ventas por hora y ranking de clientes.",
  kw="informes tpv, que informes mirar tienda, rotacion de stock informe, margen por familia, analisis ventas comercio",
  h1="Qué informes mirar de verdad y cuáles ignorar",
  sub="Un TPV puede darte cuarenta informes. Cuatro cambian decisiones y el resto es entretenimiento. Estos son los que valen.",
  bloques=[
    ("Rotación: qué se mueve y qué está muerto",
     ["Es el informe más útil y el menos consultado. Ordena tus artículos por unidades vendidas en un periodo y mira los dos extremos. Arriba está lo que nunca puedes tener agotado. Abajo está el dinero que tienes parado.",
      "El dato que de verdad importa no es cuántas unidades vendiste, sino cuánto capital tienes inmovilizado en lo que no se mueve. Diez artículos caros parados pesan más que doscientos baratos, y son los primeros que hay que liquidar."],
     ["<strong>Top de rotación:</strong> nunca dejar que se agote.",
      "<strong>Cola de rotación ordenada por capital</strong>, no por unidades.",
      "<strong>Artículos sin venta en seis meses</strong>, que son candidatos a liquidación.",
      "<strong>Rotación por familia</strong>, para ver qué sección merece más espacio."]),
    ("Margen por familia: dónde ganas de verdad",
     ["La facturación engaña. Una familia puede ser la que más vende y la que menos aporta, y otra puede ser discreta en volumen y sostener el negocio. Lo único que revela eso es el margen por familia, y necesita que los precios de coste estén bien metidos.",
      "Este informe suele producir sorpresas incómodas y útiles: descubrir que la sección a la que dedicas medio escaparate deja menos que la esquina que tienes olvidada cambia decisiones de espacio, de compra y de promoción."],
     None),
    ("Ventas por hora y por día: para qué sirve de verdad",
     ["No sirve para saber cuándo vendes más, que ya lo sabes. Sirve para decidir horarios y personal. Si el 40 % de tu facturación entra entre las 18 y las 20, ahí es donde no puedes estar solo en el mostrador.",
      "También sirve para cuestionar el horario. Muchos comercios abren por la mañana por costumbre y descubren, mirando el dato, que las tres primeras horas aportan un porcentaje mínimo que no cubre ni el coste de tener a alguien ahí."],
     None),
    ("Ranking de clientes: el 20 % que sostiene la tienda",
     ["Si trabajas con clientes identificados, este informe te dice quiénes son las personas que sostienen tu negocio. Suele ser un grupo más pequeño de lo que uno imagina.",
      "Con esa lista puedes hacer cosas concretas: avisar de novedades a quien compra esa marca, preparar una preventa de rebajas para el club, o simplemente saber a quién echas de menos si lleva tres meses sin aparecer. Para las comunicaciones comerciales necesitas su consentimiento; el programa te deja registrarlo."],
     None),
    ("Los informes que no cambian nada",
     ["Hay métricas que se miran mucho y no llevan a ninguna decisión: la facturación acumulada del año sin comparativa, el número total de tickets sin cruzarlo con nada, o los gráficos bonitos de evolución sin desglose.",
      "La prueba para saber si un informe merece tu tiempo es sencilla: pregúntate qué harías distinto según lo que salga. Si la respuesta es «nada», no vuelvas a abrirlo."],
     None),
  ],
  faqs=[
    ("¿Cuál es el informe más útil de un TPV?",
     "El de rotación, ordenando la cola por capital inmovilizado y no por unidades. Te dice qué nunca puedes tener agotado y dónde tienes el dinero parado. Es el que más decisiones cambia y el que menos se consulta."),
    ("¿Por qué mi informe de márgenes no cuadra con la realidad?",
     "Casi siempre porque los precios de coste no están actualizados. Si subes el PVP cuando el proveedor sube tarifa pero no actualizas el coste, el informe dirá que ganas más de lo que ganas. Es el error que más silenciosamente destruye rentabilidad."),
    ("¿Para qué sirve el informe de ventas por hora?",
     "Para decidir horarios y refuerzo de personal, no para saber cuándo vendes más. Y para cuestionar el horario de apertura: muchos comercios descubren que las primeras horas de la mañana no cubren el coste de tener a alguien atendiendo."),
    ("¿Cada cuánto debo mirar los informes?",
     "Rotación y stock muerto, mensual. Margen por familia, trimestral. Ventas por hora, un par de veces al año o cuando plantees un cambio de horario. Mirarlos a diario no aporta y genera decisiones a corto plazo."),
    ("¿Cómo sé si un informe merece la pena?",
     "Pregúntate qué harías distinto según lo que salga. Si la respuesta es «nada», es entretenimiento y no información. La facturación acumulada sin comparativa es el ejemplo clásico."),
    ("¿Necesito identificar a los clientes para sacar partido a los informes?",
     "Para los de rotación y margen, no. Para el ranking de clientes y cualquier acción de fidelización, sí. Y para enviarles comunicaciones comerciales necesitas su consentimiento, que conviene registrar."),
  ],
  rel=[("Cerrar temporada y liquidar stock","/cerrar-temporada-liquidar-stock.asp"),
       ("Programa de fidelización y puntos","/programa-fidelizacion-puntos.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("Cambiar precios en masa","/cambiar-precios-masivamente-tpv.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Operativa diaria del TPV","/operativa-tpv.asp")]),
}
