# -*- coding: utf-8 -*-
"""Base de hechos por sector, lote 1.

Cada entrada contiene prosa escrita para ESE sector: las unidades que maneja de
verdad, su normativa propia, su operativa y su vocabulario. El generador solo
aporta la maqueta; el contenido no es intercambiable entre sectores.
"""

SECTORES_1 = {

# ============================================================== FERRETERIA
"negocio_ferreteria.asp": dict(
  nombre="Ferreterías y suministro industrial",
  crumb="Ferreterías",
  icono="fa-screwdriver-wrench",
  title="Software TPV para Ferreterías y Suministro | Caja 5",
  desc="TPV para ferreterías: venta por unidad y a granel, tornillería sin código de barras, equivalencias entre proveedores, corte a medida y cuentas de cliente a crédito.",
  kw="tpv ferreteria, software ferreteria, programa tpv ferreteria, tpv ferreteria sin cuotas, gestion stock ferreteria, tpv suministro industrial",
  h1='Software TPV para Ferreterías. <span>Miles de referencias, muchas sin código de barras.</span>',
  sub='Una ferretería media maneja entre 8.000 y 20.000 referencias, y buena parte se vende suelta: tornillos por unidad, cable por metro, llaves copiadas al momento. Eso no lo resuelve un TPV de tienda de ropa.',
  bloques=[
    ("El problema de la ferretería es el número de referencias, no el volumen de venta",
     ["Una tienda de ropa con 600 modelos tiene un catálogo grande. Una ferretería con 12.000 referencias tiene un catálogo que ningún dependiente memoriza, donde el 70 % del stock rota dos veces al año y donde el cliente pregunta por «el tornillo ese de cabeza plana, el del año pasado».",
      "El TPV tiene que estar montado para encontrar rápido, no para lucir bonito. Búsqueda por descripción parcial, por referencia del proveedor, por código propio y por ubicación en la tienda. Si el dependiente tarda cuarenta segundos en localizar un artículo, la cola se forma sola."],
     ["<strong>Búsqueda por varias claves.</strong> Referencia interna, referencia del fabricante, código de barras si lo trae y descripción libre.",
      "<strong>Ubicación física en la ficha.</strong> Pasillo, estantería y balda. Es lo que convierte un catálogo de 12.000 líneas en algo que se puede servir.",
      "<strong>Equivalencias entre proveedores.</strong> El mismo racor lo sirven tres mayoristas con tres referencias distintas. Poder relacionarlas evita comprar duplicado.",
      "<strong>Familias profundas.</strong> Tornillería, fontanería, electricidad, pintura, jardín, con subfamilias reales que se puedan recorrer en pantalla."]),
    ("Venta por unidad, por metro y por peso",
     ["Aquí está la diferencia técnica de verdad. En ferretería se compra una caja de 500 tornillos y se venden de siete en siete. Se compra una bobina de 100 metros de cable y se corta a 3,40. Se compran sacos de 25 kilos de tornillos a granel y se venden a peso.",
      "Eso obliga a que el artículo admita una unidad de compra y otra de venta, con su factor de conversión. Si el programa solo sabe contar unidades enteras, tu stock miente desde el primer día."],
     ["<strong>Unidad de compra distinta de la de venta.</strong> Compras la caja, vendes la unidad, y el stock baja en la proporción correcta.",
      "<strong>Corte a medida.</strong> Cable, cadena, cuerda, moqueta o tubo vendidos por metro con decimales.",
      "<strong>Venta a peso</strong> conectando la balanza, para tornillería y herrajes a granel.",
      "<strong>Precio por escalado.</strong> Un precio para la unidad suelta y otro para la caja completa, aplicado solo."]),
    ("El cliente profesional no paga en el mostrador",
     ["Una parte importante de la facturación de una ferretería son albaranes a fontaneros, electricistas y pequeñas empresas que pasan durante el mes y liquidan a fin de mes. Ese cliente no quiere ticket: quiere albarán, y a final de mes una factura que agrupe todos.",
      "Si llevas eso en una libreta, tarde o temprano se te pierde un albarán, que es dinero regalado. El programa debe permitir venta a crédito con cuenta de cliente, agrupación de albaranes en factura mensual y control de riesgo por cliente."],
     ["<strong>Albarán en lugar de ticket</strong> para el cliente con cuenta abierta.",
      "<strong>Facturación agrupada</strong> a fin de mes con todos los albaranes del periodo.",
      "<strong>Tarifas por cliente.</strong> El profesional tiene su descuento por familia, distinto del precio de mostrador.",
      "<strong>Control de riesgo.</strong> Saldo pendiente por cliente y aviso cuando pasa del límite que le hayas puesto."]),
    ("Copia de llaves, mandos y servicios",
     ["Casi toda ferretería presta servicios que no son producto: copiar llaves, duplicar mandos de garaje, cortar cristal, hacer una mezcla de pintura. No tienen stock pero sí precio, y conviene facturarlos como línea propia para saber cuánto pesan en tu margen.",
      "En el caso del mando de garaje y de las llaves de seguridad hay además una cuestión de registro que no todo el mundo lleva: conviene guardar quién encargó una copia de llave restringida. Consulta con tu asesor qué exige la normativa aplicable a tu caso concreto."]),
  ],
  faqs=[
    ("¿Puedo vender tornillos por unidad si los compro en cajas de 500?",
     "Sí. El artículo se da de alta con unidad de compra «caja» y unidad de venta «unidad», indicando cuántas unidades trae la caja. Cuando recibes una caja, el stock sube 500; cuando vendes siete tornillos, baja siete. Es la única forma de que el inventario de una ferretería cuadre."),
    ("¿Cómo vendo cable o cadena por metros con decimales?",
     "Dando de alta el artículo como venta por medida. Introduces 3,40 metros en caja y el programa calcula el importe sobre el precio por metro, descontando esa cantidad de la bobina. Lo mismo sirve para cuerda, tubo, moqueta o cadena."),
    ("Tengo clientes profesionales que pagan a fin de mes. ¿Se puede llevar?",
     "Sí, con cuenta de cliente. En lugar de ticket emites albarán, y a fin de mes generas una factura que agrupa todos los albaranes de ese cliente en el periodo. Puedes fijarle además su tarifa de descuento por familia y un límite de riesgo que avise cuando lo supere."),
    ("Mis artículos no tienen código de barras. ¿Tengo que etiquetarlos todos?",
     "No hace falta etiquetar los 12.000. Lo práctico es etiquetar lo que rota y lo que tiene valor, y para el resto trabajar con búsqueda por descripción y ubicación. Muchas ferreterías etiquetan por balda en lugar de por unidad, con una etiqueta de estantería que el dependiente lee."),
    ("¿Puedo relacionar la misma pieza de dos proveedores distintos?",
     "Sí, mediante referencias equivalentes en la ficha del artículo. Es lo que evita el error clásico de comprar el mismo racor a dos mayoristas creyendo que son cosas distintas, y te deja comparar a quién se lo compras más barato."),
    ("¿Sirve para llevar también el taller o los servicios de corte?",
     "Los servicios como copia de llaves, corte de cristal o mezcla de pintura se dan de alta como artículos sin stock pero con precio, y se añaden al ticket como una línea más. Así sabes al final del año cuánto has facturado por servicio, que suele sorprender."),
  ],
  rel=[("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("Etiquetas con código de barras","/etiquetas-codigo-de-barras-tpv.asp"),
       ("TPV para tiendas de pinturas","/negocio_pinturas.asp"),
       ("Inventario con PDA o lector","/inventario-con-pda-lector-codigo-barras.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp")]),

# ================================================================== OPTICA
"negocio_optica.asp": dict(
  nombre="Ópticas y optometría",
  crumb="Ópticas",
  icono="fa-glasses",
  title="Software TPV para Ópticas: graduación y encargos | Caja 5",
  desc="TPV para ópticas: ficha de graduación por cliente, encargo de lentes al laboratorio, control de monturas por modelo y color, garantías y revisiones programadas.",
  kw="tpv optica, software optica, programa gestion optica, tpv para tienda de optica, ficha graduacion cliente, encargo lentes laboratorio",
  h1='Software TPV para Ópticas. <span>Graduación, encargos al taller y revisiones.</span>',
  sub='En una óptica la venta no termina en caja: empieza. Se toma la graduación, se encarga la lente al laboratorio, se monta y se avisa al cliente. El TPV tiene que seguir ese hilo entero.',
  bloques=[
    ("La ficha del cliente vale más que el catálogo",
     ["Una óptica vive de la recurrencia. El cliente vuelve cada dos o tres años, y cuando vuelve, lo que necesitas delante es su historial: qué graduación tenía, qué montura eligió, qué tratamiento llevaban las lentes y cuándo fue la última revisión.",
      "Eso convierte la ficha de cliente en el activo central del negocio, muy por encima del catálogo de monturas. Con el historial delante, la conversación de venta es completamente distinta a empezar de cero cada vez."],
     ["<strong>Histórico de graduaciones con fecha.</strong> Esfera, cilindro, eje, adición y distancia interpupilar de cada revisión.",
      "<strong>Qué se llevó la última vez.</strong> Montura, tipo de lente, tratamiento y precio pagado.",
      "<strong>Aviso de revisión.</strong> Listado de clientes a los que toca revisar, para llamar o mandar un correo.",
      "<strong>Garantía asociada.</strong> Fecha de entrega y periodo, para resolver una incidencia sin buscar papeles."]),
    ("El encargo al laboratorio es un pedido, no una venta",
     ["Cuando el cliente elige montura y lentes, la venta queda abierta. Hay que encargar la lente al laboratorio con la graduación exacta, esperar el plazo, montar y avisar. Entre medias suelen pasar de tres a diez días y el cliente llama para preguntar.",
      "Si eso se lleva en una libreta de encargos, la información vive en la cabeza de quien la apuntó. Con el encargo dentro del programa, cualquiera del mostrador ve en qué estado está cada gafa y qué se prometió al cliente."],
     ["<strong>Estado del encargo.</strong> Pendiente de pedir, pedido, recibido, montado y entregado.",
      "<strong>Datos técnicos en el encargo</strong>, para que lo que se pide al laboratorio sea exactamente lo medido.",
      "<strong>Señal y saldo pendiente.</strong> Lo normal es cobrar una parte al encargar y el resto al entregar.",
      "<strong>Aviso al cliente</strong> cuando la gafa está lista, por teléfono o mensaje."]),
    ("Monturas, lentes de contacto y líquidos son tres negocios distintos",
     ["La montura es un artículo de moda: tiene modelo, color y calibre, rota por temporada y se expone. Las lentes de contacto son consumible con caducidad y con recompra predecible cada mes o cada trimestre. Los líquidos y accesorios son venta de mostrador de bajo importe.",
      "Cada uno pide un tratamiento distinto en el programa. La montura, variantes por color y calibre. La lente de contacto, control de caducidad y avisos de reposición al cliente. El accesorio, velocidad en caja."],
     ["<strong>Monturas por modelo, color y calibre</strong>, con su marca y su temporada.",
      "<strong>Lentes de contacto con lote y caducidad</strong>, y recompra programada por cliente.",
      "<strong>Consumibles de mostrador</strong> con venta rápida por familia."]),
    ("Lo que conviene tener claro con los datos de salud",
     ["La graduación y el historial visual son datos de salud, y su tratamiento está sujeto a requisitos reforzados de protección de datos. Conviene que estén guardados en tu propio equipo o en un servicio con las garantías adecuadas, con acceso limitado a quien deba tenerlo, y que tengas informado al cliente de la finalidad del tratamiento.",
      "No es un detalle menor y no es algo que deba resolver una página web: habla con tu asesor sobre el registro de actividades de tratamiento y las medidas que te corresponden. Que el programa guarde los datos en local, y no en un servidor ajeno, simplifica bastante esa conversación."]),
  ],
  faqs=[
    ("¿Puedo guardar el historial de graduaciones de cada cliente?",
     "Sí. Cada cliente puede tener sucesivas graduaciones fechadas con esfera, cilindro, eje, adición y distancia interpupilar, de forma que al volver ves la evolución y qué se llevó la última vez. Ten en cuenta que son datos de salud y que su tratamiento exige medidas reforzadas: consúltalo con tu asesor."),
    ("¿Cómo controlo las gafas que están en el laboratorio?",
     "Con el encargo dentro del programa y su estado: pendiente de pedir, pedido, recibido, montado y entregado. En cualquier momento sacas el listado de encargos abiertos y sabes qué prometiste a cada cliente, sin depender de la libreta del mostrador."),
    ("¿Se puede cobrar una señal al encargar y el resto al entregar?",
     "Sí, es lo habitual en óptica. Registras el anticipo al hacer el encargo y la operación queda con saldo pendiente hasta la entrega, momento en el que se liquida el resto."),
    ("¿Puedo llevar las monturas por modelo, color y calibre?",
     "Sí, con la matriz de variantes: el modelo es la ficha y el color y el calibre son las variantes, cada una con su stock propio. Es el mismo mecanismo que usan las tiendas de ropa para tallas y colores, aplicado a lo que de verdad varía en una montura."),
    ("¿Y las lentes de contacto, que caducan?",
     "Se controlan por lote y fecha de caducidad, igual que cualquier producto sanitario con vida útil. Además puedes programar la recompra de cada cliente, que en lentes mensuales es predecible y es una de las mayores fuentes de venta recurrente de una óptica."),
    ("¿Puedo avisar a los clientes de que les toca revisión?",
     "Sí, sacando el listado de clientes cuya última revisión supera el periodo que definas y contactando por teléfono o correo. Necesitas su consentimiento para comunicaciones comerciales; el programa te permite registrarlo."),
  ],
  rel=[("Programa de fidelización y puntos","/programa-fidelizacion-puntos.asp"),
       ("TPV con gestión de clientes","/negocio_gestion_clientes.asp"),
       ("TPV para relojerías","/negocio_relojeria.asp"),
       ("Vales y tarjetas regalo","/vales-y-tarjetas-regalo-tpv.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),

# =============================================================== PAPELERIA
"negocio_papeleria.asp": dict(
  nombre="Papelerías y material de oficina",
  crumb="Papelerías",
  icono="fa-pen-ruler",
  title="Software TPV para Papelerías y Librerías | Caja 5",
  desc="TPV para papelerías: campaña de vuelta al cole, listas de material por colegio, fotocopias y servicios, encargos de libro de texto y venta rápida de bajo importe.",
  kw="tpv papeleria, software papeleria, programa tpv libreria papeleria, tpv vuelta al cole, listas material escolar, tpv fotocopias",
  h1='Software TPV para Papelerías. <span>Septiembre no se parece a ningún otro mes.</span>',
  sub='Una papelería factura en tres semanas de septiembre lo que en cuatro meses normales. El programa tiene que aguantar esa punta y, el resto del año, ir rápido con tickets de dos euros.',
  bloques=[
    ("La campaña de vuelta al cole es un negocio dentro del negocio",
     ["Entre finales de agosto y mediados de septiembre, una papelería de barrio concentra una parte enorme de su facturación anual. Colas largas, tickets con veinte líneas y padres con la lista del colegio en la mano.",
      "Lo que decide si esa campaña sale bien o mal no es el margen: es la preparación. Tener cargadas las listas de material de los colegios de la zona convierte una venta de veinte minutos en una de tres, y esa diferencia multiplicada por cientos de familias es toda la campaña."],
     ["<strong>Listas de material por colegio y curso</strong> guardadas como conjunto, para servirlas de una vez en lugar de artículo por artículo.",
      "<strong>Presupuesto previo.</strong> El padre pide precio con la lista, se lo das por escrito y vuelve a recogerlo.",
      "<strong>Encargo de lo que falta,</strong> con aviso cuando llega, en lugar de perder la venta.",
      "<strong>Reposición diaria en campaña.</strong> En septiembre el stock mínimo semanal no sirve: hay que mirar a diario qué se está agotando."]),
    ("El resto del año son tickets pequeños y muchas referencias",
     ["Fuera de campaña, la papelería vive de tickets de uno a cinco euros: un bolígrafo, un sobre, una cartulina. Con ese ticket medio, cada segundo de más en caja se paga caro, y etiquetar individualmente un bolígrafo de 0,60 € no compensa.",
      "La solución práctica es mixta: código de barras en lo que lo trae de fábrica, que en papelería es mucho, y venta rápida por familia y precio para lo suelto y lo pequeño."],
     ["<strong>Botones de acceso rápido</strong> para lo que más se vende y no está etiquetado.",
      "<strong>Artículos genéricos por precio</strong> para el material suelto de céntimos.",
      "<strong>Lector de código de barras</strong> para todo lo que ya viene con EAN, que en material de oficina es la mayoría."]),
    ("Fotocopias, plastificados y encuadernación: el margen escondido",
     ["Los servicios de reprografía suelen ser el producto de mayor margen de una papelería y el peor controlado. Se cobran a ojo, no se registran como línea y a final de año nadie sabe cuánto han supuesto.",
      "Dados de alta como artículos de servicio con su precio por unidad, empiezas a ver el dato. Muchas papelerías descubren que la fotocopiadora aporta más margen que media tienda."],
     ["<strong>Servicios como artículo sin stock:</strong> copia en blanco y negro, color, plastificado, encuadernado, impresión desde memoria.",
      "<strong>Precio por tramos.</strong> Las primeras diez copias a un precio y a partir de cien, otro.",
      "<strong>Cuenta de cliente</strong> para la gestoría o la academia del barrio que copia todos los meses y paga a fin de mes."]),
    ("Libro de texto: encargos, reservas y devolución al distribuidor",
     ["Si trabajas libro de texto, la operativa se parece más a una librería que a una papelería. Se reserva por familia antes del verano, se pide al distribuidor, llega en tandas y lo que no se vende se devuelve.",
      "Necesitas saber en todo momento qué está reservado y a nombre de quién, qué ha llegado y qué queda pendiente de devolver. Un libro devuelto fuera de plazo es margen perdido directamente."]),
  ],
  faqs=[
    ("¿Puedo cargar las listas de material de los colegios de mi zona?",
     "Sí, guardándolas como conjuntos de artículos. Cuando llega un padre con la lista del colegio y curso, cargas el conjunto de una vez y ajustas lo que sobre o falte. En campaña de septiembre esa diferencia de tiempo por cliente es lo que decide cuántas familias puedes atender."),
    ("¿Cómo cobro rápido artículos de céntimos que no puedo etiquetar?",
     "Con botones de acceso rápido para lo más vendido y artículos genéricos por precio para el material suelto. Pierdes detalle de stock en esas referencias, pero ganas velocidad, que con un ticket medio de dos euros es lo que importa. Lo etiquetado con EAN de fábrica sigue pasando por lector."),
    ("¿Puedo llevar las fotocopias y la encuadernación en el mismo ticket?",
     "Sí, dando de alta los servicios de reprografía como artículos sin stock con su precio. Puedes además definir precio por tramos, para que las primeras copias tengan un precio y a partir de cierta cantidad se aplique otro automáticamente."),
    ("Tengo academias y gestorías que copian a diario y pagan a fin de mes.",
     "Eso se lleva con cuenta de cliente: en lugar de ticket se emite albarán, y a fin de mes se agrupan todos en una factura. Puedes fijarles su tarifa propia y un límite de riesgo."),
    ("¿Sirve para llevar libro de texto con reservas?",
     "Sí. La reserva se registra a nombre de la familia y el libro queda comprometido; cuando llega del distribuidor, se avisa y se entrega. También puedes controlar qué queda pendiente de devolver al distribuidor, que es donde se escapa el margen si se pasa el plazo."),
    ("¿Aguanta el programa la punta de septiembre?",
     "La versión de PC trabaja en local, así que la velocidad depende de tu equipo y no de la conexión, que en campaña es justo cuando peor va. Si vas a montar un segundo puesto para septiembre, se conectan por la red local de la tienda."),
  ],
  rel=[("Rebajas y promociones","/rebajas-y-promociones-tpv.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
       ("TPV para jugueterías","/negocio_jugueteria.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp")]),

# =============================================================== BISUTERIA
"negocio_bisuteria.asp": dict(
  nombre="Bisutería y accesorios",
  crumb="Bisutería",
  icono="fa-ring",
  title="Software TPV para Bisutería y Accesorios | Caja 5",
  desc="TPV para bisutería: cientos de referencias de bajo importe, etiquetado propio, control por expositor, promociones por cantidad y reposición de lo que rota.",
  kw="tpv bisuteria, software tienda bisuteria, programa tpv accesorios, etiquetar bisuteria, tpv bisuteria sin cuotas, control expositor bisuteria",
  h1='Software TPV para Bisutería. <span>Mucha referencia, poco importe, rotación alta.</span>',
  sub='El reto de una bisutería no es vender: es saber qué tienes. Cuando el ticket medio son ocho euros y hay 3.000 referencias, el control se pierde en semanas si no está montado bien desde el principio.',
  bloques=[
    ("Nada de lo que compras viene etiquetado",
     ["La bisutería se compra por lotes al mayorista, muchas veces en bolsas de doce o veinticuatro piezas sin ninguna referencia. Sale de la caja sin código de barras, sin ficha y sin precio.",
      "Ese es el punto exacto donde la mayoría de tiendas pierde el control: se pone el género en el expositor sin darlo de alta, y a partir de ahí el inventario es una estimación. Generar tu propio código y etiquetar al recibir es lo que cambia el negocio."],
     ["<strong>Código interno generado por el programa</strong> para artículos que no traen EAN de fábrica.",
      "<strong>Etiqueta pequeña de 28x17 mm</strong> o etiqueta colgante, según la pieza.",
      "<strong>Alta por lote al recepcionar</strong>, aprovechando el albarán del mayorista para dar de alta las doce piezas de golpe.",
      "<strong>Precio por familia.</strong> Si todos los pendientes de una serie valen igual, se etiquetan y se cobran igual."]),
    ("El expositor es una ubicación, y saber cuál vende es dinero",
     ["Buena parte del stock de una bisutería vive en expositores giratorios, bandejas junto a caja y paneles de pared. No es un detalle decorativo: cada expositor es un microescaparate con su propio rendimiento.",
      "Si asocias los artículos a su ubicación, el informe de ventas te dice qué expositor rota y cuál lleva tres meses sin mover una pieza. Con eso decides qué reponer, qué reubicar y qué liquidar, en lugar de repetir el pedido por costumbre."]),
    ("Promociones por cantidad, que es como se vende de verdad",
     ["En bisutería la promoción no es un descuento del 20 %: es «tres por diez euros» o «la segunda unidad a mitad de precio». Son mecánicas que suben el ticket medio y que el dependiente no debería tener que calcular a mano.",
      "Configuradas como reglas por grupo de artículos, se aplican solas en caja. El dependiente pasa las tres piezas y el precio sale correcto sin acordarse de nada."],
     ["<strong>Tres por un precio cerrado</strong> sobre un grupo de artículos.",
      "<strong>Segunda unidad con descuento</strong>, aplicado automáticamente.",
      "<strong>Packs de temporada</strong> combinando piezas que se venden juntas.",
      "<strong>Precio de liquidación</strong> por familia para vaciar lo que no rota."]),
    ("Roturas, pérdidas y el descuadre que todo el mundo asume",
     ["En bisutería se rompe género, se pierde y, siendo honestos, desaparece. Con piezas pequeñas y expositores abiertos, la merma es mayor que en casi cualquier otro comercio.",
      "Asumirla sin medirla es el error. Registrando las roturas como merma y haciendo recuentos parciales frecuentes de los expositores más caros, sabes cuánto pierdes al año y en qué zonas de la tienda se concentra. Diez minutos de recuento semanal de una bandeja detecta un problema que un inventario anual solo confirma cuando ya es tarde."]),
  ],
  faqs=[
    ("Mi bisutería viene sin código de barras. ¿Cómo la doy de alta?",
     "El programa genera un código interno propio y lo imprimes en etiqueta pequeña o colgante. Lo práctico es hacerlo al recepcionar el albarán del mayorista: das de alta la referencia, indicas las doce piezas que han venido y lanzas la impresión de las doce etiquetas de una vez."),
    ("¿Merece la pena etiquetar piezas de dos euros?",
     "Depende de cuántas manejes. Por debajo de unas pocas cientos de referencias puedes trabajar con artículos genéricos por precio. A partir de ahí, sin etiqueta no hay inventario posible ni sabes qué reponer, y acabas comprando a ciegas. La mayoría de tiendas que dan el paso no vuelven atrás."),
    ("¿Puedo saber qué expositor me funciona mejor?",
     "Sí, asociando cada artículo a su ubicación. El informe de ventas por ubicación te dice qué expositores rotan y cuáles llevan meses parados, que es la información con la que se decide qué reponer y qué liquidar."),
    ("¿Cómo hago un tres por diez euros sin que el dependiente calcule?",
     "Se configura como promoción por cantidad sobre un grupo de artículos. En caja se pasan las tres piezas y el precio se ajusta solo. No hay que recordar la condición ni hacer cuentas."),
    ("¿Cómo controlo las roturas y las pérdidas?",
     "Registrándolas como merma, no como venta: el artículo sale del stock por rotura y el inventario sigue cuadrando. Al cabo del año tienes la cifra real de lo que pierdes por este concepto y en qué familias se concentra."),
    ("¿Vale el mismo programa si vendo también complementos y bolsos?",
     "Sí, y suele ser el mismo negocio. Si el peso está en complementos de mayor importe, mira también la página de TPV para complementos, que entra en el detalle de esa parte del catálogo."),
  ],
  rel=[("TPV para tiendas de complementos","/negocio_complementos.asp"),
       ("Etiquetas con código de barras","/etiquetas-codigo-de-barras-tpv.asp"),
       ("Rebajas y promociones","/rebajas-y-promociones-tpv.asp"),
       ("TPV para joyerías","/negocio_joyeria.asp"),
       ("Inventario con PDA o lector","/inventario-con-pda-lector-codigo-barras.asp"),
       ("Programa de fidelización","/programa-fidelizacion-puntos.asp")]),

# ================================================================= ESTANCO
"negocio_estanco.asp": dict(
  nombre="Estancos y expendedurías",
  crumb="Estancos",
  icono="fa-store",
  title="Software TPV para Estancos y Expendedurías | Caja 5",
  desc="TPV para estancos: precio de tabaco fijado por el Estado, control de labores por referencia, venta de recargas y efectos timbrados, y el resto del surtido con margen libre.",
  kw="tpv estanco, software estanco, programa tpv expendeduria, gestion estanco tabaco, tpv estanco sin cuotas, control stock labores tabaco",
  h1='Software TPV para Estancos. <span>Precio intervenido en el tabaco, margen libre en el resto.</span>',
  sub='Un estanco no fija el precio de lo que más vende. Eso cambia por completo cómo hay que mirar el margen, el stock y todo lo que se vende alrededor del tabaco.',
  bloques=[
    ("El tabaco tiene precio intervenido: tu margen es una comisión",
     ["En España el precio de venta al público de las labores de tabaco lo fija el fabricante y se publica oficialmente; el estanquero no puede alterarlo, ni al alza ni a la baja. Lo que percibe es un porcentaje establecido sobre ese precio.",
      "La consecuencia práctica para la gestión es que en tu producto principal no compites por precio ni puedes hacer promociones. Todo el trabajo de margen está en la rotación, en no inmovilizar capital en labores que no salen y en lo que vendes alrededor.",
      "Ten en cuenta además que la publicidad y promoción del tabaco está fuertemente restringida por normativa. Cualquier acción comercial en ese terreno conviene consultarla antes con tu asesor."],
     ["<strong>Precio fijo por referencia</strong>, con actualización cuando cambia la tarifa oficial.",
      "<strong>Rotación por labor.</strong> Saber qué cajetillas y qué marcas salen de verdad es lo único que mejora tu resultado.",
      "<strong>Control de capital inmovilizado</strong>, que en un estanco es alto y suele estar mal medido.",
      "<strong>Sin promociones sobre labores</strong>, por la normativa aplicable."]),
    ("Lo que de verdad da margen es todo lo demás",
     ["Alrededor del tabaco, un estanco vende artículos con margen libre: mecheros, papel de liar, filtros, artículos de fumador, y en muchos casos recargas de móvil, efectos timbrados, artículos de regalo, prensa o loterías.",
      "Ese surtido es donde se decide la rentabilidad real del local, y es justo el que suele estar peor controlado porque toda la atención va al tabaco. Llevarlo con familias, precios y rotación propia cambia el resultado del año."],
     ["<strong>Familias separadas</strong>: labores, artículos de fumador, recargas, timbrados y varios.",
      "<strong>Margen por familia</strong>, para ver de dónde sale de verdad el beneficio.",
      "<strong>Promociones libres</strong> en el surtido no intervenido.",
      "<strong>Reposición por rotación</strong>, no por costumbre."]),
    ("Efectos timbrados y recargas: venta sin stock convencional",
     ["Las recargas telefónicas, los efectos timbrados y productos similares no se comportan como un artículo normal: muchas veces no hay pieza física que contar, y el margen es una comisión estrecha sobre un importe alto.",
      "Conviene tratarlos como familia aparte para que no distorsionen tus estadísticas. Si mezclas 500 € de recargas con 500 € de venta de mostrador, el informe de facturación te dice algo que no es cierto sobre tu negocio."]),
    ("Cierre de caja en un negocio con mucho efectivo y precio fijo",
     ["El estanco sigue moviendo mucho efectivo, y con precio intervenido cualquier descuadre es directamente pérdida: no hay margen comercial donde absorberlo.",
      "Por eso el arqueo diario por medio de pago, con registro de las entradas y salidas de efectivo que no son venta, importa aquí más que en casi cualquier otro comercio. Un descuadre pequeño y constante en un negocio de comisión fija se come el resultado del mes sin que te des cuenta."]),
  ],
  faqs=[
    ("¿Puedo cambiar el precio del tabaco en el programa?",
     "El precio de venta al público de las labores de tabaco está intervenido: lo fija el fabricante y se publica oficialmente, y el estanquero no puede alterarlo. En el programa se cargan esos precios y se actualizan cuando cambia la tarifa. Para cualquier duda sobre tus obligaciones concretas, consulta con el organismo competente o con tu asesor."),
    ("¿Puedo hacer promociones con el tabaco?",
     "La promoción y publicidad del tabaco está sujeta a restricciones importantes en la normativa española. Las promociones tienen sentido en el resto del surtido, que sí tiene margen libre. Antes de plantear cualquier acción sobre labores, consúltalo con tu asesor."),
    ("¿Cómo separo el margen del tabaco del resto de la tienda?",
     "Con familias diferenciadas y el informe de márgenes por familia. Es la información más útil que puede darte el programa en un estanco, porque enseña qué parte del beneficio viene de la comisión fija del tabaco y qué parte del surtido con precio libre, que es donde puedes actuar."),
    ("¿Cómo llevo las recargas telefónicas y los efectos timbrados?",
     "Como familia aparte, para que no distorsionen las estadísticas. Son importes altos con comisión estrecha y sin stock físico convencional, así que mezclarlos con la venta de mostrador da una lectura falsa de la facturación."),
    ("¿El programa cumple con VeriFactu?",
     "Sí, Caja 5 emite facturas simplificadas con QR reglamentario y registro inalterable. El calendario vigente sitúa la obligación en enero de 2027 para sociedades y julio de 2027 para autónomos; confirma con tu asesor la fecha que te aplica."),
    ("¿Necesito conexión permanente a internet?",
     "No con la versión de PC: la base de datos está en tu ordenador y sigues cobrando aunque se caiga la línea. En un negocio con la afluencia de un estanco, no depender de la conexión para cobrar es una ventaja práctica evidente."),
  ],
  rel=[("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Impresora de tickets","/impresora-tickets-compatible-tpv.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp")]),

# ================================================================== VAPEO
"negocio_vapeo.asp": dict(
  nombre="Tiendas de vapeo y cigarrillo electrónico",
  crumb="Vapeo",
  icono="fa-smoking",
  title="Software TPV para Tiendas de Vapeo | Caja 5",
  desc="TPV para tiendas de vapeo: líquidos por nicotina y volumen, lotes y caducidad, control de resistencias y baterías, verificación de edad y trazabilidad del proveedor.",
  kw="tpv vapeo, software tienda vapeo, programa tpv cigarrillo electronico, tpv vapeo sin cuotas, control lotes liquidos vapeo, tpv tienda vaper",
  h1='Software TPV para Tiendas de Vapeo. <span>Líquidos por nicotina, lotes y caducidad.</span>',
  sub='Un mismo sabor de líquido existe en varios volúmenes y varias concentraciones de nicotina. Son artículos distintos con stock distinto, y llevarlos como uno solo es el error que arruina el inventario.',
  bloques=[
    ("El catálogo tiene tres variables, no una",
     ["Un líquido no es un artículo: es una combinación. El mismo sabor se vende en 10 ml y en 50 ml, y en varias concentraciones de nicotina, además de en versión sin nicotina. Cada combinación tiene su precio, su rotación y su stock.",
      "Si eso se lleva como una sola ficha, no sabes nunca de qué versión te has quedado sin género, que es justo la pregunta que hace el cliente. Con matriz de variantes, das de alta el sabor una vez y marcas qué combinaciones trabajas."],
     ["<strong>Sabor como ficha principal</strong>, con su marca y su familia.",
      "<strong>Volumen como variante</strong>: 10 ml, 30 ml, 50 ml o lo que trabajes.",
      "<strong>Concentración de nicotina como segunda variante</strong>, incluida la versión sin nicotina.",
      "<strong>Stock y código de barras propios</strong> por cada combinación real."]),
    ("Lote y caducidad no son opcionales en este producto",
     ["Los líquidos llevan lote y fecha de consumo preferente. Ante una incidencia o una retirada del fabricante, tienes que poder saber qué lote vendiste y cuándo, y eso con una libreta no se hace.",
      "Registrar el lote al recepcionar cuesta unos segundos por albarán y te ahorra un problema serio el día que haga falta. Además, el aviso de caducidad próxima te deja sacar en promoción lo que va a vencer en lugar de tirarlo."],
     ["<strong>Lote y caducidad al recepcionar</strong>, con el stock desglosado por lote.",
      "<strong>Aviso de próximos a caducar</strong> para promocionarlos a tiempo.",
      "<strong>Trazabilidad del proveedor</strong> por cada lote recibido.",
      "<strong>Localización de ventas de un lote</strong> si hay que contactar con clientes."]),
    ("Hardware, consumibles y reparaciones",
     ["Además del líquido, la tienda vende dispositivos, baterías, resistencias y pyrex. Los dispositivos son artículos de valor con número de serie y garantía; las resistencias son consumible de recompra constante; las baterías tienen consideraciones de seguridad y transporte.",
      "Cada grupo pide un tratamiento distinto. El dispositivo, control por serie y garantía asociada a la venta. La resistencia, control de stock fino porque es lo que hace volver al cliente cada pocas semanas."],
     ["<strong>Dispositivos con número de serie</strong> y garantía asociada a la venta.",
      "<strong>Resistencias por modelo y ohmios</strong>, que es como las pide el cliente.",
      "<strong>Recompra previsible</strong>: quien compró un mod concreto volverá a por sus resistencias.",
      "<strong>Servicio de reparación o limpieza</strong> como artículo sin stock."]),
    ("Verificación de edad y normativa",
     ["La venta de productos con nicotina a menores está prohibida y el sector está sujeto a normativa específica sobre composición, etiquetado, notificación de productos y restricciones de publicidad y promoción.",
      "El programa puede ayudarte con el aviso en pantalla al vender familias restringidas y con la trazabilidad de lotes, pero las obligaciones concretas de tu tienda dependen de la normativa estatal y autonómica que te aplique. No lo deduzcas de una web: confírmalo con tu asesor y con la autoridad competente de tu comunidad."]),
  ],
  faqs=[
    ("¿Cómo llevo un mismo sabor en varios volúmenes y nicotinas?",
     "Con la matriz de variantes. El sabor es la ficha, y el volumen y la concentración de nicotina son las variantes: cada combinación tiene su propio stock y su código de barras. Así sabes que te has quedado sin el de 50 ml con 3 mg pero te queda el de 10 ml."),
    ("¿Puedo controlar el lote y la caducidad de los líquidos?",
     "Sí. Al recepcionar registras lote y fecha, y el stock queda desglosado por lote. El programa avisa de lo próximo a caducar y, si hubiera una incidencia con un lote, puedes localizar en qué ventas salió."),
    ("¿Se puede controlar la garantía de los dispositivos?",
     "Sí, con control por número de serie. La venta queda asociada al aparato concreto, así que cuando el cliente vuelve compruebas la fecha de compra y el periodo de garantía en el momento, sin buscar tickets."),
    ("¿El programa impide vender a menores?",
     "Puede mostrar un aviso en pantalla al vender artículos de familias restringidas, como recordatorio para el dependiente. La verificación de la edad es responsabilidad de la tienda y las obligaciones concretas dependen de la normativa que te aplique: consúltalo con tu asesor."),
    ("¿Puedo saber cuándo va a volver un cliente a por resistencias?",
     "Si identificas al cliente en la venta, tienes su histórico y sabes qué dispositivo usa y con qué frecuencia repone. Es una de las recompras más previsibles que existen en comercio y da mucho juego para avisos y fidelización."),
    ("¿Cumple con VeriFactu?",
     "Sí, Caja 5 emite facturas simplificadas homologadas con QR reglamentario y registro inalterable de operaciones."),
  ],
  rel=[("Matriz de variantes","/matriz-tallas-y-colores.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Programa de fidelización","/programa-fidelizacion-puntos.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp")]),

# ============================================================= PARAFARMACIA
"negocio_parafarmacia.asp": dict(
  nombre="Parafarmacias y dietética",
  crumb="Parafarmacia",
  icono="fa-mortar-pestle",
  title="Software TPV para Parafarmacias y Dietética | Caja 5",
  desc="TPV para parafarmacia: lotes y caducidades, código nacional, control de complementos alimenticios, consejo al cliente y ficha con composición y alérgenos.",
  kw="tpv parafarmacia, software parafarmacia, programa tpv dietetica, tpv productos parafarmaceuticos, control lotes caducidad parafarmacia",
  h1='Software TPV para Parafarmacias. <span>Lotes, caducidades y consejo al cliente.</span>',
  sub='Una parafarmacia vende producto con fecha de caducidad y con composición que el cliente pregunta en el mostrador. El programa tiene que tener esa información a mano, no en la caja del producto.',
  bloques=[
    ("Caducidad y lote: la diferencia entre una incidencia y un problema",
     ["Prácticamente todo lo que vende una parafarmacia caduca: cosmética, complementos alimenticios, productos de higiene, dietética. Un producto vencido en la estantería es pérdida directa, y una retirada del fabricante sin saber qué lote vendiste es un problema mayor.",
      "Registrar lote y caducidad al recepcionar convierte las dos cosas en gestionable: sacas en promoción lo que está próximo a vencer y localizas un lote concreto si hace falta."],
     ["<strong>Lote y fecha de caducidad</strong> registrados en la entrada de mercancía.",
      "<strong>Aviso de próximos a vencer</strong> con margen para promocionarlos.",
      "<strong>Trazabilidad por lote</strong> hacia el proveedor y hacia la venta.",
      "<strong>Salida por caducidad como merma</strong>, no como venta, para que el inventario cuadre."]),
    ("La ficha del producto se consulta en el mostrador constantemente",
     ["El cliente de parafarmacia pregunta. Si lleva gluten, si tiene lactosa, si es apto para embarazadas, qué principio activo lleva, si se puede tomar con otra cosa. El dependiente responde mejor con la información en pantalla que buscando el bote en la estantería.",
      "Tener la composición, los alérgenos y las indicaciones en la ficha del artículo convierte el TPV en una herramienta de venta y no solo en una caja registradora."],
     ["<strong>Composición y alérgenos</strong> en campos consultables desde la venta.",
      "<strong>Código nacional o referencia del laboratorio</strong> para localizar rápido.",
      "<strong>Familias por finalidad</strong>, que es como pregunta el cliente, no por proveedor.",
      "<strong>Productos relacionados</strong> para el consejo de venta cruzada."]),
    ("Qué puede y qué no puede vender una parafarmacia",
     ["Una parafarmacia no es una farmacia. No puede dispensar medicamentos sujetos a prescripción médica, y el ámbito de lo que puede vender está delimitado por la normativa sanitaria, con diferencias entre comunidades autónomas.",
      "El programa no decide eso, pero sí conviene que tengas el catálogo organizado por familias que reflejen esa realidad, y que cualquier duda sobre qué puedes comercializar la resuelvas con la autoridad sanitaria de tu comunidad o con tu asesor antes de dar de alta el producto, no después."]),
    ("Recompra previsible y ficha de cliente",
     ["El complemento alimenticio se toma por ciclos: un bote dura treinta o sesenta días. Eso hace que la recompra sea de las más previsibles del comercio minorista, y muy pocas parafarmacias la trabajan.",
      "Con la ficha de cliente y su histórico sabes quién compró qué y cuándo, y puedes avisarle cuando se le está acabando. Necesitas su consentimiento para comunicaciones comerciales, y como algunos de estos datos pueden revelar información sobre su salud, conviene tratarlos con cuidado y consultar con tu asesor cómo hacerlo correctamente."]),
  ],
  faqs=[
    ("¿Puedo controlar lotes y caducidades de todo el catálogo?",
     "Sí. Al recepcionar registras el lote y su fecha de caducidad, y el stock queda desglosado. El programa te avisa de lo que está próximo a vencer para que puedas promocionarlo, y si hay una retirada del fabricante puedes localizar en qué ventas salió ese lote."),
    ("¿Puedo guardar la composición y los alérgenos en la ficha?",
     "Sí, en campos descriptivos consultables desde la propia venta. En parafarmacia se consultan constantemente en el mostrador, y tenerlos en pantalla es más rápido y más fiable que leer el envase."),
    ("¿Sirve para una farmacia?",
     "No es el producto adecuado para una oficina de farmacia: la dispensación de medicamentos con receta, la conexión con el sistema de receta electrónica y las obligaciones asociadas exigen un software específico de farmacia. Caja 5 está pensado para parafarmacia, dietética y herbodietética."),
    ("¿Cómo saco del stock un producto caducado?",
     "Como merma, no como venta. El artículo sale del inventario por caducidad y queda registrado, de forma que el stock cuadra y al final del año sabes cuánto dinero has perdido por producto vencido, que suele ser una cifra reveladora."),
    ("¿Puedo avisar a un cliente de que se le acaba su bote?",
     "Con la ficha de cliente y su histórico de compras puedes saber quién compró qué y cuándo, y preparar avisos. Ten en cuenta que necesitas su consentimiento para comunicaciones comerciales y que esta información puede ser sensible: consulta con tu asesor cómo tratarla correctamente."),
    ("¿Cumple con VeriFactu?",
     "Sí, Caja 5 emite facturas simplificadas con QR reglamentario y registro inalterable, conforme a la Ley Antifraude 11/2021."),
  ],
  rel=[("TPV para herbolarios y herbodietética","/negocio_herbodietetica.asp"),
       ("TPV para cosmética y droguería","/negocio_cosmetica.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Programa de fidelización","/programa-fidelizacion-puntos.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),
}
