# -*- coding: utf-8 -*-
"""Base de hechos por sector, lote 3."""

SECTORES_3 = {

# =============================================================== CARNICERIA
"negocio_carniceria.asp": dict(
  nombre="Carnicerías y charcuterías",
  crumb="Carnicerías",
  icono="fa-drumstick-bite",
  title="Software TPV para Carnicerías y Charcuterías | Caja 5",
  desc="TPV para carnicerías: venta a peso, despiece de la canal, trazabilidad de la carne, lotes y caducidad, encargos de fin de semana y reparto a hostelería.",
  kw="tpv carniceria, software charcuteria, programa tpv carniceria, tpv con balanza carniceria, trazabilidad carne lote, despiece canal control",
  h1='Software TPV para Carnicerías. <span>Despiece, peso y trazabilidad de la carne.</span>',
  sub='Compras una canal entera y vendes veinte productos distintos con precios distintos. Hasta que ese despiece no está reflejado en el programa, no sabes el margen real de nada.',
  bloques=[
    ("Compras una canal y vendes veinte cosas",
     ["Este es el problema que ningún TPV genérico resuelve. Entra media ternera a un precio por kilo, y de ahí salen solomillo, entrecot, filetes, carne picada y huesos, cada uno con su precio de venta muy distinto y con un porcentaje de merma en el corte.",
      "Si registras la compra como «media ternera» y las ventas como productos sueltos, el stock no cuadra jamás y el margen es una estimación. La forma correcta es reflejar el despiece: una entrada que se convierte en varias referencias con sus rendimientos."],
     ["<strong>Despiece registrado</strong>: una entrada de canal genera las piezas resultantes con su peso.",
      "<strong>Rendimiento por corte</strong>, incluida la merma de hueso y grasa.",
      "<strong>Coste repartido</strong> entre las piezas según su valor, para que el margen sea real.",
      "<strong>Stock por pieza</strong> y no por canal, que es como se vende."]),
    ("Peso, tara y el cliente que pide «medio kilo justo»",
     ["Toda la venta pasa por la balanza. Precio por kilo, peso real, y el cliente que quiere un peso exacto o «lo que salga» de una pieza concreta.",
      "El instrumento de pesaje utilizado en transacciones comerciales está sujeto a control metrológico y a verificaciones periódicas. Esa obligación es tuya como comerciante, independientemente del programa; consúltala con el organismo competente de tu comunidad."],
     ["<strong>Venta por peso</strong> con balanza conectada o etiqueta de balanza con código de peso.",
      "<strong>Tara descontada</strong> para envases y fiambreras del cliente.",
      "<strong>Precio por tramos</strong> para quien se lleva pieza entera o cantidad.",
      "<strong>Productos por unidad</strong> conviviendo con los de peso, para embutido envasado y preparados."]),
    ("Trazabilidad: aquí no es una buena idea, es obligación",
     ["La carne está sujeta a exigencias de trazabilidad e información al consumidor especialmente estrictas, con datos como el origen y los identificadores de lote que deben poder seguirse desde el proveedor hasta la venta.",
      "En la práctica eso significa registrar de dónde vino cada partida y poder reconstruirlo. Un TPV que lleve lote y proveedor en la entrada te da esa información sin trabajo extra en el momento de la inspección o de una alerta. Los requisitos exactos que te aplican conviene confirmarlos con tu asesor o con sanidad de tu comunidad, porque varían según el producto."],
     ["<strong>Lote y proveedor</strong> registrados en cada entrada de mercancía.",
      "<strong>Trazabilidad hacia la venta</strong> de una partida concreta.",
      "<strong>Caducidad y consumo preferente</strong> con aviso previo.",
      "<strong>Merma registrada</strong> para lo retirado, separada de la venta."]),
    ("Encargos de fin de semana y reparto a hostelería",
     ["El viernes y el sábado concentran la facturación, y buena parte llega encargada: el cordero de la comunión, las brochetas para la barbacoa, el pedido de bandejas. Cada encargo tiene fecha, hora y detalle de corte.",
      "Y muchas carnicerías reparten además a bares y restaurantes, que compran con albarán y pagan a fin de mes, con su tarifa propia distinta de la de mostrador. Son dos operativas que conviven en el mismo local y que el programa debe separar limpiamente."]),
  ],
  faqs=[
    ("¿Puedo reflejar el despiece de una canal en el programa?",
     "Sí: registras la entrada de la canal y el despiece que genera las piezas resultantes con su peso, repartiendo el coste entre ellas. Es lo que permite que el stock cuadre y que sepas el margen real de cada corte, que es imposible de calcular si vendes veinte productos de una compra registrada como una."),
    ("¿Cómo llevo la trazabilidad de la carne?",
     "Registrando lote y proveedor en cada entrada, de forma que el stock queda desglosado y puedes reconstruir de dónde vino lo que has vendido. Los requisitos concretos de trazabilidad e información al consumidor son estrictos en carne y varían por producto: confírmalos con tu asesor o con sanidad de tu comunidad."),
    ("¿Se puede conectar la balanza?",
     "Sí, o bien conectada directamente al programa, o bien mediante etiqueta de balanza con código de barras que incluye el peso y que el TPV lee. La segunda es la más habitual en mostrador. Recuerda que la balanza está sujeta a control metrológico."),
    ("¿Puedo llevar encargos para el fin de semana?",
     "Sí, con fecha, hora de recogida y detalle del corte solicitado, y con señal si la cobras. El obrador o el mostrador sacan el listado de encargos del día y no dependen de la libreta."),
    ("Reparto a bares y restaurantes. ¿Puedo facturarles a fin de mes?",
     "Sí, con cuenta de cliente: cada reparto genera albarán y a fin de mes se agrupan en una factura por cliente, con la tarifa propia que le tengas asignada, que en hostelería casi siempre es distinta de la de mostrador."),
    ("¿Puedo registrar lo que tiro?",
     "Sí, como merma: sale del stock sin computar como venta. En productos frescos con caducidad corta es el único modo de que el inventario cuadre y de saber cuánto te cuesta al mes el género retirado."),
  ],
  rel=[("TPV para tiendas de alimentación","/negocio_alimentacion.asp"),
       ("TPV para pescaderías","/negocio_pescaderia.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),

# =============================================================== PESCADERIA
"negocio_pescaderia.asp": dict(
  nombre="Pescaderías y marisquerías",
  crumb="Pescaderías",
  icono="fa-fish",
  title="Software TPV para Pescaderías y Marisquerías | Caja 5",
  desc="TPV para pescaderías: precio de lonja variable a diario, venta a peso, información obligatoria de zona de captura y arte de pesca, merma y encargos.",
  kw="tpv pescaderia, software pescaderia marisqueria, programa tpv pescado, precio lonja diario tpv, zona captura arte pesca etiqueta",
  h1='Software TPV para Pescaderías. <span>El precio cambia con la lonja, cada día.</span>',
  sub='Compras en lonja a un precio que no controlas y que cambia de un día para otro. Si cambiar precios te cuesta más de un minuto, vas a vender por debajo de coste sin enterarte.',
  bloques=[
    ("El precio de compra cambia cada mañana",
     ["Ninguna otra tienda tiene esta volatilidad. La merluza puede costar hoy la mitad que la semana pasada, o el doble. Y el precio de venta tiene que seguir a la compra el mismo día, no la semana siguiente.",
      "Eso exige que actualizar precios sea inmediato: una lista con tus referencias del día donde cambias todo de una vez y reimprimes los carteles. Cualquier fricción ahí acaba en vender con margen negativo por pereza."],
     ["<strong>Actualización de precios en bloque</strong>, con todas las referencias del día en una pantalla.",
      "<strong>Carteles reimpresos</strong> desde la misma pantalla, con precio por kilo.",
      "<strong>Margen calculado sobre la compra de hoy</strong>, no sobre un coste antiguo.",
      "<strong>Histórico de precios</strong> para comparar campañas y temporadas."]),
    ("Información obligatoria: zona de captura, arte y forma de producción",
     ["Los productos de la pesca y la acuicultura tienen requisitos de información al consumidor propios: denominación comercial y científica, método de producción (capturado, capturado en agua dulce o de acuicultura), zona de captura o país de cría, y arte de pesca, entre otros.",
      "Todo eso tiene que aparecer donde el consumidor pueda verlo. Tenerlo en la ficha del artículo hace que el cartel salga correcto y que cualquiera del mostrador pueda responder. Los datos exactos exigibles según el producto conviene confirmarlos con tu asesor o con la autoridad competente, porque el detalle es considerable."],
     ["<strong>Denominación comercial y científica</strong> en la ficha del artículo.",
      "<strong>Zona FAO o país de cría</strong>, según corresponda.",
      "<strong>Arte de pesca y método de producción</strong>.",
      "<strong>Cartel impreso con esos datos</strong>, para no rellenarlos a mano cada día."]),
    ("Peso, hielo, limpieza y lo que el cliente se lleva de verdad",
     ["El cliente compra un kilo de pescado, pero pide que se lo limpien, y lo que se lleva pesa menos. La venta se cobra sobre el peso antes de limpiar, y eso conviene tenerlo claro y bien reflejado para evitar discusiones.",
      "Además está la tara del hielo y del envase. Son detalles pequeños que, con el precio por kilo del marisco, dejan de ser pequeños muy rápido."],
     ["<strong>Precio por kilo</strong> con pesaje en el momento.",
      "<strong>Tara de envase y hielo</strong> descontada donde corresponda.",
      "<strong>Servicios de preparación</strong> reflejados si se cobran aparte.",
      "<strong>Venta por pieza</strong> para lo que se vende a unidad."]),
    ("Merma alta y encargos concentrados",
     ["El pescado fresco tiene una de las mermas más altas del comercio: lo que no se vende hoy vale mucho menos mañana y a veces nada. Registrarla a diario es lo único que da una imagen honesta del margen.",
      "Y como en la carnicería, hay concentración brutal de encargos en vísperas de fiestas: mariscadas de Navidad, pedidos de Nochebuena. Ese encargo lleva fecha, hora y a menudo señal, y se prepara con antelación."]),
  ],
  faqs=[
    ("¿Puedo cambiar los precios cada mañana según la lonja?",
     "Sí, con actualización en bloque: ves todas tus referencias del día en una pantalla y las modificas de una vez, sin entrar en cada ficha. Desde ahí reimprimes los carteles con el precio por kilo actualizado."),
    ("¿Puedo guardar la zona de captura y el arte de pesca?",
     "Sí, en la ficha del artículo, junto a la denominación comercial y científica y el método de producción, y usarlo para imprimir el cartel. Los datos exigibles según el producto tienen bastante detalle: confírmalos con tu asesor o con la autoridad competente."),
    ("¿Cómo controlo la merma diaria?",
     "Con un registro rápido de merma al cierre, por artículo o familia. Sale del stock sin computar como venta, de forma que el inventario cuadra y al final del mes tienes el coste real de lo retirado, que en pescado fresco es una cifra alta y muy reveladora."),
    ("¿Se descuenta la tara del hielo o del envase?",
     "Sí, indicando la tara en el pesaje o teniéndola predefinida para los envases habituales. Con el precio por kilo del marisco, un descuido de tara repetido a diario se nota en la caja."),
    ("¿Puedo llevar los encargos de Navidad?",
     "Sí, con fecha, hora de recogida, detalle del pedido y señal si la cobras. En vísperas de fiestas se concentra tanto encargo que llevarlo en papel es donde se producen los fallos que cuestan un cliente para siempre."),
    ("¿Necesito internet para cobrar?",
     "No con la versión de PC: la base de datos está en tu ordenador y sigues cobrando aunque falle la línea. En un mostrador con cola en sábado por la mañana, no depender de la conexión es una ventaja práctica evidente."),
  ],
  rel=[("TPV para carnicerías","/negocio_carniceria.asp"),
       ("TPV para tiendas de alimentación","/negocio_alimentacion.asp"),
       ("TPV para fruterías","/negocio_fruteria.asp"),
       ("Etiquetas y carteles de precio","/etiquetas-codigo-de-barras-tpv.asp"),
       ("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),

# =========================================================== ELECTRODOMESTICOS
"negocio_electrodomesticos.asp": dict(
  nombre="Tiendas de electrodomésticos",
  crumb="Electrodomésticos",
  icono="fa-blender",
  title="Software TPV para Tiendas de Electrodomésticos | Caja 5",
  desc="TPV para electrodomésticos: número de serie y garantía, entrega e instalación a domicilio, retirada del aparato usado, financiación y venta a crédito.",
  kw="tpv electrodomesticos, software tienda electrodomesticos, programa tpv electrodomesticos, control garantia numero serie, entrega instalacion domicilio",
  h1='Software TPV para Electrodomésticos. <span>Series, entregas, instalación y RAEE.</span>',
  sub='La venta se cierra en la tienda pero termina en casa del cliente, con un instalador, una fecha y un aparato viejo que hay que retirar. Eso hay que llevarlo, no recordarlo.',
  bloques=[
    ("Cada aparato es una unidad con nombre y apellidos",
     ["Una lavadora no es «una unidad»: es un número de serie con su fecha de venta, su garantía del fabricante y su historial de incidencias. Cuando el cliente llama a los dos años, lo primero que necesitas saber es qué aparato exacto le vendiste.",
      "Con control por serie, esa consulta se resuelve al instante y puedes tramitar con el fabricante lo que corresponda en lugar de asumir el coste por no poder demostrar la fecha."],
     ["<strong>Número de serie registrado en la venta</strong> de cada aparato.",
      "<strong>Garantía calculada desde la entrega</strong>, consultable por serie o por cliente.",
      "<strong>Historial de incidencias</strong> asociado a esa unidad concreta.",
      "<strong>Trazabilidad al proveedor</strong>, para tramitar con el fabricante."]),
    ("Entrega, instalación y retirada del usado",
     ["La venta de un frigorífico incluye normalmente transporte, a menudo instalación y muchas veces retirada del aparato antiguo. Cada una de esas cosas ocupa a una persona, una furgoneta y una franja horaria concreta.",
      "Sin un listado de entregas por día, eso se lleva de memoria y falla. El cliente que se toma la mañana libre y no recibe el electrodoméstico no vuelve a comprarte."],
     ["<strong>Fecha y franja de entrega</strong> comprometidas en la venta.",
      "<strong>Listado de entregas del día</strong> para el repartidor, con dirección y teléfono.",
      "<strong>Servicios de instalación y retirada</strong> como líneas propias con su precio.",
      "<strong>Observaciones de acceso</strong>: piso, ascensor, medidas de puerta."]),
    ("Ticket alto, pago aplazado y financiación",
     ["El ticket medio de una tienda de electrodomésticos es de los más altos del comercio minorista, y una parte importante se paga a plazos o con financiación de una entidad.",
      "El programa debe reflejar señal, saldo pendiente y forma de pago, y dejar claro en el arqueo qué se cobró de verdad en caja y qué se financió. Mezclar ambas cosas es la vía rápida a un cierre de caja que no cuadra nunca."],
     ["<strong>Señal y saldo pendiente</strong> hasta la entrega.",
      "<strong>Financiación registrada como medio de pago propio</strong>, separada del efectivo y la tarjeta.",
      "<strong>Arqueo por medio de pago</strong>, para que el cierre sea real.",
      "<strong>Factura al cliente</strong> emitida desde la misma venta cuando la pide."]),
    ("Etiqueta energética y obligaciones de RAEE",
     ["Los electrodomésticos llevan etiquetado energético obligatorio con su clase, y la información al consumidor debe mostrarse según la normativa aplicable, incluida la venta a distancia.",
      "Además, la venta de aparatos eléctricos y electrónicos conlleva obligaciones sobre residuos, entre ellas la recogida del aparato usado en los supuestos previstos. Guardar la clase energética en la ficha te facilita el cartel; las obligaciones concretas de RAEE y su reflejo en factura conviene confirmarlas con tu asesor y con el sistema de gestión al que estés adherido."]),
  ],
  faqs=[
    ("¿Puedo registrar el número de serie de cada aparato vendido?",
     "Sí, con control por serie: la venta queda asociada a esa unidad concreta. Cuando el cliente vuelve, buscas por serie o por su nombre y ves la fecha de venta y el estado de la garantía sin buscar tickets."),
    ("¿Puedo llevar las entregas a domicilio pendientes?",
     "Sí. La venta registra fecha y franja de entrega, dirección, teléfono y observaciones de acceso, y el repartidor saca el listado del día. Es lo que evita el fallo más caro de este sector, que es no aparecer el día prometido."),
    ("¿Cómo cobro la instalación y la retirada del aparato viejo?",
     "Como artículos de servicio sin stock, con su precio, añadidos al ticket como líneas propias. Así queda claro para el cliente qué está pagando y tú sabes cuánto facturas por servicio al cabo del año."),
    ("¿Se puede registrar una venta financiada?",
     "Sí, con la financiación como medio de pago separado del efectivo y la tarjeta. Es importante para que el arqueo diario cuadre: el dinero de una venta financiada no entra en tu caja ese día."),
    ("¿Puedo guardar la clase energética del producto?",
     "Sí, en la ficha del artículo, y usarla para el cartel. Las obligaciones concretas sobre etiquetado energético e información al consumidor están reguladas: confírmalas con tu asesor, especialmente si vendes también a distancia."),
    ("¿El programa gestiona lo relativo a RAEE?",
     "Puede reflejar en la venta los conceptos que correspondan, pero las obligaciones sobre residuos de aparatos eléctricos dependen de la normativa vigente y del sistema de gestión al que estés adherido. Consúltalo con tu asesor."),
  ],
  rel=[("TPV para tiendas de informática","/negocio_informatica.asp"),
       ("TPV para tiendas de muebles","/negocio_muebles.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),

# ================================================================ ORTOPEDIA
"negocio_ortopedia.asp": dict(
  nombre="Ortopedias y ayudas técnicas",
  crumb="Ortopedias",
  icono="fa-wheelchair",
  title="Software TPV para Ortopedias y Ayudas Técnicas | Caja 5",
  desc="TPV para ortopedias: productos sanitarios con lote y caducidad, adaptaciones a medida, alquiler de material, encargos y ficha de paciente.",
  kw="tpv ortopedia, software ortopedia, programa gestion ortopedia, alquiler material ortopedico, productos sanitarios lote, ficha paciente ortopedia",
  h1='Software TPV para Ortopedias. <span>Productos sanitarios, adaptaciones y alquiler.</span>',
  sub='Vendes producto sanitario con lote, adaptas material a medida de cada persona y alquilas equipo que tiene que volver. Tres operativas distintas en un mostrador.',
  bloques=[
    ("Producto sanitario: lote, caducidad y trazabilidad",
     ["Buena parte del catálogo de una ortopedia son productos sanitarios sujetos a requisitos propios de identificación y trazabilidad, con lote y, en muchos casos, fecha de caducidad.",
      "Ante una nota de seguridad del fabricante o una retirada, tienes que poder saber qué lote entró, de qué proveedor y a quién salió. Registrar lote y proveedor al recepcionar es lo que hace eso posible sin trabajo adicional. Los requisitos concretos aplicables a los productos que comercializas conviene confirmarlos con tu asesor o con la autoridad sanitaria."],
     ["<strong>Lote y proveedor en la entrada</strong> de cada partida.",
      "<strong>Caducidad con aviso previo</strong> para retirar a tiempo.",
      "<strong>Trazabilidad hasta la venta</strong>, incluido a qué cliente salió.",
      "<strong>Retirada registrada como merma</strong>, separada de la venta."]),
    ("La adaptación a medida no es una venta de mostrador",
     ["Una plantilla a medida, una faja adaptada o una silla configurada implican toma de medidas, encargo al fabricante, plazo y una prueba con la persona antes de entregar.",
      "Ese circuito necesita quedar registrado con las medidas tomadas, el estado del encargo y la cita de prueba. Y casi siempre con señal cobrada, porque un producto hecho a medida que nadie recoge no se puede vender a otro."],
     ["<strong>Medidas y especificaciones</strong> guardadas en el encargo.",
      "<strong>Estados hasta la entrega</strong>: medido, pedido, recibido, probado, entregado.",
      "<strong>Cita de prueba</strong> asociada al encargo.",
      "<strong>Señal cobrada</strong> y saldo liquidado en la entrega."]),
    ("Alquiler de material: sale del local y tiene que volver",
     ["Camas articuladas, sillas de ruedas, muletas, grúas y andadores se alquilan por semanas o meses. Es una línea de negocio importante y opera distinto de la venta: hay fianza, fechas, revisión del estado y limpieza entre usos.",
      "Sin control, el material se pierde, se devuelve tarde o vuelve dañado sin que nadie sepa cómo salió."],
     ["<strong>Salida y devolución con fechas</strong>, y aviso de lo vencido.",
      "<strong>Fianza registrada</strong> y devuelta al cierre del alquiler.",
      "<strong>Estado a la salida y a la vuelta</strong>, anotado en el mismo documento.",
      "<strong>Disponibilidad por fechas</strong>, para no comprometer dos veces la misma cama."]),
    ("Datos de las personas: aquí hay que ser especialmente cuidadoso",
     ["La ficha de un cliente de ortopedia suele contener información sobre su situación de salud: la patología, las medidas, el material prescrito. Eso son datos de categoría especial con requisitos reforzados.",
      "Conviene guardarlos en tu propio equipo, limitar quién accede, informar de la finalidad y recoger el consentimiento donde proceda. Que Caja 5 para PC mantenga la base de datos en local, y no en un servidor de terceros, simplifica esa conversación, pero las medidas concretas que te corresponden debes acordarlas con tu asesor."]),
  ],
  faqs=[
    ("¿Puedo llevar lote y caducidad de los productos sanitarios?",
     "Sí. Al recepcionar registras lote, proveedor y caducidad, con el stock desglosado por lote y aviso de lo próximo a vencer. Si hay una nota de seguridad o una retirada, puedes reconstruir qué entró y a quién salió. Los requisitos exactos que te aplican conviene confirmarlos con la autoridad sanitaria."),
    ("¿Puedo registrar las medidas para una adaptación a medida?",
     "Sí, en el encargo, junto con las especificaciones y el estado hasta la entrega. Puedes asociar la cita de prueba y cobrar señal, que en producto hecho a medida es lo razonable porque no se puede revender."),
    ("¿Se puede gestionar el alquiler de camas y sillas?",
     "Sí, registrando salida y devolución con fechas, fianza y estado del material. El programa te muestra qué debería haber vuelto ya y en qué condiciones salió, que es lo que necesitas si aparece un desperfecto."),
    ("¿Puedo saber si un material alquilado está libre en unas fechas?",
     "Sí, consultando la disponibilidad por fechas de ese artículo, para no comprometer la misma cama a dos personas en el mismo periodo."),
    ("¿Dónde se guardan los datos de mis clientes?",
     "Con Caja 5 para PC, en tu propio ordenador. Como en ortopedia esa información suele revelar datos de salud, con requisitos reforzados, conviene limitar el acceso e informar de la finalidad del tratamiento. Consulta con tu asesor las medidas que te correspondan."),
    ("¿Sirve si además vendo parafarmacia?",
     "Sí, conviven en el mismo catálogo con familias distintas. Si el peso de tu negocio está en complementos y cosmética, mira también la página de TPV para parafarmacias."),
  ],
  rel=[("TPV para parafarmacias","/negocio_parafarmacia.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("TPV con gestión de clientes","/negocio_gestion_clientes.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("Vales y tarjetas regalo","/vales-y-tarjetas-regalo-tpv.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),

# =============================================================== CERRAJERIA
"negocio_cerrajeria.asp": dict(
  nombre="Cerrajerías y duplicado de llaves",
  crumb="Cerrajerías",
  icono="fa-key",
  title="Software TPV para Cerrajerías y Duplicado de Llaves | Caja 5",
  desc="TPV para cerrajerías: copia de llaves y mandos, avisos y salidas a domicilio, presupuestos de instalación, urgencias fuera de horario y facturación a comunidades.",
  kw="tpv cerrajeria, software cerrajeria, programa gestion cerrajero, copia llaves mandos tpv, facturacion comunidades vecinos, presupuesto instalacion cerradura",
  h1='Software TPV para Cerrajerías. <span>Mostrador, avisos a domicilio y comunidades.</span>',
  sub='La mitad de lo que factura una cerrajería no pasa por el mostrador: son salidas, urgencias e instalaciones que hay que presupuestar, ejecutar y cobrar.',
  bloques=[
    ("El mostrador: copias, mandos y venta rápida",
     ["La copia de llave es el clásico: servicio de dos minutos, importe pequeño, mucho volumen. El mando de garaje y la copia de llave de coche con transpondedor son más caros y más técnicos, con su propio material.",
      "Todo eso conviene darlo de alta como servicios con precio, no cobrarlo a ojo. Es la única forma de saber al final del año cuánto pesa el mostrador frente a las salidas, que casi siempre sorprende."],
     ["<strong>Servicios con precio</strong>: copia estándar, llave de seguridad, mando, transpondedor.",
      "<strong>Material asociado</strong> descontado del stock: llave virgen, mando, batería.",
      "<strong>Precio por tipo de llave</strong>, porque una de seguridad no vale lo que una normal.",
      "<strong>Cobro rápido</strong>, que con importes de cinco euros importa."]),
    ("La salida a domicilio es un trabajo, no un ticket",
     ["Una apertura de puerta, un cambio de bombín o una instalación se presupuesta, se ejecuta y se factura, a veces días después. Entre medias hay desplazamiento, mano de obra y material.",
      "Ese trabajo necesita su documento: qué se hizo, qué material se usó, cuántas horas y a qué precio. Sin eso, el cobro es una negociación en la puerta y el margen es un misterio."],
     ["<strong>Presupuesto previo</strong> convertible en trabajo sin reescribirlo.",
      "<strong>Parte de trabajo</strong> con desplazamiento, mano de obra y material.",
      "<strong>Material imputado</strong> que sale del stock del taller o de la furgoneta.",
      "<strong>Factura desde el parte</strong>, sin volver a teclear nada."]),
    ("Urgencias fuera de horario y su tarifa",
     ["Las aperturas de urgencia de madrugada o en festivo tienen una tarifa distinta, y conviene que esa diferencia esté en el programa y no en la cabeza de quien atiende el teléfono.",
      "Además, en este servicio es especialmente importante informar del precio antes de actuar y dejar constancia de lo presupuestado, porque es un sector donde las reclamaciones por precio son frecuentes. Ten claro qué información debes facilitar al consumidor antes de intervenir; consúltalo con tu asesor."],
     ["<strong>Tarifa de urgencia</strong> configurada aparte de la ordinaria.",
      "<strong>Presupuesto aceptado</strong> registrado antes de intervenir.",
      "<strong>Desplazamiento facturado</strong> como concepto propio.",
      "<strong>Histórico por dirección</strong>, útil cuando se repite el aviso en el mismo portal."]),
    ("Comunidades de vecinos y clientes con contrato",
     ["Buena parte del negocio estable de una cerrajería son comunidades y administradores de fincas: mantenimiento de portales, copias de llave del portal, reposiciones. Compran con factura y pagan a treinta o sesenta días.",
      "Eso pide cuenta de cliente, albaranes agrupados en factura mensual y tarifa propia. Y control de riesgo, porque el administrador que acumula seis meses de albaranes sin pagar es un problema que se ve venir en el informe de saldos."]),
  ],
  faqs=[
    ("¿Puedo llevar los servicios de copia de llave como artículos?",
     "Sí, como servicios con precio, distinguiendo tipos: copia estándar, llave de seguridad, mando de garaje o llave con transpondedor. El material que consumen (llave virgen, mando, batería) se descuenta del stock, así que sabes el coste real de cada copia."),
    ("¿Puedo hacer presupuestos de instalación y convertirlos en factura?",
     "Sí. El presupuesto se guarda con su validez y, cuando el cliente acepta, se convierte en trabajo y después en factura sin volver a teclear las líneas. También te deja ver cuántos presupuestos acaban en trabajo."),
    ("¿Cómo registro una salida a domicilio con material y mano de obra?",
     "Con un parte de trabajo que recoge desplazamiento, horas y material utilizado. El material sale del stock y la factura se emite desde el propio parte, con el desglose que el cliente necesita."),
    ("¿Puedo tener una tarifa distinta para urgencias?",
     "Sí, configurando la tarifa de urgencia aparte de la ordinaria, para que no dependa de que quien coge el teléfono se acuerde. Conviene además dejar registrado el presupuesto aceptado antes de intervenir; consulta con tu asesor qué información debes facilitar al consumidor de antemano."),
    ("Trabajo para comunidades que pagan a 60 días. ¿Se puede llevar?",
     "Sí, con cuenta de cliente: los trabajos generan albarán y a fin de mes se agrupan en factura, con la tarifa propia de esa comunidad o administrador. El informe de saldos pendientes te avisa cuando alguien acumula demasiado."),
    ("¿Debo registrar quién encarga copias de llaves restringidas?",
     "En llaves de seguridad con perfil restringido lo habitual es exigir tarjeta de propiedad y dejar constancia del encargo. Las obligaciones concretas dependen del sistema de la marca y de la normativa aplicable: confírmalo con tu asesor y con el fabricante."),
  ],
  rel=[("TPV para ferreterías","/negocio_ferreteria.asp"),
       ("TPV con órdenes de reparación","/negocio_reparaciones.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),

# ================================================================== QUIOSCO
"negocio_quiosco.asp": dict(
  nombre="Quioscos de prensa",
  crumb="Quioscos",
  icono="fa-newspaper",
  title="Software TPV para Quioscos de Prensa | Caja 5",
  desc="TPV para quioscos: devolución diaria de prensa, coleccionables por fascículos, reservas de clientes, márgenes estrechos y venta rápida de bajo importe.",
  kw="tpv quiosco prensa, software quiosco, programa tpv prensa revistas, control devolucion prensa, coleccionables fasciculos reservas",
  h1='Software TPV para Quioscos. <span>Lo que no se vende hoy se devuelve mañana.</span>',
  sub='Un quiosco recibe género cada madrugada y devuelve lo que no vendió. Si no controlas esa devolución al día, el margen, que ya es estrecho, desaparece.',
  bloques=[
    ("La devolución diaria es el corazón del negocio",
     ["La prensa funciona a consignación: recibes ejemplares cada día y devuelves los no vendidos. Lo que no devuelves a tiempo lo pagas tú, y con el margen de un periódico eso duele enseguida.",
      "Llevar entradas y devoluciones al día, título a título, es lo que separa un quiosco rentable de uno que trabaja mucho y gana poco. El dato que necesitas es sencillo pero hay que tenerlo: cuántos recibí, cuántos vendí, cuántos devuelvo."],
     ["<strong>Entrada diaria por título</strong> con los ejemplares recibidos.",
      "<strong>Devolución calculada</strong> a partir de lo vendido, sin contar a mano.",
      "<strong>Aviso de plazo</strong> para no pasarse la fecha de devolución.",
      "<strong>Histórico por título</strong>, para ajustar cuántos ejemplares pedir."]),
    ("Ajustar el pedido es donde se gana el margen",
     ["Pedir de más significa devolver mucho y perder tiempo; pedir de menos significa quedarte sin el suplemento del domingo a las diez de la mañana. Ninguna de las dos es gratis.",
      "El histórico de ventas por título y por día de la semana es la herramienta. Un dominical no se comporta como un diario, y una revista mensual tiene su propio patrón."],
     ["<strong>Ventas por título y día de la semana</strong>, que es como se comporta la prensa.",
      "<strong>Porcentaje de devolución por título</strong>, para detectar lo que siempre sobra.",
      "<strong>Comparativa con semanas anteriores</strong> para ajustar el pedido.",
      "<strong>Alertas de títulos con devolución alta</strong> mantenida."]),
    ("Coleccionables y reservas de clientes",
     ["Los coleccionables por fascículos generan una clientela que reserva desde el número uno y espera encontrarlo cada semana. Perder un número de un cliente que lleva cuarenta es perder la colección entera.",
      "Eso exige llevar reservas por cliente y por título, saber qué número va y apartar los ejemplares comprometidos antes de ponerlos a la venta."],
     ["<strong>Reserva por cliente y título</strong>, con el número que le corresponde.",
      "<strong>Ejemplares apartados</strong> antes de la venta al público.",
      "<strong>Aviso de reservas sin recoger</strong>, que ocupan sitio y dinero.",
      "<strong>Histórico del coleccionable</strong> para saber cuántos pedir según avanza la colección."]),
    ("Márgenes estrechos y mucho efectivo",
     ["El quiosco vende a precio de portada, con un margen que no controla, y mueve mucho efectivo en tickets de uno o dos euros. En ese contexto, cualquier descuadre es pérdida directa: no hay margen comercial donde absorberlo.",
      "Por eso el arqueo diario, con registro de las entradas y salidas de efectivo que no son venta, importa más aquí que en un comercio con margen holgado. Y por eso conviene tener claro qué parte de la facturación viene de prensa a margen fijo y qué parte de golosinas, bebidas o artículos con precio libre, que es donde se puede mejorar el resultado."]),
  ],
  faqs=[
    ("¿Puedo controlar la devolución diaria de prensa?",
     "Sí: registras los ejemplares recibidos por título y el programa calcula la devolución a partir de lo vendido, sin que tengas que contar a mano. También avisa del plazo, que es donde se pierde dinero cuando se lleva de memoria."),
    ("¿Me ayuda a saber cuántos ejemplares pedir?",
     "El histórico de ventas por título y día de la semana es exactamente eso, y el porcentaje de devolución te señala los títulos que siempre sobran. Con esos dos datos el pedido deja de ser una costumbre heredada."),
    ("¿Puedo llevar las reservas de coleccionables por cliente?",
     "Sí, por cliente y título, sabiendo qué número le corresponde y apartando los ejemplares comprometidos antes de ponerlos a la venta. En coleccionables, perder un número puede costarte al cliente para el resto de la colección."),
    ("¿Puedo separar el margen de la prensa del resto de la tienda?",
     "Sí, con familias diferenciadas y el informe de márgenes por familia. Es la información más útil en un quiosco, porque enseña cuánto aporta la prensa a margen fijo y cuánto lo que vendes con precio libre, que es donde puedes actuar."),
    ("¿Es rápido para cobrar un periódico de 1,80 €?",
     "Sí, con botones de acceso rápido para los títulos diarios y cobro en efectivo con importes habituales. Con ese ticket medio, la velocidad de caja es lo que determina cuánta gente puedes atender en la hora punta de la mañana."),
    ("¿Necesito conexión a internet?",
     "No con la versión de PC: los datos están en tu equipo y sigues cobrando aunque falle la línea. En un quiosco de calle, donde la conexión no siempre es buena, es una diferencia práctica importante."),
  ],
  rel=[("TPV para papelerías","/negocio_papeleria.asp"),
       ("TPV para librerías","/negocio_libreria.asp"),
       ("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("TPV para estancos","/negocio_estanco.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),

# ============================================================== SUPERMERCADO
"negocio_supermercado.asp": dict(
  nombre="Supermercados y autoservicios",
  crumb="Supermercados",
  icono="fa-cart-shopping",
  title="Software TPV para Supermercados y Autoservicios | Caja 5",
  desc="TPV para supermercados: varias cajas en red, miles de referencias con EAN, secciones de peso, distintos tipos de IVA, ofertas por temporada y control de cajeros.",
  kw="tpv supermercado, software autoservicio, programa tpv supermercado, varias cajas en red tpv, control cajeros supermercado, tpv alimentacion multiple iva",
  h1='Software TPV para Supermercados. <span>Varias cajas, miles de referencias y tres IVAs.</span>',
  sub='Con dos o tres cajas trabajando a la vez sobre el mismo catálogo, lo que decide el día no es el TPV: es que las tres vean el mismo stock y el mismo precio en el mismo momento.',
  bloques=[
    ("Varias cajas sobre el mismo catálogo",
     ["Un autoservicio con dos o tres puestos necesita que un cambio de precio hecho en la oficina llegue a todas las cajas, y que el stock se descuente de un único inventario aunque vendan tres personas a la vez.",
      "Con Caja 5 para PC eso se monta sobre la red local del establecimiento: un equipo hace de servidor y el resto de puestos trabajan contra él. La ventaja frente a un TPV solo en la nube es que si se cae internet, las cajas siguen funcionando, porque la red interna no depende de la línea exterior."],
     ["<strong>Puestos conectados por red local</strong>, sin depender de la conexión a internet.",
      "<strong>Catálogo y precios únicos</strong> para todas las cajas.",
      "<strong>Stock descontado de un único inventario</strong> en tiempo real.",
      "<strong>Cierre por caja y por cajero</strong>, además del cierre global del día."]),
    ("Secciones de peso conviviendo con producto envasado",
     ["Un supermercado mezcla producto con EAN de fábrica, que se lee y ya está, con secciones de peso: fruta, carnicería, charcutería o panadería, donde se pesa y se etiqueta.",
      "Lo habitual es que las balanzas de sección impriman una etiqueta con código de barras que lleva el peso incorporado, y que la caja la lea sin que el cajero teclee nada. Ese circuito hay que montarlo bien una vez y después funciona solo."],
     ["<strong>Lectura de etiquetas de balanza</strong> con peso incorporado en el código.",
      "<strong>Secciones de peso</strong> con su propio catálogo y sus precios por kilo.",
      "<strong>Producto envasado con EAN</strong> leído directamente.",
      "<strong>Tara y precio por tramos</strong> donde haga falta."]),
    ("Control de cajeros y descuadres",
     ["Con varias personas cobrando, un descuadre sin usuario identificado es un descuadre que no se puede investigar. Cada caja debe cerrarse por cajero, con su fondo inicial, sus ventas por medio de pago y sus entradas y salidas de efectivo.",
      "No se trata de desconfiar de nadie: se trata de poder reconstruir qué pasó un jueves concreto cuando faltan cuarenta euros, que casi siempre resulta ser un cambio mal dado o una salida de efectivo sin registrar."],
     ["<strong>Usuario identificado</strong> en cada venta, devolución y apertura de cajón.",
      "<strong>Arqueo por cajero y por turno</strong>, no solo del día completo.",
      "<strong>Anulaciones y devoluciones registradas</strong> con quién las hizo.",
      "<strong>Histórico de cierres</strong> consultable por fecha."]),
    ("Ofertas, tipos de IVA y etiquetado",
     ["Un ticket de supermercado mezcla productos con distintos tipos de IVA y muy a menudo lleva alguna promoción encima. Ambas cosas tienen que salir bien sin que el cajero calcule nada.",
      "El tipo se define por artículo o familia y el ticket lo desglosa; las ofertas se configuran como campañas con fecha de inicio y fin. Ten en cuenta que los tipos aplicables a determinados alimentos han cambiado varias veces en los últimos años: confirma con tu asesor los vigentes. Y recuerda que la indicación del precio por unidad de medida es exigible en muchos productos, así que conviene tenerlo previsto en el cartel."]),
  ],
  faqs=[
    ("¿Puedo tener tres cajas trabajando sobre el mismo stock?",
     "Sí. Se monta sobre la red local del establecimiento: un equipo hace de servidor y los demás puestos trabajan contra él, con el mismo catálogo, los mismos precios y un único inventario. Como la red es interna, un corte de internet no para las cajas."),
    ("¿Puedo leer las etiquetas de las balanzas de sección?",
     "Sí. Las balanzas que imprimen etiqueta con código de barras que incorpora el peso se leen directamente en caja, sin teclear. Es el circuito estándar en autoservicios con secciones de fruta, carnicería o charcutería."),
    ("¿Puedo saber qué cajero ha hecho cada operación?",
     "Sí, trabajando con usuarios identificados: cada venta, devolución, anulación y apertura de cajón queda asociada a quien la hizo, y el arqueo se puede hacer por cajero y por turno. Es lo que permite investigar un descuadre concreto."),
    ("¿Aplica bien los distintos tipos de IVA en el mismo ticket?",
     "Sí, el tipo se define por artículo o familia y el ticket lo desglosa automáticamente, igual que el cierre de caja. Como los tipos de algunos alimentos han cambiado varias veces, confirma con tu asesor cuáles te corresponden ahora mismo."),
    ("¿Se pueden programar ofertas con fecha de inicio y fin?",
     "Sí, como campañas: defines qué artículos entran, el tipo de descuento y las fechas, y se aplican y se retiran solos sin que nadie tenga que acordarse."),
    ("¿Qué pasa si se estropea el equipo servidor?",
     "Por eso la copia de seguridad automática es lo primero que hay que configurar, con una copia fuera del local. Con la copia al día, restaurar en otro equipo es cuestión de minutos, y los puestos se reconectan al nuevo servidor."),
  ],
  rel=[("TPV para tiendas de alimentación","/negocio_alimentacion.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
       ("TPV para carnicerías","/negocio_carniceria.asp"),
       ("Rebajas y promociones","/rebajas-y-promociones-tpv.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),
}
