# -*- coding: utf-8 -*-
"""Base de hechos por sector, lote 2."""

SECTORES_2 = {

# ============================================================== INFORMATICA
"negocio_informatica.asp": dict(
  nombre="Tiendas de informática y servicio técnico",
  crumb="Informática",
  icono="fa-computer",
  title="Software TPV para Tiendas de Informática | Caja 5",
  desc="TPV para tiendas de informática: número de serie y garantía, partes de reparación, montaje de equipos a medida, RAEE y venta a empresas con albarán.",
  kw="tpv tienda informatica, software tienda ordenadores, programa tpv servicio tecnico informatico, control numero serie garantia, tpv montaje pc",
  h1='Software TPV para Tiendas de Informática. <span>Series, garantías y partes de taller.</span>',
  sub='La mitad del negocio son componentes con número de serie y garantía del fabricante. La otra mitad son horas de taller. Son dos formas de facturar que casi ningún TPV lleva a la vez.',
  bloques=[
    ("El componente se controla por unidad, no por cantidad",
     ["Un disco duro no es «una unidad de disco»: es un número de serie con una fecha de compra, un periodo de garantía del fabricante y, si falla, un RMA que hay que tramitar. Cuando el cliente vuelve a los catorce meses, lo primero que necesitas saber es qué unidad exacta le vendiste y cuándo.",
      "Sin control por serie, esa consulta se resuelve buscando tickets en una caja. Con control por serie, se resuelve en el mostrador en diez segundos y además sabes si la garantía del fabricante sigue viva para tramitar el RMA en lugar de comerte la reposición."],
     ["<strong>Número de serie en la venta</strong> de componentes y equipos completos.",
      "<strong>Garantía calculada desde la fecha de compra</strong>, visible al buscar por serie o por cliente.",
      "<strong>Trazabilidad hacia el proveedor</strong>, que es lo que necesitas para tramitar el RMA.",
      "<strong>Búsqueda por serie</strong> desde el mostrador, sin depender de encontrar el ticket."]),
    ("El equipo a medida es una lista de materiales, no un artículo",
     ["Montar un PC a medida significa consumir una placa, un procesador, memoria, disco, fuente y caja del stock, sumarles unas horas de montaje y vender el conjunto como un solo producto con su propio precio.",
      "Si eso se factura como seis líneas sueltas, el cliente ve el desglose completo y tú pierdes la referencia de qué configuración le montaste. Si se factura como un artículo genérico, el stock de componentes no baja. La forma correcta es un artículo compuesto que descuenta sus componentes."],
     ["<strong>Artículo compuesto</strong> que al venderse descuenta cada componente del stock.",
      "<strong>Mano de obra de montaje</strong> incluida como línea de servicio.",
      "<strong>Configuración guardada</strong>, para saber qué le montaste a ese cliente dentro de dos años.",
      "<strong>Coste real calculado</strong> sobre lo que costaron de verdad las piezas."]),
    ("El taller funciona con partes, no con tickets",
     ["Cuando entra un portátil a reparar hay que registrar de quién es, qué le pasa según el cliente, con qué accesorios llega y en qué estado. Ese resguardo evita discusiones a la entrega y es un documento que un TPV de tienda no contempla.",
      "Después el parte pasa por diagnóstico, presupuesto, aprobación, reparación y entrega, consumiendo piezas del stock por el camino. Cada estado con su fecha, para poder responder al teléfono sin ir a preguntar al técnico."],
     ["<strong>Parte de reparación con resguardo</strong> para el cliente al dejar el equipo.",
      "<strong>Estados con fecha</strong>: recibido, diagnosticado, presupuestado, aprobado, reparado, entregado.",
      "<strong>Piezas imputadas al parte</strong>, que salen del stock y forman el coste real del trabajo.",
      "<strong>Garantía propia de la reparación</strong>, distinta de la del fabricante."]),
    ("Venta a empresas y obligaciones de RAEE",
     ["Buena parte de la facturación de una tienda de informática viene de pequeñas empresas y autónomos que compran con factura y a veces a crédito. Eso pide albarán, factura agrupada a fin de mes y tarifas propias por cliente.",
      "Además, la venta de aparatos eléctricos y electrónicos lleva asociadas obligaciones sobre residuos (RAEE), incluida la recogida del aparato usado en determinados supuestos, y hay que reflejar en factura lo que corresponda. Los detalles dependen de la normativa vigente y de tu situación: consúltalos con tu asesor y con el sistema de gestión al que estés adherido."]),
  ],
  faqs=[
    ("¿Puedo asociar el número de serie a cada venta de componente?",
     "Sí. Los artículos marcados para control por serie se venden unidad a unidad registrando el número, de forma que después puedes buscar por esa serie y ver a quién y cuándo se vendió. Es lo que te permite resolver una garantía en el mostrador sin buscar tickets."),
    ("¿Cómo facturo un PC montado a medida sin que el stock quede mal?",
     "Como artículo compuesto: defines qué componentes lleva y, al venderlo, el programa descuenta cada uno de su stock. El cliente ve un solo producto con su precio y tú mantienes el inventario correcto y el coste real del equipo."),
    ("¿Se pueden llevar los partes de reparación en el mismo programa?",
     "Sí. El parte se abre al recibir el equipo, imprime resguardo para el cliente y va cambiando de estado hasta la entrega. Las piezas que uses se imputan al parte y salen del stock, así que sabes cuánto te ha costado de verdad cada reparación."),
    ("¿Puedo distinguir la garantía del fabricante de la de mi reparación?",
     "Sí, son dos periodos distintos y se registran por separado: la del producto se cuenta desde la venta y la del trabajo desde la entrega de la reparación. Al volver el cliente, ves ambas."),
    ("Vendo a empresas que pagan a fin de mes. ¿Se puede?",
     "Sí, con cuenta de cliente: emites albarán en lugar de ticket y a fin de mes agrupas todos los albaranes en una factura. Puedes fijar tarifas por cliente y un límite de riesgo que avise al superarlo."),
    ("¿El programa gestiona lo relativo a RAEE?",
     "Puede reflejar en la venta los conceptos que correspondan, pero las obligaciones concretas sobre residuos de aparatos eléctricos y electrónicos dependen de la normativa vigente y del sistema de gestión al que estés adherido. Confírmalo con tu asesor."),
  ],
  rel=[("TPV para telefonía móvil","/negocio_telefonia.asp"),
       ("TPV con órdenes de reparación","/negocio_reparaciones.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Hardware compatible con el TPV","/hardware-tpv-compatible.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),

# ================================================================ ESTETICA
"negocio_estetica.asp": dict(
  nombre="Centros de estética y belleza",
  crumb="Centros de estética",
  icono="fa-spa",
  title="Software TPV para Centros de Estética | Caja 5",
  desc="TPV para centros de estética: bonos de sesiones, agenda de citas, cabinas y profesionales, consumo de producto por tratamiento y ficha de cliente con histórico.",
  kw="tpv centro estetica, software centro de belleza, programa gestion estetica, bonos sesiones estetica, agenda citas centro estetica",
  h1='Software TPV para Centros de Estética. <span>Bonos, cabinas y consumo por tratamiento.</span>',
  sub='En estética casi nada se cobra en el momento del servicio: se venden bonos por adelantado y se van consumiendo. Llevar eso en una ficha de cartón es el origen de la mayoría de discusiones con clientas.',
  bloques=[
    ("El bono de sesiones es un pasivo, no una venta cerrada",
     ["Cuando una clienta compra un bono de diez sesiones, has cobrado diez pero has prestado cero. Ese dinero es un compromiso: debes diez sesiones. Hasta que no se consumen, el ingreso no está ganado del todo.",
      "Llevar los bonos en fichas de papel provoca dos problemas. El primero, discusiones sobre cuántas sesiones quedan. El segundo, y peor, que no sabes cuántas sesiones debe el centro en total, que es un dato relevante de tu negocio."],
     ["<strong>Bono con sesiones restantes</strong> visible al identificar a la clienta.",
      "<strong>Consumo registrado</strong> con fecha, profesional y cabina.",
      "<strong>Caducidad del bono</strong> si la aplicas, informada al vender.",
      "<strong>Informe de sesiones pendientes</strong> del centro entero, que es tu compromiso real."]),
    ("Cabina, profesional y hora: el recurso escaso no es el producto",
     ["En una tienda, el límite es el stock. En un centro de estética, el límite es el tiempo de cabina. Cada tratamiento ocupa una cabina durante un rato y a una profesional concreta, y el negocio se optimiza llenando esos huecos.",
      "Por eso la agenda no es un accesorio: es la herramienta central. Saber qué huecos quedan libres esta semana y qué profesional tiene disponibilidad es lo que decide la facturación del mes."],
     ["<strong>Duración por tratamiento</strong>, para que la agenda calcule el hueco real.",
      "<strong>Cita por profesional y cabina</strong>, evitando dobles reservas.",
      "<strong>Recordatorio a la clienta</strong>, que reduce las ausencias sin avisar.",
      "<strong>Ocupación por profesional</strong>, para ver quién tiene hueco y quién va saturada."]),
    ("Cada tratamiento consume producto de cabina",
     ["Una sesión de limpieza facial gasta producto profesional que compraste al proveedor. Ese consumo no se factura a la clienta como línea, pero es coste real y sale del almacén.",
      "Si no lo descuentas, el stock de cabina nunca cuadra y no sabes cuánto te cuesta de verdad cada tratamiento. Definir el consumo estimado por tratamiento resuelve las dos cosas y te da el margen real por servicio."],
     ["<strong>Consumo de producto por tratamiento</strong>, descontado del almacén de cabina.",
      "<strong>Almacén de cabina separado</strong> del producto de venta al público.",
      "<strong>Coste y margen por tratamiento</strong>, contando producto y tiempo.",
      "<strong>Reposición de cabina</strong> basada en tratamientos realizados, no en cálculo a ojo."]),
    ("La ficha de la clienta y los datos sensibles",
     ["El histórico de tratamientos, las alergias, los tipos de piel y las contraindicaciones son información necesaria para trabajar bien y, a la vez, información sensible. Parte de ella puede considerarse datos de salud, con requisitos reforzados.",
      "Conviene tenerla guardada en tu propio equipo con acceso limitado, informar a la clienta de para qué la tratas y recoger su consentimiento donde corresponda. Habla con tu asesor sobre qué medidas concretas te aplican; no es algo que deba resolver una web."]),
  ],
  faqs=[
    ("¿Puedo llevar bonos de sesiones y saber cuántas quedan?",
     "Sí. El bono se vende con su número de sesiones y, al identificar a la clienta, se ve el saldo restante. Cada consumo queda registrado con fecha y profesional, así que las discusiones sobre cuántas sesiones quedaban desaparecen."),
    ("¿Sé cuántas sesiones debe el centro en total?",
     "Sí, con el informe de sesiones pendientes. Es un dato que casi ningún centro tiene y que importa: son servicios ya cobrados que todavía tienes que prestar, y por tanto un compromiso de tu negocio."),
    ("¿Puedo gestionar la agenda de cabinas y profesionales?",
     "Sí, con cita por profesional y cabina, y duración definida por tratamiento para que los huecos se calculen solos. Así se evitan dobles reservas y ves de un vistazo qué disponibilidad real te queda esta semana."),
    ("¿Cómo controlo el producto que se gasta en cabina?",
     "Definiendo el consumo estimado de cada tratamiento, que se descuenta de un almacén de cabina separado del producto de venta al público. Con eso el stock cuadra y conoces el coste real de cada servicio."),
    ("¿Puedo vender también producto de cosmética en el mismo programa?",
     "Sí, y es habitual: el mismo TPV lleva la venta de producto al público y los servicios de cabina. Lo importante es tener los almacenes separados para que el consumo profesional no se confunda con la venta."),
    ("¿Dónde se guardan los datos de mis clientas?",
     "Con Caja 5 para PC, en tu propio ordenador. Como parte de esa información puede ser sensible, conviene limitar quién accede e informar a la clienta del tratamiento de sus datos; consulta con tu asesor las medidas que te correspondan."),
  ],
  rel=[("TPV para peluquerías","/negocio_peluqueria.asp"),
       ("Programa de fidelización y puntos","/programa-fidelizacion-puntos.asp"),
       ("Vales y tarjetas regalo","/vales-y-tarjetas-regalo-tpv.asp"),
       ("TPV para perfumerías","/negocio_perfumeria.asp"),
       ("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp")]),

# =============================================================== FOTOGRAFIA
"negocio_fotografia.asp": dict(
  nombre="Tiendas de fotografía y revelado",
  crumb="Fotografía",
  icono="fa-camera",
  title="Software TPV para Tiendas de Fotografía | Caja 5",
  desc="TPV para tiendas de fotografía: encargos de revelado e impresión, material con número de serie, alquiler de equipo, reportajes y trabajos por encargo.",
  kw="tpv tienda fotografia, software estudio fotografico, programa tpv revelado, gestion encargos fotografia, alquiler material fotografico",
  h1='Software TPV para Tiendas de Fotografía. <span>Encargos, alquiler y material con serie.</span>',
  sub='Tres negocios en un local: venta de equipo caro con número de serie, trabajo por encargo que tarda días y, cada vez más, alquiler de material por jornadas.',
  bloques=[
    ("El encargo de laboratorio manda sobre el ticket",
     ["Buena parte de lo que factura una tienda de fotografía no se lleva el cliente en el momento: se encarga. Copias, ampliaciones, álbumes, fotolibros, restauraciones y reportajes tienen un plazo, un formato, un acabado y un precio que depende de todo eso.",
      "El encargo tiene que registrar esas especificaciones y su estado, porque el cliente llama para preguntar y porque un error de formato es un trabajo perdido. Y casi siempre se cobra una señal al encargar."],
     ["<strong>Especificaciones en el encargo</strong>: formato, acabado, cantidad y soporte.",
      "<strong>Estados con fecha</strong>: recibido, en laboratorio, listo, entregado.",
      "<strong>Señal y saldo pendiente</strong> hasta la recogida.",
      "<strong>Aviso al cliente</strong> cuando el trabajo está listo."]),
    ("Cámaras y objetivos: valor alto, unidad a unidad",
     ["Un objetivo de mil euros no se lleva por cantidades. Se controla por número de serie, con su garantía y su trazabilidad hacia el proveedor, igual que en informática pero con importes por unidad todavía mayores.",
      "En material de este valor, además, el margen es estrecho y el capital inmovilizado es alto. Saber qué lleva seis meses en la vitrina sin venderse es una información cara de ignorar."],
     ["<strong>Control por número de serie</strong> en cuerpos, ópticas y flashes.",
      "<strong>Garantía asociada a la venta</strong>, consultable por serie.",
      "<strong>Rotación por referencia</strong>, para no repetir compras de lo que no sale.",
      "<strong>Valoración del inmovilizado</strong>, que en fotografía es de las partidas más altas del balance."]),
    ("Alquiler por jornadas: ni venta ni servicio corriente",
     ["Alquilar un cuerpo, una óptica o un juego de flashes por fin de semana se ha vuelto una línea de negocio en muchas tiendas. Operativamente no se parece ni a una venta ni a un servicio: el artículo sale del local y tiene que volver.",
      "Eso pide llevar la fianza, las fechas de salida y devolución previstas, y el estado en que salió y volvió el material. Un equipo que no vuelve, o vuelve dañado, sin nada registrado es una pérdida difícil de reclamar."],
     ["<strong>Salida y devolución con fechas</strong>, y aviso de lo que debería haber vuelto ya.",
      "<strong>Fianza registrada</strong> y devuelta al cerrar el alquiler.",
      "<strong>Estado del material</strong> anotado a la salida y a la vuelta.",
      "<strong>Disponibilidad por fechas</strong>, para no comprometer dos veces el mismo equipo."]),
    ("Reportajes y trabajos con derechos de imagen",
     ["Si además haces reportajes, la facturación cambia: hay presupuesto previo, anticipo, entrega y a veces derechos de uso de las imágenes. Conviene que el presupuesto quede guardado y se convierta en factura sin reescribirlo.",
      "En cuanto a las imágenes de personas, la cesión de derechos y el tratamiento de esas imágenes tienen sus propias exigencias legales. Ten preparados tus modelos de autorización y consúltalos con tu asesor: el programa gestiona la parte comercial, no la jurídica."]),
  ],
  faqs=[
    ("¿Puedo llevar los encargos de revelado y su estado?",
     "Sí. El encargo guarda formato, acabado, cantidad y soporte, y va cambiando de estado hasta la entrega. Puedes cobrar una señal al encargar y liquidar el resto en la recogida, y sacar en cualquier momento el listado de trabajos pendientes."),
    ("¿Se pueden controlar cámaras y objetivos por número de serie?",
     "Sí, con control por serie: cada unidad se vende registrando su número, de forma que la garantía y la trazabilidad quedan asociadas a ese aparato concreto. En material de este valor es prácticamente imprescindible."),
    ("¿Puedo gestionar el alquiler de equipo por días?",
     "Puedes llevarlo registrando la salida y la devolución con fechas, la fianza y el estado del material. Así sabes qué debería haber vuelto ya y en qué condiciones salió, que es lo que necesitas si hay que reclamar un desperfecto."),
    ("¿Puedo hacer presupuestos de reportaje y convertirlos en factura?",
     "Sí. El presupuesto se guarda con su validez y, cuando el cliente acepta, se convierte en venta sin volver a teclear las líneas. También puedes registrar el anticipo y el saldo pendiente hasta la entrega."),
    ("¿El programa gestiona los derechos de imagen?",
     "No: eso es documentación jurídica que debes tener preparada aparte, con tus modelos de autorización. El programa lleva la parte comercial del trabajo. Consulta con tu asesor cómo documentar la cesión de derechos en tu caso."),
    ("¿Sirve si además vendo marcos y álbumes?",
     "Sí, es venta de mostrador normal y convive en el mismo catálogo. Si el peso de tu negocio está en enmarcación a medida, échale un vistazo también a la página de TPV para enmarcación."),
  ],
  rel=[("TPV para enmarcación","/negocio_enmarcacion.asp"),
       ("TPV para tiendas de informática","/negocio_informatica.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Vales y tarjetas regalo","/vales-y-tarjetas-regalo-tpv.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),

# =============================================================== ALIMENTACION
"negocio_alimentacion.asp": dict(
  nombre="Tiendas de alimentación y ultramarinos",
  crumb="Alimentación",
  icono="fa-basket-shopping",
  title="Software TPV para Tiendas de Alimentación | Caja 5",
  desc="TPV para tiendas de alimentación: venta a peso con balanza, lotes y caducidades, trazabilidad, alérgenos, IVA reducido por familia y cuentas de barrio.",
  kw="tpv tienda alimentacion, software ultramarinos, programa tpv alimentacion, tpv con balanza, trazabilidad lotes alimentacion, tpv tienda barrio",
  h1='Software TPV para Tiendas de Alimentación. <span>Peso, lotes, alérgenos y varios tipos de IVA.</span>',
  sub='Vender comida obliga a cosas que no obliga vender ropa: pesar con balanza homologada, saber de qué lote salió cada cosa y aplicar bien tres tipos de IVA distintos en el mismo ticket.',
  bloques=[
    ("Un ticket de alimentación puede llevar tres tipos de IVA",
     ["En un mismo ticket puedes tener pan, leche y fruta a un tipo, conservas a otro y productos no alimentarios a otro. Aplicarlo a mano es imposible y equivocarse tiene consecuencias fiscales.",
      "El tipo de IVA se define en la ficha del artículo o en su familia, y el ticket lo desglosa solo. Ten en cuenta además que los tipos aplicables a determinados alimentos han cambiado varias veces en los últimos años: confirma con tu asesor los que te corresponden ahora mismo."],
     ["<strong>Tipo de IVA por artículo o familia</strong>, aplicado automáticamente.",
      "<strong>Desglose por tipo en el ticket</strong> y en el cierre de caja.",
      "<strong>Actualización masiva</strong> cuando cambia un tipo, sin repasar el catálogo entero.",
      "<strong>Resumen por tipo</strong> para pasarle a tu asesoría cada periodo."]),
    ("Venta a peso y metrología legal",
     ["Fruta, embutido, queso, frutos secos y legumbres se venden por peso. Eso significa balanza conectada al TPV o balanza que imprime etiqueta con código de barras que el TPV lee.",
      "Y significa también que el instrumento de pesaje utilizado en transacciones comerciales está sujeto a control metrológico, con sus verificaciones periódicas. La obligación es tuya como comerciante y no depende del software; confirma con tu asesor o con el organismo competente de tu comunidad qué te corresponde."],
     ["<strong>Artículos de venta por peso</strong> con precio por kilo.",
      "<strong>Balanza conectada</strong> o lectura de la etiqueta de balanza con código de peso.",
      "<strong>Tara descontada</strong> cuando el cliente trae su envase.",
      "<strong>Precio por tramos</strong> para el que se lleva cantidad."]),
    ("Lotes, caducidades y trazabilidad",
     ["En alimentación la trazabilidad no es una buena práctica: es una exigencia. Ante una alerta alimentaria tienes que poder decir de qué proveedor y de qué lote venía un producto, y retirarlo.",
      "Registrar lote y caducidad al recepcionar es el trabajo que hace posible eso. Como efecto secundario, el aviso de caducidad próxima te permite bajar de precio lo que va a vencer en lugar de tirarlo, que en alimentación es margen puro."],
     ["<strong>Lote y caducidad en la entrada</strong> de cada partida.",
      "<strong>Trazabilidad hacia el proveedor</strong> por lote.",
      "<strong>Aviso de próximos a caducar</strong> con días de margen configurables.",
      "<strong>Merma registrada</strong> para lo que se retira, separada de la venta."]),
    ("Alérgenos y la pregunta del mostrador",
     ["La información sobre alérgenos en alimentos es obligatoria, también en productos sin envasar servidos en el establecimiento, con la forma de facilitarla regulada por normativa europea y española.",
      "Tener los alérgenos en la ficha del artículo hace que cualquiera del mostrador pueda responder sin buscar el envase. Cómo debes facilitar esa información en tu caso concreto (cartel, ficha, verbalmente con soporte escrito disponible) conviene confirmarlo con tu asesor o con sanidad de tu comunidad."]),
  ],
  faqs=[
    ("¿Puedo aplicar distintos tipos de IVA en el mismo ticket?",
     "Sí, y es imprescindible en alimentación. El tipo se define en la ficha del artículo o de su familia y el ticket lo desglosa automáticamente. Como los tipos aplicables a algunos alimentos han cambiado varias veces, confirma con tu asesor cuáles te corresponden ahora."),
    ("¿Se puede conectar la balanza al TPV?",
     "Sí, de dos formas: balanza conectada que envía el peso al programa, o balanza que imprime una etiqueta con código de barras que incluye el peso y que el TPV lee. La segunda es la más habitual en tiendas con mostrador."),
    ("¿La balanza tiene que estar homologada?",
     "Los instrumentos de pesaje usados en transacciones comerciales están sujetos a control metrológico y a verificaciones periódicas. Esa obligación es tuya como comerciante, independientemente del software; consúltala con el organismo competente de tu comunidad."),
    ("¿Puedo llevar la trazabilidad por lotes?",
     "Sí. Al recepcionar registras lote y caducidad, y el stock queda desglosado, de forma que ante una alerta puedes identificar proveedor y partida. Es la información que te van a pedir si hay una retirada de producto."),
    ("¿Puedo guardar los alérgenos de cada producto?",
     "Sí, en la ficha del artículo, consultable desde la venta. La forma en que debes facilitar esa información al consumidor está regulada; confirma con tu asesor o con sanidad qué te aplica exactamente."),
    ("Tengo clientes de barrio que apuntan y pagan a fin de mes.",
     "Se lleva con cuenta de cliente: se registra la venta como pendiente y a fin de mes se liquida o se agrupa en factura. Queda todo registrado, con su saldo, en lugar de en una libreta."),
  ],
  rel=[("TPV para fruterías","/negocio_fruteria.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp")]),

# ================================================================= FRUTERIA
"negocio_fruteria.asp": dict(
  nombre="Fruterías y verdulerías",
  crumb="Fruterías",
  icono="fa-apple-whole",
  title="Software TPV para Fruterías y Verdulerías | Caja 5",
  desc="TPV para fruterías: venta a peso, precios que cambian cada semana, merma diaria de género fresco, origen del producto y pedidos a mercado.",
  kw="tpv fruteria, software fruteria verduleria, programa tpv frutas verduras, tpv con balanza fruteria, control merma genero fresco",
  h1='Software TPV para Fruterías. <span>El precio cambia cada semana y la merma es diaria.</span>',
  sub='Una frutería compra en el mercado a precio distinto cada semana y tira género todos los días. Un programa que no permita cambiar precios en treinta segundos no sirve aquí.',
  bloques=[
    ("El precio de compra cambia cada semana y el de venta también",
     ["En casi todo el comercio, el precio de un artículo se pone una vez y dura meses. En una frutería, el precio del tomate depende de lo que costó esta semana en el mercado, y puede variar dos veces en siete días.",
      "Eso obliga a que cambiar precios sea trivial: una pantalla donde ves tus cuarenta referencias frescas y las actualizas de golpe, no una ficha por artículo con seis clics cada una. Y obliga a reimprimir los carteles de precio con la misma facilidad."],
     ["<strong>Actualización rápida de precios</strong> por familia o por lista, no artículo a artículo.",
      "<strong>Carteles de precio reimpresos</strong> desde la misma pantalla.",
      "<strong>Histórico de precios</strong>, para saber a cómo lo vendiste el mes pasado.",
      "<strong>Margen calculado sobre el coste de esta semana</strong>, no sobre uno antiguo."]),
    ("La merma de fresco no es una anomalía: es el día a día",
     ["En género fresco se tira producto todos los días, y esa merma puede llegar a porcentajes que en otro comercio serían alarmantes. No medirla es renunciar a saber tu margen real.",
      "Registrar la merma diaria por familia, aunque sea de forma rápida al cerrar, cambia por completo la información que tienes: descubres qué productos te hacen perder dinero pese a venderse, y ajustas cuánto compras."],
     ["<strong>Registro de merma diaria</strong> por artículo o familia, rápido de introducir.",
      "<strong>Merma separada de la venta</strong>, para que el inventario y el margen sean reales.",
      "<strong>Coste de la merma</strong> acumulado por semana y por mes.",
      "<strong>Ajuste de compra</strong> basado en lo que de verdad se vendió, no en lo que se pidió."]),
    ("Peso, tara y el cliente que compra media pieza",
     ["Toda la operativa gira alrededor de la balanza. Precio por kilo, tara del envase, y a menudo el cliente que quiere media sandía o un cuarto de kilo justo.",
      "Además hay artículos que se venden por unidad y no por peso (una lechuga, un manojo), así que el catálogo mezcla ambas formas y el programa tiene que distinguirlas sin que el dependiente piense."],
     ["<strong>Artículos por peso y por unidad</strong> conviviendo en el mismo catálogo.",
      "<strong>Balanza conectada</strong> o lectura de etiqueta con peso incorporado.",
      "<strong>Tara descontada</strong> para el cliente que trae su bolsa o su caja.",
      "<strong>Precio por tramos</strong> para la caja o el saco completo."]),
    ("Origen del producto y pedidos a mercado",
     ["La normativa de información al consumidor exige indicar determinados datos en frutas y hortalizas frescas, como el país de origen y la categoría. Tenerlo en la ficha del artículo facilita imprimir el cartel correcto y responder en el mostrador.",
      "Del lado de la compra, el pedido al mercado o al mayorista se hace de madrugada y con lo vendido del día anterior delante. El informe de ventas por artículo del día es la herramienta que convierte ese pedido en una decisión y no en una costumbre. Las exigencias concretas de etiquetado conviene confirmarlas con tu asesor."]),
  ],
  faqs=[
    ("¿Puedo cambiar precios rápido cuando varía el mercado?",
     "Sí, con actualización por lista o por familia: ves tus referencias frescas en una pantalla y las cambias de golpe, sin entrar en la ficha de cada una. Desde ahí mismo puedes reimprimir los carteles de precio."),
    ("¿Cómo registro lo que tiro cada día?",
     "Como merma, en una entrada rápida por artículo o familia al cerrar. Sale del stock sin computar como venta, así que el inventario cuadra y al final del mes tienes el coste real de la merma, que en fresco es una cifra que conviene mirar."),
    ("¿Puedo vender unos artículos por peso y otros por unidad?",
     "Sí, conviven en el mismo catálogo. Cada artículo se define como venta por peso o por unidad, y el dependiente no tiene que hacer nada distinto en caja."),
    ("¿Se puede descontar la tara si el cliente trae su envase?",
     "Sí, indicando la tara en el momento del pesaje o teniéndola predefinida para envases habituales. Es cada vez más frecuente y evita cobrar de más."),
    ("¿Puedo guardar el origen y la categoría del producto?",
     "Sí, en la ficha del artículo, y usarlo para imprimir el cartel. Las exigencias concretas de información al consumidor en frutas y hortalizas conviene confirmarlas con tu asesor, porque tienen su detalle."),
    ("¿Me ayuda a decidir cuánto comprar en el mercado?",
     "El informe de ventas por artículo y día es exactamente eso: lo que de verdad salió ayer y la semana pasada. Con eso el pedido de madrugada deja de basarse en la costumbre. Es donde más dinero se gana o se pierde en una frutería."),
  ],
  rel=[("TPV para tiendas de alimentación","/negocio_alimentacion.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
       ("Etiquetas y carteles de precio","/etiquetas-codigo-de-barras-tpv.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),

# ================================================================ PANADERIA
"negocio_panaderia.asp": dict(
  nombre="Panaderías y pastelerías",
  crumb="Panaderías",
  icono="fa-bread-slice",
  title="Software TPV para Panaderías y Pastelerías | Caja 5",
  desc="TPV para panaderías: producción diaria, encargos de tartas, venta rápida en horas punta, alérgenos obligatorios, obradores y reparto a hostelería.",
  kw="tpv panaderia, software pasteleria, programa tpv panaderia obrador, encargos tartas tpv, alergenos panaderia, tpv reparto pan hosteleria",
  h1='Software TPV para Panaderías. <span>Producción diaria, encargos y colas de las ocho.</span>',
  sub='El género se fabrica cada mañana y caduca el mismo día. Eso convierte la decisión de cuánto producir en la más importante del negocio, y la velocidad de caja en la segunda.',
  bloques=[
    ("Cuánto producir es la decisión que decide el año",
     ["Una panadería no compra género: lo fabrica. Y lo que sobra al cerrar no vale nada al día siguiente. Producir de más es tirar dinero; producir de menos es perder ventas a las once de la mañana.",
      "La única forma de acertar es mirar lo que de verdad se vendió, por producto y por día de la semana. Un martes no se parece a un sábado, y el 1 de noviembre no se parece a nada. El histórico de ventas por día es la herramienta de producción."],
     ["<strong>Ventas por producto y día de la semana</strong>, que es como se planifica el obrador.",
      "<strong>Comparativa con el mismo día del año anterior</strong> para fechas señaladas.",
      "<strong>Sobrante registrado al cierre</strong>, para saber cuánto se está produciendo de más.",
      "<strong>Coste de la merma diaria</strong>, que en panadería se subestima siempre."]),
    ("A las ocho de la mañana hay cola y el ticket son dos euros",
     ["La hora punta de una panadería es brutal y el ticket medio bajo. Cada segundo de caja cuenta, y no se puede pedir al dependiente que busque referencias en una lista mientras hay quince personas esperando.",
      "Aquí sí tiene sentido la pantalla táctil con botones grandes por producto, que es justo lo contrario de lo que conviene en una tienda de ropa. Barra de pan, croissant, napolitana: un toque cada uno."],
     ["<strong>Botones grandes por producto</strong> para lo que se vende a diario.",
      "<strong>Cobro rápido en efectivo</strong> con importes habituales predefinidos.",
      "<strong>Segundo puesto en punta</strong>, conectado por la red local de la tienda.",
      "<strong>Apertura de cajón automática</strong>, que con esa cola se agradece."]),
    ("Encargos de tartas: fecha, hora y decoración",
     ["El encargo de una tarta es un compromiso con fecha y hora concretas, con un texto que va escrito encima y a veces con requisitos por alergia. Un error ahí no se arregla: la comunión es a la una.",
      "Por eso el encargo debe recoger todo el detalle y aparecer en el listado del obrador del día correspondiente. Con señal cobrada, para que el que no viene a recoger no salga gratis."],
     ["<strong>Fecha y hora de recogida</strong> en el encargo, con listado por día para el obrador.",
      "<strong>Detalle completo</strong>: tamaño, sabor, texto de la inscripción y observaciones.",
      "<strong>Avisos de alergia</strong> destacados en el encargo.",
      "<strong>Señal cobrada al encargar</strong> y saldo liquidado en la recogida."]),
    ("Alérgenos: aquí no es opcional",
     ["En productos de panadería y pastelería, muchos sin envasar, la información sobre alérgenos es obligatoria y es una de las inspecciones más habituales. Gluten, huevo, leche, frutos secos y trazas aparecen en casi todo lo que sale del obrador.",
      "Tener los alérgenos en la ficha de cada producto permite responder en el mostrador con seguridad y preparar la documentación que corresponda. La forma concreta en que debes facilitar esa información al consumidor está regulada: confírmala con tu asesor o con sanidad de tu comunidad antes de dar nada por bueno."]),
  ],
  faqs=[
    ("¿Puedo saber cuánto producir de cada cosa?",
     "El informe de ventas por producto y día de la semana es lo más cerca que vas a estar de esa respuesta: te dice qué se vendió de verdad cada martes y cada sábado. Con eso y el sobrante registrado al cierre, la producción deja de ser una corazonada."),
    ("¿Cómo agilizo la caja en la hora punta?",
     "Con botones grandes por producto para lo de diario, cobro rápido en efectivo e importes habituales predefinidos. En panadería, a diferencia de una tienda de ropa, la pantalla táctil sí aporta: el producto no tiene código de barras y se vende a toque."),
    ("¿Puedo llevar los encargos de tartas con su fecha y hora?",
     "Sí, con todo el detalle: tamaño, sabor, texto de la inscripción, avisos de alergia y hora de recogida. El obrador saca el listado de encargos del día y no depende de una libreta que puede perderse."),
    ("¿Puedo cobrar señal por un encargo?",
     "Sí, se registra el anticipo y la operación queda con saldo pendiente hasta la recogida. Es lo que evita que un encargo que nadie recoge sea pérdida completa."),
    ("¿Puedo guardar los alérgenos de cada producto?",
     "Sí, en la ficha, consultable desde la venta. En panadería es especialmente relevante porque casi todo lleva algún alérgeno. La forma en que debes facilitar esa información está regulada: confírmalo con tu asesor o con sanidad."),
    ("Reparto pan a bares y restaurantes. ¿Se puede llevar?",
     "Sí, con cuenta de cliente: cada reparto genera albarán y a fin de mes se agrupan en una factura por cliente. Puedes fijarles su tarifa propia, que en hostelería casi siempre es distinta de la de mostrador."),
  ],
  rel=[("TPV para tiendas de alimentación","/negocio_alimentacion.asp"),
       ("Arqueo de caja y cierre diario","/arqueo-de-caja-cierre-diario.asp"),
       ("TPV táctil o con teclado","/tpv-tactil-o-teclado-raton.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("Impresora de tickets","/impresora-tickets-compatible-tpv.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),

# ================================================================= LIBRERIA
"negocio_libreria.asp": dict(
  nombre="Librerías",
  crumb="Librerías",
  icono="fa-book",
  title="Software TPV para Librerías: ISBN y depósito | Caja 5",
  desc="TPV para librerías: búsqueda por ISBN, precio fijo del libro, encargos a distribuidor, depósito y devoluciones, y campaña de libro de texto.",
  kw="tpv libreria, software libreria, programa tpv libros isbn, gestion deposito libreria, encargos libros distribuidor, precio fijo libro",
  h1='Software TPV para Librerías. <span>ISBN, precio fijo y devolución al distribuidor.</span>',
  sub='El libro tiene precio fijado por ley, llega muchas veces en depósito y se devuelve si no se vende. Ese trío no aparece en ningún otro comercio.',
  bloques=[
    ("El precio del libro no lo pones tú",
     ["En España el precio de venta al público del libro está fijado por el editor o el importador, con un margen de descuento limitado por la normativa del sector y excepciones tasadas, como determinadas campañas o los libros de texto en ciertos supuestos.",
      "Para la gestión eso significa que no compites por precio y que el descuento que puedes aplicar tiene un tope legal. El programa debe respetar ese precio y avisar si alguien intenta pasarse del descuento permitido. Los porcentajes y excepciones aplicables conviene confirmarlos con tu asesor, porque tienen matices."],
     ["<strong>Precio de cubierta como precio de venta</strong>, cargado con la ficha.",
      "<strong>Límite de descuento configurable</strong>, para no rebasar sin darte cuenta.",
      "<strong>Excepciones marcadas</strong> por familia, cuando la normativa las permita.",
      "<strong>Margen sobre el precio de compra al distribuidor</strong>, que es donde se juega tu rentabilidad."]),
    ("ISBN: la referencia universal que sí te viene dada",
     ["A diferencia de la ferretería o la bisutería, la librería tiene la suerte de que todo su catálogo llega identificado. El ISBN es el código de barras del libro y sirve para buscar, vender, encargar y devolver.",
      "Eso hace que el alta de novedades sea rápida y que la caja vaya con lector sin excepciones. Lo que sí conviene es tener buenas familias por materia, porque el cliente no pregunta por ISBN: pregunta por «una novela negra que esté bien»."],
     ["<strong>Búsqueda y venta por ISBN</strong> con lector, sin teclear nada.",
      "<strong>Clasificación por materia</strong>, autor, editorial y colección.",
      "<strong>Novedades y fondo separados</strong>, porque rotan de forma completamente distinta.",
      "<strong>Localización en la tienda</strong> por sección, para no recorrer la librería entera."]),
    ("Depósito y devolución: el género no siempre es tuyo",
     ["Buena parte del fondo de una librería llega en depósito o con derecho de devolución. Es decir, lo tienes en la estantería pero solo lo pagas si se vende, y lo que no sale vuelve al distribuidor dentro de un plazo.",
      "Perder el control de esos plazos es perder dinero directamente: un libro devuelto tarde ya no se puede devolver y pasa a ser tuyo. Necesitas saber en todo momento qué está en depósito, de quién y hasta cuándo."],
     ["<strong>Marca de depósito</strong> en la entrada de mercancía, con distribuidor y fecha.",
      "<strong>Aviso de plazo de devolución</strong> antes de que venza.",
      "<strong>Liquidación al distribuidor</strong> de lo vendido en depósito.",
      "<strong>Preparación de la devolución</strong> con listado y valoración."]),
    ("Encargos: el cliente que pide un título que no tienes",
     ["Ninguna librería tiene todo. La operativa que fideliza es el encargo: el cliente pide un título, lo pides al distribuidor, llega en unos días y le avisas.",
      "Ese circuito, bien llevado, es una de las mayores fuentes de clientela fiel de una librería, y mal llevado es la forma más rápida de perderla. El encargo debe quedar registrado con el ISBN, el cliente y su teléfono, y aparecer en el listado de pendientes hasta que se entrega."]),
  ],
  faqs=[
    ("¿El programa respeta el precio fijo del libro?",
     "Sí: el precio de cubierta se carga con la ficha y puedes configurar el límite de descuento permitido para que nadie lo rebase por error. Los porcentajes y las excepciones que contempla la normativa del libro conviene confirmarlos con tu asesor, porque tienen bastantes matices."),
    ("¿Puedo vender leyendo el ISBN?",
     "Sí, el ISBN funciona como código de barras: se lee con el lector y el libro entra en el ticket con su precio. También sirve para buscar en tu catálogo, encargar al distribuidor y preparar devoluciones."),
    ("¿Cómo controlo lo que tengo en depósito?",
     "Marcando la mercancía como depósito al recepcionarla, con su distribuidor y su fecha límite. El programa te avisa antes de que venza el plazo de devolución, que es justo donde se pierde dinero cuando se lleva a mano."),
    ("¿Puedo preparar las devoluciones al distribuidor?",
     "Sí, generando el listado de lo que vas a devolver con su valoración, a partir de lo que sigue en stock del depósito. Así la devolución sale con papeles y no de memoria."),
    ("¿Puedo llevar los encargos de clientes?",
     "Sí, con el ISBN, los datos del cliente y su estado hasta la entrega. Es el circuito que más fideliza en una librería, y basta con que se pierda un par de veces para perder al cliente."),
    ("¿Sirve también si vendo papelería además de libros?",
     "Sí, conviven en el mismo catálogo con familias distintas. Si el peso de tu negocio está más en material escolar y campaña de septiembre, mira también la página de TPV para papelerías."),
  ],
  rel=[("TPV para papelerías","/negocio_papeleria.asp"),
       ("TPV para cómics y coleccionismo","/negocio_comics.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Programa de fidelización","/programa-fidelizacion-puntos.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp")]),
}
