# -*- coding: utf-8 -*-
"""Comparativas con competidores, reescritas una a una.

Cada pagina se estructura alrededor del argumento real de ESE competidor, no de
un esquema comun. Los datos objetivos salen del CSV de investigacion del cliente;
las criticas se atribuyen a opiniones publicas de usuarios.
"""

OPERATIVA_VS1 = {

"stockagile-vs-caja5.asp": dict(
  nom="Stockagile", crumb="Stockagile vs Caja 5", icono="fa-cloud",
  title="Alternativa a Stockagile: comparativa con Caja 5",
  desc="Stockagile cuesta 79 €/mes: 4.740 € a cinco años. Comparativa honesta con Caja 5, licencia de 333 €, y en qué casos Stockagile sigue siendo mejor opción.",
  kw="alternativa a stockagile, stockagile precio, stockagile opiniones, stockagile vs caja 5, tpv moda sin cuotas",
  h1="Alternativa a Stockagile: cuando la cuota deja de compensar",
  sub="Stockagile es un buen producto para lo que fue diseñado. La pregunta no es si funciona, sino si tu tienda necesita lo que estás pagando cada mes.",
  faq_titulo="Preguntas frecuentes sobre Stockagile y sus alternativas",
  cta=("Haz tú la cuenta con tus números",
       "Descarga la demo de Caja 5, mete tu catálogo real con tallas y colores, y compara. Sin tarjeta y sin que te llamemos después."),
  bloques=[
    ("Para qué está hecho Stockagile de verdad",
     ["Stockagile nació para marcas de moda que venden en varios canales a la vez: dos o tres tiendas propias, un e-commerce y presencia en marketplaces como Zalando o Amazon. Su matriz de tallas y colores es de las mejores del mercado español y su sincronización multicanal funciona en tiempo real.",
      "Si ese es tu escenario, la cuota tiene sentido. Pagar 79 euros al mes por mantener sincronizado el stock de cuatro canales es barato comparado con el coste de vender dos veces la misma prenda. No vamos a decirte lo contrario."],
     None),
    ("Los 4.740 euros que casi nadie calcula",
     ["El plan de entrada son 79 euros al mes. En cinco años eso son <strong>4.740 euros</strong>, o 948 al año. Una licencia de Caja 5 para PC son 333 euros una sola vez.",
      "La diferencia a cinco años ronda los 4.407 euros, y eso sin contar subidas de tarifa, que en SaaS son la norma y no la excepción. Ahora el matiz honesto, que es importante: si dejas de pagar Stockagile pierdes el acceso a tu programa; con una licencia en propiedad, el software sigue siendo tuyo aunque no vuelvas a pagarnos nada.",
      "La cuenta cambia si tienes varias cajas: Stockagile factura por plan, no por puesto, mientras que en licencia cada puesto tiene su coste. Con cuatro o cinco puestos, la distancia se estrecha."],
     None),
    ("Lo que dicen sus usuarios en foros y reseñas",
     ["Con 4,6 sobre 5 y más de 120 opiniones públicas, la valoración general es buena. La crítica que más se repite es concreta: <em>soporte lento en periodos de rebajas y fallos de sincronización con Shopify en picos de tráfico</em>.",
      "Es una queja coherente con el modelo: cuando toda la base de clientes tiene el mismo pico a la vez, en enero y en julio, el soporte se satura. Es opinión de usuarios y no juicio nuestro, pero merece la pena que preguntes por sus tiempos de respuesta en campaña antes de decidir."],
     None),
    ("Dónde encaja Caja 5 y dónde no",
     ["Caja 5 está pensado para la tienda independiente española que quiere comprar su programa una vez. Matriz de tallas y colores, control de stock, etiquetas, fidelización, vales y VeriFactu, con soporte telefónico incluido y sin comisión por venta.",
      "Y donde no encaja, dicho claro: si tu negocio vive de vender en Zalando y Amazon con stock sincronizado al segundo, Stockagile hace eso mejor. Caja 5 Nube sincroniza tienda física y web, pero la integración nativa con marketplaces internacionales no es nuestro terreno."],
     ["<strong>Te encaja Caja 5 si:</strong> tienes una o dos tiendas, te molesta la cuota indefinida y quieres el programa en propiedad.",
      "<strong>Te encaja Caja 5 si:</strong> quieres seguir cobrando cuando se cae internet.",
      "<strong>Sigue con Stockagile si:</strong> vendes en marketplaces con sincronización en tiempo real.",
      "<strong>Sigue con Stockagile si:</strong> gestionas varias tiendas propias y un e-commerce con volumen alto."]),
    ("Cómo sería la migración",
     ["Si exportas desde Stockagile el catálogo con sus variantes, el stock y la ficha de clientes a Excel o CSV, se importa en Caja 5. La matriz de tallas y colores se reconstruye a partir de esas variantes.",
      "Lo que no viaja es el histórico de ventas ticket a ticket. Y recuerda que tienes obligaciones de conservación de esa documentación: no des de baja el servicio antiguo sin confirmar antes con tu asesor cuánto tiempo debes conservarla y en qué forma."],
     None),
  ],
  faqs=[
    ("¿Cuánto cuesta Stockagile al año?",
     "Su plan de entrada publicado son 79 euros al mes, es decir 948 euros al año y 4.740 a cinco años. Confirma las tarifas vigentes en su web, porque cambian. Caja 5 para PC son 333 euros en pago único."),
    ("¿Qué hace mejor Stockagile que Caja 5?",
     "La sincronización en tiempo real con marketplaces internacionales y la gestión multicanal cuando tienes varias tiendas propias más e-commerce con volumen. Si ese es tu caso, es mejor herramienta para ti que la nuestra."),
    ("¿Qué pasa si dejo de pagar Stockagile?",
     "Pierdes el acceso, como en cualquier SaaS. Es la diferencia estructural con una licencia en propiedad: Caja 5 para PC sigue funcionando en tu ordenador aunque no vuelvas a pagar nada. Es el argumento principal a favor del modelo de licencia."),
    ("¿Puedo llevarme mis datos de Stockagile?",
     "Si puedes exportar catálogo con variantes, stock y clientes a Excel o CSV, sí. Es lo primero que conviene comprobar antes de comprometerse con cualquier programa, y muy poca gente lo pregunta al contratar."),
    ("¿Caja 5 tiene matriz de tallas y colores como Stockagile?",
     "Sí, con talla, color y una tercera variable libre. Es la función central del producto para moda. La diferencia con Stockagile no está ahí: está en el modelo de pago y en la integración con marketplaces."),
    ("¿Y las comisiones por cobro con tarjeta?",
     "Con Caja 5 cobras con el datáfono de tu banco a la comisión que hayas negociado con él, y nosotros no participamos. En Stockagile la comisión depende de la pasarela que integres."),
  ],
  rel=[("Comparativas de TPV","/comparativas-tpv.asp"),
       ("Alternativa a Glop","/glop-vs-caja5.asp"),
       ("Alternativa a Catinfog","/catinfog-vs-caja5.asp"),
       ("Software TPV para tiendas de ropa","/negocio_moda.asp"),
       ("Pago único frente a cuotas mensuales","/tpv-pago-unico-vs-cuotas-mensuales.asp"),
       ("Cómo cambiar de programa TPV","/migrar-de-tpv-cambiar-programa.asp")]),

"square-vs-caja5.asp": dict(
  nom="Square", crumb="Square vs Caja 5", icono="fa-percent",
  title="Alternativa a Square: la cuenta de las comisiones",
  desc="Square cobra entre 1,25 % y 2,5 % por transacción. Qué supone eso al año según tu facturación, comparado con una licencia sin comisión, y cuándo Square compensa.",
  kw="alternativa a square tpv, square comisiones españa, square opiniones, square vs caja 5, tpv sin comision por venta",
  h1="Alternativa a Square: cuánto te cuesta la comisión al año",
  sub="Square tiene el mejor hardware del mercado y la interfaz más fácil que existe. Toda la discusión está en el porcentaje que se lleva de cada venta.",
  faq_titulo="Preguntas frecuentes sobre Square y sus alternativas",
  cta=("Calcula tu comisión anual y compárala",
       "Multiplica tu facturación con tarjeta por el porcentaje que pagas. Esa cifra, cada año, frente a 333 € una vez."),
  bloques=[
    ("Square no vende software: vende procesamiento de pagos",
     ["Esta es la clave para entender el producto. El plan de software cuesta 49 euros al mes, pero el negocio de Square está en la comisión de entre 1,25 % y 2,5 % que se lleva de cada cobro con tarjeta.",
      "Por eso su hardware es tan bueno y su interfaz tan cuidada: cuanto más fácil sea cobrar contigo, más cobras, y más comisión generan. Es un modelo legítimo y muy bien ejecutado. Solo hay que tener claro qué estás pagando."],
     None),
    ("La cuenta, con números reales",
     ["Tomemos un 1,5 % de comisión, que es un valor intermedio en su horquilla, y veamos qué supone según tu facturación anual con tarjeta:",
      "A eso hay que sumarle los 49 euros al mes del plan, otros 588 euros al año. Una licencia de Caja 5 para PC son 333 euros una vez, y cobras con el datáfono que tú contrates: la comisión la negocias con tu banco y nosotros no tocamos esa operación."],
     ["<strong>100.000 € de facturación con tarjeta:</strong> 1.500 € al año en comisiones.",
      "<strong>200.000 €:</strong> 3.000 € al año.",
      "<strong>350.000 €:</strong> 5.250 € al año.",
      "<strong>A cinco años, con 200.000 € anuales:</strong> unos 15.000 € solo en comisión, más 2.940 € de plan."]),
    ("Las retenciones de fondos, que es la queja más seria",
     ["Con 4,7 sobre 5 y más de mil opiniones globales, la valoración de Square es muy alta, sobre todo por su facilidad de uso. Pero entre las críticas de usuarios españoles aparece una que no es cosmética: <em>retenciones preventivas de fondos de ventas y soporte telefónico difícil de alcanzar en una emergencia</em>.",
      "Que un procesador de pagos retenga fondos ante un patrón de venta inusual es una práctica del sector, no una anomalía de Square. Pero conviene saberlo antes: si tu negocio tiene picos fuertes de facturación, como una campaña de Navidad o unas rebajas, es el escenario donde estas retenciones aparecen y donde peor te viene quedarte sin liquidez."],
     None),
    ("El hardware cerrado te ata dos veces",
     ["Square funciona con su propio terminal y su propio lector. El hardware es excelente, de eso no hay duda, pero implica que el día que quieras cambiar de software también tienes que cambiar de hardware, y que no puedes usar el datáfono que ya tienes contratado con tu banco.",
      "Caja 5 va al revés: funciona con hardware estándar de Windows. Si tu impresora, tu lector o tu ordenador ya funcionan, sirven. Y cobras con el datáfono de tu banco, al precio que hayas negociado."],
     None),
    ("Cuándo Square es la opción correcta",
     ["Con honestidad: si facturas poco con tarjeta, no quieres desembolso inicial, valoras el diseño y necesitas empezar a cobrar esta misma tarde, Square es difícil de batir. Con 30.000 euros anuales de facturación con tarjeta, la comisión son 450 euros al año y la comodidad puede compensarlo de sobra.",
      "El punto de inflexión llega con el volumen. A partir de cierta facturación, lo que pagas en comisión supera con mucho lo que costaría comprar el programa y contratar un datáfono normal. Haz esa cuenta con tus propios números: es de las más rentables que puedes hacer en media hora."],
     None),
  ],
  faqs=[
    ("¿Cuánto cobra Square de comisión en España?",
     "Su horquilla publicada está entre el 1,25 % y el 2,5 % por transacción según el tipo de cobro, más 49 euros al mes en el plan de pago. Confirma las condiciones vigentes en su web. Sobre 200.000 euros de facturación con tarjeta, un 1,5 % son 3.000 euros al año."),
    ("¿Caja 5 cobra comisión por venta?",
     "No. Caja 5 es una licencia de software: 333 euros en pago único para PC. El cobro con tarjeta lo haces con el datáfono que tú contrates con tu banco, con la comisión que negocies con él. Nosotros no participamos en esa operación."),
    ("¿Puedo usar mi datáfono actual con Square?",
     "Square está diseñado alrededor de su propio hardware de cobro, que es parte de su modelo de negocio. Con Caja 5 puedes seguir con el datáfono de tu banco, que es una diferencia práctica importante si ya tienes una comisión negociada."),
    ("¿Es cierto que Square retiene fondos?",
     "Aparece entre las críticas de usuarios: retenciones preventivas ante patrones de venta inusuales. Es una práctica del sector de procesadores de pago, no exclusiva de Square, pero conviene tenerlo presente si tu negocio tiene picos fuertes de facturación."),
    ("¿Square cumple con VeriFactu?",
     "La información que manejamos indica que estaba en proceso de certificación. Es un dato que cambia rápido: pídeles su declaración responsable actualizada por escrito antes de decidir, que es el documento que acredita el cumplimiento."),
    ("¿Cuándo compensa Square?",
     "Con facturación baja con tarjeta, sin desembolso inicial disponible y valorando el hardware y la facilidad de uso. Con 30.000 euros anuales, la comisión son unos 450 euros al año y puede compensar de sobra. El punto de inflexión llega con el volumen."),
  ],
  rel=[("Comparativas de TPV","/comparativas-tpv.asp"),
       ("TPV: software o datáfono","/tpv-software-o-datafono.asp"),
       ("Hardware compatible con el TPV","/hardware-tpv-compatible.asp"),
       ("Alternativa a Stockagile","/stockagile-vs-caja5.asp"),
       ("Pago único frente a cuotas","/tpv-pago-unico-vs-cuotas-mensuales.asp"),
       ("TPV gratis para comercio","/tpv-gratis-para-comercio.asp")]),

"solvermedia-vs-caja5.asp": dict(
  nom="Solvermedia", crumb="Solvermedia vs Caja 5", icono="fa-database",
  title="Alternativa a Solvermedia: el problema de la base",
  desc="Solvermedia cuesta 99 € y es de las opciones más baratas. Qué pasa con su base de datos al acumular años de tickets y qué mirar antes de decidir por precio.",
  kw="alternativa a solvermedia, solvermedia tpv precio, solvermedia opiniones, solvermedia vs caja 5, tpv moda barato",
  h1="Alternativa a Solvermedia: lo que pasa al tercer año",
  sub="Noventa y nueve euros de licencia es difícil de batir por precio. La pregunta es qué pasa cuando la base de datos lleva tres años acumulando tickets.",
  faq_titulo="Preguntas frecuentes sobre Solvermedia y sus alternativas",
  cta=("Prueba con tu volumen real",
       "Si vienes de un programa que se ha vuelto lento, instala la demo y carga tu catálogo completo. La diferencia se nota en el primer minuto."),
  bloques=[
    ("El precio de entrada más bajo del mercado",
     ["Noventa y nueve euros en pago único. Para una tienda pequeña que empieza y solo necesita cobrar, es una barrera de entrada mínima y perfectamente razonable.",
      "Con 3,5 sobre 5 y más de 25 opiniones, la valoración pública es la más baja del grupo de competidores que analizamos, pero conviene leerla en contexto: quien paga 99 euros y quien paga 2.000 no espera lo mismo. La crítica no es que sea caro para lo que da."],
     None),
    ("Lo que sí preocupa: el rendimiento a largo plazo",
     ["La crítica que más se repite en foros y reseñas es técnica y concreta: <em>bases de datos basadas en Microsoft Access que se vuelven lentas e inestables al acumular años de tickets</em>.",
      "Merece la pena entender por qué importa. Un motor de base de datos de tipo fichero funciona bien con volúmenes moderados y se degrada cuando el histórico crece, sobre todo si hay varios puestos accediendo a la vez. No es un defecto de programación: es una limitación del planteamiento.",
      "En la práctica eso significa que el programa que va perfecto el primer año puede tardar en abrir un ticket el tercero. Y para entonces tienes todo tu catálogo y tu histórico dentro, que es justo cuando cambiar cuesta más."],
     None),
    ("Soporte de pago: el otro coste",
     ["La otra queja recurrente es que <em>el soporte técnico es de pago y poco eficaz</em>, con modalidades de pago por llamada o contrato anual de entre 60 y 80 euros.",
      "Esto convierte los 99 euros iniciales en una cifra menos redonda de lo que parece: si necesitas soporte dos veces al año durante cinco años, el coste real se acerca bastante al de una licencia que lo incluye. Con Caja 5, el soporte telefónico está incluido y te atiende una persona."],
     None),
    ("Qué mirar antes de elegir por precio",
     ["Elegir el programa más barato es una decisión legítima, sobre todo si el negocio arranca con poco margen. Lo que conviene es hacerlo con los ojos abiertos y comprobando tres cosas concretas.",
      "Y sobre todo: comprueba que puedas exportar tus datos. Si el programa barato no te deja sacar el catálogo, el precio de salida es infinito, porque cambiar significa teclear todo de nuevo."],
     ["<strong>Prueba con volumen real</strong>, no con veinte artículos: carga tu catálogo entero en la demo.",
      "<strong>Pregunta por el motor de base de datos</strong> y por su comportamiento con varios puestos.",
      "<strong>Confirma qué incluye el soporte</strong> y qué se cobra aparte.",
      "<strong>Comprueba que puedes exportar</strong> artículos, stock y clientes a Excel o CSV."]),
    ("VeriFactu: un motivo para revisar la decisión ahora",
     ["Nuestra información indica que en Solvermedia la adaptación normativa llegaba mediante actualizaciones de pago. Con VeriFactu obligatorio en enero de 2027 para sociedades y julio de 2027 para autónomos, eso significa un coste que hay que preguntar por escrito.",
      "Si de todas formas vas a tener que pagar una actualización, es el momento natural para replantear si el programa te sirve para los próximos cinco años. Pide a tu proveedor actual su declaración responsable y el precio de la adaptación antes de decidir nada."],
     None),
  ],
  faqs=[
    ("¿Cuánto cuesta Solvermedia?",
     "Su licencia de entrada son 99 euros en pago único, la más económica del grupo analizado. El soporte va aparte, con modalidades de pago por llamada o contrato anual de unos 60 a 80 euros. Confirma las condiciones vigentes con el fabricante."),
    ("¿Es verdad que se vuelve lento con el tiempo?",
     "Es la crítica que más se repite en foros y reseñas de usuarios: bases de datos de tipo fichero que se degradan al acumular años de tickets, especialmente con varios puestos. Es opinión de usuarios; la forma de comprobarlo tú es cargar tu catálogo completo en una demo y probar con volumen real."),
    ("¿Merece la pena elegir el TPV más barato?",
     "Puede merecerla si el negocio arranca justo de margen. Lo que conviene es comprobar tres cosas: cómo se comporta con tu volumen real, qué incluye el soporte y si puedes exportar tus datos. Sin exportación, el precio de salida del programa es infinito."),
    ("¿Solvermedia cumple con VeriFactu?",
     "Nuestra información indica que la adaptación normativa llegaba mediante actualizaciones de pago. Pídeles por escrito su declaración responsable y el precio de la adaptación: con la obligación llegando en 2027, es información que necesitas ahora."),
    ("¿Puedo pasar mis datos a Caja 5?",
     "Si puedes exportar artículos, stock y clientes a Excel o CSV, sí, y te acompañamos por teléfono durante el proceso. El histórico de tickets no suele migrarse; consulta con tu asesor tus obligaciones de conservación antes de dar de baja el sistema antiguo."),
    ("¿El soporte de Caja 5 se paga aparte?",
     "No. El soporte telefónico está incluido y te atiende una persona en horario comercial. Es una de las diferencias prácticas que más se notan frente a los modelos de soporte por llamada o contrato anual."),
  ],
  rel=[("Comparativas de TPV","/comparativas-tpv.asp"),
       ("Alternativa a SimplyGest","/simplygest-vs-caja5.asp"),
       ("Cómo cambiar de programa TPV","/migrar-de-tpv-cambiar-programa.asp"),
       ("Copias de seguridad del TPV","/copia-seguridad-tpv.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp"),
       ("Software TPV para tiendas de ropa","/negocio_moda.asp")]),

"stmoda-vs-caja5.asp": dict(
  nom="STMODA", crumb="STMODA vs Caja 5", icono="fa-building",
  title="Alternativa a STMODA para tiendas independientes",
  desc="STMODA (Status2) es una solución enterprise para cadenas, con implantación desde 2.000 €. Por qué no encaja en una tienda independiente y qué alternativa hay.",
  kw="alternativa a stmoda, stmoda status2 precio, stmoda opiniones, stmoda vs caja 5, tpv cadena moda",
  h1="Alternativa a STMODA: cuando no eres su cliente",
  sub="STMODA es excelente en lo suyo. Lo que pasa es que lo suyo son cadenas con decenas de tiendas y un departamento de sistemas detrás.",
  faq_titulo="Preguntas frecuentes sobre STMODA y sus alternativas",
  cta=("¿Tienes una o dos tiendas?",
       "Entonces probablemente no necesitas una implantación de semanas. Descarga la demo y monta tu catálogo esta misma tarde."),
  bloques=[
    ("Un producto enterprise en un mercado de tiendas pequeñas",
     ["STMODA, de Status2, es una solución de gama alta para marcas de moda consolidadas: matriz multinivel con cuatro variables, omnicanalidad real, sincronización en segundos e integración con ERP central. En su terreno es de lo mejor que hay en España.",
      "El problema no es el producto: es el encaje. Está diseñado para organizaciones con varias tiendas, personal de sistemas y presupuesto de implantación. Una tienda independiente que lo contrata acaba pagando por capacidades que no va a usar nunca."],
     None),
    ("El coste real no es la licencia: es la implantación",
     ["El precio es a medida, con implantaciones que parten de más de 2.000 euros y una suscripción mensual de mantenimiento elevada. Pero la cifra que más sorprende no es esa.",
      "Es el tiempo. Una implantación de este tipo requiere semanas de consultoría: análisis de procesos, parametrización, migración de datos, formación. Durante ese periodo alguien de tu negocio tiene que estar disponible, y en una tienda de dos personas ese alguien eres tú, que además estás atendiendo el mostrador.",
      "Ese coste de oportunidad no aparece en ningún presupuesto y es la razón principal por la que las soluciones enterprise fracasan en comercios pequeños, aunque el software sea magnífico."],
     None),
    ("Lo que dicen quienes lo han mirado",
     ["No hay valoración pública consolidada, algo habitual en productos enterprise que se venden por canal comercial y no por autoservicio. La observación que se repite entre comerciantes que lo han evaluado es directa: <em>inaccesible para tiendas independientes por su coste, con una implementación que requiere semanas de consultoría</em>.",
      "No es una crítica al producto. Es una constatación de a quién está dirigido, y viene bien tenerla clara antes de pedir presupuesto."],
     None),
    ("Qué necesita de verdad una tienda independiente",
     ["Si tienes una o dos tiendas, la lista de lo que necesitas es más corta de lo que la industria te quiere hacer creer: matriz de tallas y colores que funcione, control de stock fiable, etiquetas con código de barras, vales y devoluciones bien llevados, cierre de caja que cuadre y cumplimiento de VeriFactu.",
      "Eso lo cubre Caja 5 con una licencia de 333 euros que instalas tú mismo el mismo día, sin consultoría, sin parametrización y sin que nadie tenga que dedicar tres semanas al proyecto. Cuando crezcas hasta necesitar omnicanalidad real con marketplaces y ERP central, entonces STMODA será una conversación razonable."],
     ["<strong>Sin implantación:</strong> instalas y empiezas a cobrar el mismo día.",
      "<strong>Sin consultoría obligatoria</strong> ni parametrización previa.",
      "<strong>Soporte telefónico incluido</strong>, sin contrato premium.",
      "<strong>333 € una vez</strong>, frente a implantación más suscripción mensual."]),
    ("Cuándo sí deberías mirar STMODA",
     ["Para no ser injustos: si tienes ocho tiendas o más, vendes en varios países, necesitas que el stock de todas las tiendas y el e-commerce estén sincronizados al segundo y tienes alguien que pueda gestionar el proyecto, STMODA es una opción seria y nosotros no somos tu alternativa.",
      "El error sería contratarlo con dos tiendas pensando en las ocho que quizá tengas dentro de cinco años. Cuando llegues a ocho, el mercado será otro y la decisión se toma entonces."],
     None),
  ],
  faqs=[
    ("¿Cuánto cuesta STMODA?",
     "Es un precio a medida, con implantaciones que parten de más de 2.000 euros y una suscripción mensual de mantenimiento elevada. Para conocer tu cifra hay que pasar por su proceso comercial, que ya es un indicio del tipo de cliente al que se dirigen."),
    ("¿Por qué no encaja en una tienda pequeña?",
     "No por el software, que es bueno, sino por el encaje: exige semanas de implantación y consultoría durante las cuales alguien de tu negocio tiene que estar disponible. En una tienda de dos personas ese alguien eres tú, atendiendo el mostrador."),
    ("¿Qué necesita de verdad una tienda independiente?",
     "Matriz de tallas y colores, control de stock fiable, etiquetas, vales y devoluciones, cierre de caja y VeriFactu. Es una lista más corta de lo que la industria sugiere, y se cubre con una licencia que instalas el mismo día."),
    ("¿Y si tengo pensado crecer?",
     "Contratar una solución enterprise por las ocho tiendas que quizá tengas dentro de cinco años es un error frecuente. Cuando llegues a ese tamaño, el mercado habrá cambiado y la decisión se toma entonces, con el negocio ya generando caja."),
    ("¿Cuándo sí debería mirar STMODA?",
     "Con ocho tiendas o más, venta en varios países, necesidad de sincronización al segundo entre todos los canales y alguien capaz de gestionar el proyecto. En ese escenario es una opción seria y nosotros no somos tu alternativa."),
    ("¿Cuánto tardo en poner en marcha Caja 5?",
     "Cobrar, el mismo día: instalar y configurar los datos fiscales y la impresora lleva un rato. Lo que lleva tiempo es cargar el catálogo, y la recomendación es empezar por lo que más vendes e ir ampliando, no esperar a tenerlo todo."),
  ],
  rel=[("Comparativas de TPV","/comparativas-tpv.asp"),
       ("Alternativa a Gesio","/gesio-vs-caja5.asp"),
       ("Software TPV para tiendas de ropa","/negocio_moda.asp"),
       ("Caja 5 Nube","/caja5_nube.asp"),
       ("Matriz de tallas y colores","/matriz-tallas-y-colores.asp"),
       ("Preguntas frecuentes sobre TPV","/preguntas-frecuentes-tpv.asp")]),

"catinfog-vs-caja5.asp": dict(
  nom="Catinfog", crumb="Catinfog vs Caja 5", icono="fa-arrow-up-right-dots",
  title="Alternativa a Catinfog cuando tu tienda crece",
  desc="Catinfog monta un TPV en dos minutos por 29 €/mes con tienda online incluida. Dónde se queda corto al crecer: stock avanzado, multialmacén y web externa.",
  kw="alternativa a catinfog, catinfog precio, catinfog opiniones, catinfog vs caja 5, tpv nube tienda online",
  h1="Alternativa a Catinfog: el techo que aparece al crecer",
  sub="Catinfog hace muy bien una cosa difícil: que montes un TPV en dos minutos. El problema llega cuando tu tienda necesita más de lo que da.",
  faq_titulo="Preguntas frecuentes sobre Catinfog y sus alternativas",
  cta=("¿Se te ha quedado corto?",
       "Si ya notas que necesitas multialmacén o conectar tu web actual, prueba la demo con tu catálogo real y compara."),
  bloques=[
    ("Lo que hace bien, y lo hace de verdad",
     ["Catinfog resuelve un problema real: la barrera de entrada. Por 29 euros al mes te montas en dos minutos, sin instalar nada, y además incluye una tienda online integrada de serie, lo cual para quien empieza de cero y no tiene web es un argumento potente.",
      "Con 4,5 sobre 5 y más de 60 opiniones públicas, la valoración es buena y coherente con lo que ofrece: sencillez. Si estás empezando, no tienes web y quieres cobrar mañana, es una opción perfectamente sensata y no vamos a fingir lo contrario."],
     None),
    ("Los tres techos que aparecen al crecer",
     ["Las críticas de usuarios apuntan a un mismo sitio: <em>falta de funcionalidades avanzadas de stock e imposibilidad de conectar con tiendas online externas ya hechas</em>. Traducido a la práctica de una tienda que crece, son tres límites concretos.",
      "El primero es el multialmacén: cuando abres una segunda tienda o quieres separar sala de trastienda, necesitas stock por ubicación y traspasos con documento. El segundo es la gestión de proveedores: sin pedidos de compra ni control de coste por proveedor, compras a ciegas. El tercero, y el que más duele, es la web."],
     ["<strong>Sin control multialmacén:</strong> un solo stock, sin traspasos entre ubicaciones.",
      "<strong>Sin gestión de proveedores</strong> ni pedidos de compra ni órdenes automáticas.",
      "<strong>Sin generación automática de SKU</strong> para catálogos que crecen rápido.",
      "<strong>Sin conexión con Shopify, WooCommerce o Prestashop</strong> ya existentes."]),
    ("El problema de la tienda online integrada",
     ["Que la web venga incluida es la mayor virtud de Catinfog y, a la vez, su mayor atadura. Funciona porque es la misma base de datos, así que la sincronización es instantánea. Pero si ya tienes una tienda online hecha en WooCommerce o Prestashop, o si algún día quieres tener una con diseño propio, no puedes conectarla.",
      "Eso convierte una decisión de TPV en una decisión sobre tu e-commerce, que es un ámbito bastante mayor. Para quien no tiene web es un regalo; para quien la tiene o piensa tenerla a medida, es un límite estructural."],
     None),
    ("Nube o local, que no es una cuestión menor",
     ["Catinfog funciona en la nube y no ofrece modo sin conexión: si se cae internet, dejas de facturar. Es el mismo planteamiento que Caja 5 Nube, así que aquí no hay superioridad nuestra si comparas ese producto.",
      "La diferencia está en que Caja 5 también existe en versión para PC, con la base de datos en tu ordenador y funcionamiento sin conexión. Para una tienda de calle en una zona con conexión regular, esa opción existe y en Catinfog no."],
     None),
    ("Cuándo cambiar y cuándo quedarse",
     ["Quédate en Catinfog si estás empezando, tienes una sola tienda, la web integrada te sirve y valoras la sencillez por encima de todo. Es una herramienta honesta para ese caso.",
      "Plantéate cambiar cuando abras una segunda tienda, cuando necesites gestión seria de proveedores y compras, cuando quieras conectar una web propia o cuando el catálogo crezca hasta el punto de necesitar generación automática de referencias. Ahí es donde el techo se nota."],
     None),
  ],
  faqs=[
    ("¿Cuánto cuesta Catinfog?",
     "Su plan profesional publicado son 29 euros al mes, que a cinco años son 1.740 euros. Incluye una tienda online integrada, que para quien no tiene web es parte importante del valor. Caja 5 para PC son 333 euros en pago único."),
    ("¿Qué le falta a Catinfog frente a Caja 5?",
     "Control multialmacén con traspasos, gestión de proveedores y pedidos de compra, generación automática de referencias y conexión con tiendas online externas ya existentes. Son las limitaciones que señalan sus propios usuarios cuando el negocio crece."),
    ("¿Puedo conectar mi WooCommerce a Catinfog?",
     "Según la información que manejamos, no: su modelo se basa en la tienda online integrada propia. Si ya tienes una web hecha en WooCommerce o Prestashop, es probablemente el límite más importante a considerar. Confírmalo con ellos."),
    ("¿Catinfog funciona sin internet?",
     "No, funciona en la nube y sin modo offline: si se cae la línea, dejas de facturar. Caja 5 Nube tiene el mismo planteamiento; la diferencia es que Caja 5 también existe en versión para PC con la base de datos en local."),
    ("¿Cuándo debería plantearme cambiar?",
     "Cuando abras una segunda tienda, cuando necesites gestionar compras y proveedores en serio, cuando quieras conectar una web propia o cuando el catálogo crezca lo suficiente para necesitar referencias automáticas."),
    ("¿Puedo llevarme mis datos de Catinfog?",
     "Comprueba primero que permita exportar artículos, stock y clientes a Excel o CSV. Es la pregunta clave antes de cualquier migración, y conviene hacerla al contratar y no cuando quieres irte."),
  ],
  rel=[("Comparativas de TPV","/comparativas-tpv.asp"),
       ("Control de stock multialmacén","/control-de-stock-multialmacen.asp"),
       ("Vender online y en tienda con un solo stock","/vender-online-y-tienda-fisica-stock.asp"),
       ("Alternativa a Stockagile","/stockagile-vs-caja5.asp"),
       ("Caja 5 Nube","/caja5_nube.asp"),
       ("Proveedores y pedidos de compra","/gestion-de-proveedores-y-pedidos.asp")]),
}
