# -*- coding: utf-8 -*-
"""Comparativas con competidores, lote 2. Cada una con su propio argumento."""

OPERATIVA_VS2 = {

"glop-vs-caja5.asp": dict(
  nom="Glop", crumb="Glop vs Caja 5", icono="fa-file-invoice-dollar",
  title="Alternativa a Glop: el coste que llega después",
  desc="Glop parte de 120 € de licencia, pero el coste real está en la suscripción anual de 150 a 250 € y en las actualizaciones fiscales. Comparativa con Caja 5.",
  kw="alternativa a glop, glop tpv precio, glop opiniones, glop vs caja 5, glop mantenimiento anual",
  h1="Alternativa a Glop: mira el segundo año, no el primero",
  sub="Ciento veinte euros de licencia suena bien. Lo que decide si Glop es caro o barato es lo que pagas a partir del mes trece.",
  faq_titulo="Preguntas frecuentes sobre Glop y sus alternativas",
  cta=("Compara el coste a cinco años, no el de entrada",
       "Suma licencia más mantenimiento anual más actualizaciones fiscales. Esa cifra frente a 333 € una vez con soporte incluido."),
  bloques=[
    ("Glop viene de la hostelería, y eso se nota",
     ["Glop es una marca muy asentada en bares y restaurantes, con una red de distribuidores por toda España que es probablemente su mayor activo: tener un técnico en tu provincia que viene si algo falla tiene un valor real.",
      "Su versión para moda es una adaptación de ese producto. Funciona, tiene matriz de tallas y colores con dos variables y estabilidad en local, pero se nota que el ADN del programa es otro. Con 4,2 sobre 5 y más de 50 opiniones, la valoración es correcta sin ser sobresaliente."],
     None),
    ("La estructura de costes es la clave de esta comparativa",
     ["El precio de entrada de la versión Mini son 120 euros en pago único, más barato que Caja 5. Pero ese número solo cuenta parte de la historia.",
      "A partir de ahí aparece una suscripción anual de entre 150 y 250 euros para mantener soporte y actualizaciones. En cinco años eso son entre 750 y 1.250 euros adicionales, con lo que el total ronda entre 870 y 1.370 euros frente a los 333 de una licencia con soporte incluido.",
      "Y hay una tercera partida que es la que más molesta a sus usuarios: los cobros por actualizaciones cuando cambia la normativa fiscal. Con VeriFactu llegando en 2027, esa es exactamente la situación en la que conviene tener claro por escrito qué se cobra y qué no."],
     ["<strong>Licencia Mini:</strong> 120 € en pago único.",
      "<strong>Mantenimiento anual:</strong> entre 150 y 250 € para soporte y actualizaciones.",
      "<strong>Actualizaciones fiscales:</strong> según sus usuarios, se han cobrado aparte.",
      "<strong>A cinco años:</strong> entre 870 y 1.370 €, frente a 333 € de Caja 5."]),
    ("Lo que critican sus usuarios",
     ["Dos cosas se repiten en foros y reseñas: <em>interfaz de Windows anticuada</em> y <em>costes ocultos de soporte y cobros por actualizaciones de leyes fiscales</em>.",
      "La primera es discutible y depende de gustos: una interfaz sobria que va rápida puede ser preferible a una moderna que va lenta. La segunda es más objetiva y es la que conviene aclarar por escrito antes de comprar, preguntando exactamente qué entra en el mantenimiento y qué se factura aparte."],
     None),
    ("Dos variables frente a tres",
     ["En la matriz de variantes hay una diferencia técnica concreta: Glop Moda trabaja con dos variables, típicamente talla y color. Caja 5 admite una tercera variable libre que puedes renombrar según tu sector.",
      "Para una tienda de ropa generalista, dos variables bastan. Donde se nota es en calzado con horma o ancho, en ropa laboral con largo de pernera, en corsetería o en moda flamenca, donde la tercera dimensión existe de verdad y sin ella acabas creando artículos duplicados."],
     None),
    ("Dónde Glop es mejor opción que nosotros",
     ["Con honestidad: si ya tienes un distribuidor Glop de confianza en tu provincia que te atiende bien, ese es un argumento serio y difícil de igualar por teléfono. La cercanía tiene valor.",
      "Y si tu negocio combina hostelería con tienda, Glop tiene una integración natural entre ambos mundos que nosotros no ofrecemos: Caja 5 es un producto de comercio minorista, no de hostelería."],
     None),
  ],
  faqs=[
    ("¿Cuánto cuesta Glop en realidad?",
     "La licencia Mini parte de 120 euros en pago único, pero la cifra relevante es el mantenimiento anual de 150 a 250 euros para conservar soporte y actualizaciones. A cinco años el total ronda entre 870 y 1.370 euros. Confirma las condiciones vigentes con ellos."),
    ("¿Cobran por adaptar el programa a cambios fiscales?",
     "Es la crítica que más se repite entre sus usuarios en foros. Con VeriFactu llegando en 2027, conviene preguntarlo por escrito antes de comprar: qué entra en el mantenimiento y qué se factura aparte."),
    ("¿Cuántas variables admite la matriz de Glop?",
     "Dos, típicamente talla y color. Caja 5 admite una tercera variable libre, que se nota en calzado con horma, ropa laboral con largo de pernera, corsetería o moda flamenca, donde sin ella acabas duplicando artículos."),
    ("¿Glop es mejor para hostelería?",
     "Sí, es su origen y su terreno natural, con una red de distribuidores muy extendida. Caja 5 es un producto de comercio minorista: si tu negocio combina bar y tienda, Glop tiene una integración que nosotros no ofrecemos."),
    ("¿Merece la pena tener un distribuidor local?",
     "Es un argumento serio, sobre todo si te atiende bien. La contrapartida es que el soporte depende de esa relación concreta. Con Caja 5 el soporte telefónico es directo con el fabricante y está incluido en la licencia."),
    ("¿Puedo migrar de Glop a Caja 5?",
     "Si puedes exportar artículos con sus variantes, stock y clientes a Excel o CSV, sí. Compruébalo antes de decidir, y consulta con tu asesor tus obligaciones de conservación del histórico antes de dar de baja el sistema antiguo."),
  ],
  rel=[("Comparativas de TPV","/comparativas-tpv.asp"),
       ("Pago único frente a cuotas mensuales","/tpv-pago-unico-vs-cuotas-mensuales.asp"),
       ("Alternativa a SimplyGest","/simplygest-vs-caja5.asp"),
       ("Matriz de tallas y colores","/matriz-tallas-y-colores.asp"),
       ("Qué es VeriFactu","/que-es-verifactu.asp"),
       ("Software TPV para tiendas de ropa","/negocio_moda.asp")]),

"simplygest-vs-caja5.asp": dict(
  nom="SimplyGest", crumb="SimplyGest vs Caja 5", icono="fa-triangle-exclamation",
  title="Alternativa a SimplyGest Tallas y Colores",
  desc="SimplyGest cuesta 149 € en licencia perpetua. Qué dicen sus usuarios sobre estabilidad tras actualizaciones y soporte de pago, y qué comprobar antes de decidir.",
  kw="alternativa a simplygest, simplygest tallas y colores precio, simplygest opiniones, simplygest vs caja 5",
  h1="Alternativa a SimplyGest: la cuestión es la estabilidad",
  sub="La relación calidad-precio de entrada es buena y nadie lo discute. Lo que hay que mirar es qué pasa después de cada actualización y quién te atiende cuando algo falla.",
  faq_titulo="Preguntas frecuentes sobre SimplyGest y sus alternativas",
  cta=("Prueba antes de decidir",
       "Instala la demo, carga tu catálogo real y comprueba la estabilidad tú mismo. Es la única forma fiable de saberlo."),
  bloques=[
    ("Una licencia perpetua muy extendida",
     ["SimplyGest lleva años en el pequeño comercio español y su versión de Tallas y Colores es conocida en el sector. Ciento cuarenta y nueve euros en pago único por una licencia perpetua con matriz de variantes es una propuesta razonable, y con 4,0 sobre 5 y más de 40 opiniones la valoración es aceptable.",
      "Su planteamiento es el mismo que el nuestro en lo esencial: compras el programa y es tuyo, sin cuota obligatoria para seguir usándolo. Así que esta comparativa no va de modelo de negocio, como las de los SaaS, sino de dos productos que compiten en el mismo terreno."],
     None),
    ("Las dos críticas que hay que tomar en serio",
     ["En foros y reseñas se repiten dos cosas: <em>errores y cuelgues tras las actualizaciones, con problemas de estabilidad al integrar con tiendas online</em>, y <em>cobro por soporte</em>.",
      "La primera es la más importante porque afecta al trabajo diario. Un programa que se cuelga con la tienda llena no es un inconveniente: es dinero perdido y clientes que se van. Y una actualización que rompe algo que funcionaba es especialmente frustrante porque no la has pedido tú.",
      "No podemos ni queremos afirmar que esos problemas persistan hoy: son opiniones de usuarios y el software cambia. Lo que sí recomendamos es probarlo tú con tu catálogo completo antes de comprometerte, y preguntar a comercios de tu zona que lo usen."],
     None),
    ("Soporte: la diferencia práctica más clara",
     ["En SimplyGest el soporte va ligado a un contrato de mantenimiento de pago. En Caja 5 el soporte telefónico está incluido en la licencia y te atiende una persona.",
      "Esto parece un detalle hasta el día en que el programa no arranca a las nueve de la mañana con la tienda abriendo. Ahí la diferencia entre poder llamar y tener que abrir un ticket o contratar soporte de urgencia es enorme, y es el momento en que la gente cambia de proveedor."],
     None),
    ("Integración con tienda online: comprobar antes de contar con ello",
     ["SimplyGest ofrece sincronización con tiendas online a través de un módulo adicional, con sincronización por lotes manual o programada. Es un planteamiento distinto de la sincronización en tiempo real de los SaaS.",
      "Si vender online es parte importante de tu negocio, es el punto que más conviene probar antes de decidir, porque las críticas de usuarios apuntan precisamente ahí. Pide una demostración con tu propia web, no una genérica."],
     None),
    ("En qué se parecen y en qué no",
     ["Ambos son licencia perpetua con matriz de variantes, VeriFactu y sin cuota obligatoria. Las diferencias prácticas están en tres sitios concretos.",
      "Y una cosa que sí compartimos: los dos somos productos españoles pensados para el pequeño comercio, no adaptaciones de software internacional. Eso se nota en cómo están resueltas las cosas del día a día."],
     ["<strong>Soporte:</strong> incluido en Caja 5, contrato de pago en SimplyGest.",
      "<strong>Variables:</strong> tres en Caja 5, dos en SimplyGest.",
      "<strong>Precio de entrada:</strong> 149 € SimplyGest, 333 € Caja 5.",
      "<strong>Sincronización web:</strong> por lotes en SimplyGest, en tiempo real con Caja 5 Nube."]),
  ],
  faqs=[
    ("¿Cuánto cuesta SimplyGest Tallas y Colores?",
     "Ciento cuarenta y nueve euros en pago único por la licencia perpetua, más barato que Caja 5 en la entrada. El soporte va aparte mediante contrato de mantenimiento, que es donde se estrecha la diferencia. Confirma condiciones con el fabricante."),
    ("¿Es cierto que se cuelga tras las actualizaciones?",
     "Es la crítica que más se repite en reseñas de usuarios, junto con problemas al integrar con tiendas online. No podemos afirmar que persista hoy: el software cambia. Pruébalo con tu catálogo completo y pregunta a comercios de tu zona que lo usen."),
    ("¿El soporte de SimplyGest se paga?",
     "Va ligado a un contrato de mantenimiento de pago. En Caja 5 el soporte telefónico está incluido en la licencia. Es la diferencia que más se nota el día que el programa no arranca con la tienda abriendo."),
    ("¿Cuál sincroniza mejor con la tienda online?",
     "SimplyGest lo hace por lotes, manual o programada, mediante un módulo adicional. Caja 5 Nube sincroniza en tiempo real. Si vender online es importante para ti, pide una demostración con tu propia web antes de decidir."),
    ("¿Los dos cumplen con VeriFactu?",
     "Ambos figuran como adaptados en nuestra información. En cualquier caso, pide a cualquier fabricante su declaración responsable por escrito: es el documento que acredita el cumplimiento y es tu garantía."),
    ("¿Merece la pena pagar 333 en vez de 149?",
     "Depende de qué valores. Si el soporte incluido, la tercera variable de la matriz y la sincronización en tiempo real te aportan, la diferencia se recupera rápido. Si no los necesitas, 149 euros es menos dinero y es una decisión legítima."),
  ],
  rel=[("Comparativas de TPV","/comparativas-tpv.asp"),
       ("Alternativa a Glop","/glop-vs-caja5.asp"),
       ("Alternativa a Solvermedia","/solvermedia-vs-caja5.asp"),
       ("Matriz de tallas y colores","/matriz-tallas-y-colores.asp"),
       ("Vender online y en tienda con un solo stock","/vender-online-y-tienda-fisica-stock.asp"),
       ("Software TPV para zapaterías","/negocio_calzado.asp")]),

"gesio-vs-caja5.asp": dict(
  nom="Gesio", crumb="Gesio vs Caja 5", icono="fa-diagram-project",
  title="Alternativa a Gesio: sin consultoría ni implantación",
  desc="Gesio es un ERP potente con contabilidad y CRM por 29 €/caja al mes, pero exige implantación y consultoría. Cuándo compensa y cuándo es demasiado programa.",
  kw="alternativa a gesio, gesio tpv precio, gesio opiniones, gesio vs caja 5, tpv sin implantacion",
  h1="Alternativa a Gesio: cuando el ERP es demasiado programa",
  sub="Gesio hace muchas más cosas que Caja 5. La pregunta no es cuál tiene más funciones, sino cuántas de ellas vas a usar y cuánto cuesta aprenderlas.",
  faq_titulo="Preguntas frecuentes sobre Gesio y sus alternativas",
  cta=("¿Necesitas un ERP o un TPV?",
       "Si la respuesta es un TPV, instala la demo y estarás cobrando esta tarde. Sin consultoría y sin parametrización."),
  bloques=[
    ("Gesio es un ERP que además tiene TPV",
     ["Esta distinción explica toda la comparativa. Gesio no es un programa de caja al que le han añadido informes: es un sistema de gestión empresarial con contabilidad real, CRM de marketing, gestión de compras y módulo de e-commerce, que incluye un punto de venta.",
      "Con 4,4 sobre 5 y más de 70 opiniones, y una matriz de hasta cuatro variables, es de los productos más completos que hemos analizado. Si necesitas contabilidad integrada y gestionas varias tiendas con personal administrativo, es una opción muy seria."],
     None),
    ("El coste que no aparece en la web: implantación y aprendizaje",
     ["El precio publicado son 29 euros al mes por caja TPV, que es competitivo. Pero las críticas de usuarios señalan otra cosa: <em>curva de aprendizaje empinada y costes de implantación inicial y consultoría obligatorios</em>.",
      "Ese es el coste real de un ERP, y no es un defecto: es lo que cuesta poner en marcha un sistema que hace muchas cosas. Un programa que gestiona contabilidad, compras, CRM y TPV necesita parametrizarse, y alguien tiene que decidir cómo.",
      "El problema aparece cuando quien tiene que aprenderlo es un dependiente que además atiende el mostrador. En una tienda de dos personas, tres semanas de curva de aprendizaje es un coste enorme que no figura en ningún presupuesto."],
     None),
    ("Cuenta las funciones que vas a usar de verdad",
     ["Es un ejercicio incómodo y muy útil. Coge la lista de funciones de cualquier ERP y marca honestamente cuáles usarás cada semana. En una tienda independiente, la respuesta suele ser: cobrar, controlar stock, etiquetar, hacer pedidos y cerrar caja.",
      "Si tu lista es esa, un ERP es pagar y aprender mucho más de lo que necesitas. Si además de eso llevas contabilidad interna, gestionas campañas de marketing segmentadas y necesitas consolidar varias sociedades, entonces Gesio tiene sentido y Caja 5 se te queda corto."],
     ["<strong>Te encaja Gesio si:</strong> necesitas contabilidad real integrada en el mismo sistema.",
      "<strong>Te encaja Gesio si:</strong> gestionas varias tiendas con equipo administrativo.",
      "<strong>Te encaja Caja 5 si:</strong> quieres cobrar bien, controlar stock y no dedicar semanas a implantar.",
      "<strong>Te encaja Caja 5 si:</strong> tu asesoría ya lleva tu contabilidad y no necesitas duplicarla."]),
    ("Nube frente a local, otra vez",
     ["Gesio funciona en la nube sin modo offline. Si se cae internet, se para la caja. Para una tienda en un centro comercial con buena conexión es asumible; para una tienda de calle en una zona con línea regular, es un riesgo diario.",
      "Caja 5 para PC trabaja en local y sigue cobrando sin conexión. Si prefieres la nube, Caja 5 Nube existe, pero entonces compartes esa limitación y la comparativa vuelve al terreno de las funciones."],
     None),
    ("La comparación honesta de coste",
     ["Veintinueve euros al mes por caja son 1.740 euros a cinco años con un solo puesto, más la implantación inicial. Caja 5 para PC son 333 euros una vez.",
      "Pero si lo que necesitas es un ERP, comparar con un TPV no tiene sentido: estarías comparando un coche con una furgoneta. La pregunta correcta no es cuál es más barato, sino qué tipo de herramienta necesita tu negocio."],
     None),
  ],
  faqs=[
    ("¿Cuánto cuesta Gesio?",
     "Su tarifa publicada son 29 euros al mes por caja TPV, unos 1.740 euros a cinco años con un puesto. A eso hay que sumarle la implantación y la consultoría iniciales, que según sus usuarios son obligatorias y no siempre están claras al principio."),
    ("¿Por qué se dice que tiene curva de aprendizaje?",
     "Porque es un ERP, no solo un TPV: gestiona contabilidad, compras, CRM y e-commerce. Un sistema que hace tanto necesita parametrizarse y aprenderse. No es un defecto; es el coste natural de esa potencia."),
    ("¿Cuándo necesito un ERP y cuándo un TPV?",
     "Haz la lista de funciones que usarás cada semana. Si es cobrar, controlar stock, etiquetar, pedir y cerrar caja, necesitas un TPV. Si además llevas contabilidad interna y consolidas varias sociedades, necesitas un ERP."),
    ("¿Gesio funciona sin internet?",
     "No, funciona en la nube sin modo offline. Para una tienda de calle con conexión irregular es un riesgo diario. Caja 5 para PC trabaja en local y sigue cobrando aunque se caiga la línea."),
    ("¿Qué hace Gesio que no haga Caja 5?",
     "Contabilidad real integrada, CRM de marketing con envíos masivos, matriz de hasta cuatro variables y un módulo de e-commerce propio. Si necesitas eso, es mejor herramienta para ti y te lo decimos con claridad."),
    ("¿Cuánto tardo en poner en marcha Caja 5?",
     "Cobrar, el mismo día. No hay implantación ni consultoría obligatoria: instalas, configuras datos fiscales e impresora y empiezas. Cargar el catálogo lleva más, y la recomendación es hacerlo por fases mientras ya estás vendiendo."),
  ],
  rel=[("Comparativas de TPV","/comparativas-tpv.asp"),
       ("Alternativa a STMODA","/stmoda-vs-caja5.asp"),
       ("TPV que funciona sin internet","/tpv-sin-internet-modo-offline.asp"),
       ("Alternativa a OfiTienda","/ofitienda-vs-caja5.asp"),
       ("Funciones del TPV","/funciones-tpv.asp"),
       ("Caja 5 Nube","/caja5_nube.asp")]),

"noproblem-vs-caja5.asp": dict(
  nom="No Problem", crumb="No Problem vs Caja 5", icono="fa-gauge-high",
  title="Alternativa a No Problem Moda: velocidad con variantes",
  desc="No Problem Moda es completo en retail tradicional pero sus usuarios reportan lentitud con carga masiva de variantes. Qué comprobar si tu catálogo es grande.",
  kw="alternativa a no problem moda, no problem tpv precio, no problem opiniones, no problem vs caja 5",
  h1="Alternativa a No Problem Moda: prueba con tu catálogo entero",
  sub="Un programa puede ir perfecto con cien artículos y arrastrarse con cinco mil combinaciones de talla y color. Esa prueba hay que hacerla antes de comprar, no después.",
  faq_titulo="Preguntas frecuentes sobre No Problem y sus alternativas",
  cta=("Haz la prueba de carga",
       "Instala la demo y mete tu catálogo completo con todas sus tallas y colores. Es la prueba que de verdad distingue un programa de otro."),
  bloques=[
    ("Completo en funciones de retail tradicional",
     ["No Problem Moda es un producto veterano con una licencia de 350 euros y una cobertura funcional amplia: matriz de variantes, multialmacén, gestión de proveedores, órdenes automáticas, mermas y fidelización. Sobre el papel no le falta casi nada de lo que necesita una tienda de ropa.",
      "Su valoración pública es la más baja del grupo analizado, con 3,8 sobre 5 y algo más de 15 opiniones, aunque con esa muestra conviene no sacar conclusiones fuertes. Lo relevante no es la nota media sino el contenido de las críticas."],
     None),
    ("La crítica que más importa: el rendimiento con muchas variantes",
     ["Lo que reportan sus usuarios es concreto: <em>software lento en la carga masiva de variantes e interfaz anticuada</em>, además de <em>soporte postventa deficiente</em>.",
      "La primera es la seria, y merece explicarse. En moda, un catálogo de 400 modelos con seis tallas y cinco colores son 12.000 combinaciones. Un programa que gestiona bien 500 artículos puede comportarse muy distinto con 12.000 registros, sobre todo al cargar temporada completa o al hacer inventario.",
      "Es el tipo de problema que no se detecta en una demo comercial con veinte artículos de ejemplo y que aparece el día que cargas la temporada de verano entera."],
     None),
    ("Cómo hacer esa prueba tú mismo, con cualquier programa",
     ["Esta es la parte útil de esta página, y sirve para evaluar cualquier TPV de moda, incluido el nuestro. No te fíes de la demo con datos de ejemplo: exige probar con tu volumen.",
      "Si un programa no supera esta prueba, no lo va a superar dentro de dos años con más histórico encima. Y para entonces cambiar cuesta mucho más."],
     ["<strong>Carga tu catálogo real completo</strong>, con todas las combinaciones de talla y color.",
      "<strong>Cronometra la búsqueda</strong> de un artículo con el catálogo lleno.",
      "<strong>Simula una entrada de temporada</strong>: alta masiva de un albarán grande.",
      "<strong>Prueba un recuento de inventario</strong> con lector sobre ese volumen.",
      "<strong>Abre y cierra caja</strong> varias veces para ver los tiempos."]),
    ("Soporte postventa: pregunta antes de comprar",
     ["La otra queja recurrente es el soporte tras la venta. Es difícil de evaluar desde fuera y depende mucho del distribuidor concreto que te atienda, así que la recomendación práctica es sencilla: antes de comprar, pide referencias de comercios de tu zona que lo usen y llámalos.",
      "Con Caja 5 el soporte telefónico está incluido en la licencia y es directo con el fabricante, sin intermediarios. No es garantía de nada por sí solo, pero elimina la variable del distribuidor."],
     None),
    ("Dos variables frente a tres, otra vez",
     ["No Problem Moda trabaja con dos variables en la matriz, igual que Glop y SimplyGest. Caja 5 admite una tercera libre.",
      "Si vendes ropa generalista con talla y color, no notarás la diferencia. Si trabajas calzado con horma, ropa laboral con largo, corsetería con copa o moda flamenca, la tercera variable es lo que evita duplicar artículos y ensuciar el catálogo."],
     None),
  ],
  faqs=[
    ("¿Cuánto cuesta No Problem Moda?",
     "Su licencia única publicada son 350 euros, con contrato anual de mantenimiento de pago. Confirma las condiciones vigentes con el fabricante o su distribuidor."),
    ("¿Es cierto que va lento con muchas variantes?",
     "Es la crítica que más se repite entre sus usuarios: lentitud en la carga masiva de variantes. No podemos afirmar que persista hoy. Lo que sí puedes hacer es la prueba tú mismo cargando tu catálogo completo en una demo, que es la única forma fiable."),
    ("¿Cómo pruebo el rendimiento de un TPV antes de comprarlo?",
     "Carga tu catálogo real completo con todas las combinaciones, cronometra una búsqueda con el catálogo lleno, simula el alta de un albarán grande de temporada y prueba un recuento con lector. Si no supera eso, no lo superará dentro de dos años."),
    ("¿Qué pasa con el soporte postventa?",
     "Aparece entre las críticas de usuarios, aunque depende mucho del distribuidor concreto. Pide referencias de comercios de tu zona y llámalos antes de comprar. Con Caja 5 el soporte es directo con el fabricante y va incluido."),
    ("¿Cuántas variables admite su matriz?",
     "Dos, típicamente talla y color. Caja 5 admite una tercera libre, que importa en calzado con horma, ropa laboral con largo de pernera, corsetería o moda flamenca."),
    ("¿Puedo migrar de No Problem a Caja 5?",
     "Si permite exportar artículos con variantes, stock y clientes a Excel o CSV, sí. Compruébalo antes de decidir y consulta con tu asesor las obligaciones de conservación del histórico."),
  ],
  rel=[("Comparativas de TPV","/comparativas-tpv.asp"),
       ("Matriz de tallas y colores","/matriz-tallas-y-colores.asp"),
       ("Alternativa a SimplyGest","/simplygest-vs-caja5.asp"),
       ("Inventario con PDA o lector","/inventario-con-pda-lector-codigo-barras.asp"),
       ("Software TPV para tiendas de ropa","/negocio_moda.asp"),
       ("Cómo cambiar de programa TPV","/migrar-de-tpv-cambiar-programa.asp")]),

"ofitienda-vs-caja5.asp": dict(
  nom="OfiTienda", crumb="OfiTienda vs Caja 5", icono="fa-graduation-cap",
  title="Alternativa a OfiTienda: fácil para el dependiente",
  desc="OfiTienda es robusto para grandes inventarios y contabilidad, pero sus usuarios reportan una curva dura y nula adaptación a tablets. Comparativa con Caja 5.",
  kw="alternativa a ofitienda, ofitienda precio, ofitienda opiniones, ofitienda vs caja 5, tpv facil de usar",
  h1="Alternativa a OfiTienda: cuánto tarda en aprenderlo un dependiente nuevo",
  sub="La pregunta que casi nadie hace al comprar un TPV es cuánto tarda en manejarlo alguien que entra a trabajar en septiembre. En una tienda con rotación de personal, esa es la pregunta.",
  faq_titulo="Preguntas frecuentes sobre OfiTienda y sus alternativas",
  cta=("Pon a alguien nuevo a probarlo",
       "La mejor prueba de un TPV no la haces tú: la hace alguien que no lo ha visto nunca. Descarga la demo y ponle a cobrar veinte tickets."),
  bloques=[
    ("Robustez industrial para inventarios grandes",
     ["OfiTienda, de Ofimática, es un producto sólido con licencia en torno a los 500 euros, orientado a comercios con inventarios amplios y necesidades contables serias. Su fuerte es precisamente eso: aguanta volumen y tiene una gestión de fondo potente.",
      "Con 4,1 sobre 5 y más de 30 opiniones, la valoración es correcta. En su terreno, comercios medianos con almacén grande y contabilidad interna, es una opción defendible."],
     None),
    ("La curva de aprendizaje es un coste real, no una molestia",
     ["La crítica principal de sus usuarios es clara: <em>curva de aprendizaje muy dura para dependientes, altos costes iniciales y nula adaptación a tablets iPad o Android modernas</em>.",
      "Conviene traducir eso a dinero, porque se subestima siempre. En comercio hay rotación de personal, refuerzos de campaña y bajas. Cada vez que entra alguien nuevo, alguien con experiencia tiene que enseñarle, y ese tiempo sale de atender clientes.",
      "Si formar a una persona lleva tres días en lugar de tres horas, y contratas dos refuerzos cada Navidad, el coste anual de esa curva es perfectamente calculable y suele superar la diferencia de precio entre programas."],
     None),
    ("La prueba del dependiente nuevo",
     ["Hay una forma sencilla de evaluar esto y casi nadie la hace: no pruebes tú el programa. Ponlo delante de alguien que no lo haya visto nunca, dale un lector y pídele que haga veinte tickets, una devolución y un cierre de caja.",
      "Lo que tarde y las veces que pregunte es tu coste de formación real, multiplicado por cada persona que pase por tu tienda en los próximos cinco años. Es una prueba de media hora que dice más que cualquier folleto."],
     None),
    ("Tablets y movilidad",
     ["OfiTienda es un producto de Windows sin adaptación a tablets modernas, según sus usuarios. Caja 5 para PC también es Windows, así que en eso estamos igual y no vamos a presumir de lo que no tenemos.",
      "La diferencia es que existe Caja 5 Nube, que funciona desde el navegador en iPad o tablet Android. Si te interesa vender en la sala con un dispositivo móvil, o consultar desde casa, esa vía existe en nuestro caso."],
     None),
    ("Contabilidad: la pregunta que decide",
     ["El argumento más fuerte de OfiTienda es su integración contable. Y aquí conviene una reflexión honesta: la mayoría de comercios pequeños tienen una asesoría que les lleva la contabilidad.",
      "Si ese es tu caso, pagar por un módulo contable que no vas a usar es pagar de más, y además duplicas trabajo. Si en cambio llevas tú la contabilidad internamente y quieres todo en un sistema, OfiTienda tiene ahí una ventaja real sobre nosotros."],
     ["<strong>Te encaja OfiTienda si:</strong> llevas la contabilidad internamente y la quieres integrada.",
      "<strong>Te encaja OfiTienda si:</strong> tienes un almacén muy grande y necesidades de fondo potentes.",
      "<strong>Te encaja Caja 5 si:</strong> tu asesoría lleva la contabilidad y no quieres duplicarla.",
      "<strong>Te encaja Caja 5 si:</strong> tienes rotación de personal y necesitas que se aprenda rápido."]),
  ],
  faqs=[
    ("¿Cuánto cuesta OfiTienda?",
     "Su licencia ronda los 500 euros, con suscripción mensual o anual obligatoria para mantener el soporte. Es el precio de entrada más alto entre las licencias perpetuas del grupo analizado. Confirma las condiciones vigentes con el fabricante."),
    ("¿Es difícil de aprender?",
     "Es la crítica principal de sus usuarios: curva dura para dependientes. Conviene traducirlo a coste real: cada persona nueva que entre en tu tienda necesita formación, y ese tiempo sale de atender clientes. Con rotación de personal, se acumula."),
    ("¿Cómo evalúo si un TPV es fácil de usar?",
     "No lo pruebes tú. Ponlo delante de alguien que no lo haya visto nunca y pídele que haga veinte tickets, una devolución y un cierre. Lo que tarde es tu coste de formación real. Es una prueba de media hora que dice más que cualquier demostración comercial."),
    ("¿Funciona en tablet?",
     "Según sus usuarios, no tiene adaptación a tablets modernas. Caja 5 para PC tampoco, así que en eso estamos igual. La diferencia es que Caja 5 Nube funciona desde el navegador en iPad o Android."),
    ("¿Necesito contabilidad integrada en el TPV?",
     "Solo si la llevas tú internamente. Si tienes una asesoría que se ocupa, pagar por un módulo contable es pagar de más y además duplica trabajo. Si la llevas tú, OfiTienda tiene ahí una ventaja real sobre Caja 5."),
    ("¿Qué pasa si tengo un inventario muy grande?",
     "Es el terreno donde OfiTienda es fuerte. Con Caja 5 conviene que hagas la prueba de carga con tu catálogo completo antes de decidir, igual que recomendamos hacer con cualquier programa, incluido el nuestro."),
  ],
  rel=[("Comparativas de TPV","/comparativas-tpv.asp"),
       ("Alternativa a Gesio","/gesio-vs-caja5.asp"),
       ("Caja 5 Nube","/caja5_nube.asp"),
       ("TPV táctil o con teclado","/tpv-tactil-o-teclado-raton.asp"),
       ("Cómo controlar la caja con varios empleados","/controlar-empleados-tpv.asp"),
       ("Software TPV por sector","/tpv_negocios.asp")]),
}
