/**
 * Données FICTIVES de l'itération 1.
 *
 * Le jeu couvre volontairement toutes les combinaisons de critères (les 3
 * spécialisations, les 2 modes, les 2 sexes, une large plage de prix, 7
 * villes, les 4 plages de dispo) pour que chaque filtre de l'annuaire ait un
 * effet visible en démo.
 *
 * Les composants n'importent JAMAIS ce fichier directement : ils passent par
 * la façade src/lib/coaches.ts, qui basculera sur Supabase (RPC
 * search_coaches) sans changement d'API. Les avatars pointent vers pravatar
 * (placeholder) ; hors ligne, l'<Avatar> retombe sur les initiales.
 */

import type { Coach } from "./types";

export const mockCoaches: Coach[] = [
  {
    id: "c1",
    slug: "camille-roussel",
    fullName: "Camille Roussel",
    avatarUrl: "https://i.pravatar.cc/300?img=47",
    gender: "female",
    headline: "Coach force & powerlifting — du débutant au compétiteur",
    bio: "Ancienne compétitrice de force athlétique (-63 kg), j'accompagne depuis 8 ans des pratiquants de tous niveaux sur le squat, le développé couché et le soulevé de terre. Mon objectif : que chaque séance vous rapproche d'une barre plus lourde, sans blessure.",
    methodology:
      "Programmation à faible volume et haute intensité : des séances courtes et denses pour optimiser le temps passé en salle. La technique passe avant la charge, toujours.",
    specializations: ["strength"],
    modes: ["online", "in_person"],
    city: "Lyon",
    pricePerSession: 60,
    priceMonthly: 180,
    rating: 4.9,
    reviewCount: 41,
    yearsExperience: 8,
    certifications: ["BPJEPS AF", "Formation FFForce"],
    availability: ["evening", "weekend"],
    verified: true,
  },
  {
    id: "c2",
    slug: "karim-benali",
    fullName: "Karim Benali",
    avatarUrl: "https://i.pravatar.cc/300?img=12",
    gender: "male",
    headline: "Préparateur bodybuilding — esthétique et prise de masse",
    bio: "Coach spécialisé en hypertrophie et préparation aux compétitions men's physique. Je suis mes athlètes de la sèche au jour J, nutrition comprise.",
    methodology:
      "Volume progressif piloté par le carnet d'entraînement et les sensations. Chaque bloc de 4 semaines est ajusté sur vos mesures réelles, pas sur un plan générique.",
    specializations: ["bodybuilding"],
    modes: ["in_person"],
    city: "Paris",
    pricePerSession: 75,
    priceMonthly: 250,
    rating: 4.7,
    reviewCount: 63,
    yearsExperience: 11,
    certifications: ["BPJEPS AF", "Diplôme nutrition sportive"],
    availability: ["morning", "evening"],
    verified: true,
  },
  {
    id: "c3",
    slug: "lea-fontaine",
    fullName: "Léa Fontaine",
    avatarUrl: "https://i.pravatar.cc/300?img=45",
    gender: "female",
    headline: "Entraînement hybride — force + endurance sans compromis",
    bio: "Triathlète et haltérophile, je construis des plans qui font coexister la barre et le cardio. Idéal si vous refusez de choisir entre soulever lourd et courir vite.",
    methodology:
      "Périodisation par blocs avec gestion fine des interférences force/endurance : on priorise une qualité à la fois, on entretient le reste.",
    specializations: ["strength", "hybrid"],
    modes: ["online"],
    city: "Bordeaux",
    pricePerSession: 50,
    priceMonthly: 150,
    rating: 4.8,
    reviewCount: 27,
    yearsExperience: 6,
    certifications: ["CQP Instructeur fitness", "Licence STAPS"],
    availability: ["midday", "weekend"],
    verified: true,
  },
  {
    id: "c4",
    slug: "thomas-leroy",
    fullName: "Thomas Leroy",
    avatarUrl: "https://i.pravatar.cc/300?img=14",
    gender: "male",
    headline: "Powerlifting en ligne — programmation sur mesure",
    bio: "Coach 100 % à distance pour pratiquants intermédiaires et avancés. Analyse vidéo de vos barres chaque semaine, ajustements sous 24 h.",
    methodology:
      "Approche RPE : l'intensité se pilote à l'effort perçu plutôt qu'au pourcentage fixe, pour coller à votre forme du jour.",
    specializations: ["strength"],
    modes: ["online"],
    city: "Nantes",
    pricePerSession: 40,
    priceMonthly: 120,
    rating: 4.6,
    reviewCount: 52,
    yearsExperience: 5,
    certifications: ["Formation FFForce"],
    availability: ["evening"],
    verified: false,
  },
  {
    id: "c5",
    slug: "ines-marchal",
    fullName: "Inès Marchal",
    avatarUrl: "https://i.pravatar.cc/300?img=26",
    gender: "female",
    headline: "Bodybuilding féminin — bikini & wellness",
    bio: "Préparatrice spécialisée dans les catégories bikini et wellness. J'insiste autant sur la construction musculaire que sur une relation saine à l'alimentation.",
    methodology:
      "Hypertrophie en double progression (charges puis répétitions), avec des phases de maintien planifiées pour durer sur la saison.",
    specializations: ["bodybuilding"],
    modes: ["online", "in_person"],
    city: "Marseille",
    pricePerSession: 55,
    priceMonthly: 170,
    rating: 4.8,
    reviewCount: 34,
    yearsExperience: 7,
    certifications: ["BPJEPS AF"],
    availability: ["morning", "midday"],
    verified: true,
  },
  {
    id: "c6",
    slug: "hugo-dasilva",
    fullName: "Hugo Da Silva",
    avatarUrl: "https://i.pravatar.cc/300?img=8",
    gender: "male",
    headline: "Hybride & préparation physique généraliste",
    bio: "Ancien rugbyman, je prépare des profils qui veulent être forts, rapides et endurants à la fois — du sportif amateur au pompier en préparation de concours.",
    methodology:
      "Entraînement concourant organisé par dominantes hebdomadaires ; beaucoup de travail unilatéral et de gainage sous fatigue.",
    specializations: ["hybrid"],
    modes: ["in_person"],
    city: "Toulouse",
    pricePerSession: 45,
    rating: 4.5,
    reviewCount: 19,
    yearsExperience: 4,
    certifications: ["Licence STAPS"],
    availability: ["morning", "evening", "weekend"],
    verified: false,
  },
  {
    id: "c7",
    slug: "sofia-almeida",
    fullName: "Sofia Almeida",
    avatarUrl: "https://i.pravatar.cc/300?img=20",
    gender: "female",
    headline: "Force pour débutantes — bases solides, zéro intimidation",
    bio: "J'apprends aux femmes qui débutent à squatter, tirer et pousser avec confiance. Petit groupe ou individuel, dans une salle bienveillante.",
    methodology:
      "Progression linéaire simple sur les mouvements de base : peu d'exercices, beaucoup de maîtrise, des charges qui montent chaque semaine.",
    specializations: ["strength"],
    modes: ["in_person"],
    city: "Paris",
    pricePerSession: 35,
    rating: 4.9,
    reviewCount: 48,
    yearsExperience: 3,
    certifications: ["CQP Instructeur fitness"],
    availability: ["midday", "evening"],
    verified: true,
  },
  {
    id: "c8",
    slug: "maxime-girard",
    fullName: "Maxime Girard",
    avatarUrl: "https://i.pravatar.cc/300?img=13",
    gender: "male",
    headline: "Coach premium bodybuilding & recomposition corporelle",
    bio: "15 ans de plateau, des dizaines d'athlètes montés sur scène. Suivi ultra-individualisé : entraînement, nutrition, récupération, gestion du stress.",
    methodology:
      "Chaque exercice a une raison d'être : sélection selon vos leviers et votre historique de blessures, exécution filmée et corrigée à chaque séance.",
    specializations: ["bodybuilding", "strength"],
    modes: ["online", "in_person"],
    city: "Lyon",
    pricePerSession: 120,
    priceMonthly: 400,
    rating: 5.0,
    reviewCount: 88,
    yearsExperience: 15,
    certifications: ["BPJEPS AF", "Certification PICP", "Diplôme nutrition sportive"],
    availability: ["morning", "midday", "evening"],
    verified: true,
  },
  {
    id: "c9",
    slug: "elise-bernard",
    fullName: "Élise Bernard",
    avatarUrl: "https://i.pravatar.cc/300?img=32",
    gender: "female",
    headline: "Hybride à distance — pour les emplois du temps impossibles",
    bio: "Coach en ligne pour actifs surbookés : des plans force + cardio qui tiennent en 3 séances de 45 minutes par semaine, suivis via une app dédiée.",
    methodology:
      "Minimum efficace : on identifie les 20 % d'exercices qui produisent 80 % de vos résultats et on s'y tient. La régularité bat l'héroïsme.",
    specializations: ["hybrid"],
    modes: ["online"],
    city: "Lille",
    pricePerSession: 38,
    priceMonthly: 110,
    rating: 4.4,
    reviewCount: 22,
    yearsExperience: 4,
    certifications: ["CQP Instructeur fitness"],
    availability: ["morning", "weekend"],
    verified: false,
  },
  {
    id: "c10",
    slug: "antoine-morel",
    fullName: "Antoine Morel",
    avatarUrl: "https://i.pravatar.cc/300?img=17",
    gender: "male",
    headline: "Haltérophilie & force olympique",
    bio: "Entraîneur d'haltérophilie en club depuis 10 ans. Arraché, épaulé-jeté et tout le travail de force qui les soutient — technique d'abord.",
    methodology:
      "Cycles de 6 semaines construits autour des mouvements olympiques complets, avec dérivés de force en second plan.",
    specializations: ["strength"],
    modes: ["in_person"],
    city: "Marseille",
    pricePerSession: 65,
    rating: 4.7,
    reviewCount: 31,
    yearsExperience: 10,
    certifications: ["BPJEPS AF", "Brevet fédéral haltérophilie"],
    availability: ["evening", "weekend"],
    verified: true,
  },
  {
    id: "c11",
    slug: "nadia-cherif",
    fullName: "Nadia Cherif",
    avatarUrl: "https://i.pravatar.cc/300?img=49",
    gender: "female",
    headline: "Bodybuilding & remise en forme après 40 ans",
    bio: "Spécialiste de l'hypertrophie chez les pratiquants matures : construire du muscle en respectant les articulations et l'agenda familial.",
    methodology:
      "Tempo contrôlé et amplitudes complètes plutôt que charges maximales ; la récupération est programmée au même titre que les séances.",
    specializations: ["bodybuilding", "hybrid"],
    modes: ["online", "in_person"],
    city: "Toulouse",
    pricePerSession: 48,
    priceMonthly: 140,
    rating: 4.6,
    reviewCount: 26,
    yearsExperience: 9,
    certifications: ["BPJEPS AF"],
    availability: ["morning", "midday"],
    verified: true,
  },
  {
    id: "c12",
    slug: "romain-petit",
    fullName: "Romain Petit",
    avatarUrl: "https://i.pravatar.cc/300?img=11",
    gender: "male",
    headline: "Hybride compétition — HYROX et courses à obstacles",
    bio: "Je prépare spécifiquement aux formats HYROX, Spartan et déca-fit : du seuil, de la force utile et beaucoup de transitions sous fatigue.",
    methodology:
      "Blocs spécifiques calés sur votre calendrier de course, avec simulations chronométrées toutes les 3 semaines pour valider la progression.",
    specializations: ["hybrid", "strength"],
    modes: ["online", "in_person"],
    city: "Lille",
    pricePerSession: 58,
    priceMonthly: 175,
    rating: 4.8,
    reviewCount: 37,
    yearsExperience: 7,
    certifications: ["Licence STAPS", "Juge HYROX"],
    availability: ["evening", "weekend"],
    verified: true,
  },
];
