# -*- coding: utf-8 -*-
"""Paginas nucleares de carrito5.com.

Las tres paginas existentes enlazan a estas y hoy devuelven 404. Cada una se
escribe entera: el filtro de similitud rechaza lo que salga de una plantilla.

Tono segun el dossier del cliente: sin alarmismo, sin cliches de IA, empatia con
la friccion real del comerciante y CTA de baja friccion por WhatsApp.
"""

NUCLEO = {

# ============================================================ pagina de dinero
"descargar-tpv-gratis.html": dict(
  title="Descargar TPV Gratis para Windows | Carrito5",
  desc="Descarga Carrito5 TPV gratis para Windows: instalación en minutos, sin tarjeta y sin caducidad. Qué incluye el plan gratuito y dónde están sus límites.",
  kw="descargar tpv gratis, tpv gratis, software tpv gratis, descargar programa caja registradora gratis, tpv gratis windows, programa tpv gratuito",
  h1="Descargar TPV gratis para Windows",
  sub="Instalación directa, sin tarjeta y sin fecha de caducidad. Aquí te contamos también dónde están los límites del plan gratuito, que es lo que nadie explica.",
  badge="DESCARGA DIRECTA",
  crumb="Descargar gratis",
  trail=[("Inicio", "index.html"), ("Descargar gratis", "descargar-tpv-gratis.html")],
  aside=("Descarga y prueba hoy",
         "El instalador ocupa poco y no pide datos de pago. Si algo no arranca, escríbenos por WhatsApp y lo miramos contigo."),
  cta=("Empieza a cobrar esta misma tarde",
       "Descarga, instala y da de alta tus primeros artículos. Si te atascas, te ayudamos por WhatsApp sin compromiso."),
  bloques=[
    ("Qué necesitas para instalarlo",
     ["Carrito5 es una aplicación de escritorio para Windows. Funciona en Windows 10 y 11, y también en equipos con Windows 8 y 7 que sigan operativos en muchas tiendas.",
      "No necesitas un ordenador nuevo. La mayoría de comercios lo instalan en el equipo que ya tienen en el mostrador, y el requisito que más se nota no es el procesador sino el disco: con un SSD la caja va notablemente más ágil.",
      "Y no hace falta conexión permanente. Los datos se guardan en tu propio ordenador, así que si se cae internet sigues cobrando con normalidad."],
     ["<strong>Windows 7, 8, 10 u 11.</strong> No hay versión para Mac ni para tablet Android.",
      "<strong>Instalador directo.</strong> Descargas, ejecutas y sigue el asistente.",
      "<strong>Sin tarjeta ni datos de pago</strong> para empezar.",
      "<strong>Impresora de tickets opcional:</strong> puedes empezar imprimiendo en la que ya tengas."]),
    ("Qué incluye el plan gratuito y dónde está el límite",
     ["Preferimos decirlo claro en lugar de que lo descubras en el mes tres. El plan Inicio de Carrito5 está pensado para autónomos y comercios pequeños, con un límite de <strong>1.000 artículos en catálogo</strong>.",
      "Dentro de ese límite tienes el programa completo para lo esencial: catálogo de artículos, control de stock, cobro, emisión de tickets y cierre de caja. No es una versión mutilada que te obliga a pagar para hacer lo básico.",
      "Si tu catálogo pasa de 1.000 artículos, la capacidad se amplía adquiriendo la licencia comercial. Y si tu volumen es alto y prefieres comprar el programa una vez en lugar de pagar mensualidad, la opción es Caja 5, de la misma casa, con licencia en propiedad."],
     None),
    ("Por qué es gratis y qué pedimos a cambio",
     ["Cuando un software es gratuito conviene preguntar por dónde cobra, y tienes derecho a saberlo antes de montar tu tienda encima.",
      "En nuestro caso el modelo es sencillo: gratuito hasta 1.000 artículos, y a partir de ahí licencia comercial. No cobramos comisión por cada venta, no te obligamos a comprar nuestro hardware y no vendemos los datos de tu negocio. Cobras con el datáfono que tengas contratado con tu banco.",
      "Ese es el modelo entero. Si en algún momento decides irte, puedes exportar tu catálogo y tus clientes: es la pregunta que casi nadie hace al instalar un programa gratuito y la que más cara sale después."],
     ["<strong>Sin comisión por venta.</strong> Lo que cobres con tarjeta no pasa por nosotros.",
      "<strong>Sin hardware obligatorio.</strong> Aprovechas el ordenador y la impresora que tengas.",
      "<strong>Tus datos son tuyos</strong> y viven en tu ordenador, no en un servidor ajeno.",
      "<strong>Sin caducidad.</strong> No es una prueba de 30 días que se apaga."]),
    ("Los primeros treinta minutos, en orden",
     ["El error más común al empezar con cualquier TPV es intentar meter todo el catálogo antes de cobrar la primera venta. Nunca se termina y a las tres semanas se vuelve a la caja de siempre.",
      "Haz al revés: da de alta lo que más vendes, ponte a cobrar, y ve añadiendo el resto según entra mercancía. En dos meses tienes el catálogo completo y además limpio, porque solo has metido lo que se mueve de verdad."],
     ["Instala y configura los datos fiscales de tu negocio.",
      "Selecciona la impresora de tickets y saca uno de prueba.",
      "Da de alta las veinte o treinta referencias que más vendes.",
      "Haz una venta real y cierra caja al terminar el día.",
      "A partir de ahí, añade artículos según llegan los albaranes."]),
  ],
  faqs=[
    ("¿Carrito5 es gratis de verdad o es una prueba de 30 días?",
     "El plan Inicio es gratuito de forma indefinida hasta 1.000 artículos en catálogo. No caduca ni se apaga pasado un plazo. Si tu catálogo crece por encima, la capacidad se amplía con la licencia comercial."),
    ("¿Necesito poner una tarjeta para descargarlo?",
     "No. La descarga y el uso del plan gratuito no piden datos de pago."),
    ("¿Funciona en Mac o en tablet?",
     "No. Carrito5 es una aplicación de Windows: 7, 8, 10 y 11. Si necesitas trabajar desde iPad o Android, la vía es un TPV en navegador, y ahí te podemos orientar aunque no sea este producto."),
    ("¿Qué pasa si mi catálogo pasa de 1.000 artículos?",
     "La capacidad se amplía adquiriendo la licencia comercial. Y si prefieres un producto con licencia en propiedad y gestión más amplia, Caja 5 es de la misma casa."),
    ("¿Necesito internet para cobrar?",
     "No. Los datos están en tu ordenador, así que si se cae la línea sigues cobrando, imprimiendo tickets y cerrando caja. Es una de las razones por las que muchos comercios de calle prefieren un programa de escritorio."),
    ("¿Cobráis comisión por cada venta con tarjeta?",
     "No. Cobras con el datáfono que hayas contratado con tu banco, a la comisión que tengas negociada con él. Nosotros no participamos en esa operación ni nos llevamos un porcentaje."),
    ("¿Puedo sacar mis datos si algún día quiero cambiar de programa?",
     "Sí, puedes exportar el catálogo y la ficha de clientes. Es la pregunta que conviene hacer al instalar cualquier programa gratuito, y la que casi nadie hace hasta que quiere irse."),
    ("¿Sirve para cumplir con VeriFactu?",
     "Carrito5 está adaptado a VeriFactu. Recuerda que la obligación llega el 1 de enero de 2027 para sociedades y el 1 de julio de 2027 para autónomos, así que durante 2026 la adaptación es voluntaria. Confirma tu fecha con tu asesor."),
    ("¿Hay soporte si me atasco instalando?",
     "Sí, por WhatsApp al 611 500 052 y por teléfono, con atención en España. Para las dudas de instalación y de primeros pasos es donde más se resuelve."),
  ],
  satelites=[("Qué es VeriFactu y cuándo te obliga", "verifactu-gratis.html", "Fechas de 2027 y qué necesitas"),
             ("TPV para tiendas de ropa", "tpv-tienda-ropa.html", "Matriz de tallas y colores"),
             ("TPV para zapaterías", "tpv-zapateria.html", "Números EU, UK y control de pares"),
             ("Todos los sectores", "sectores-y-negocios.html", "Elige el tuyo"),
             ("TPV para el comercio local", "software-tpv-comercio-local.html", "Por qué una tienda de barrio"),
             ("Tallas y colores", "tallas-y-colores.html", "Cómo funciona la matriz")]),

# ============================================================ hub de sectores
"sectores-y-negocios.html": dict(
  title="TPV Gratis por Sector: elige tu tipo de negocio | Carrito5",
  desc="Software TPV gratuito adaptado a cada sector: ropa, zapatería, ferretería, papelería, joyería, juguetería, herboristería, droguería y más. Descarga directa.",
  kw="tpv por sector, tpv gratis comercio, software tpv tienda, programa tpv sectores, tpv especializado negocio",
  h1="TPV gratis, según lo que vendas",
  sub="Un TPV de ropa y uno de ferretería no se parecen en nada. Estas páginas cuentan qué cambia en cada oficio y qué te va a hacer falta de verdad.",
  badge="SECTORES Y NEGOCIOS",
  crumb="Sectores",
  trail=[("Inicio", "index.html"), ("Sectores", "sectores-y-negocios.html")],
  aside=("Empieza por tu sector",
         "Cada página cuenta lo específico de ese oficio: qué se cuenta en el inventario, qué variantes maneja y qué se le pide a la caja."),
  cta=("¿No ves tu sector en la lista?",
       "Escríbenos por WhatsApp y te decimos si Carrito5 te encaja. Si vemos que no, te lo diremos igual."),
  bloques=[
    ("Por qué el sector cambia el programa que necesitas",
     ["La diferencia no está en el logotipo ni en los colores de la pantalla: está en qué se cuenta y cómo se busca.",
      "Una tienda de ropa cuenta combinaciones de talla y color, y necesita una matriz para no dar de alta treinta artículos por modelo. Una ferretería cuenta miles de referencias, muchas sin código de barras, y buena parte se venden sueltas o por metro. Una frutería no cuenta stock casi: lo que controla es la merma diaria y un precio que cambia cada semana.",
      "Por eso las páginas de abajo no son la misma con el nombre cambiado. Cada una cuenta lo que de verdad pasa en ese mostrador."],
     None),
    ("Lo que sí es común a todos",
     ["Al margen del sector, hay una base que cualquier comercio necesita y que Carrito5 cubre en su plan gratuito: cobrar rápido, emitir el ticket, saber qué queda en stock y cuadrar la caja al cerrar.",
      "Y una obligación que llega para todos: a partir de 2027 el programa con el que factures tiene que cumplir VeriFactu. Empezar ya con uno adaptado te ahorra cambiar dos veces."],
     ["Catálogo con familias y búsqueda rápida.",
      "Control de stock y avisos de mínimos.",
      "Emisión de tickets y cierre de caja diario.",
      "Ficha de clientes para devoluciones y fidelización.",
      "Adaptado a VeriFactu."]),
  ],
  faqs=[
    ("¿Cambia el programa según el sector o es el mismo?",
     "Es el mismo programa, configurado de forma distinta. Lo que cambia es qué variantes usas, cómo organizas las familias y qué funciones te hacen falta a diario. Las páginas por sector explican esa configuración."),
    ("Mi negocio es mixto, vendo cosas de dos sectores.",
     "Es más común de lo que parece: papelería que vende regalo, ferretería que vende menaje. Se lleva con familias distintas dentro del mismo catálogo. Mira la página del sector que más peso tenga en tu facturación."),
    ("¿Sirve para hostelería, bares o restaurantes?",
     "Carrito5 está pensado para comercio minorista. La hostelería tiene necesidades propias, como comandas y mesas, que son otro tipo de producto. Si tu negocio es mixto, escríbenos y lo miramos."),
    ("¿El plan gratuito vale para cualquier sector?",
     "Sí, el límite es de tamaño de catálogo (1.000 artículos), no de sector. Lo que cambia según el oficio es lo rápido que llegas a ese número: una ferretería lo pasa enseguida y una tienda de muebles puede no alcanzarlo nunca."),
    ("¿Puedo probarlo antes de decidir?",
     "Es gratis: descargas, instalas y lo pruebas con tus propios artículos. Media hora con tu catálogo real te dirá más que cualquier folleto."),
    ("¿Y si mi sector no está en la lista?",
     "Escríbenos por WhatsApp al 611 500 052 y te decimos si te encaja. Si vemos que necesitas otra cosa, te lo diremos: no vendemos lo que no sirve."),
  ],
  satelites=[("Tiendas de ropa y boutiques", "tpv-tienda-ropa.html", "Matriz de tallas y colores"),
             ("Zapaterías y calzado", "tpv-zapateria.html", "Números EU/UK y pares"),
             ("Ferreterías", "tpv-ferreteria.html", "Miles de referencias y venta suelta"),
             ("Papelerías", "tpv-papeleria.html", "Campaña escolar y copistería"),
             ("Joyerías y relojerías", "tpv-joyeria-relojeria.html", "Piezas de valor y etiquetas pequeñas"),
             ("Jugueterías y regalos", "tpv-jugueteria-regalos.html", "Campaña y reservas"),
             ("Herboristerías", "tpv-herboristeria.html", "Lotes y caducidades"),
             ("Droguerías", "tpv-drogueria.html", "Granel y familias amplias"),
             ("Boutiques", "tpv-boutique.html", "Ticket alto y trato personal"),
             ("Complementos", "tpv-complementos.html", "Mucha referencia de bajo importe"),
             ("Tiendas de deportes", "tpv-tienda-deportes.html", "Tallas técnicas y temporada"),
             ("Tiendas de muebles", "tpv-tienda-muebles.html", "Pedidos a medida y entregas"),
             ("Electrónica e informática", "tpv-electronica-informaticas.html", "Números de serie y garantías"),
             ("Supermercados de barrio", "tpv-supermercado-barrio.html", "Peso, IVA y varias cajas"),
             ("Sexshop", "tpv-sexshop.html", "Discreción en ticket y catálogo"),
             ("Comercio local en general", "software-tpv-comercio-local.html", "Si no encaja en ninguno")]),

# ================================================== comercio local (posicionamiento)
"software-tpv-comercio-local.html": dict(
  title="Software TPV para Comercio Local y de Barrio | Carrito5",
  desc="TPV gratuito pensado para la tienda de barrio: sin cuotas obligatorias, sin comisión por venta, funciona sin internet y con soporte por WhatsApp en español.",
  kw="software tpv comercio local, tpv tienda de barrio, programa caja tienda pequeña, tpv autonomo comercio, tpv pequeño comercio gratis",
  h1="Un TPV pensado para la tienda de barrio",
  sub="La mayoría del software de caja está diseñado para cadenas y luego se recorta para el comercio pequeño. Este va al revés.",
  badge="COMERCIO LOCAL",
  crumb="Comercio local",
  trail=[("Inicio", "index.html"), ("Comercio local", "software-tpv-comercio-local.html")],
  aside=("Sin compromiso y sin tarjeta",
         "Descarga, prueba con tus artículos y decide. Si tienes dudas, te contestamos por WhatsApp una persona, no un bot."),
  cta=("Pruébalo con tu propio catálogo",
       "Es gratis y no pide tarjeta. Media hora con tus artículos reales te dice si te sirve."),
  bloques=[
    ("Lo que le sobra a una tienda pequeña",
     ["Cuando un comerciante con una tienda de sesenta metros mira software de caja, se encuentra con productos pensados para otra escala: paneles de control con veinte informes, módulos de recursos humanos, integraciones con marketplaces internacionales.",
      "Nada de eso es malo. Simplemente no es para ti, y lo pagas igual, en dinero y en tiempo de aprendizaje. La curva de un programa que hace cuarenta cosas la paga quien solo necesita cinco.",
      "Lo que de verdad necesita una tienda de barrio cabe en una lista corta: cobrar rápido, saber qué queda, imprimir el ticket bien y cuadrar la caja."],
     None),
    ("Las tres cosas que más aprietan al comercio pequeño",
     ["Hablando por teléfono con comerciantes, las quejas se repiten y no son las que uno esperaría. Casi nunca son de funciones: son de dinero y de dependencia.",
      "La primera, pagar una cuota indefinida por un programa que nunca llega a ser tuyo. La segunda, la comisión por venta cuando el software va atado a una pasarela de cobro: un porcentaje pequeño sobre toda tu facturación, todos los años. Y la tercera, quedarse sin poder cobrar porque se ha caído internet un sábado por la mañana."],
     ["<strong>Cuotas:</strong> el plan gratuito no caduca y no exige tarjeta.",
      "<strong>Comisiones:</strong> cero. Cobras con el datáfono de tu banco.",
      "<strong>Internet:</strong> los datos están en tu ordenador, sigues cobrando sin línea.",
      "<strong>Hardware:</strong> aprovechas el equipo y la impresora que ya tienes."]),
    ("Soporte: quién coge el teléfono",
     ["En un comercio pequeño no hay departamento de informática. Cuando el programa no arranca a las nueve de la mañana con la persiana subiendo, lo que necesitas es hablar con alguien, no abrir un ticket y esperar.",
      "Por eso el canal principal es WhatsApp al 611 500 052 y el teléfono, con atención en España. Es la diferencia práctica que más se nota y la que menos aparece en las comparativas de funciones."],
     None),
    ("Cuándo Carrito5 se te va a quedar corto",
     ["Lo decimos aunque no ayude a vender. Si tu tienda pasa de 1.000 artículos en catálogo, y basta con tener movimiento para pasarlos, necesitarás el plan de pago o Caja 5, que es el producto con licencia en propiedad de la misma casa.",
      "Y si necesitas varias cajas trabajando a la vez, contabilidad integrada o sincronización en tiempo real con marketplaces, este no es tu programa. Preferimos decírtelo ahora que dentro de seis meses."],
     None),
  ],
  faqs=[
    ("¿Por qué un TPV gratis para comercio local?",
     "Porque la barrera de entrada al software de caja deja fuera a muchas tiendas pequeñas, que acaban trabajando con una calculadora y una libreta. El plan Inicio cubre a quien está empezando o tiene un catálogo contenido; a partir de 1.000 artículos, la licencia comercial."),
    ("¿Hay cuotas obligatorias?",
     "En el plan Inicio no hay cuota ni caducidad. Si tu catálogo pasa de 1.000 artículos, se amplía con la licencia comercial."),
    ("¿Me cobráis un porcentaje de mis ventas?",
     "No. Cobras con el datáfono que tú contrates, con la comisión que negocies con tu banco. Es una diferencia importante frente a plataformas donde el software es gratis pero se llevan un porcentaje de cada venta."),
    ("¿Puedo usar el ordenador que ya tengo?",
     "Casi siempre sí, si tiene Windows y está en condiciones. Lo que más se nota no es el procesador sino el disco: con SSD la caja va bastante más ágil. Pruébalo antes de comprar nada nuevo."),
    ("¿Qué pasa si se cae internet?",
     "Sigues cobrando. Los datos viven en tu ordenador, no en un servidor remoto, así que un corte de línea no para la caja. Es una de las razones por las que muchos comercios de calle prefieren un programa de escritorio."),
    ("¿Cómo os pido ayuda si algo falla?",
     "Por WhatsApp al 611 500 052 o por teléfono, en horario comercial y con atención en España. Sin ticket ni cola de chat."),
    ("¿Y si mi tienda crece?",
     "Cuando el catálogo pase de 1.000 artículos, se amplía con la licencia comercial. Y si necesitas varias cajas y gestión más amplia, la salida natural es Caja 5, con licencia en propiedad."),
  ],
  satelites=[("Descargar gratis", "descargar-tpv-gratis.html", "Instalador para Windows"),
             ("Elige tu sector", "sectores-y-negocios.html", "Qué cambia en cada oficio"),
             ("VeriFactu gratis", "verifactu-gratis.html", "Qué te obliga y desde cuándo"),
             ("Tallas y colores", "tallas-y-colores.html", "Si vendes moda o calzado")]),
}
