# -*- coding: utf-8 -*-
"""Cluster VeriFactu de carrito5.com.

Angulo propio del sitio: el que llega aqui busca «gratis» y «descargar», no
«licencia». El contenido no se recicla de abacosoftware.com aunque los hechos
normativos sean los mismos: son dominios del mismo dueño y duplicar texto entre
ellos perjudica a los dos. El comando `cruzado` del motor lo vigila.

Fechas verificadas: RD-ley 15/2025 aplaza a 1-ene-2027 (sociedades) y
1-jul-2027 (autonomos). 2026 es voluntario.
"""

AVISO = ("Esta página es información general, no asesoramiento fiscal. Los plazos de "
         "VeriFactu se han movido dos veces y pueden volver a cambiar: confirma tu caso "
         "con tu asesor o en la sede electrónica de la Agencia Tributaria.")

VERIFACTU = {

"verifactu-gratis.html": dict(
  title="VeriFactu Gratis: opciones reales para tu comercio | Carrito5",
  desc="Qué opciones gratuitas hay para cumplir con VeriFactu: la aplicación de la AEAT, los TPV gratuitos y dónde está la letra pequeña de cada una.",
  kw="verifactu gratis, programa verifactu gratis, software verifactu gratis, tpv verifactu gratis, facturacion verifactu gratuita",
  h1="VeriFactu gratis: qué opciones hay de verdad",
  sub="Sí se puede cumplir sin pagar, y hay más de un camino. Lo que conviene es saber para qué sirve cada uno antes de montar tu tienda encima.",
  badge="VERIFACTU SIN COSTE",
  crumb="VeriFactu gratis",
  trail=[("Inicio", "index.html"), ("VeriFactu gratis", "verifactu-gratis.html")],
  aside=("Carrito5 ya está adaptado",
         "El plan gratuito emite tickets conformes hasta 50 al mes. Descarga, pruébalo y sal de dudas sin poner tarjeta."),
  cta=("Sal de dudas descargando",
       "Instala Carrito5, emite un ticket de prueba y comprueba tú mismo cómo sale el QR."),
  bloques=[
    ("Tres caminos gratuitos, y no sirven para lo mismo",
     [AVISO,
      "Cuando alguien busca cumplir con VeriFactu sin gastar, se encuentra tres opciones que suelen mezclarse en la misma conversación. Separarlas ahorra bastante tiempo.",
      "La primera es la aplicación gratuita que ha previsto la Agencia Tributaria para emitir facturas conformes. La segunda son los TPV con plan gratuito, como el nuestro. Y la tercera, la más peligrosa, es seguir con la hoja de cálculo de siempre creyendo que ya vale."],
     ["<strong>Aplicación de la AEAT:</strong> emite facturas cumpliendo. No es un TPV: no lleva catálogo, ni stock, ni caja.",
      "<strong>TPV con plan gratuito:</strong> además de cumplir, gestiona la tienda. Con límite de volumen.",
      "<strong>Hoja de cálculo:</strong> no cumple y no va a cumplir. Es el cambio que sí o sí hay que hacer."]),
    ("Cuándo te basta la aplicación de Hacienda",
     ["Si emites unas pocas facturas al mes, no llevas inventario y tu negocio no tiene mostrador, la herramienta gratuita de la AEAT probablemente te sobra para cumplir. Te lo decimos aunque nosotros vendamos software.",
      "Donde se queda corta es en todo lo demás: no tiene catálogo de artículos con precios, no descuenta stock, no hace cierre de caja ni conoce a tus clientes. Sirve para facturar, no para llevar una tienda.",
      "Consulta sus condiciones y limitaciones actuales en la sede electrónica de la Agencia Tributaria, porque es información que puede cambiar."],
     None),
    ("La letra pequeña de los TPV gratuitos",
     ["Ningún fabricante regala software por gusto, así que la pregunta correcta no es «¿es gratis?» sino «¿por dónde cobras?». Hay cuatro respuestas posibles y conviene saber cuál te aplica.",
      "En Carrito5 la nuestra es la primera y la decimos sin rodeos: el plan Inicio es gratuito con hasta 1.000 artículos en catálogo local, y se amplía adquiriendo licencia comercial. No cobramos comisión por venta, no obligamos a comprar hardware nuestro y tus datos se quedan en tu ordenador."],
     ["<strong>Límite de volumen:</strong> gratis hasta X tickets o facturas. Honesto si el límite está claro.",
      "<strong>Comisión por venta:</strong> el software no cuesta pero se llevan un porcentaje de cada cobro. Es el más caro a la larga.",
      "<strong>Hardware obligatorio:</strong> el programa es gratis, el terminal que te obligan a comprar no.",
      "<strong>Funciones capadas:</strong> cobras gratis pero el stock o los informes se pagan."]),
    ("La pregunta que casi nadie hace",
     ["Antes de empezar con cualquier opción gratuita, comprueba que puedas <strong>exportar tus datos</strong>: artículos, stock y clientes a Excel o CSV.",
      "Si no puedes, no estás eligiendo un programa: estás firmando una permanencia indefinida sin contrato. Y lo descubrirás el día que quieras cambiar, con tres años de catálogo dentro."],
     None),
  ],
  faqs=[
    ("¿Hay algún programa VeriFactu gratis de verdad?",
     "Sí. La Agencia Tributaria ha previsto una aplicación gratuita para emitir facturas conformes, y existen TPV con plan gratuito como Carrito5. La diferencia es que la de la AEAT solo factura, mientras que un TPV además gestiona catálogo, stock y caja."),
    ("¿La aplicación de la AEAT me sirve para mi tienda?",
     "Si haces pocas facturas y no llevas inventario, probablemente sí. Si tienes mostrador, catálogo y cobros diarios, se te quedará corta enseguida: no gestiona artículos, ni stock, ni cierre de caja."),
    ("¿Carrito5 cumple con VeriFactu en el plan gratuito?",
     "Sí, el plan Inicio emite tickets conformes. El límite es de tamaño de catálogo, hasta 1.000 artículos, no de cumplimiento normativo."),
    ("¿Puedo seguir facturando con Excel?",
     "A partir de la fecha que te aplique, no. La norma exige un sistema informático de facturación que genere registros con los requisitos establecidos, y una hoja de cálculo no los cumple. Es el cambio inevitable si facturas así."),
    ("¿Tengo que pagar alguna tasa a Hacienda por VeriFactu?",
     "No existe ninguna tasa ni cuota. Lo que puede costarte dinero es adaptar o cambiar tu programa, que es un asunto entre tú y tu proveedor de software."),
    ("¿Desde cuándo es obligatorio?",
     "El 1 de enero de 2027 para sociedades y el 1 de julio de 2027 para autónomos, según el calendario vigente tras el Real Decreto-ley 15/2025. Durante 2026 la adaptación es voluntaria."),
    ("¿Cómo sé que un programa cumple de verdad?",
     "Pidiendo al fabricante la declaración responsable por escrito, con la versión y la fecha. Un logotipo de «homologado» en una web no es ese documento."),
    ("¿Y si mi programa actual no se adapta?",
     "Si el fabricante te da una fecha concreta, espera. Si tu programa es antiguo, está sin mantenimiento o el fabricante ya no existe, no habrá adaptación: empieza a mirar alternativas ahora y no en el último trimestre de 2026."),
  ],
  satelites=[("Cuándo entra en vigor VeriFactu", "verifactu-entrada-en-vigor.html", "Calendario 2027"),
             ("VeriFactu para autónomos", "verifactu-autonomos.html", "Tu fecha es julio de 2027"),
             ("Descargar de la AEAT", "verifactu-aeat-descargar.html", "Qué ofrece Hacienda"),
             ("Ley Crea y Crece", "ley-crea-y-crece-facturacion.html", "La otra obligación, distinta"),
             ("Descargar Carrito5 gratis", "descargar-tpv-gratis.html", "Adaptado y sin tarjeta")]),

"verifactu-entrada-en-vigor.html": dict(
  title="VeriFactu: cuándo entra en vigor. Fechas 2027 | Carrito5",
  desc="Calendario actualizado de VeriFactu tras el aplazamiento del RD-ley 15/2025: enero de 2027 para sociedades, julio de 2027 para autónomos y 2026 voluntario.",
  kw="verifactu entrada en vigor, verifactu cuando entra en vigor, verifactu 2027, verifactu aplazamiento, calendario verifactu",
  h1="Cuándo entra en vigor VeriFactu",
  sub="El calendario se ha aplazado dos veces y sigue circulando el antiguo. Estas son las fechas que están vigentes ahora mismo.",
  badge="CALENDARIO",
  crumb="Entrada en vigor",
  trail=[("Inicio", "index.html"), ("VeriFactu gratis", "verifactu-gratis.html"),
         ("Entrada en vigor", "verifactu-entrada-en-vigor.html")],
  aside=("Adelántate sin gastar",
         "Puedes empezar a facturar con un programa adaptado hoy mismo y sin coste. Así no dependes de las prisas de 2026."),
  cta=("Empieza adaptado desde el primer ticket",
       "Descarga Carrito5 gratis y no tendrás que cambiar de programa cuando llegue tu fecha."),
  bloques=[
    ("Las dos fechas que te afectan",
     [AVISO,
      "El Real Decreto-ley 15/2025, aprobado el 2 de diciembre de 2025, retrasó un año más la implantación. Con el calendario actual hay dos fechas y la que te aplica depende de tu forma jurídica, no de tu sector ni de tu tamaño."],
     ["<strong>1 de enero de 2027:</strong> sociedades y demás contribuyentes del Impuesto sobre Sociedades.",
      "<strong>1 de julio de 2027:</strong> autónomos y el resto de contribuyentes.",
      "<strong>Durante 2026:</strong> adaptación voluntaria. Ni obligación ni sanción por esperar.",
      "<strong>País Vasco:</strong> lo aplicable es ticketBAI, con su propio calendario foral."]),
    ("Por qué se ha movido dos veces",
     ["El reglamento original, el Real Decreto 1007/2023, fijaba fechas bastante más tempranas. Tras las alegaciones del sector y de las asociaciones de autónomos, Hacienda movió el calendario a 2026 y después, con el RD-ley 15/2025, a 2027.",
      "La lectura práctica es que el aplazamiento da margen pero no elimina nada. El marco antifraude sigue plenamente vigente: lo que se ha movido es la fecha desde la que se exige."],
     None),
    ("Adelantarse sale gratis y evita el atasco",
     ["Aquí hay un argumento que no tiene que ver con el miedo sino con la logística. Si todo el sector cambia de programa a la vez en el último trimestre antes de la fecha, los plazos de instalación se alargan y el soporte de todos los fabricantes se satura.",
      "Hacerlo con calma en un mes tranquilo es mucho mejor que hacerlo con la persiana subida y prisa. Y si el programa que eliges es gratuito, adelantarse no cuesta dinero: solo el rato de montar el catálogo."],
     ["Pregunta hoy a tu proveedor si su programa está adaptado y si te dará la declaración responsable.",
      "Si te da largas o te cobra la adaptación, empieza a mirar alternativas ya.",
      "Elige tu mes de menos facturación para hacer el cambio.",
      "Haz inventario antes de migrar, para cargar stock real en el sistema nuevo."]),
  ],
  faqs=[
    ("¿Cuándo entra en vigor VeriFactu exactamente?",
     "El 1 de enero de 2027 para sociedades y el 1 de julio de 2027 para autónomos, según el calendario vigente tras el RD-ley 15/2025. Como ya se ha aplazado dos veces, confirma la fecha con tu asesor antes de planificar."),
    ("¿Es obligatorio en 2026?",
     "No. Durante 2026 la adaptación es voluntaria y no hay sanción por no haberla hecho. Puedes adelantarte, y es recomendable, pero no estás obligado."),
    ("¿La fecha depende de mi sector o de mi facturación?",
     "De tu forma jurídica. Sociedades en enero de 2027, autónomos y resto en julio de 2027. Ni el sector ni el volumen cambian tu fecha."),
    ("Tengo la tienda en Bilbao. ¿Me aplica esto?",
     "En Álava, Bizkaia y Gipuzkoa lo aplicable es ticketBAI, el sistema de las haciendas forales, que tiene su propia normativa y su calendario. Confírmalo con tu asesor o con tu hacienda foral."),
    ("¿Por qué se ha aplazado tantas veces?",
     "Tras las alegaciones del sector y de las asociaciones de autónomos, Hacienda movió el calendario primero a 2026 y después a 2027. El aplazamiento da margen pero no elimina la obligación."),
    ("¿Merece la pena adelantarse?",
     "Por logística, sí. Si todo el sector migra a la vez en el último trimestre, los plazos se alargan y el soporte se satura. Y si el programa es gratuito, adelantarse solo cuesta el rato de montar el catálogo."),
    ("¿Qué pasa si llego tarde a mi fecha?",
     "A partir de ese momento, emitir con un programa no conforme deja de ser válido, y la ley contempla un régimen sancionador. Los importes y supuestos concretos debe valorarlos tu asesor, no una web."),
  ],
  satelites=[("VeriFactu gratis", "verifactu-gratis.html", "Opciones sin coste"),
             ("VeriFactu para autónomos", "verifactu-autonomos.html", "Julio de 2027"),
             ("Descargar Carrito5", "descargar-tpv-gratis.html", "Ya adaptado"),
             ("Ley Crea y Crece", "ley-crea-y-crece-facturacion.html", "No la confundas")]),

"verifactu-autonomos.html": dict(
  title="VeriFactu para Autónomos: tu fecha es julio de 2027 | Carrito5",
  desc="Qué te obliga VeriFactu si eres autónomo, desde cuándo, qué necesitas exactamente y cuánto cuesta adaptarse. Sin alarmismo y con opciones gratuitas.",
  kw="verifactu autonomos, verifactu para autonomos, autonomos verifactu obligatorio, factura autonomo verifactu, tpv autonomo gratis",
  h1="VeriFactu para autónomos",
  sub="Tu fecha es el 1 de julio de 2027, no antes. Y lo que necesitas es bastante menos de lo que te están contando.",
  badge="AUTÓNOMOS",
  crumb="Para autónomos",
  trail=[("Inicio", "index.html"), ("VeriFactu gratis", "verifactu-gratis.html"),
         ("Para autónomos", "verifactu-autonomos.html")],
  aside=("Sin gastar para empezar",
         "El plan Inicio de Carrito5 es gratuito hasta 1.000 artículos y ya está adaptado. Sin tarjeta."),
  cta=("Prepárate sin poner dinero",
       "Descarga Carrito5, emite tus facturas conformes y decide más adelante si necesitas más."),
  bloques=[
    ("Tu fecha, y por qué es distinta",
     [AVISO,
      "El calendario separa dos grupos según la forma jurídica. Las sociedades entran el 1 de enero de 2027. Los autónomos y el resto de contribuyentes, el 1 de julio de 2027.",
      "Esa separación viene del RD-ley 15/2025, que aplazó todo un año. Durante 2026 y el primer semestre de 2027 la adaptación es voluntaria para ti."],
     None),
    ("Lo que de verdad necesitas",
     ["Menos de lo que la mayoría teme. No hay que contratar ningún servicio con Hacienda, ni cambiar de banco, ni comprar hardware nuevo, ni pagar cuota alguna a la Agencia Tributaria.",
      "Lo que necesitas es que el programa con el que emites tus facturas o tickets esté adaptado y que su fabricante te dé la declaración responsable. Si facturas con una hoja de cálculo o con un documento de texto, eso sí tendrá que cambiar."],
     ["Un programa de facturación o TPV adaptado, con su declaración responsable.",
      "Tus datos fiscales bien configurados en el programa.",
      "Una impresora que saque el QR con calidad legible, si emites en papel.",
      "Nada más. Ni gestor obligatorio ni certificado adicional para el caso general."]),
    ("Cuánto cuesta adaptarse siendo autónomo",
     ["Depende de lo que factures y conviene mirarlo a varios años, no solo el primer recibo. Los programas por suscripción del mercado español se mueven habitualmente entre 10 y 40 euros al mes para un autónomo, lo que a cinco años supone entre 600 y 2.400 euros.",
      "Si tu volumen es bajo, hay dos salidas sin coste: la aplicación gratuita de la AEAT, si solo necesitas facturar, o un TPV con plan gratuito como el nuestro, si además llevas artículos y stock. En Carrito5 es el plan Inicio: hasta 1.000 artículos sin pagar nada.",
      "Y si tu volumen es alto y te molesta pagar todos los meses, la opción es una licencia en propiedad: Caja 5, de la misma casa, se compra una vez y es tuya."],
     None),
    ("Tres cosas que circulan y no son ciertas",
     ["El terreno de VeriFactu se ha llenado de anuncios que venden con miedo, así que conviene desmontar lo que más se repite.",
      "Primero, que Hacienda va a ver tu caja en directo: lo que se remiten son los registros de las facturas emitidas, no un acceso a tu negocio. Segundo, que hay que pagar una cuota a la AEAT: no la hay. Y tercero, que te multan mañana: hasta julio de 2027 no hay obligación para ti.",
      "Toma la decisión con tu asesor y con datos. Un proveedor que te vende con prisa y con cifras de multas tajantes te está diciendo algo sobre cómo va a ser el trato después."],
     None),
  ],
  faqs=[
    ("¿Desde cuándo me obliga VeriFactu si soy autónomo?",
     "Desde el 1 de julio de 2027, según el calendario vigente tras el RD-ley 15/2025. Durante 2026 y el primer semestre de 2027 la adaptación es voluntaria. Confirma la fecha con tu asesor, porque ya se ha movido dos veces."),
    ("¿Puedo seguir haciendo facturas en Excel o en Word?",
     "Hasta tu fecha, sí. A partir de ella, no: la norma exige un sistema informático de facturación que genere los registros exigidos, y una hoja de cálculo no los cumple."),
    ("¿Tengo que pagar algo a Hacienda?",
     "No. No existe tasa ni cuota por VeriFactu. Lo único que puede costarte dinero es adaptar o cambiar tu programa de facturación."),
    ("Facturo muy poco. ¿Hay opción gratis?",
     "Sí, dos. La aplicación gratuita de la AEAT si solo necesitas emitir facturas, y un TPV con plan gratuito como Carrito5 si además llevas artículos y stock. En nuestro caso es el plan Inicio, gratuito hasta 1.000 artículos."),
    ("¿Necesito un gestor para cumplir?",
     "No para el hecho de facturar con un programa adaptado. Otra cosa es que un asesor te ahorre disgustos con tu régimen fiscal, que es una conversación distinta y normalmente rentable."),
    ("¿Va a ver Hacienda todas mis ventas en tiempo real?",
     "No en el sentido que sugiere esa frase. Se remiten los registros de facturación con la información que establece la norma. No es un acceso a tu caja ni a tu contabilidad."),
    ("¿Me sirve el programa que uso ahora?",
     "Solo si el fabricante lo ha adaptado y puede entregarte la declaración responsable. Pídesela por escrito: es el documento que lo acredita y es tu respaldo."),
    ("Si mi negocio crece, ¿qué hago?",
     "Cuando tu catálogo pase de 1.000 artículos, se amplía adquiriendo la licencia comercial. También existen planes en la nube si necesitas trabajar desde varios sitios."),
  ],
  satelites=[("Cuándo entra en vigor", "verifactu-entrada-en-vigor.html", "Las dos fechas de 2027"),
             ("VeriFactu gratis", "verifactu-gratis.html", "Opciones sin coste"),
             ("Descargar Carrito5", "descargar-tpv-gratis.html", "Plan Inicio gratuito"),
             ("TPV para comercio local", "software-tpv-comercio-local.html", "Pensado para tienda pequeña")]),

"verifactu-aeat-descargar.html": dict(
  title="VeriFactu AEAT: qué ofrece Hacienda y qué no | Carrito5",
  desc="Qué es la aplicación gratuita de la Agencia Tributaria para VeriFactu, para quién sirve, qué no hace y cuándo necesitas un TPV en su lugar.",
  kw="verifactu aeat descargar, aplicacion verifactu hacienda, programa aeat facturacion gratis, descargar verifactu agencia tributaria",
  h1="La aplicación de la AEAT: para quién sirve y para quién no",
  sub="Hacienda ha previsto una herramienta gratuita para emitir facturas conformes. Es una buena noticia, y también conviene saber dónde termina.",
  badge="HERRAMIENTA OFICIAL",
  crumb="Aplicación de la AEAT",
  trail=[("Inicio", "index.html"), ("VeriFactu gratis", "verifactu-gratis.html"),
         ("Aplicación de la AEAT", "verifactu-aeat-descargar.html")],
  aside=("¿Necesitas más que facturar?",
         "Si llevas artículos, stock y cobras en mostrador, la herramienta de Hacienda se te quedará corta. Carrito5 cubre eso y también es gratis para empezar."),
  cta=("Prueba la diferencia sin gastar",
       "Descarga Carrito5 y compara: catálogo, stock, tickets y cierre de caja, además del cumplimiento."),
  bloques=[
    ("Qué es y dónde encontrarla",
     [AVISO,
      "La Agencia Tributaria ha previsto una aplicación gratuita para que los contribuyentes puedan emitir facturas conforme al sistema VeriFactu sin tener que contratar software.",
      "Es la opción de coste cero más obvia y, para determinados perfiles, perfectamente suficiente. Consulta sus condiciones, requisitos y limitaciones actuales en la sede electrónica de la Agencia Tributaria: es información oficial que puede cambiar y no conviene fiarse de lo que diga una web comercial, incluida esta."],
     None),
    ("Para quién es suficiente",
     ["Si emites unas pocas facturas al mes, tu actividad no tiene mostrador y no llevas inventario, cumples con ella y te ahorras el dinero. Te lo decimos aunque vendamos software: no tiene sentido montar un TPV para hacer seis facturas mensuales.",
      "El perfil típico es el profesional que factura a empresas, el consultor, el técnico que trabaja por encargos. Ahí la herramienta oficial hace su trabajo."],
     None),
    ("Dónde se queda corta",
     ["No es un TPV, y no pretende serlo. La diferencia no es de calidad: es de propósito. Sirve para emitir facturas cumpliendo la norma, no para llevar una tienda.",
      "Si tu día a día es un mostrador con clientes, catálogo de artículos y cobros continuos, vas a echar de menos casi todo lo que hace funcionar una tienda."],
     ["<strong>No tiene catálogo</strong> de artículos con precios y códigos de barras.",
      "<strong>No controla stock</strong> ni te avisa de lo que se agota.",
      "<strong>No hace cierre de caja</strong> ni arqueo por medio de pago.",
      "<strong>No guarda clientes</strong> ni resuelve devoluciones sobre el ticket original.",
      "<strong>No imprime etiquetas</strong> ni gestiona tallas y colores."]),
    ("Cómo elegir entre las dos",
     ["La pregunta es sencilla: ¿lo que necesitas es emitir facturas o llevar una tienda?",
      "Si es lo primero, la herramienta de Hacienda te vale y no hace falta que sigas leyendo. Si es lo segundo, necesitas un TPV, y ahí la buena noticia es que también lo hay gratis: el plan Inicio de Carrito5 es gratuito hasta 1.000 artículos, con catálogo, stock y caja incluidos."],
     None),
  ],
  faqs=[
    ("¿La Agencia Tributaria ofrece un programa gratis para VeriFactu?",
     "Sí, ha previsto una aplicación gratuita para emitir facturas conformes. Consulta sus condiciones y limitaciones actuales en la sede electrónica de la AEAT, porque es información oficial que puede cambiar."),
    ("¿Me sirve para mi tienda?",
     "Depende de si necesitas facturar o llevar una tienda. No tiene catálogo, ni stock, ni cierre de caja, ni fichas de cliente. Para un mostrador con cobros continuos se queda corta enseguida."),
    ("¿Es mejor la de Hacienda o un TPV gratuito?",
     "No compiten: hacen cosas distintas. La de Hacienda emite facturas cumpliendo. Un TPV además gestiona la tienda. Si solo necesitas lo primero, ahórrate el software."),
    ("¿Puedo usar las dos a la vez?",
     "No tiene sentido y complica la trazabilidad: tus registros de facturación quedarían repartidos entre dos sistemas. Elige uno."),
    ("¿Dónde la descargo?",
     "En la sede electrónica de la Agencia Tributaria. Desconfía de webs de terceros que ofrezcan descargarla: la fuente oficial es la única fiable para una herramienta de este tipo."),
    ("Si empiezo con la de Hacienda, ¿puedo cambiar después?",
     "Sí, aunque tendrás que montar el catálogo desde cero en el programa nuevo, porque la herramienta oficial no lo tiene. Y conserva tu documentación fiscal según los plazos que te indique tu asesor."),
  ],
  satelites=[("VeriFactu gratis", "verifactu-gratis.html", "Todas las opciones"),
             ("Cuándo entra en vigor", "verifactu-entrada-en-vigor.html", "Fechas de 2027"),
             ("Descargar Carrito5", "descargar-tpv-gratis.html", "TPV completo y gratis"),
             ("Para autónomos", "verifactu-autonomos.html", "Tu fecha y tus opciones")]),

"ley-crea-y-crece-facturacion.html": dict(
  title="Ley Crea y Crece: ¿te afecta a ti? | Carrito5",
  desc="La factura electrónica entre empresas no es VeriFactu y probablemente no te afecta si vendes a particulares. Comprueba en un minuto en cuál de las dos estás.",
  kw="ley crea y crece factura electronica, factura electronica obligatoria, crea y crece me afecta, factura electronica comercio minorista",
  h1="Ley Crea y Crece: comprueba si te afecta",
  sub="Antes de que te vendan nada: si tu tienda cobra con tickets a particulares, esta obligación probablemente no va contigo. Aquí lo compruebas en un minuto.",
  badge="COMPRUEBA TU CASO",
  crumb="Crea y Crece",
  trail=[("Inicio", "index.html"), ("VeriFactu gratis", "verifactu-gratis.html"),
         ("Crea y Crece", "ley-crea-y-crece-facturacion.html")],
  aside=("Si vendes con tickets, tu tema es VeriFactu",
         "Carrito5 ya está adaptado y su plan gratuito emite tickets conformes. Descarga y sal de dudas."),
  cta=("¿Sigues con la duda?",
       "Cuéntanos por WhatsApp qué vendes y a quién. Te decimos cuál de las dos te toca, sin venderte nada por el camino."),
  bloques=[
    ("Tres preguntas y sabes en cuál estás",
     [AVISO,
      "Se están mezclando dos obligaciones distintas en el mismo discurso comercial, y eso hace que mucha gente compre soluciones que no necesita. Responde a esto y sales de dudas:"],
     ["<strong>¿La mayoría de tus ventas son a particulares que se llevan un ticket?</strong> Entonces tu obligación es VeriFactu, y Crea y Crece te afecta poco o nada.",
      "<strong>¿Facturas habitualmente a otras empresas o profesionales?</strong> Esa parte de tu actividad sí entra en el ámbito de Crea y Crece.",
      "<strong>¿Aún emites facturas con Excel o Word?</strong> Eso hay que cambiarlo en cualquiera de los dos casos.",
      "<strong>¿Tu tienda está en Álava, Bizkaia o Gipuzkoa?</strong> Entonces lo tuyo es ticketBAI, no VeriFactu."]),
    ("Por qué se confunden tanto",
     ["Porque salieron casi a la vez, las dos hablan de facturas y las dos se han retrasado. Pero vienen de leyes distintas y persiguen cosas distintas.",
      "Una mira hacia dentro de tu programa: que no puedas borrar una venta sin dejar rastro. La otra mira hacia fuera: en qué formato le mandas la factura a otra empresa para que su sistema la procese sola. No tienen nada que ver salvo la palabra factura."],
     None),
    ("El comercio minorista está mayoritariamente fuera",
     ["Esto es lo importante para quien lee esta página desde una tienda. La obligación de Crea y Crece se refiere a operaciones entre empresarios y profesionales. Vender una camiseta a alguien que entra por la puerta no es eso.",
      "Donde sí puede tocarte es en la parte de tu facturación a empresas, si la tienes. El fontanero que te compra material con factura, la comunidad de vecinos, la academia del barrio. Si esa parte es marginal, tu prioridad sigue estando en otro sitio."],
     None),
    ("Qué no hacer todavía",
     ["No compres una solución de factura electrónica B2B porque un comercial te haya dicho que es urgente. El despliegue de esta obligación depende de un desarrollo reglamentario que ha sufrido retrasos y cuyos plazos se ligan al volumen de facturación.",
      "Lo sensato ahora es tener claro en qué grupo estás, resolver VeriFactu si vendes con tickets, y volver a esto cuando las fechas estén cerradas. Tu asesor te dirá cuándo."],
     None),
  ],
  faqs=[
    ("Tengo una tienda y vendo a particulares. ¿Me afecta Crea y Crece?",
     "Poco o nada. La obligación se refiere a operaciones entre empresarios y profesionales, y los tickets a consumidor final quedan fuera. Lo que sí te aplica es VeriFactu."),
    ("¿Cómo sé en cuál de las dos estoy?",
     "Mira a quién facturas. Si son particulares con ticket, VeriFactu. Si son empresas con factura, esa parte entra en Crea y Crece. Puedes estar en las dos si tienes ambos tipos de cliente."),
    ("¿Por qué se confunden VeriFactu y Crea y Crece?",
     "Porque salieron casi a la vez, ambas hablan de facturas y ambas se han retrasado. Pero una regula cómo se comporta tu programa por dentro y la otra el formato en que mandas la factura a otra empresa."),
    ("¿Me tengo que preocupar ya?",
     "Si vendes con tickets, tu prioridad es VeriFactu. Para Crea y Crece, el despliegue depende de un desarrollo reglamentario con retrasos y plazos ligados al volumen: no compres nada hasta que tu asesor te confirme tu fecha."),
    ("Facturo a algunas empresas. ¿Qué hago ahora?",
     "Calcula qué porcentaje de tu facturación es a empresas. Si es marginal, resuelve primero VeriFactu. Si es una parte importante, habla con tu asesor sobre tu calendario."),
    ("¿Vale mandar la factura en PDF?",
     "Para esta obligación no: se refiere a un formato estructurado que el sistema del destinatario procese automáticamente, además de informar sobre los estados de la factura."),
    ("Mi tienda está en el País Vasco.",
     "Entonces tu sistema no es VeriFactu sino ticketBAI, el de las haciendas forales, con su propia normativa y calendario. Consúltalo con tu asesor o con tu hacienda foral."),
  ],
  satelites=[("VeriFactu gratis", "verifactu-gratis.html", "Lo que probablemente sí te toca"),
             ("Cuándo entra en vigor VeriFactu", "verifactu-entrada-en-vigor.html", "Fechas de 2027"),
             ("Para autónomos", "verifactu-autonomos.html", "Julio de 2027"),
             ("Descargar Carrito5", "descargar-tpv-gratis.html", "Adaptado y gratis")]),
}
