export type Branch = {
  id: string;
  name: string;
  city: string;
  region: string;
  address: string;
  phone: string;
  hours: string;
  services: string[];
  flagship?: boolean;
};

/** Extrait représentatif du réseau BIAT (plus de 200 agences).
 *  Données de démonstration. */
export const BRANCHES: Branch[] = [
  {
    id: "tun-hbb",
    name: "Agence Habib Bourguiba — Siège",
    city: "Tunis",
    region: "Grand Tunis",
    address: "70-72, Avenue Habib Bourguiba, 1080 Tunis",
    phone: "+216 71 340 733",
    hours: "Lun–Ven · 08h00–16h30",
    services: ["Change", "Coffres-forts", "Espace Patrimoine", "GAB 24/7"],
    flagship: true,
  },
  {
    id: "tun-lac2",
    name: "Agence Les Berges du Lac 2",
    city: "Tunis",
    region: "Grand Tunis",
    address: "Rue du Lac de Constance, Les Berges du Lac 2, 1053 Tunis",
    phone: "+216 71 962 410",
    hours: "Lun–Ven · 08h00–16h30",
    services: ["Espace Entreprises", "Change", "GAB 24/7"],
  },
  {
    id: "tun-marsa",
    name: "Agence La Marsa",
    city: "La Marsa",
    region: "Grand Tunis",
    address: "Avenue Habib Bourguiba, 2078 La Marsa",
    phone: "+216 71 749 250",
    hours: "Lun–Ven · 08h00–16h30",
    services: ["Change", "GAB 24/7"],
  },
  {
    id: "tun-menzah6",
    name: "Agence El Menzah VI",
    city: "Ariana",
    region: "Grand Tunis",
    address: "Avenue Hédi Nouira, El Menzah VI, 2091 Ariana",
    phone: "+216 71 238 522",
    hours: "Lun–Ven · 08h00–16h30",
    services: ["Espace Jeunes", "GAB 24/7"],
  },
  {
    id: "tun-ennasr",
    name: "Agence Ennasr",
    city: "Ariana",
    region: "Grand Tunis",
    address: "Avenue Hédi Karray, Cité Ennasr II, 2037 Ariana",
    phone: "+216 71 827 640",
    hours: "Lun–Ven · 08h00–16h30",
    services: ["Change", "GAB 24/7"],
  },
  {
    id: "sfx-centre",
    name: "Agence Sfax Centre",
    city: "Sfax",
    region: "Sfax",
    address: "Avenue Habib Bourguiba, 3000 Sfax",
    phone: "+216 74 228 733",
    hours: "Lun–Ven · 08h00–16h30",
    services: ["Espace Entreprises", "Change", "Coffres-forts", "GAB 24/7"],
    flagship: true,
  },
  {
    id: "sfx-jadida",
    name: "Agence Sfax El Jadida",
    city: "Sfax",
    region: "Sfax",
    address: "Avenue 14 Janvier, Sfax El Jadida, 3027 Sfax",
    phone: "+216 74 402 118",
    hours: "Lun–Ven · 08h00–16h30",
    services: ["Change", "GAB 24/7"],
  },
  {
    id: "sou-centre",
    name: "Agence Sousse Boujaafar",
    city: "Sousse",
    region: "Sahel",
    address: "Avenue Habib Bourguiba, 4000 Sousse",
    phone: "+216 73 225 611",
    hours: "Lun–Ven · 08h00–16h30",
    services: ["Change", "Espace Patrimoine", "GAB 24/7"],
    flagship: true,
  },
  {
    id: "mon-centre",
    name: "Agence Monastir",
    city: "Monastir",
    region: "Sahel",
    address: "Avenue de l'Indépendance, 5000 Monastir",
    phone: "+216 73 461 205",
    hours: "Lun–Ven · 08h00–16h30",
    services: ["Change", "GAB 24/7"],
  },
  {
    id: "nab-hammamet",
    name: "Agence Hammamet",
    city: "Hammamet",
    region: "Cap Bon",
    address: "Avenue Habib Bourguiba, 8050 Hammamet",
    phone: "+216 72 280 444",
    hours: "Lun–Ven · 08h00–16h30",
    services: ["Change", "GAB 24/7"],
  },
  {
    id: "nab-nabeul",
    name: "Agence Nabeul",
    city: "Nabeul",
    region: "Cap Bon",
    address: "Avenue Habib Thameur, 8000 Nabeul",
    phone: "+216 72 232 155",
    hours: "Lun–Ven · 08h00–16h30",
    services: ["Change", "GAB 24/7"],
  },
  {
    id: "biz-centre",
    name: "Agence Bizerte",
    city: "Bizerte",
    region: "Nord",
    address: "Rue Habib Bourguiba, 7000 Bizerte",
    phone: "+216 72 431 622",
    hours: "Lun–Ven · 08h00–16h30",
    services: ["Change", "GAB 24/7"],
  },
  {
    id: "djb-houmt",
    name: "Agence Djerba Houmt Souk",
    city: "Djerba",
    region: "Sud",
    address: "Avenue Habib Bourguiba, Houmt Souk, 4180 Djerba",
    phone: "+216 75 650 210",
    hours: "Lun–Ven · 08h00–16h30",
    services: ["Change", "GAB 24/7"],
  },
  {
    id: "gab-centre",
    name: "Agence Gabès",
    city: "Gabès",
    region: "Sud",
    address: "Avenue Farhat Hached, 6000 Gabès",
    phone: "+216 75 270 388",
    hours: "Lun–Ven · 08h00–16h30",
    services: ["GAB 24/7"],
  },
  {
    id: "kai-centre",
    name: "Agence Kairouan",
    city: "Kairouan",
    region: "Centre",
    address: "Avenue de la République, 3100 Kairouan",
    phone: "+216 77 233 900",
    hours: "Lun–Ven · 08h00–16h30",
    services: ["GAB 24/7"],
  },
  {
    id: "gaf-centre",
    name: "Agence Gafsa",
    city: "Gafsa",
    region: "Sud-Ouest",
    address: "Avenue Habib Bourguiba, 2100 Gafsa",
    phone: "+216 76 224 517",
    hours: "Lun–Ven · 08h00–16h30",
    services: ["GAB 24/7"],
  },
];

export const REGIONS = [...new Set(BRANCHES.map((b) => b.region))];
